package com.google.android.libraries.places.internal;

/* compiled from: com.google.android.libraries.places:places@@3.5.0 */
/* loaded from: classes27.dex */
final class zzun implements zzaty {
    static final zzaty zza = new zzun();

    private zzun() {
    }

    @Override // com.google.android.libraries.places.internal.zzaty
    public final boolean zza(int i) {
        switch (i) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 13:
            case 14:
            case 15:
            case 16:
            case 17:
            case 18:
            case 19:
            case 20:
            case 21:
            case 22:
            case 23:
            case 24:
            case 25:
            case 26:
            case 27:
            case 28:
            case 29:
            case 30:
            case 31:
            case 32:
            case 33:
            case 34:
            case 35:
            case 36:
            case 37:
            case 38:
            case 39:
            case 40:
            case 41:
            case 42:
            case 43:
            case 44:
            case 45:
            case 46:
            case 47:
            case 48:
            case 49:
            case 50:
            case 51:
            case 52:
            case 53:
            case 54:
            case 55:
            case 56:
            case 57:
            case 58:
            case 59:
            case 60:
            case 61:
            case 62:
            case 63:
            case 64:
            case 65:
            case 66:
            case 67:
            case SDK_ASSET_ICON_HOME_VALUE:
            case 69:
            case 70:
            case SDK_ASSET_ICON_GUIDE_VALUE:
            case SDK_ASSET_ICON_GLOBE_VALUE:
            case 73:
            case 74:
            case 75:
            case 76:
            case 77:
            case 78:
            case 79:
            case 80:
            case 81:
            case 82:
            case 83:
            case 84:
            case 85:
            case 86:
            case 87:
            case 88:
            case 89:
            case 90:
            case 91:
            case 92:
            case 93:
            case 94:
            case 95:
            case 96:
            case 97:
            case 98:
            case 99:
            case 100:
            case 101:
            case 102:
            case 103:
            case 104:
            case 105:
            case 106:
            case 107:
            case 108:
            case 109:
            case 110:
            case 111:
            case 112:
            case 113:
            case 114:
            case 115:
            case 116:
            case 117:
            case 118:
            case 119:
            case 120:
            case SDK_ASSET_ILLUSTRATION_DEPOSIT_SWITCH_VALUE:
            case SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE:
            case 123:
            case SDK_ASSET_ILLUSTRATION_SIGNATURE_VALUE:
            case 125:
            case SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE:
            case SDK_ASSET_ILLUSTRATION_BRIEFCASE_VALUE:
            case 128:
            case SDK_ASSET_ILLUSTRATION_FORM_VALUE:
            case SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE:
            case 131:
            case SDK_ASSET_ILLUSTRATION_IN_CONTROL_VALUE:
            case SDK_ASSET_ILLUSTRATION_DEV_FAULTY_DATA_VALUE:
            case SDK_ASSET_ILLUSTRATION_DEV_LOGS_VALUE:
            case SDK_ASSET_ILLUSTRATION_DEV_RAISE_INSTITUTION_VALUE:
            case 136:
            case SDK_ASSET_ILLUSTRATION_INSTITUTION_CIRCLE_VALUE:
            case SDK_ASSET_ILLUSTRATION_SHARE_YOUR_DATA_VALUE:
            case SDK_ASSET_ILLUSTRATION_SPOT_PX_FEATURE_01_VALUE:
            case SDK_ASSET_ICON_ALERT_ERROR_RED_VALUE:
            case SDK_ASSET_CONNECTIVITY_DOWN_ILLUSTRATION_VALUE:
            case SDK_ASSET_CONNECTIVITY_WARNING_ILLUSTRATION_VALUE:
            case SDK_ASSET_ICON_ALERT_ERROR_BLACK_VALUE:
            case 144:
            case SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_ACCOUNT_VALUE:
            case SDK_ASSET_ILLUSTRATION_PLAID_OVERLAY_PERSON_VALUE:
            case 147:
            case SDK_ASSET_ICON_CHECKMARK_GREEN_SQUARE_CASH_VALUE:
            case SDK_ASSET_ILLUSTRATION_SDK_EMPTY_SVG_VALUE:
            case 150:
            case 151:
            case SDK_ASSET_ICON_CHECKMARK_BLUE_VALUE:
            case SDK_ASSET_ILLUSTRATION_SQUARE_CASH_GENERIC_INSTITUTION_VALUE:
            case SDK_ASSET_ILLUSTRATION_UPLOAD_VALUE:
            case 155:
            case 156:
            case SDK_ASSET_ILLUSTRATION_FALLBACK_INSTITUTION_VALUE:
            case SDK_ASSET_ILLUSTRATION_WALLET_VALUE:
            case SDK_ASSET_ILLUSTRATION_INCOME_VALUE:
            case SDK_ASSET_ILLUSTRATION_SECURE_TOKENIZATION_VALUE:
            case SDK_ASSET_ILLUSTRATION_WARNING_EXIT_SPOT_VALUE:
            case SDK_ASSET_ILLUSTRATION_SUPPORT_VALUE:
            case SDK_ASSET_ILLUSTRATION_PAYWITHPLAID_LOGO_VALUE:
            case SDK_ASSET_ILLUSTRATION_SIGNIN_HEADER_VALUE:
            case 165:
            case SDK_ASSET_ILLUSTRATION_ETH_WITH_PLAID_VALUE:
            case 167:
            case SDK_ASSET_ILLUSTRATION_CODE_ACCOUNT_VERIFICATION_VALUE:
            case SDK_ASSET_HEADER_CARD_COLLECT_VALUE:
            case SDK_ASSET_ILLUSTRATION_INCOME_PAYROLL_URL_VALUE:
            case SDK_ASSET_ILLUSTRATION_CONSENT_HEADER_WEB3_VALUE:
            case SDK_ASSET_ILLUSTRATION_CONSENT_HEADER_WEB3_DARK_APPEARANCE_VALUE:
            case SDK_ASSET_HEADER_FINAL_ERROR_DARK_APPEARANCE_VALUE:
            case SDK_ASSET_ILLUSTRATION_NETWORK_SWITCH_VALUE:
            case SDK_ASSET_ILLUSTRATION_NETWORK_SWITCH_DARK_APPEARANCE_VALUE:
            case SDK_ASSET_ILLUSTRATION_PLAID_LOGO_NAVBAR_DARK_APPEARANCE_VALUE:
            case SDK_ASSET_HEADER_FINAL_SUCCESS_DARK_APPEARANCE_VALUE:
            case f2773x8d9721ad:
            case f2780x600b66fe:
            case SDK_ASSET_HEADER_NOT_LISTED_ERROR_VALUE:
            case SDK_ASSET_ILLUSTRATION_PLAID_REVIEW_CONNECTION_VALUE:
            case 182:
            case SDK_ASSET_ILLUSTRATION_PLAID_PINWHEEL_VALUE:
            case SDK_ASSET_ILLUSTRATION_PLAID_PINWHEEL_TEXT_VALUE:
            case SDK_ASSET_ILLUSTRATION_PLAID_ATOMIC_VALUE:
            case SDK_ASSET_ILLUSTRATION_PLAID_ATOMIC_TEXT_VALUE:
            case SDK_ASSET_ILLUSTRATION_ATOMIC_LOGO_VALUE:
            case 188:
            case SDK_ASSET_ILLUSTRATION_CODE_ACCOUNT_VERIFICATION_2_VALUE:
            case SDK_ASSET_ILLUSTRATION_MD_ERROR_ATTEMPT_1_NEW_VALUE:
            case SDK_ASSET_ILLUSTRATION_MD_ERROR_ATTEMPT_2_NEW_VALUE:
            case 192:
            case SDK_ASSET_ILLUSTRATION_WARNING_EXIT_SPOT_2_VALUE:
            case SDK_ASSET_ICON_EXTERNAL_VALUE:
            case SDK_ASSET_ICON_ALERT_WARNING_VALUE:
            case SDK_ASSET_ICON_ARROW_DOWN_VALUE:
            case SDK_ASSET_ICON_ARROW_RIGHT_DOWN_VALUE:
            case SDK_ASSET_ICON_ARROW_UP_VALUE:
            case SDK_ASSET_ICON_CANCEL_VALUE:
            case 200:
                return true;
            default:
                return false;
        }
    }
}
