
9
-futures_order_confirmation_state_queued_titleö™ÄÂ¶µÑÿ
?
2futures_order_confirmation_state_unconfirmed_title©®ĞôÿËšÉ
<
0futures_order_confirmation_state_confirmed_title—­¦É›Úß‹V
C
7futures_order_confirmation_state_partially_filled_titleÁŠÿ‹Ø¤Óí
9
-futures_order_confirmation_state_filled_titleÃŠşËÖæò›
<
/futures_order_confirmation_state_rejected_titleÆõ¾Ÿ²õ˜İï
<
/futures_order_confirmation_state_canceled_title›®ÿñù±¨úš
8
,futures_order_confirmation_state_queued_desc—ğùè”Ûïúr
@
3futures_order_confirmation_state_queued_market_descÓüÃË¯ÃèÒÁ
=
1futures_order_confirmation_state_unconfirmed_descûì±¦­­±ˆ6
E
8futures_order_confirmation_state_unconfirmed_market_descÊÅĞİ˜ÅÊ…°
;
/futures_order_confirmation_state_confirmed_descŒ‰ß“‹±ÇÔ
B
6futures_order_confirmation_state_confirmed_market_descè«™ãÊÿ³õ0
C
6futures_order_confirmation_state_partially_filled_descõ†ÓßşÓ¬œÜ
Q
Dfutures_order_confirmation_state_partially_filled_rest_canceled_desc¿´Ğ’±úÂÊ£
9
,futures_order_confirmation_state_filled_descàõ¼îûİø
:
.futures_order_confirmation_state_rejected_desc’Œ‹ßÈÒ·u
;
.futures_order_confirmation_state_canceled_desc£Âì°å¿Êû
'
futures_order_market_labelï¬Â ¥‰–İ´
&
futures_order_limit_labelÁöÇü˜¥Ú´
)
futures_order_stop_loss_label‰èª™…¶ò0
+
futures_order_stop_limit_label•ä´×°á¨¸ò
0
$futures_order_confirmation_buy_labelß“ßå»Ï¼[
2
%futures_order_confirmation_sell_label£Ô½­ôéÊÙ”
0
#futures_order_confirmation_done_ctaî’Ü¢²øğøÙ
5
)futures_order_confirmation_view_order_cta•à§´ªÔÌ”
1
%futures_order_partial_quantity_format¢ïöûØ¿¾ûs
7
+futures_order_confirmation_filled_qty_labelÄ­ÿ¿€Í©Âr
>
1futures_order_confirmation_avg_filled_price_label±œç¹Á¾Á—
1
&futures_order_form_review_button_label¦¼Ï™üï
3
'futures_order_form_caret_double_up_descáô´×¿î€©G
,
 futures_order_form_caret_up_descËßî²ÀõÇ;
.
"futures_order_form_caret_down_descõºüïµù’”
6
)futures_order_form_caret_double_down_descåë§ãÁñÏ´
,
 futures_order_form_summary_titleÆ”£²¨‘ '
(
futures_order_summary_prices±Õ¨øªçÒ¢8
6
*futures_order_summary_gfd_expiration_today¿÷ÀÃÓ´é®i
:
-futures_order_summary_gfd_expiration_tomorrowÆ Ñí¶ ÒÜè
7
+futures_order_summary_gfd_expiration_futureòøº³Í³çúr
-
 futures_order_gold_savings_label›¯Ÿ ©´ÑÏƒ
 
futures_ftux_tooltipÂãöĞÛµ”å}
!
futures_flatten_label¡õÙÄ‘«†
#
futures_settings_labelò¿°™ÒŞ˜Ñ
3
'futures_settings_advanced_trading_labelèÁÒñâï—ëW
4
(futures_pnl_price_switcher_tooltip_labelı¼şˆàù
-
!futures_trade_time_in_force_labelÊ¦éĞ›¸¹õ
#
futures_trade_gfd_desc’¼—ñşé¹§
#
futures_trade_gtc_desc¡¤™ãêäû›
*
futures_trade_education_labelÌÔğ±áÉ¹¥â
7
*futures_trade_ladder_education_description¢îÂ¨ìüƒ¥å
8
,futures_trade_ladder_education_open_link_ctaŒˆŸ¨œÊîÎJ
3
&futures_settings_autosend_toggle_label¥Ø“Ëèğ·–¾
1
%futures_settings_autosend_toggle_descÆ øˆ‹—Ö@
2
%futures_order_form_market_order_label“ÕöØããÉÛù
1
$futures_order_form_limit_order_label³ÙØÛ…µı÷
0
#futures_order_form_stop_order_labelĞïæûãıÍ§
)
futures_order_form_buy_title±şòÆ‚ØÎó
)
futures_order_form_sell_titleÆ‡şÈÊøòz
6
)futures_order_form_buying_power_availableœİ”¡ƒí‹ŠÆ
-
!futures_order_form_quantity_labelğ±È“ÍÇP
7
+futures_order_form_market_order_price_labelüğûãí¶À
6
*futures_order_form_limit_order_price_labelÛ€é‹ò¨í|
5
)futures_order_form_stop_order_price_label†  ÷³×ÏÒ^
)
futures_order_form_bid_labelÉ‚¤À«œûó
(
futures_order_form_ask_labeløÃÊ¹ˆœÒ§x
<
/futures_order_form_time_in_force_selector_titleé¹òáÒÌŠ¬±
=
0futures_order_form_est_buying_power_effect_labelÒÚÄ€ë¸Œğ
2
&futures_order_form_commission_and_feesÒ·ÉòèÑØ
2
%futures_order_form_margin_requirement­“Û½í¡úª€
/
#futures_order_form_total_commissionÎíˆŠİãêİ 
;
/futures_order_form_regulatory_and_exchange_fees‹Õ×²ŠşÛ¬O
%
futures_order_type_labelã×Àæ€¥ˆ¥
4
(futures_order_type_market_buy_order_descºß¸‡¥ßæø 
5
)futures_order_type_market_sell_order_descºß¸‡¥ßæø 
4
'futures_order_type_limit_buy_order_descÈûÅ°èÛë‘¢
5
(futures_order_type_limit_sell_order_desc·ÈªÜ“Š”·
3
&futures_order_type_stop_buy_order_descÛ•©¢ôÍİ’
4
'futures_order_type_stop_sell_order_desc€ªÑÚşà³Ó
&
futures_ladder_title_label•èü¹Ş‡××a
1
%futures_order_form_summary_market_buyéßŒ‘€°éØT
2
&futures_order_form_summary_market_sellÁŞ²Ôßåïe
5
(futures_order_form_summary_limit_buy_gfd°™Ê°ô”İæ¸
6
)futures_order_form_summary_limit_sell_gfdˆ¹Éõ†ÅüÅé
4
(futures_order_form_summary_limit_buy_gtcôúŠ©õ™¥ÄB
5
)futures_order_form_summary_limit_sell_gtc¿³Î‡Õ‹¨éA
5
(futures_order_form_summary_limit_buy_ioc¢·é²Å”»â
6
)futures_order_form_summary_limit_sell_ioc¹Şª§Í±ê—ä
4
'futures_order_form_summary_stop_buy_gfd‰¶’¨ÌÁˆ¦¾
5
(futures_order_form_summary_stop_sell_gfdâããÂŞûºÂÆ
4
'futures_order_form_summary_stop_buy_gtcÓƒÔÒÄ‹¦î
5
(futures_order_form_summary_stop_sell_gtcÿïÇÆğ‚º¦‡
4
'futures_order_form_summary_stop_buy_iocÃû™§„µäû¤
4
(futures_order_form_summary_stop_sell_ioc¼½œ¤çæ¬