
0
$instrument_ratings_summary_label_buy¥¨×÷¢·˜£m
1
%instrument_ratings_summary_label_holdìµ·çá¦Ì“
1
%instrument_ratings_summary_label_sellš•Î¾Úâh
0
$instrument_ratings_rating_header_buyĞé“ÍĞ³Ö6
2
%instrument_ratings_rating_header_holdÆÆéÍ¯¤»Î
2
%instrument_ratings_rating_header_sellÌƒ¦÷ü¦óÇº
2
%instrument_ratings_rating_body_format‡ïÍËíâŠÄŞ
G
:gated_morningstar_instrument_ratings_rating_source_defaultÁĞâÜ‹÷éøÕ
3
&instrument_ratings_rating_published_onªøı–šØÜ»ï
/
#instrument_ratings_rating_show_moreÑ†¹¨„ĞÚì
5
)content_description_expand_collapse_caretÒœ¶±úñ„¼j