
3
&futures_order_detail_view_contract_ctaÒâûëÏêŞ»ï
/
"futures_order_detail_queued_headerğğæâ†Ï§×„
+
futures_order_detail_subheaderşƒ•›à“…ã·
.
"futures_order_detail_account_label´­øû±éQ
1
$futures_order_detail_account_futures¿ó®¥ÕÁ­
3
'futures_order_detail_order_status_label«æÃã¸€©Œ&
4
(futures_order_detail_time_in_force_labelÊ¦éĞ›¸¹õ
1
$futures_order_detail_submitted_label·¯Ìò¥š—•ü
2
&futures_order_detail_limit_price_labelÛ€é‹ò¨í|
1
%futures_order_detail_stop_price_label†  ÷³×ÏÒ^
6
*futures_order_detail_filled_quantity_labelÄ­ÿ¿€Í©Âr
7
+futures_order_detail_filled_quantity_format•›÷Ü‰ß“.
3
&futures_order_detail_filled_time_labelåãÓáºµ¨Îæ
8
+futures_order_detail_avg_filled_price_label±œç¹Á¾Á—
6
*futures_order_detail_execution_price_labeláå×ÒŒÌ‡ÀS
6
*futures_order_detail_realized_profit_labelçäŞ‹¿ô™É
5
(futures_order_detail_realized_loss_labelæœ¸¨õ„ØÁÆ
$
futures_total_cost_label£ºè—íñ¥œ
'
futures_total_credit_labelİ‰¼İÛı—Áı
7
*futures_exchange_and_regulatory_fees_labelÒĞê¼§™ò¬
)
futures_commission_fees_labelÿ–ÚÏ¿¬©Í_
-
 futures_total_gold_savings_label‰ÇÚƒ¦ßúç¡
+
futures_order_detail_cancel_ctaé†Éï‹•Îù~
1
$futures_cash_correction_detail_titleİï†ÖšÓôÒÚ
9
-futures_cash_correction_detail_pay_date_labelˆ©¹©Îçï÷i
8
+futures_cash_correction_detail_reason_labelÀÕº¹ÀÅè±ª
9
,futures_cash_correction_detail_reason_credit“ ñÚÆ¢èÈ±
L
@futures_cash_correction_detail_reason_commission_and_fees_creditşïÅÛÙ•ö¼
<
/futures_cash_correction_detail_reason_write_off±Å¸Áòµ ¼
=
0futures_cash_correction_detail_reason_adjustmentİï†ÖšÓôÒÚ
=
1futures_cash_correction_detail_reason_unspecified¦»È¶¿ËÚS
0
#events_cash_correction_detail_titleãšåÒ‰ôÔçë
7
+events_cash_correction_detail_reason_creditÓç—ˆ¹€‰ÅZ
K
?events_cash_correction_detail_reason_commission_and_fees_credit¸ÔæÄÍÆé?
:
.events_cash_correction_detail_reason_write_offÒÊÚü½ŞøÅ_
<
/events_cash_correction_detail_reason_adjustmentãšåÒ‰ôÔçë
0
#futures_history_disclaimer_markdown¿Üà«Ÿâœ“È
+
futures_executions_detail_title€‰ªâù­¢ğ	
3
'futures_executions_detail_account_label´­øû±éQ
4
'futures_executions_detail_account_valueˆÏ¿Æªãéü
<
/futures_executions_detail_settlement_time_labelºô…€ °“†‹
=
0futures_executions_detail_settlement_price_labelÙÖ‘¶¯ßü¡¥
4
(futures_executions_detail_quantity_labelğ±È“ÍÇP
;
/futures_executions_detail_realized_profit_labelçäŞ‹¿ô™É
:
-futures_executions_detail_realized_loss_labelæœ¸¨õ„ØÁÆ
1
$futures_executions_detail_fees_labelÒĞê¼§™ò¬
6
*futures_executions_detail_commission_labelÿ–ÚÏ¿¬©Í_
3
&futures_executions_detail_gold_savings›¯Ÿ ©´ÑÏƒ
6
*futures_executions_detail_total_cost_label£ºè—íñ¥œ
9
,futures_executions_detail_total_credit_labelİ‰¼İÛı—Áı