
,
 order_confirmation_status_queued¬„•Ğ‰†³,
1
%order_confirmation_status_unconfirmedÿôÏ‡¹„â
/
#order_confirmation_status_confirmed¹ìÜÔ†ˆ’
6
*order_confirmation_status_partially_filled€­ÿÂì¬"
5
(order_confirmation_status_pending_cancelŸÕ€ğà‹ìë
,
 order_confirmation_status_filledä¢€éòÕÖ„
.
"order_confirmation_status_rejectedª ôòĞ¨¨æ&
.
"order_confirmation_status_canceled÷˜¾­Ÿõæˆ!
,
 order_confirmation_status_failedªÙòİ»ˆÄô
,
 order_confirmation_status_voidedÓ¦û’ÿÌŸİ
.
"order_confirmation_status_locatingÿôÏ‡¹„â
M
Aorder_confirmation_description_order_type_market_collaring_memberŸ’¼óŒ×ƒ_
;
/order_confirmation_description_order_type_limit²§©í«‚€Ô]
@
3order_confirmation_description_order_type_stop_loss›×¥€Êùê„
@
4order_confirmation_description_order_type_stop_limitª°ØÒÚ¡äb
C
7order_confirmation_description_order_type_trailing_stop¸ÑŸáæı¹È7
O
Border_confirmation_shares_buy_queued_description_collaring_removalÆ‡¹ëï€â°Û
E
8order_confirmation_shares_buy_queued_description_pre_ipo¶ÔÜæüòü–Ú
B
5order_confirmation_shares_buy_unconfirmed_descriptionçåêëµóğÙÇ
?
3order_confirmation_shares_buy_confirmed_descriptionÃùæªÕ¿íS
G
:order_confirmation_shares_buy_partially_filled_descriptionÔÚŸÛÇ÷ü¡å
<
0order_confirmation_shares_buy_filled_description÷é«ãŒ©Ğ¼7
?
2order_confirmation_shares_buy_rejected_descriptionè¸ÇÄ„ş­Ä
D
8order_confirmation_shares_buy_pending_cancel_descriptionùğß©ñüŞ
>
2order_confirmation_shares_buy_canceled_description‡¹º§Â˜‚ºW
=
0order_confirmation_shares_buy_failed_description­˜Øó…×öÌö
<
0order_confirmation_shares_buy_voided_descriptionÖ’ªõÍšø±!
F
9order_confirmation_shares_buy_to_close_queued_descriptionÊ±Öâ§¢û¹
J
>order_confirmation_shares_buy_to_close_unconfirmed_description€Á‘–ÛúS
I
<order_confirmation_shares_buy_to_close_confirmed_descriptionåÂ½§©Áş
O
Corder_confirmation_shares_buy_to_close_partially_filled_description…£ßÚ”N
E
9order_confirmation_shares_buy_to_close_filled_descriptionæ™Ì¤ê¬
H
;order_confirmation_shares_buy_to_close_rejected_descriptionØÈæ»®¶ó¢
M
Aorder_confirmation_shares_buy_to_close_pending_cancel_descriptionÄöíù«àò:
G
;order_confirmation_shares_buy_to_close_canceled_descriptionú—½èÌ”°ÜZ
F
9order_confirmation_shares_buy_to_close_failed_descriptionÌŠ÷»ƒÙ»Š‰
F
9order_confirmation_shares_buy_to_close_voided_descriptionÒË”¿Ø¿°»ô
P
Corder_confirmation_shares_sell_queued_description_collaring_removal»¯ëö¢Ë‹¨š
F
9order_confirmation_shares_sell_queued_description_pre_ipoÎŒ¹ù¸ËûàŠ
B
6order_confirmation_shares_sell_unconfirmed_descriptionÛ¼ì§ğÆø³
A
4order_confirmation_shares_sell_confirmed_description‚Ü”æñşŠÊ„
G
;order_confirmation_shares_sell_partially_filled_description”ºşÕÓŸĞÆ+
=
1order_confirmation_shares_sell_filled_description’¯Îæ÷õëß
@
3order_confirmation_shares_sell_rejected_descriptioníé«¨½…“¶ø
E
9order_confirmation_shares_sell_pending_cancel_description¼æ•ÄÆ½Ó

?
3order_confirmation_shares_sell_canceled_descriptionøíº½¼’ïŠE
=
1order_confirmation_shares_sell_failed_description÷¹úòá•–çZ
>
1order_confirmation_shares_sell_voided_descriptionàéÄºôÿàÄ›
C
7order_confirmation_shares_sell_short_queued_descriptionÀé–À½é:
H
<order_confirmation_shares_sell_short_unconfirmed_descriptionå¦²ìÔ‚©|
G
:order_confirmation_shares_sell_short_confirmed_descriptionüé¸ÑäÄÍê 
M
Aorder_confirmation_shares_sell_short_partially_filled_descriptionĞÊÓ÷½¼ì¶!
C
7order_confirmation_shares_sell_short_filled_descriptionÍµ×¨Î™ç¦:
F
9order_confirmation_shares_sell_short_rejected_descriptionŞî±¶¶ÕÕ‡
K
?order_confirmation_shares_sell_short_pending_cancel_description¶ÖÌ…ñ»Œo
E
9order_confirmation_shares_sell_short_canceled_descriptionóòÌæåí¬Ø
C
7order_confirmation_shares_sell_short_failed_description’ßÏÚâäÍ
D
7order_confirmation_shares_sell_short_voided_description´«Õù¹¼‰™
F
9order_confirmation_shares_sell_short_locating_description¬şÇÚ¡ö™Š¼
J
>order_confirmation_shares_sell_short_locate_failed_descriptionÀŞ¤»ÍéÚ\
O
Border_confirmation_dollar_buy_queued_description_collaring_removalşÓéõÙØÂáÛ
D
8order_confirmation_dollar_buy_queued_description_pre_ipoƒ¶Óúµ¸ö§l
A
5order_confirmation_dollar_buy_unconfirmed_description¿Ë²“Æ¢Şız
?
3order_confirmation_dollar_buy_confirmed_description¥Š·‹£ÍÓÇX
F
:order_confirmation_dollar_buy_partially_filled_descriptionøÖÙ€Şèº˜/
<
0order_confirmation_dollar_buy_filled_descriptionÖºüúüãêJ
=
2order_confirmation_dollar_buy_rejected_descriptionãç‰ö¡æìz
>
2order_confirmation_dollar_buy_canceled_description…³Ûİ‹ˆ”…|
=
0order_confirmation_dollar_buy_failed_descriptionÁáö§ıúóµƒ
P
Corder_confirmation_dollar_sell_queued_description_collaring_removalâ¸³ò…‡Í
F
9order_confirmation_dollar_sell_queued_description_pre_ipoŒÄ•…Øƒâ¶
C
6order_confirmation_dollar_sell_unconfirmed_description‰Øéı¤€‚–
@
4order_confirmation_dollar_sell_confirmed_description¸ß¢Ù‰×­'
G
;order_confirmation_dollar_sell_partially_filled_description—ÊÊü‡Œ¸;
>
1order_confirmation_dollar_sell_filled_descriptionÑØòÈëúÂô
?
3order_confirmation_dollar_sell_rejected_descriptionâŸÄÃö¸½2
@
3order_confirmation_dollar_sell_canceled_description˜“óã™Õ¦¶í
=
1order_confirmation_dollar_sell_failed_description¤—°ìÄá“˜v
-
 replace_order_old_pending_cancelÄƒæïÎ‘‚¡â
&
replace_order_old_canceled¸Ğéş¡ãÛÇJ
1
%order_confirmation_buy_quantity_labelææÊêüèœÆ
2
&order_confirmation_sell_quantity_label‚ú‚‡“íÅ»G
8
,order_confirmation_sell_short_quantity_label÷ƒÎ–î€Á¾C
/
#order_confirmation_buy_amount_labelêìÏ«›òìù7
1
$order_confirmation_sell_amount_labeläÚ©—õíÓ†
5
(order_confirmation_partial_fill_quantityŠÊõİ¶Ûö£Î
2
&order_confirmation_partial_fill_amountÇˆãÔò¦*
(
replace_order_new_queued_buy®áÉ÷Ú®
.
!replace_order_new_unconfirmed_buyìßî§ëûáó­
+
replace_order_new_confirmed_buy±ñçœ™÷›
2
&replace_order_new_partially_filled_buyæ¦¦Œ¶ê¶t
(
replace_order_new_filled_buy÷‰¯Õï™³É
*
replace_order_new_rejected_buyğ£ñÜŞğ¦¨P
)
replace_order_new_voided_buy˜Šş›©˜èµÕ
0
$replace_order_new_pending_cancel_buy‚Ï‡¤‡ØÂ¥/
+
replace_order_new_canceled_buyÓç©Íªæ›ÿ³
(
replace_order_new_failed_buyŸØßÕè§Ş‚j
2
%replace_order_new_queued_buy_to_closeğüÚ­úÄ¨Øğ
7
*replace_order_new_unconfirmed_buy_to_close¾ñÛ Î×¡ã
4
(replace_order_new_confirmed_buy_to_close›ÖËáô‚š¤8
<
/replace_order_new_partially_filled_buy_to_closeó£İê¦»„Ç
2
%replace_order_new_filled_buy_to_close“¥™»úè–œ¯
4
'replace_order_new_rejected_buy_to_closeèÏ¡°ŠõšËÊ
1
%replace_order_new_voided_buy_to_close¯Áš¨áùŸâU
9
-replace_order_new_pending_cancel_buy_to_closeã¿ï¹ø¾ú¸<
3
'replace_order_new_canceled_buy_to_closeØ£ôÁ¯îÓ
1
%replace_order_new_failed_buy_to_close¨‹Ãš¥«øÃ
*
replace_order_new_queued_sellŸå½±ô•ë®
/
"replace_order_new_unconfirmed_sellÆÕï’ç§ú²µ
,
 replace_order_new_confirmed_sellóŸŞ®§™ùe
3
'replace_order_new_partially_filled_sellŠ­¬”æ’íç0
*
replace_order_new_filled_sell…ˆÀ’‚ÜÔ²œ
+
replace_order_new_rejected_sellğé§™á–à‹?
*
replace_order_new_voided_sellª¯ãÌÛŸáÑ
2
%replace_order_new_pending_cancel_sellô›¯©…ÅûìÄ
+
replace_order_new_canceled_sell²æ¦ØÏ°ûb
)
replace_order_new_failed_sellŸÃ¶Ëøá ;
0
#replace_order_new_queued_sell_short·Ûœ¨’©èúæ
5
(replace_order_new_unconfirmed_sell_short§Ï¼”å¬€Ô­
3
&replace_order_new_confirmed_sell_shortõĞôÇöéíò™
9
-replace_order_new_partially_filled_sell_shortÁÂŞœ€«ÁØH
0
#replace_order_new_filled_sell_shortÑØè²»÷ûî
2
%replace_order_new_rejected_sell_shortÎ…â¢â›âş
/
#replace_order_new_voided_sell_shortôßó×ôöŠã

7
+replace_order_new_pending_cancel_sell_short§’¨œöüÖ%
1
%replace_order_new_canceled_sell_short±×´‹‘ÿ Çl
0
#replace_order_new_failed_sell_shortí‰¯ç½ÊÅô·
1
%replace_order_new_locating_sell_shortî¢˜¥ÑáK
7
*replace_order_new_locate_failed_sell_shortêÉ›‰ı£“â­
#
replace_order_remainingŞ¶¤ºÄ•ğÏ1