
.
"insights_edit_investment_btn_title‹¼Ş‰Àóñ4
(
recurring_frequency_biweekly¬àÕÚ¥ñ®>
%
recurring_frequency_daily´ªêªÈ÷á
'
recurring_frequency_monthly‚‘àçéƒÎø5
'
recurring_frequency_weekly¦‚ã¥ßî•Ö‰
.
"recurring_frequency_label_biweekly¬àÕÚ¥ñ®>
8
,recurring_frequency_label_biweekly_lowercase›™ÛõÏÈíáj
+
recurring_frequency_label_dailyóÙõ‡¡´„Ã
6
)recurring_frequency_label_daily_lowercaseÍÇŠêÇ±âñœ
.
!recurring_frequency_label_monthlyóÌ×„®ô»
8
+recurring_frequency_label_monthly_lowercase¬›Ø’À¿ë´“
-
 recurring_frequency_label_weekly­ë²°¢­¬ÈÏ
7
*recurring_frequency_label_weekly_lowercaseéå‰Ë˜¯ŠÃ
4
(recurring_amount_buying_power_info_titleæªÀÙ¡ÿ¬ÖM
:
.recurring_amount_buying_power_info_descriptionğ—´ÕıP
E
8recurring_tokenized_amount_buying_power_info_descriptionºÖ‰«Œƒ»¥Ï
9
,recurring_amount_buying_power_info_ok_buttonŸ¡Ô·øñª‹
2
&recurring_source_of_funds_buying_poweræªÀÙ¡ÿ¬ÖM
 
recurring_date_todayóÕ¸†çı³¶V
'
recurring_date_today_lowerÇñ´Ô·°ûúÚ
$
recurring_date_tomorrow÷…‘§Ø”Œ
)
recurring_date_tomorrow_lower®¼»ÒÉ‚ÒË7
1
$recurring_disclosure_frequency_dailyÍÇŠêÇ±âñœ
1
%recurring_disclosure_frequency_weeklyäæî¼ÆáóS
4
'recurring_disclosure_frequency_biweeklyùÖï¤€ä¡¿
3
&recurring_disclosure_frequency_monthlyçâğ©ÍÓÓ¡İ