
,
advanced_chart_onboarding_titleçåîø»¶ú«ì
2
%advanced_chart_onboarding_descriptionğàË³æ…Ä„
)
advanced_chart_learn_more_url‰„íÎ›ú›ò~
0
$advanced_chart_edit_indicator_periodÖù˜¿ßºr
:
.advanced_chart_edit_indicator_overbought_levelìÉ˜é×ÿŞä
9
,advanced_chart_edit_indicator_oversold_level¼¥÷úİÙàµ
6
)advanced_chart_edit_indicator_fast_periodƒŠÕ…ÅÒà‡Š
6
)advanced_chart_edit_indicator_slow_periodıõÕŸ¨£ßÌ
8
+advanced_chart_edit_indicator_signal_period¶¾€‰£Ú€şî
8
+advanced_chart_edit_indicator_length_periodøï‰ ¾ä­İ»
7
+advanced_chart_edit_indicator_std_deviationÂı×Ù¢ííÂ
9
,advanced_chart_empty_state_add_indicator_btn–¥¾Ñ‹Ÿä¶í
/
#advanced_chart_indicator_list_titleÈîÌ½Ôüë©
8
+advanced_chart_indicator_list_add_indicator©Ü™æØ¯œßà
4
(advanced_chart_indicator_list_empty_list¥‰°ãî˜‡ŞI
?
2advanced_chart_add_indicator_title_with_indicatorsË°Öí¯àïìã
0
$advanced_chart_error_single_ti_title€˜Ê®‘‹‹Œ
2
&advanced_chart_error_single_ti_messageµí¤ƒÂ·Ær
.
!advanced_chart_error_max_ti_title·š¥À¼„¦
/
#advanced_chart_error_max_ti_message„š¸•Íü´
7
*advanced_chart_zoom_nux_bottom_sheet_title¯õÿşËé˜ıõ
5
)advanced_chart_zoom_nux_bottom_sheet_body·â¿ÄäÏƒú.