
%
acats_plaid_partial_bodyâÀÿ†ĞŸÙ­·
)
acats_plaid_partial_continueğñ·‡ªıÍÖö
?
2acats_plaid_partial_non_transferable_assets_banner¼¿äêÉš˜…È
/
"acats_plaid_partial_cash_sort_chipòî€å¸œÚÓ
C
6acats_plaid_partial_options_expiration_contracts_shortİùŸ“‡è‡×¦
A
5acats_plaid_partial_options_expiration_contracts_longš—¬Šâ„Ñ§
4
(acats_plaid_partial_transfer_confirm_btnËÑöŠï»úŠW
4
'acats_plaid_partial_transfer_remove_btnë±şÅ¯–íÑ
:
.acats_plaid_review_non_transferable_assets_cta»ñÁ¿æËğøY
@
3gated_etf_acats_plaid_partial_transfer_stocks_titleÆ¥æ²ßŠ¼ôŠ
;
.acats_plaid_partial_transfer_edit_cash_balance†ú´ÿÒÑ·±
9
,acats_plaid_partial_transfer_edit_stock_etfsÎƒ‰Ö¡’ŒÌ±
=
0acats_plaid_partial_transfer_edit_margin_balance ¥çô£ÆÚÓÓ
9
,acats_plaid_partial_transfer_edit_update_btn¢çÉåÄß
;
.acats_plaid_partial_transfer_edit_whole_number”èÈ¬ıöÔ²€
5
)acats_plaid_partial_transfer_edit_invalid¥ÔÓßíÖ°èb
.
!acats_plaid_cannot_complete_title©©ÏíŞ¾´›Ï
,
 acats_plaid_cannot_complete_body¤ä¿åêÜ½Ók
,
 acats_plaid_cannot_complete_linkñƒê«¬·
-
 acats_plaid_cannot_complete_doneî’Ü¢²øğøÙ
5
)acats_plaid_partial_transfer_removal_bodyİèÎïéì ½Q
9
,acats_plaid_partial_transfer_removal_confirmôÍ¹İ­ë¶´‰
8
+acats_plaid_partial_transfer_removal_cancelÜ’¦¼©ÂÅ«
6
*acats_plaid_partial_transfer_removal_titlešÂòü°óóE
>
1acats_plaid_partial_transfer_removal_title_margin¬ª ‚èû’¬õ
;
/acats_plaid_partial_transfer_removal_title_cash‡ù±ØçôÌ¹#
9
,acats_plaid_partial_transfer_swipe_to_removeôÍ¹İ­ë¶´‰
<
/acats_plaid_partial_transfer_onback_alert_titleº³”Â“Âô˜¨
:
.acats_plaid_partial_transfer_onback_alert_bodyÚßŠ¸Ï™„ì
>
1acats_plaid_partial_transfer_onback_alert_confirm«ëç±ì«‘±
<
0acats_plaid_partial_transfer_onback_alert_cancelÖï³¼Ì†€!
9
,acats_plaid_partial_options_expiration_shortŒ³í°Şœõ®ß
7
+acats_plaid_partial_options_expiration_long¡ß¥¨äÂ£ãz
0
$acats_plaid_unsupported_assets_titleäÎ¸ÎÒ‹¿F
2
&acats_plaid_unsupported_assets_messageÖè®àê¯~
8
+acats_plaid_unsupported_assets_message_link¬ƒ…ûòÎ™·ß
/
#acats_plaid_fractional_shares_title›èš”Ë½ú…W
*
acats_plaid_mutual_funds_titleşË×ÑÔÕÈ(
+
acats_plaid_fixed_income_titleÖŠ¼±¿Î¼¸’
#
acats_plaid_other_titleËïçªâÆËç
&
acats_plaid_partial_title°×ïİòë†‰

sharesÓ€µ¨ú‚³¨}

	contracts§øØøˆşõÅ