
(
advanced_chart_empty_string¹ì½¡Œïç”
,
 advanced_chart_indicator_type_ma÷Ö¹ÄÔŸŠÀ2
-
!advanced_chart_indicator_type_rsi¾ùà‰—öŠŒr
/
"advanced_chart_indicator_type_macd­×“ÛÃ´’â
.
!advanced_chart_indicator_type_ema€÷ÃŞ§ù‡›
.
"advanced_chart_indicator_type_vwapëãÈ™Š»Şêy
/
"advanced_chart_indicator_type_bollò¨İ’ƒôÏı
6
)advanced_chart_info_bottom_sheet_title_maè•½Ø…×˜“Ê
6
*advanced_chart_info_bottom_sheet_title_rsi•¿ŠÎ¥ëóİY
7
+advanced_chart_info_bottom_sheet_title_macdš¨²Àéß¥ƒ_
6
*advanced_chart_info_bottom_sheet_title_ema¯ÍùêçÓú÷<
7
+advanced_chart_info_bottom_sheet_title_vwapÁê¹íµÍ¿Ô]
7
+advanced_chart_info_bottom_sheet_title_bollà“Ò…û›ÉH
8
+advanced_chart_info_bottom_sheet_content_maü¥–ÓÛä–
9
,advanced_chart_info_bottom_sheet_content_rsi¯©¢ïö…¡
:
-advanced_chart_info_bottom_sheet_content_macd†³…Èî¾®ëİ
9
,advanced_chart_info_bottom_sheet_content_emaİùœ¬öş‹É“
9
-advanced_chart_info_bottom_sheet_content_vwapéüéµÿ×‹´$
:
-advanced_chart_info_bottom_sheet_content_boll”ò‰µƒ„Œ‡â