
*
option_alert_onboarding_titleÚµÅ¥ÖºŒÜ—
)
post_trade_option_alert_title¥¤˜¥¬¾øÎ*
,
option_alert_onboarding_summary Éè¦®Íš¾
+
post_trade_option_alert_summaryÙ´Ï¬¯Í¸ñg
4
'option_alert_onboarding_positive_button¯¼˜é¾ÑÜå
8
+option_alert_go_to_settings_positive_button“à÷”ó°ƒ–É
4
'option_alert_onboarding_negative_buttonûÒãİ“êÂ™ü
6
*option_alert_onboarding_error_dialog_titleàÅ¹»†…äİ
9
,option_alert_onboarding_error_dialog_message—ï¬ çÑğ§•
2
&option_alert_onboarding_learn_more_url’€Šéƒİ«ûb
4
(option_alert_retirement_onboarding_title”ÆÉ¹ğÎ¦#
6
*option_alert_retirement_onboarding_summaryêÀÓ¡¥ÔøJ
.
!option_alert_onboarding_title_new˜ÍŸßàˆºû¸
0
#option_alert_onboarding_summary_newÄÅ®İ‹Ş½ä©
8
+option_alert_onboarding_negative_button_newäœ€Ê¬‡…²
<
/trade_on_expiration_upsell_default_account_nameÚ’ñ‹ÂíÖ°
?
2trade_on_expiration_upsell_title_with_account_info¤¸ŒÈ¯ùù•
/
#trade_on_expiration_upsell_subtitleÚ²ñÂ†ù­ëR
/
#trade_on_expiration_upsell_bullet_1Ïñ‘ÉéÄ·‚?
.
!trade_on_expiration_upsell_body_1üß™ÈÑ¯ÉÈ¡
/
#trade_on_expiration_upsell_bullet_2¿æ„¯ÏÚÃë5
.
!trade_on_expiration_upsell_body_2›ı¤°“†ùÅé
/
#trade_on_expiration_upsell_bullet_3¿ˆÜŸí‘x
-
!trade_on_expiration_upsell_body_3òÊ³êïôÅ
6
*trade_on_expiration_upsell_button_positiveüİÃÄ¬ƒ•üQ
7
*trade_on_expiration_upsell_button_negativeûÒãİ“êÂ™ü
;
.trade_on_expiration_upsell_button_negative_newäœ€Ê¬‡…²
/
"option_settings_confirmation_titleÃ»Ä­¢±Íı
4
(option_settings_confirmation_descriptionÚúœã§šåİg
2
&option_settings_explore_options_buttonßäİÀ£Ó=
1
$discover_zero_dte_bottom_sheet_title›šè±©ô·
0
#discover_zero_dte_bottom_sheet_bodyôâıéæ±Š¢ê
G
;gated_etf_discover_zero_dte_bottom_sheet_body_index_optionsøôÇâé¯¨=
K
>gated_etf_discover_zero_dte_bottom_sheet_body_index_options_si¬ëñÇ¢Ô¥Ü
E
9non_etf_discover_zero_dte_bottom_sheet_body_index_optionsœÌÆ“•™Óe
L
@discover_zero_dte_bottom_sheet_body_index_options_pdt_postscript…®Æû çÒà
1
$discover_zero_dte_bottom_primary_cta·Ø€Ÿ¯Âº 
.
"discover_zero_dte_snackbar_contentöÎ´†‡Œ
.
!discover_zero_dte_snackbar_action‰’ø¢ƒÈæ¬¼
*
option_confirmation_title_sdpŞ¤Áöø„Ë½«
-
!option_confirmation_title_non_sdp“ÕÄ…‡ğ–Èq
0
#option_confirmation_description_sdpèÿé–†ã„
3
'option_confirmation_description_non_sdpšª–ÓŞ•³ØQ
-
!profit_loss_chart_education_title¯èÒÇ¸ŒÔ´.
4
'profit_loss_chart_education_descriptionà­²×°ç×”
9
-profit_loss_chart_education_chart_description£‹«–”òùŸe
?
2profit_loss_chart_education_chart_max_profit_titleıšÚ’¿•îÈ¸
D
8profit_loss_chart_education_chart_max_profit_description—î™ö˜ŞÑ¦s
=
1profit_loss_chart_education_chart_breakeven_titleÉïÉ‘øÛi
C
7profit_loss_chart_education_chart_breakeven_description¢íÚ€ú®ÖÖ)
<
0profit_loss_chart_education_chart_max_loss_titleĞ±‚Õ¶(
C
6profit_loss_chart_education_chart_max_loss_description˜ºÄİ¡å€®
9
,profit_loss_chart_education_help_center_linkÓù¨Øª‚Ìé³
7
*double_tap_to_watchlist_bottom_sheet_titleòõ“ıÍ½ˆ‹ê
5
)double_tap_to_watchlist_bottom_sheet_bodyÄÛºŠ‘ï×‘
1
$option_upgrade_experience_disclaimer£†ñïŸËóÂË
B
6option_upgrade_professional_question_investment_advice®—Ä¯·­•ï
D
8option_upgrade_professional_question_financial_regulatorğì˜¬‰ÛşêL
2
&option_upgrade_professional_disclaimer½—…¦±û¤t
/
"option_order_contract_equity_priceÃ·ÍšâÈáâ±
-
!option_order_contract_index_valueüşùÂæåß”I
*
option_strategy_header_greeksÈ¶ ‹ßš½éÄ
%
option_detail_quote_sizeıˆ¸ˆùÉšó
/
"option_detail_statistics_bid_labelÉ‚¤À«œûó
.
"option_detail_statistics_ask_label¸¢ã»Øòáş
%
option_order_est_max_cost¬‰’„ÂıÍ2
(
option_order_est_min_credit½èÜÅõ€„™µ
#
option_order_est_total»¥¢æ¦‹¬ûï
"
option_order_est_costêº¤×»§£àş
#
option_order_est_creditš¦ÇŞ‘æ¦
(
option_order_estimated_total¡¹¤›êÑ±Ü0
'
option_order_estimated_costè…˜œáµ±¦
)
option_order_estimated_creditñÓ÷«¥™ÓŒA
(
option_order_max_cost_label¡¿ıŒİôî¾ë
)
option_order_min_credit_label›•Š°˜Ğ·¼$
.
"option_order_ambiguous_total_labelÌØãŞí…Èx
,
option_order_total_credit_labelİ‰¼İÛı—Áı
)
option_order_total_cost_label£ºè—íñ¥œ
3
&option_order_est_ambiguous_total_label»¥¢æ¦‹¬ûï
/
#option_order_est_total_credit_labelâˆ£Ò¸ŸÄW
-
!option_order_est_total_cost_label óúî°ºÅ„