
E
9gated_crypto_order_type_education_limit_buy_prompt_crypto›ŒÊ‰¾ÜÕûj
F
:gated_crypto_order_type_education_limit_sell_prompt_crypto¾ËªÊ½ïñò
J
>gated_crypto_order_type_education_animation_label_crypto_price©ñ¯šïª±.
J
=gated_crypto_order_type_education_animation_label_limit_price™ÓÜ’ñŒ°Ü
I
<gated_crypto_order_type_education_animation_label_stop_priceòÜêÌñç§°Ï
J
>gated_crypto_order_type_education_animation_label_market_order¬¼ÙèéÇü½S
$
order_type_market_title“ÕöØããÉÛù
#
order_type_limit_title³ÙØÛ…µı÷
"
order_type_stop_titleĞïæûãıÍ§
'
order_type_stop_limit_titleí¶ñİÆèŞ¡d
=
1order_type_education_stop_limit_buy_prompt_cryptoçĞ¬‚¶Á‡’s
>
2order_type_education_stop_limit_sell_prompt_cryptoÅìÚÆó•šü
B
5order_type_education_stop_buy_prompt_collaring_memberşø²Ñ¤àøÔÇ
C
6order_type_education_stop_sell_prompt_collaring_memberÔâ‰‹è’Ş”ü
I
=gated_crypto_order_type_education_limit_long_prompt_perpetualêÑˆ—îÜÁğ_
J
>gated_crypto_order_type_education_limit_short_prompt_perpetualà¹õµ£ô/
<
/tokenized_order_type_education_limit_buy_prompt¶èãúé´˜Àû
<
0tokenized_order_type_education_limit_sell_promptÉ‡ìİ±„ºÎ
G
:tokenized_order_type_education_animation_label_token_priceÀõ¸Æ‚µÅÖÔ
5
(order_type_education_recurring_buy_title®©Ò“ï±“¡€
2
&order_type_education_market_buy_promptõ—Û½÷¨€t
4
'order_type_education_market_sell_promptÀÊƒÖ³Ì¡ÑÂ
2
%order_type_education_limit_buy_promptÖäé‰ÁèØ‰ß
2
&order_type_education_limit_sell_promptø›Ã›Îšæş
7
*order_type_education_stop_limit_buy_promptãí›À˜¢î€Ù
8
+order_type_education_stop_limit_sell_promptê™Ë‹úšğ­½
J
>order_type_education_trailing_stop_buy_prompt_collaring_member‡òÛŞÏ‡äJ
K
?order_type_education_trailing_stop_sell_prompt_collaring_memberÏ‹ä§¨İ—©6
6
)order_type_education_recurring_buy_prompt„‰ÏÕåÉ–ºğ
;
.order_type_education_recurring_disclaimer_textÚŞ€ÎÎëøÅ©
A
5order_type_education_recurring_disclaimer_alert_title¥ÚØíÿ·3
H
;order_type_education_recurring_disclaimer_alert_descriptionİŒ¢üØÄÌÏ˜
<
0order_type_education_animation_label_stock_price³‰Ş–ä²¼ÌA
;
/order_type_education_animation_label_stop_price†  ÷³×ÏÒ^
E
8order_type_education_animation_label_trailing_stop_priceÖ“’ßİ¯æ¶
>
1order_type_education_animation_label_market_order²»İÈ­Èè
*
order_type_trailing_stop_titleı®ä ²ÇäQ