
4
(rewards_onboarding_setup_brokerage_title˜¼¼÷»ÑÛ_
6
*rewards_onboarding_setup_brokerage_message¬è•İ‡Ë™ù	
6
)rewards_onboarding_setup_brokerage_buttonó®Õ§ï¡›Šö
.
"rewards_onboarding_asset_selectionûâÏ•½ş¼
/
"rewards_onboarding_sign_up_turn_on‚ûíŒà¾é¨¤
<
0rewards_onboarding_crypto_agreement_dialog_title¦–ÄóÃÚ‹Û9
>
2rewards_onboarding_crypto_agreement_dialog_message£¸ÚªÜí¶
/
#rewards_onboarding_review_agreement¢ñ¦ò¶®Ğ¨q
8
+rewards_onboarding_suitability_dialog_title­äí´çÕ½š
8
-rewards_onboarding_suitability_dialog_message·çƒĞÁˆƒ+
#
rewards_learn_more_urlùÅƒáòığüÁ
;
/rewards_onboarding_application_submitting_titleµ÷•±¶¶¾‰J
?
2rewards_onboarding_application_submitting_subtitle•ÇÿıéÎ³š
D
8rewards_onboarding_application_submitting_title_spending«ıà®Ä•±­M
H
;rewards_onboarding_application_submitting_subtitle_spending˜ÄÚ˜Ë±¥Š÷
2
&rewards_onboarding_application_pendingÖÜçìÄÌÁG
7
+rewards_onboarding_application_review_titleÆÇ°ÇÆìÄi
9
-rewards_onboarding_application_review_messageºÌÔê•×†
:
-rewards_onboarding_application_approved_titleËÊÍ‹œçèÅĞ
;
/rewards_onboarding_application_approved_message–¢›©ÒŞåº
B
6rewards_onboarding_application_approved_title_spending–¨¦‚ù´âï
D
8rewards_onboarding_application_approved_message_spending½´£–’ˆõ¨?
=
1rewards_onboarding_suitability_comfirmation_titleËåÍäÅŞœ„(
@
3rewards_onboarding_suitability_comfirmation_messageë¬¨ˆ´Ö©’
J
=rewards_onboarding_suitability_comfirmation_message_no_symbol÷·«¯Šô×¡
5
)rewards_onboarding_crypto_agreement_titleØ†¹Ï¯êò¿L
7
+rewards_onboarding_crypto_agreement_message‡ü…ä¡·´ÇM
A
5rewards_onboarding_crypto_agreement_message_no_symbol¨½ËçòÌù¬;
@
4rewards_overview_pending_roundups_bottom_sheet_title®»øÊë‘ÒÑE
G
:rewards_overview_pending_roundups_bottom_sheet_descriptionìÌÒÈ§Ûî¿Û
%
rewards_overview_roundups©ŞÆáá±é>
)
rewards_overview_created_timeÖ¸»èö‹õ5
,
rewards_overview_roundups_total„æåØãš¬…ˆ
)
rewards_overview_bonus_total¨–ü’İ¤Ó¡
)
rewards_overview_weekly_heldÁ¯ÕŸîá¼¤ï
2
&rewards_overview_eligible_transactionsèö ğÀ°Ãö/
.
"rewards_overview_invested_roundups…ÿ½“ªëüĞ
-
 rewards_overview_asset_selection®Øú½ùš•¼…
-
!rewards_overview_roundup_settings©ŞÆáá±é>
8
+rewards_overview_no_transactions_no_roundup›ç™ôş·Ù†Í
,
 rewards_overview_no_transactionsÖâ·™íçêœ\
,
rewards_overview_roundup_paused®˜¦‰øä¼ÚÕ
,
rewards_overview_roundup_resume®Óí¾Ú™íÃÿ
/
#rewards_overview_roundup_disclosureÖä·ÑÍÔàP
,
rewards_overview_settings_title‰’ø¢ƒÈæ¬¼
(
pause_roundups_dialog_titleŸåÆâªáÍ´Ç
)
pause_roundups_dialog_messageÃÂÈƒÊˆÿøU
.
"pause_zero_roundups_dialog_message¿±áïşºú»!
1
$pause_roundups_dialog_primary_buttonÉÌÚšç÷ß‘
/
#pause_roundups_success_dialog_titleıüË¡Æ±¼ï
2
%pause_roundups_success_dialog_message±İè•†ÕáÛ
6
*pause_zero_roundups_success_dialog_messageñÓíİÊòøÍJ
0
$rewards_notification_weekly_congratsØ†¹Ï¯êò¿L
3
&rewards_notification_weekly_bonus_rateâ½ú·»¼¸İ‘
0
#rewards_notification_weekly_roundup¿×¹Ğ•ùŠ›ı
.
!rewards_notification_weekly_bonusÊÿø¨î¢îŸˆ
-
!rewards_notification_weekly_totalÖìÉÛáü¦è
=
0rewards_notification_weekly_brokerage_disclaimerÉáƒ„œæë¬ï
:
-rewards_notification_weekly_crypto_disclaimerÓ„¾¦Âêòÿ
9
-rewards_notification_weekly_see_order_detailsîø¿ÿˆÀò×O
(
rewards_intro_bottom_button‘§‘‚ §¿Ë
+
rewards_intro_image_description£”’ıê‹¢{
,
 rewards_signup_image_description¬‰üõúÉÊÓg
+
rewards_asset_selection_header×²èÊÆÃ­„
%
rewards_disclosure_learn¬ƒ…ûòÎ™·ß
&
rewards_disclosure_got_itŞÿø‚æÃƒì