

url_mfa_faq”Èºİõï©êà
!
url_auth_app_deeplink¸©äšˆ¡
,
device_settings_learn_more_linkˆî’ù“ŒğÜà
3
&security_center_security_section_titleÜåò¡¬çóÃµ
1
%security_center_privacy_section_title´à»êçÇô«
4
(security_center_privacy_section_subtitle…ğ‰×¦ÆŞ³
+
security_center_update_password¾…»†ÆüÑ³
+
security_center_two_factor_auth‘‹—³ı’Œ8
+
security_center_device_securityêÌ‘ğÜ…˜îk
$
security_center_devices§¢œ•÷âßŸÚ
+
security_center_create_passkey¿„íÓìõÕÒÓ
2
&security_center_passkey_already_existsşÎµÁ‚®æ”
2
%security_center_passkey_exists_notice¡†¤şã•Ê
.
"security_center_create_new_passkey¡ª‚ ëó¹­3
4
'security_center_passkey_success_message„ßŠ™·£ğê
#
security_center_success¾¦‘ââÕ´‰T
#
failed_to_setup_passkeyÜóå¬æ²œf
/
"security_center_profile_visibility÷âÈ¼¾ıûô
%
security_center_blocking¾¿Ô¦ª³…û
0
$security_center_app_privacy_settingsÚ›–ÑºÄ
'
security_center_data_accessµÉßõ¯ùÙ¯$
*
security_center_data_deletion¯¯ƒæîµóâ
)
security_center_data_sharing­”Ì—’—ÊÅ¯
(
security_center_manage_data“÷âƒå™ü‚ö
+
security_center_privacy_policyáÌ¼ÚµÀÕ™
"
security_center_logoutêòû÷¡úâ„,
,
security_center_mfa_enabled_smsÉÁ±äÉıÕã×
,
security_center_mfa_enabled_appÊğÅ¾¦¡’ºÁ
/
#security_center_mfa_enabled_promptsËÇ¦÷ÈåÁçI
)
security_center_mfa_disabled›àæ˜¾ßíšÎ
5
)security_center_device_security_biometricŠú¨“ù¦‰áN
0
#security_center_device_security_pin¿«ïÕÍ±–ïÜ
9
-security_center_device_security_biometric_pin ¬Úç–°İœy
5
(security_center_device_security_disabled›àæ˜¾ßíšÎ

setting_mfa_titleİŠ—ä²ôÄ
,
 setting_mfa_current_method_title¯¾¼ûÉšãß>
,
setting_mfa_switch_method_title±ĞÍ˜€ØŠß
,
setting_mfa_select_method_titleõÊöóƒ•´²›
)
setting_mfa_method_sms_labelÉÁ±äÉıÕã×
)
setting_mfa_method_app_labelÊğÅ¾¦¡’ºÁ
,
 setting_mfa_method_prompts_labelËÇ¦÷ÈåÁçI
/
"setting_mfa_sms_phone_number_label²±èÅ»ùÜö
1
$setting_mfa_auth_app_selection_title‡ŒÁ¸æ²ôõè
/
#setting_mfa_auth_app_type_app_title®ÒÚù¿úøh
2
%setting_mfa_auth_app_type_other_title±­úÌ´®ƒÌê
2
%setting_mfa_auth_app_selection_footerüË½ˆ”ßØØ½
+
setting_mfa_auth_app_key_titleÙÙ¤ÎªíÊ
.
!setting_mfa_auth_app_key_subtitle—ÿªÚÃûÍÉÛ
.
!setting_mfa_auth_app_key_step_one½“¯ç•“ã¾õ
-
!setting_mfa_auth_app_key_step_twoù£¡‚šà†– 
0
#setting_mfa_auth_app_key_step_threeó•¸È±›Ôÿ„
.
"setting_mfa_auth_app_key_step_four«şÖß×†ƒk
/
#setting_mfa_auth_app_copy_key_labelè¼õİ„Àâ@
3
'setting_mfa_auth_app_key_clipdata_labelëÿèÆ­œÛ€b
4
(setting_mfa_auth_app_no_app_dialog_title¶¼ù‰ßí²ß7
6
*setting_mfa_auth_app_no_app_dialog_messageÅÉªÁ÷ºíş|
=
1setting_mfa_auth_app_no_app_dialog_positive_label«ÄŸıÿ²ŸA
>
1setting_mfa_auth_app_no_app_dialog_negative_labelÿı¡ˆòÓæ
.
!setting_mfa_auth_app_verify_title—¯»ç·®êáÿ
1
$setting_mfa_auth_app_verify_subtitleÃˆ—³†ŸÛÁ
6
)setting_mfa_auth_app_recovery_retry_title¡•Ó……Æ›–¸
7
+setting_mfa_auth_app_recovery_retry_messageî°„•È†şD
5
(setting_mfa_auth_app_recovery_fail_titleüËİòÿ’öœŠ
7
*setting_mfa_auth_app_recovery_fail_messageÿšˆù´í¤¯
7
*setting_mfa_auth_app_revovery_fail_primaryááõÔËÚğıÇ
8
+setting_mfa_auth_app_recovery_success_titleÊŠ×ê¡Ñ­†Ó
:
-setting_mfa_auth_app_recovery_success_messageœ÷ô”•»Ñ¹Ë
+
setting_mfa_sms_verify_v2_titleÎ¬°Ò¤™–´%
.
"setting_mfa_sms_verify_v2_subtitleû§†½œ±Ë•Y
3
&setting_mfa_sms_verify_v2_resend_label¥È‰ŸÁèÒ’
9
-setting_mfa_sms_verify_v2_change_number_labelãšÚÕ–º›“Y
;
.setting_mfa_sms_verify_v2_recovery_retry_title¡•Ó……Æ›–¸
=
0setting_mfa_sms_verify_v2_recovery_retry_messageÍ÷ê¤­äğ©
)
setting_mfa_copy_token_alert®¶ğ«¬¶õî
;
.gated_crypto_setting_mfa_subtitle_markdown_rhcêé ¦¢½Ø¥©
5
(trusted_device_detail_device_type_mobile”×úıªÈ†ô
2
%trusted_device_detail_device_type_webáõÅÃ©›äŞ
5
)trusted_device_detail_device_type_unknown™ø°Ÿ®÷o
'
device_settings_list_title§¢œ•÷âßŸÚ
0
$device_settings_remove_devices_label¤“ËÈ„À×¨O
9
-device_settings_remove_devices_dialog_messageÇ‰³ôµ³™æ
,
 device_settings_device_approvalsËÇ¦÷ÈåÁçI
%
device_details_last_seen¸»Ï„ñéı
,
device_details_state_active_now»ø¹®Ğ¡¾‰š
#
device_details_locationÏÂº‰™·÷O
'
device_details_device_typeÿıÓ¡Öªûë
(
device_details_remove_deviceä´ŠµØ¤€€k
6
*device_details_device_removal_prompt_titleä´ŠµØ¤€€k
8
,device_details_device_removal_prompt_messageæ¼Ü¡ğ¾Ğõ
4
(device_details_device_removal_prompt_ctaä´ŠµØ¤€€k
<
0device_details_device_removal_confirmation_title†Şöñ“‚Ÿ®Q
>
2device_details_device_removal_confirmation_messageêùà£«Î„«5
!
device_security_titleêÌ‘ğÜ…˜îk
,
 device_security_biometric_headerŠú¨“ù¦‰áN
-
!device_security_biometric_summary¬ş·¼å–Úø

4
'device_security_biometric_enable_action·¶Œî“©Èÿ
'
device_security_pin_headerÅ¤İŞˆ§ˆ›Ì
-
!device_security_pin_enable_actionôåäÀ¿¢ÿ™)
@
3device_security_pin_as_backup_for_biometric_summaryÄ§Ş—µ±±«£
*
device_security_pin_set_action¸€è¡êÒŒE
+
device_security_pin_disclaimerÏÆ²œä¢ü Ñ
"
device_security_enableüİÃÄ¬ƒ•üQ
#
device_security_enabled¯äƒÀÔ„–
+
device_security_timeout_header„íò‚¸ˆ’õø
+
device_security_timeout_action»²µşİØÀ˜
0
#device_security_timeout_immediately”¼Æ–ÛıÒşÛ
1
$device_security_timeout_five_secondsŒÇşäÚ­Ù¶
/
"device_security_timeout_one_minute¿æÖá®Ëîó
1
$device_security_timeout_five_minutesÂûñÍİĞµ
3
'device_security_timeout_fifteen_minutesñƒ©ü˜€ÉQ
-
 device_security_timeout_one_hourÍçöªè‘ØŸ
/
"device_security_timeout_four_hoursŞíûÎ¬›ıÒ…
*
device_settings_list_subtitleß×¡şÌ¸«“
.
"personal_data_access_request_title°¯É…ÊŠÂ
2
%personal_data_access_request_subtitle¾î­×ìß‰Ãƒ
6
*personal_data_access_request_details_title‡â§œ–¾à`
/
#personal_data_access_request_footerÌ£ÎÙìğÊ0
,
 personal_data_access_request_ctaµÉßõ¯ùÙ¯$
7
*personal_data_pending_access_request_title²¦ı Â¿
:
-personal_data_pending_access_request_subtitleé‘ø××ã¥’
C
7personal_data_pending_access_request_timeline_top_titleäíÕÙİ¹í®j
F
:personal_data_pending_access_request_timeline_middle_titleÄõ­åíˆÙx
G
:personal_data_pending_access_request_timeline_bottom_title¼¤¯Ö‰î…Âè
4
(personal_data_pending_access_request_ctaúÛ‡†®·¬Ô
<
/personal_data_access_request_confirmation_titleÁêá˜à·õ¿Ò
?
2personal_data_access_request_confirmation_subtitle•€›«Õ³›
9
-personal_data_access_request_confirmation_ctaúÛ‡†®·¬Ô
/
"personal_data_delete_request_titleÎÿš«‡˜Úë·
1
%personal_data_delete_request_subtitle¹û™•íåÉÄ
6
*personal_data_delete_request_details_titleÊüò…àƒÅ’0
-
 personal_data_delete_request_cta¯¯ƒæîµóâ
7
*personal_data_pending_delete_request_title²¦ı Â¿
9
-personal_data_pending_delete_request_subtitle¡æİçôâ¤âx
C
7personal_data_pending_delete_request_timeline_top_titleÉŒ‰ò‰ÿ¨¹7
F
:personal_data_pending_delete_request_timeline_middle_titleŒŞÙóó±ø0
G
:personal_data_pending_delete_request_timeline_bottom_titleê’š¶°Æ‚º
4
(personal_data_pending_delete_request_ctaúÛ‡†®·¬Ô
<
/personal_data_delete_request_confirmation_titleÁêá˜à·õ¿Ò
>
2personal_data_delete_request_confirmation_subtitle’ÂñÔ¤Îµ]
9
-personal_data_delete_request_confirmation_ctaúÛ‡†®·¬Ô
)
personal_data_download_titleÈÁœŞ²ÃÙªÔ
,
personal_data_download_subtitleû’µæœé©‡ú
0
$personal_data_download_details_title‡â§œ–¾à`
4
(personal_data_download_expiration_footerİÍ¦¸±Ã°çO
'
personal_data_download_cta…íÅÄ°ìÛãŠ
-
 personal_data_error_dialog_titleæ²›‚¶¨ôœ
.
"personal_data_error_dialog_messageŒè¨ë³Ö_
+
data_sharing_permissions_title­”Ì—’—ÊÅ¯
2
&data_sharing_permissions_enabled_labelöìĞô‘åî9
4
'data_sharing_permissions_disabled_labelùƒ´Õê–“
#
data_sharing_learn_moreíÌ‰ÓªÔ
1
$data_sharing_learn_more_article_link¸ª—†á¥¶‡ä

data_sharing_footerÏõõó¤—¾¾[