
'
option_order_title_rollingÂ›£»¸óÖü
5
)option_order_title_rolling_settle_on_openÇ˜úáçÏí^
5
(option_order_title_rolling_no_expirationš²ÚŞìë’Œ
'
option_order_title_multileg¶ÒÓ³¯‘·>
7
*option_order_title_multileg_settle_on_open±Ê÷‡À¹şø
5
)option_order_title_multileg_no_expirationª§õæ”üši
1
$order_option_instrument_detail_title¥ê·›Ó™Øâ’
@
3order_option_instrument_detail_title_settle_on_openì©•ÿ¥ˆã´€
-
!option_order_review_multileg_left°ıã˜ˆæ’W
<
0option_order_review_multileg_left_settle_on_openÕ¡Äî˜Ÿ©Á
.
"option_order_review_multileg_right£ŠâŒÌÂôºW
+
option_order_cost_shares_label«Ùö¦¡àĞ•”
!
option_order_bid_askÇı†¹ÏİÄŸ¶
&
option_order_bid_ask_fullÇı†¹ÏİÄŸ¶
+
option_order_price_placeholderŒÿ»›–şğ‘¬
*
option_order_symbol_with_quoteó„¹È‹ªÜ>
<
/option_order_symbol_with_quote_and_buying_power¡ÛÜ€‡¡æ€
*
option_order_account_row_title´­øû±éQ
5
(option_position_shares_held_for_exerciseöÇ¥à¥ÃÄ¢
2
&option_position_cash_held_for_exercise¦Œ²Ûï„óªA
-
 options_order_confirmation_title–æËË½”‘˜¡
*
option_order_fill_price_label×€—¬Ñùƒé
2
%option_order_average_fill_price_labelãğ£²š…­“ÿ
7
+option_order_confirmation_limit_price_labelÛ€é‹ò¨í|
?
2option_order_confirmation_stop_trigger_price_labelªÙİ»¹Å›İÒ
4
'option_order_confirmation_bid_ask_label”ş’ûäˆ•š
9
,option_order_confirmation_new_position_label¡Ú­¨ÈÑÜ¤
*
option_order_limit_price_labelÛ€é‹ò¨í|
)
option_order_stop_price_label†  ÷³×ÏÒ^
2
%option_order_stop_trigger_price_labelªÙİ»¹Å›İÒ
+
option_order_market_price_labelüğûãí¶À
,
 option_order_time_in_force_labelÊ¦éĞ›¸¹õ
.
"option_order_trading_session_labelÖÃ•«¶õ€Çx
<
0option_order_trading_session_regular_hours_label…§èäïÕü½~
>
1option_order_trading_session_extended_hours_labelºÀØ€«ÉùÿŞ
:
.options_order_trading_session_time_range_label²¤«À’œp

dollar_sign_formatôÇäñ†¶‡£o
'
option_cancels_failed_descª„ì£ˆŒ¬ã¤
G
;option_order_create_error_crypto_buying_power_failure_titleàÅ¹»†…äİ
I
=option_order_create_error_crypto_buying_power_failure_messageÌ±åè•âH
O
Boption_order_create_error_crypto_buying_power_failure_button_labelÛ‰¶’•Ïè²•
$
order_types_header_textã×Àæ€¥ˆ¥
%
time_in_force_header_textÊ¦éĞ›¸¹õ
+
option_order_form_tooltip_textóç ñµš¾ıü
4
'option_order_marketability_empty_string¹ì½¡Œïç”
2
%option_order_marketability_learn_moreéÖéÜú‹ª
3
'option_order_marketability_bottom_sheetÚİè”àV
/
"option_order_marketability_low_tag§¼®Á¨ü ¿×
>
1option_order_marketability_low_bottom_sheet_title§¼®Á¨ü ¿×
C
7option_order_marketability_low_bottom_sheet_descriptionœí‰í÷à­[
1
%option_order_marketability_medium_tagÑâ›ËîÏåäM
@
4option_order_marketability_medium_bottom_sheet_titleÑâ›ËîÏåäM
G
:option_order_marketability_medium_bottom_sheet_description°¿âì¨ğ€ïÎ
0
#option_order_marketability_high_tag„ãñÇåë±ÓÄ
?
2option_order_marketability_high_bottom_sheet_title„ãñÇåë±ÓÄ
D
8option_order_marketability_high_bottom_sheet_description¸Ã±ü‡ÃÑ™
>
2option_order_per_contract_fee_specific_description›¼è®Í„Üa
D
8option_order_per_contract_fee_specific_description_shortüšÈ ¢Ü¾J
6
*option_order_confirmation_trading_fee_linkİìà½Ôæ¦€,
?
2option_order_per_contract_fee_fallback_description¶äãÛ«÷›‹ß
D
8index_option_order_per_contract_fee_specific_descriptionñŠ…™ëz
K
>index_option_order_per_contract_fee_specific_description_shortËïÚÖŸ‹Ü–¸
H
;index_option_contract_fee_per_contract_specific_descriptionÔ½Ûáå›ÌÏ
.
"gated_option_sales_tax_description¿·ğ œ’š©
G
:gated_gold_index_option_total_gold_fee_savings_descriptionƒÎ·ÑëµÓ
9
,option_order_confirmation_fee_footer_generalÃß©â©ùá„Ğ
9
-option_order_confirmation_fee_footer_specificÚ×¢ú¢«Ö^
K
>option_order_confirmation_fee_footer_specific_inline_link_textÿ¶ÀœÃ‹Â
G
;gated_gold_index_option_order_confirmation_gold_fee_savings¥³şÄ¹ËÍÙ
3
'uk_option_order_confirmation_fee_footerüší­…·ƒ^
D
8uk_option_order_confirmation_fee_footer_inline_link_text†¡ÚÌ…ï¹H
7
+uk_option_order_confirmation_fee_footer_urlÅû§ˆëó¢z
6
)apac_option_order_confirmation_fee_footer´Å—Õº“††
9
-apac_option_order_confirmation_fee_footer_urlÅû§ˆëó¢z
#
option_order_bid_labelÉ‚¤À«œûó
#
option_order_mark_labelôôôø…ïÓğ
"
option_order_ask_label¸¢ã»Øòáş
3
'option_order_bid_ask_bar_no_quote_error½™³úÜı­©D
1
%option_order_bid_ask_bar_no_bid_error¹†Ë•™°å€9
2
%option_order_bid_ask_bar_no_ask_errorûÓ®§î•®ê¾
4
(option_order_configuration_section_limit±¹“œÏ€Íl
5
)option_order_configuration_section_marketé‰È¿„˜é6
9
,option_order_configuration_stop_market_titleÙ¬è÷¿Èï‘
<
/option_order_configuration_stop_market_subtitleÉÇé­ßßıÅ
C
7option_order_configuration_stop_market_discovery_headerèÂûüÅå‡3
3
'option_order_configuration_market_titleé‰È¿„˜é6
;
.option_order_configuration_market_subtitle_buy¨†ıæ£Ÿ¨œœ
;
/option_order_configuration_market_subtitle_sellÆ·ÜŞÅŠ­ÎR
I
<option_order_configuration_error_sell_to_close_only_subtitleæ³ûÓÅ¦ŠÄÓ
F
9option_order_configuration_error_single_leg_only_subtitleˆ·®¹è²Ÿ¿
J
>option_order_configuration_error_outside_market_hours_subtitle…²‹¢ÛÀÓø5
Y
Loption_order_configuration_error_outside_market_hours_subtitle_no_late_close¢¶£´˜êùí
D
8option_order_configuration_error_non_market_day_subtitleìóç¤—•ìª
=
1option_order_configuration_error_gtc_market_titleŸÆ£¢‘§ø†|
C
7option_order_configuration_error_gtc_market_descriptionÓòÁ¢ù‰…Ù,
4
(option_order_education_stop_market_titleÑªæëÇÏ
7
+option_order_education_stop_market_subtitle´À“şÅß»E
6
)option_order_education_stop_market_banner¼ÚÄ¨Î¸¼¿
0
#option_order_education_market_title“ÕöØããÉÛù
2
&option_order_education_market_subtitleè—–Õ‚’†Ò6
0
$option_order_education_market_banner¡Ï¡·Ë¨ƒu
-
!replace_option_order_dialog_titleÚİò¤ğ…¡Í&
0
#replace_option_order_dialog_messageá•„ŠŠ¶«±
4
'replace_option_order_fill_error_messageÀÄÉÿßŠÓ±
0
#replace_option_order_go_back_actionÜ’¦¼©ÂÅ«
4
'option_order_after_hour_disclosure_textÈÒ½·‡Şƒ
@
3option_order_after_hour_disclosure_inline_link_text¬ƒ…ûòÎ™·ß
>
2option_order_after_hour_disclosure_inline_link_urlû»±íğÄèt
B
5option_order_after_hour_disclosure_inline_link_url_uká—õ÷İ¢–×à
,
option_order_new_position_valueããì½ã…‡â
4
'option_order_shares_per_contracts_labelŒ´˜üãÎ¨