
"
account_overview_title´­øû±éQ
.
!spending_account_statements_title‚ƒ¬å ‹ó€º
2
%spending_account_statement_item_titleä˜¸ÄÎüëüË
>
2account_overview_levered_amount_label_cash_account´œ°ïÕê’‘A
4
(account_overview_portfolio_section_labelÓ”×ğ‡÷­s
7
*account_overview_portfolio_section_summary¼×—¯ÊİåÂè
8
+account_overview_market_value_section_label¾ş®èŠµƒ¨
:
-account_overview_market_value_section_summaryÏï®Æª·ôş
(
account_overview_cash_labelòî€å¸œÚÓ
-
 account_overview_portfolio_labelğ­˜ÍÒÎí
/
#account_overview_market_value_label„Î©¬¼Í²+
1
%account_overview_levered_amount_labelš‚«éÿÿäÛT
+
account_overview_crypto_equityÇŞÄè’”•½
2
&account_overview_event_contract_equity½ÜØ°÷Œ”ÙO
,
account_overview_futures_equityºÒ©à»±™¿
.
"account_overview_stock_and_optionsØ™—­à™÷¥!
#
account_overview_stockìã‘ßàÙ›‘Ï
#
account_overview_equityŞ«²ªõÜ°á
0
$account_overview_investment_scheduleÂ€·¸ù…¢
=
0account_overview_investment_schedule_descriptionõ¢É£ËúäÁÇ
7
+account_overview_investment_schedule_status˜¼İ«”²è
4
(account_overview_investment_schedule_btn¿®±»ôòíÂ	
5
(account_overview_investment_schedule_urlÊ†ÑÜİ»™ÚÉ
(
account_overview_drip_label–·¾Ç´©…§
+
account_overview_drip_disabled›àæ˜¾ßíšÎ
)
account_overview_drip_enabled¯äƒÀÔ„–
/
#account_overview_drip_enable_actionš€Ÿ¦ôöé$
.
!account_overview_drip_edit_actionÃß¦æ€åÔö¾
)
account_overview_drip_summary¤Ÿ¿ŞÜ¼—Î?
%
account_overview_drip_urlŠÃ Ø™™Àào
5
)account_overview_gold_section_margin_usedš‚«éÿÿäÛT
=
0account_overview_gold_section_margin_maintenanceÑ‘©’¨ö¦ä«
=
0account_overview_gold_section_options_collateralôÊöº¥‚ –
@
3account_overview_gold_section_today_day_trade_limit™ï€úß‡ˆº˜
:
.account_overview_gold_section_learn_more_error¹ˆ©¼’®æèI
B
6account_overview_margin_section_margin_investing_title¸œï– îëJ
9
-account_overview_margin_section_enabled_label¯äƒÀÔ„–
;
.account_overview_margin_section_disabled_label›àæ˜¾ßíšÎ
?
3account_overview_margin_section_enabled_descriptionÎ §Ş˜”²Í
C
6account_overview_margin_section_enabled_description_ukáËâŞáïË¾º
=
1account_overview_margin_section_enable_margin_ctaÃßëÓ•øœ¡
?
3account_overview_margin_section_margin_settings_ctaì—Ü×áÃÌ£^
N
Aaccount_overview_margin_section_cash_account_disabled_description€çÙ¥•À¨Ü
P
Daccount_overview_margin_section_cash_account_disabled_description_ukÇùËœî‰şú1
P
Caccount_overview_margin_section_margin_account_disabled_description«Ò¯é³³ÛØ¥
R
Faccount_overview_margin_section_margin_account_disabled_description_ukà¢Ú°¤äãÚ
C
7account_overview_margin_section_cash_account_learn_moreŠ†±‹¾€õˆq
-
 margin_overview_help_center_link›ÅÊ¡…ä÷»²
:
.account_overview_instant_deposit_deposit_fundsÄùğÀÂ¶§à(

documents_help_urlÈµµøÕ¶´

sweep_interest_apyçÛ„·¨‰ŸR
.
"documents_tax_certification_promptŸì²ôÇŒ—Â
&
options_setting_card_titleà‚ª˜ã«ß
+
options_setting_disabled_label›àæ˜¾ßíšÎ
$
options_setting_l2_labeló³ä×Ü½Ææ"
%
options_setting_l3_label¶€íÎøŞåòä
.
!gated_options_action_needed_label©ÈÂæÍÙÀ†œ
(
gated_options_pending_labelĞù‡ñå·¤ä
0
#options_custodial_unavailable_label­•Ò×”üª
6
*options_setting_downgrade_to_basic_successøØ¼ƒƒôğî/
6
*options_setting_downgrade_to_basic_pending‘„÷÷ñÖŸ¦a
2
&options_setting_remove_options_success–ÿ¤Ÿ¬÷Ó¢;
2
&options_setting_remove_options_pendingÎìä¹››ù 
"
options_enable_actionÒ½¿¡ƒ£¤Å§
(
options_schedule_call_action«ñÕ¿ ÉF
#
options_settings_action¢çÏ¾¤ÎÉ
>
2gated_options_settings_continue_application_actionÓúÃ£ëà#
5
(options_settings_view_appointment_actionÚ®—ƒç‰§
#
options_enable_summary‰´¥ÑĞ‚ÀÜŞ
-
!options_enable_summary_level_2_uk¹Ò©Ï¶áÉÜu
-
!options_enable_summary_level_3_uk½‹‡œ¶æ–”[
3
&gated_options_joint_account_l0_summaryıî–¥Ëááó¹
)
account_overview_options_urlË©×…îî´û½
1
%account_overview_options_call_put_urlØ¾µÖÒ¿
:
.account_overview_options_advanced_strategy_urlæÖÙÃ‰ÛÃÔ
>
1gated_options_level0_needs_to_start_manual_review´¦÷ØÚàåÂÀ
>
1gated_options_level2_needs_to_start_manual_review¶½¹Ô•êÏïœ
6
*gated_options_level0_pending_manual_review‘ç¼òøèÌ6
6
*gated_options_level2_pending_manual_review¹Œ›ƒ†›â
>
1gated_options_joint_account_l0_incomplete_summary¹¡—ì É×ş´
C
7gated_options_joint_account_l0_pending_co_owner_summaryìêÓ®Á¬êÌV
R
Egated_options_joint_account_l0_pending_co_owner_manual_review_summaryı‡³ê¿ŞüôÛ
I
=gated_options_joint_account_l0_manual_review_required_summaryØ• à–Æšš
T
Ggated_options_joint_account_l0_manual_review_required_summary_link_text¸ÁíéŒî¸Ê
C
7gated_options_joint_account_l2_pending_co_owner_summaryÉÓ÷šİÂÏá<
Q
Egated_options_joint_account_l2_pending_co_owner_manual_review_summaryıì›Ç‡‡´–m
J
=gated_options_joint_account_l2_manual_review_required_summary­¤û£»ºııú
S
Ggated_options_joint_account_l2_manual_review_required_summary_link_textœœ’Üïšç·
4
(gated_options_level3_entry_point_summaryë¬«ˆèœİŸ
8
+gated_options_custodial_unavailable_summary¤Âåè›ÀşˆÂ
6
)account_overview_cash_sweep_program_label°”¶Ğ˜µ÷å
:
-account_overview_card_annual_percentage_yieldº›Ê¤Âã»§ 
9
,account_overview_card_annual_equivalent_rate›¬ôŞæ÷‚õ·
4
(account_overview_card_swept_cash_balance²ÖóÂùÍd
3
&account_overview_card_pending_interest¼¼øË¢’ûøÑ
8
+account_overview_card_total_interest_earnedãçÊÒË°ªË
<
/account_overview_sweep_enrollment_disabled_descïŒ‡¥‘Ã“¤À
@
3mcw_account_overview_sweep_enrollment_disabled_descÑ¤Ö´îş„Ã
7
+account_overview_cash_sweep_view_cash_sweepŞ°çÖâ…˜øC
:
-account_overview_cash_sweep_enable_cash_sweep³¯…¢•ƒìÅÓ
/
#account_overview_cash_sweep_enabled¯äƒÀÔ„–
4
(account_overview_cash_sweep_enabled_descÉöÅêäÎ¹äR
9
,mcw_account_overview_cash_sweep_enabled_descü±®àŞø£ù
3
'account_overview_cash_sweep_paused_desc˜İ–ÿ†ø¸8
8
+mcw_account_overview_cash_sweep_paused_desc°ø²ÂÔÚƒÇ
8
+account_overview_cash_sweep_paused_pdt_desc³Ñ­æÕŠé»‡
7
+account_overview_cash_sweep_paused_pdt_link½Ÿƒì‘£–å
>
1account_overview_non_margin_sweep_paused_pdt_link°ÔÈ¦á¼€Ğ£
;
.account_overview_cash_sweep_disable_cash_sweep¼Ø’‡äáêÌ¿
C
6account_overview_interest_earning_read_full_disclosure©áà›÷÷÷À
/
#swept_cash_explanation_dialog_title¨““àÌÄôc
2
%swept_cash_explanation_dialog_messageÉÒà³ŠğÊó
5
)mcw_swept_cash_explanation_dialog_messageß‰ªµ¸¿ùq
#
cd_swept_cash_info_iconÈòóí¬ªn
,
cd_swept_cash_balance_info_iconµ‰ıöÑ‘
'
account_type_section_label™ß‡çµ¿ÓÎ
4
'account_type_section_cash_account_labelòî€å¸œÚÓ
6
*account_type_section_cash_account_label_ukÉØ·üà¡˜v
5
)account_type_section_margin_account_labelù­Ê¾²áá¬v
5
)account_type_section_limited_margin_label²Í‹›Û†ªÍ;
6
)account_type_section_cash_account_summaryÜÑ¶üàŒ²‹Í
B
5account_type_section_cash_account_summary_without_pdtéÛ®“ğ²™ï€
7
+account_type_section_margin_account_summary•ß»¦ĞÌ¬£A
D
7account_type_section_margin_account_summary_without_pdt¤÷ºòÀ½ã»°
?
3account_type_section_limited_margin_account_summary¯—˜Ëç…¬
K
?account_type_section_limited_margin_account_summary_without_pdtŞö¶Ïßã¸I
@
4account_type_section_cash_retirement_account_summary¿Í©Ò­„òï8
L
@account_type_section_cash_retirement_account_summary_without_pdtö¸œ “ƒŞè
,
account_type_section_summary_uk¹Üï…‘ÀÌ¬³
<
/account_type_section_switch_to_cash_account_cta–³÷ŠÃÅ­Î
>
2account_type_section_switch_to_cash_account_cta_uk¥ŠòêöĞ¬È
=
1account_type_section_switch_to_margin_account_ctaµ¿ëÓ£æ¬R
F
9account_type_section_switch_to_limited_margin_account_ctaÍÅŒ´‘­İ
/
#account_type_section_learn_more_url´¶³°¹üĞôK
C
6account_type_section_retirement_account_learn_more_url×¬Š¨İøÊë×
3
'documents_rhy_account_statement_summaryê‚º“êıÎÏ