
,
 crypto_transfer_label_learn_moreö¢„Îóöü•`
0
$crypto_enrollment_menu_transfer_info€ÙƒúØÿÛc
4
(crypto_transfer_enrollment_protect_titleÕåö©â–ëÑt
?
3crypto_transfer_enrollment_protect_sheet_subtitle_1ƒÓÙ»ó¯ôÂ
C
7crypto_transfer_enrollment_protect_sheet_subtitle_1_rhcÊÑÚ×Ü¢‰ËU
@
3crypto_transfer_enrollment_protect_sheet_subtitle_2Ö˜¾èı•ÄÙ®
?
3crypto_transfer_enrollment_protect_sheet_subtitle_3Ü±»³îË×Ìv
C
7crypto_transfer_enrollment_protect_sheet_subtitle_3_rhc³ç€•Š¶îµO
A
4crypto_transfer_enrollment_checklist_verify_identityù¤äíÙÜ™‚
L
@crypto_transfer_enrollment_checklist_verify_identity_in_progressÒ±‘º®íÆ„%
@
4crypto_transfer_enrollment_checklist_email_and_phoneç½’â “ú'
@
3crypto_transfer_enrollment_checklist_two_factor_eta§”Õ­ËŠæ
<
/crypto_transfer_enrollment_create_account_erroräÛ…×¿ı’·
9
-crypto_transfer_enrollment_checklist_v2_titleèó±¾œ…šñ|
>
1crypto_transfer_enrollment_pending_approval_title“ª•¡´ûÍî
@
4crypto_transfer_enrollment_pending_approval_subtitleÚªÿ ‡¿šÅ
2
&crypto_transfer_enrollment_error_titleŒÜŞâîîœ´W
6
)crypto_transfer_enrollment_error_subtitleÔî®Æ–ùÍÂ
6
*crypto_transfer_enrollment_completed_title£•ÆÁ·à°”y
:
.crypto_transfer_enrollment_completed_title_rhc¥õØİŠÌ÷¿M
:
-crypto_transfer_enrollment_completed_subtitleíÍ¼´²ÜÖŠ
>
1crypto_transfer_enrollment_completed_subtitle_rhcß›ûŞ“åƒõ‘
6
*crypto_transfer_enrollment_agreement_titleêğŠ«ååâ­.
;
.crypto_transfer_enrollment_agreement_title_rhcÀ½ãÎ‚êò¹
@
3crypto_transfer_enrollment_agreement_primary_button˜½¹¦èÄŠØ
B
7crypto_transfer_enrollment_agreement_primary_button_rhc¦¼Ï™üï
B
5crypto_transfer_enrollment_agreement_secondary_buttonµ¨«Ø¡ü¸
<
/crypto_transfer_enrollment_agreement_disclaimerÑ¸ıä˜Ò–‡î
?
3crypto_transfer_enrollment_agreement_disclaimer_rhc³ÓÅ‚Ÿªù^
*
crypto_receive_subtitle_qr_v2§©»ƒÅˆµú
/
#crypto_receive_subtitle_qr_v2_tokenÇğ¤´ı±”„e
'
crypto_receive_copy_address–ÀÕ¯”ñÖ²j
3
&crypto_receive_network_selection_title±ËÏ©Âı¹ãá
5
)crypto_receive_network_selection_subtitle×†ÅÅÎÕşÈt
:
-crypto_receive_network_selection_subtitle_rhcšëÈ¤ú”ĞØ
6
*crypto_receive_network_selection_row_titleõÖÃÎÚâ³÷
9
-crypto_receive_network_selection_row_subtitleÉ™ôåÔŒòµ-
(
crypto_receive_share_address“Ë¿ôÈÍ…øo
.
!crypto_receive_mfa_required_titleÿŞ«°¡ŸË½Ì
&
crypto_send_error_messageáŸ¶¿ôò¿å
(
crypto_send_error_buy_actionê—É¹¥€«¡^
-
 crypto_send_error_back_to_walletİúµ–ØŒè
*
crypto_send_mfa_required_titleí‰Ì•î½¢`
-
!crypto_send_mfa_required_subtitle„½¡çÅÿ­Ó
5
)crypto_send_address_page_input_label_text´Ù’¹¦Õ»Î
<
/crypto_send_address_page_input_placeholder_textÂÃæ‰ÀÒ‘µ¡
,
 crypto_send_address_v2_menu_itemÜËÃ°éĞæö
/
"crypto_send_address_v2_helper_scan¯Ú÷ºøå×
1
$crypto_send_address_v2_helper_typingßÁÁ¥²­ıÉ
)
crypto_send_address_v2_helperŸë…ˆƒò»‚4
-
 crypto_send_address_v2_more_tips“¶Ÿ´šåÉûŸ
?
3crypto_send_qr_action_menu_item_content_descriptioné…æ­’öû„;
4
'crypt_send_review_network_fee_row_labelø‚µ˜­îšªá
-
!crypt_send_review_total_row_labelÌØãŞí…Èx
/
#crypt_send_review_expiry_start_over şşû¥ËØP
6
)crypto_send_review_subtractive_disclosureŞƒËÛ¡¾ÒºÍ
2
&crypto_send_review_additive_disclosure¸³•ô×óƒ<
=
0crypto_send_review_network_fee_sheet_descriptionÿçíº§‰»˜â
A
4crypto_send_review_network_fee_sheet_description_rhc–õê¶¥îÕûé
9
,crypto_send_review_network_fee_sheet_cta_rhcŸ¡Ô·øñª‹
(
crypto_transfer_support_url£Êò”Ï¢ïâç
+
crypto_transfer_support_url_rhcÈ¨’¨ÚĞ¼
8
,crypto_transfer_send_review_memo_label_emptyØà“×Ë”Æ§
<
/crypto_transfer_send_review_submit_without_memoğí•ßº‡¥ùñ
:
-crypto_send_confirmation_return_to_wallet_btn¥ì„Ÿå½ø
7
*crypto_send_confirmation_view_transfer_btnéÒÇ‹æî÷İĞ
-
 crypto_input_mode_selector_title¥ÑšÍÓİ¨™­
4
'crypto_input_mode_selector_primary_textÌ•şáàö÷¢
D
8crypto_input_mode_selector_quote_currency_secondary_text³…‰¡íòÍ÷5
I
<crypto_input_mode_selector_quote_currency_secondary_text_rhcÄ›üß¹ñèàì
E
8crypto_input_mode_selector_asset_currency_secondary_text—à¶™œÕ“ùÉ
3
&crypto_transfer_enrollment_intro_titleæ¸®»Á¤” 
6
)crypto_transfer_enrollment_intro_subtitleå¯×†Ûÿæ
,
 crypto_transfers_tip_sheet_title‹»‰™Ã™Ô±~
*
crypto_transfer_limit_increase¸ÛÀ… à†ã

*
crypto_transfer_limit_content»ĞÿòÓÁ®
-
 crypto_transfer_limit_disclaimerüäÑ–˜ê¯Ãê
/
#crypto_review_transfer_limits_titleø«ÄŠ…Ï¥
&
crypto_unified_send_title·úÇÑŒÌûÆ
2
&crypto_unified_send_title_with_networkÖÔäšÒ™óA
'
crypto_unified_receive_chipõÖÃÎÚâ³÷
9
-crypto_unified_receive_disclaimer_multi_chain“üÏÊÒŞÉ!
>
1crypto_unified_receive_disclaimer_multi_chain_ercîÀÖ…Í‹µÛŠ
2
&crypto_unified_receive_disclaimer_memoŠªşÎœ»ãög
3
&crypto_unified_tips_sheet_compat_titleéãñ¾Ñå
J
=crypto_unified_tips_sheet_compat_subtitle_multi_chain_receiveìÔµêä™Œê‡
:
.crypto_unified_tips_sheet_compat_subtitle_sendæ½Â¡×Ÿ
3
'crypto_unified_tips_sheet_one_way_titleÔªËüµßò£X
7
*crypto_unified_tips_sheet_one_way_subtitleØ¼Áîºûú‰„
;
.crypto_unified_tips_sheet_one_way_subtitle_rhc˜ÛÈŒÒé‡å‹
1
%crypto_unified_tips_sheet_small_title„Ï’Û·„âÒP
=
0crypto_unified_tips_sheet_small_subtitle_receive‡¡õÊÇŠ²Ê
9
-crypto_unified_tips_sheet_small_subtitle_sendÏ–”±òº¯ºj
3
&crypto_unified_tips_sheet_limits_title°œá‹ğ‡“Ôî
6
)crypto_unified_tips_sheet_limits_subtitleúÒû‡î÷öî½
2
%crypto_unified_tips_sheet_primary_ctaŞÿø‚æÃƒì
6
)crypto_unified_tips_sheet_primary_cta_rhcî’Ü¢²øğøÙ
'
crypto_unified_qr_send_cta„³¡÷ˆ÷éŒ
.
!crypto_unified_qr_send_permission¯Æôÿğš´Ò
2
%crypto_unified_qr_send_permission_rhcƒğ’š¶ÁÔı
4
(crypto_unified_qr_send_permission_denied‘©¦ğãğ¥í.
8
,crypto_unified_qr_send_permission_denied_rhc’êÏ©¬ÔÕ¬
4
'crypto_unified_qr_send_permission_allow‰ş²Ò¶Â›Â
&
crypto_send_all_with_codeş³šùÁ†öŞ
!
crypto_send_availableŠ´™¸¬ù³


crypto_send_estÛµÜ¿»Çµç°
#
crypto_send_fiat_amount÷áÅÇÙï£Z
)
crypto_order_status_too_largeËÑ€Í•–£™g
(
crypto_amount_available_send°ÂÿŞÕ´˜Ï
$
crypto_limits_learn_moreæÂîÇä¸·c
(
crypto_limits_learn_more_rhcÆ”ÄÑˆ±§J
)
crypto_review_transfer_limitsø«ÄŠ…Ï¥
!
crypto_review_got_itŞÿø‚æÃƒì

crypto_review_okŸ¡Ô·øñª‹
9
-crypto_amount_available_ineligible_for_limitsºâš—Ú¥ıÁ@
8
+crypto_amount_available_eligible_for_limits¥Ã¹¥ÀÑÎàù
-
!crypto_amount_available_unlimitedµ×Œî²Ç™ç?
'
crypto_amount_available_rhc¾ô÷ñŠ¸A
0
#crypto_send_fiat_amount_single_lineÒ³¬¡Ë­ªöŞ
C
6crypto_create_saved_address_button_content_description¸¹áá¬›ó·é
3
&crypto_saved_addresses_section_headingé§«‚ÄáüÙõ
>
2crypto_saved_addresses_refresh_address_lists_errorÈ‹æøîªË´
/
#crypto_saved_addresses_scan_tooltipú²¸½Ùù›{
3
'crypto_recent_addresses_section_heading­ãªŞİª‚u
2
&crypto_recent_addresses_section_footer½•Î¿éÆÚ•+
&
crypto_send_total_balanceùÏ“ŞÊ„–İ
(
crypto_amount_exceeds_limitÀÛ’‹Î±ı™
$
crypto_high_amount_risk³€ıÃ·®Î
"
crypto_send_error_ctaŸ¡Ô·øñª‹
7
+crypto_save_address_bottom_sheet_heading_v2™‡ò‡¬ø’U
9
,crypto_save_address_bottom_sheet_placeholder’ÍœÂ»Òº
:
.crypto_save_address_bottom_sheet_cancel_buttonÖï³¼Ì†€!
9
,crypto_save_address_bottom_sheet_save_button‘çÅİó±è ¨
.
!crypto_save_address_generic_errorŞ¥£Ä‘š×©ñ
,
crypto_send_address_error_titleçÓ˜ÕºïŠ³‰
*
crypto_send_address_error_btn±æÓ¥±ÅªÊË

crypto_disclosuresÿ‡õóßÃõğ
,
 crypto_send_review_address_label”‰©¤·ßˆ(
)
crypto_send_review_memo_labelÆ´¢·¢ĞÒ”9
4
'crypto_send_review_total_secondary_textª¦”™ØÌéß
+
crypto_send_review_title_total˜çÕÿ•ÚŒÿş
)
crypt_send_review_network_row¶œÏÜÑÛg
-
!crypt_send_review_network_fee_row¸ÚùğØ¬K
+
crypto_transfer_disclosure_url³ˆôÀÛÂáÆñ
/
"crypto_transfer_disclosure_url_rhcŸÀç»ã°ûÕË
E
9crypto_transfer_send_receipt_multi_chain_helper_text_fiat‚æöÀ›çËóM
:
-crypto_transfer_send_receipt_helper_text_fiatêØø ŠÙıØ
=
1crypto_transfer_send_receipt_helper_text_fiat_ercè¡¾´¤Íîæ*
<
/crypto_transfer_send_receipt_helper_text_cryptoË²ßë®ÎÚô
H
;crypto_transfer_send_receipt_multi_chain_helper_text_crypto“¼Û¦îÅó¿µ
?
3crypto_transfer_send_receipt_helper_text_crypto_ercºÆ¹ºïØã>
E
9crypto_transfer_send_receipt_multi_chain_helper_text_fullšÎ‡à†‘Ê³C
9
-crypto_transfer_send_receipt_helper_text_fullïÊ¦¼Ëú†à1
=
1crypto_transfer_send_receipt_helper_text_full_ercß‘ñÍ‰“’ä2
2
%crypto_transfer_send_receipt_to_label¾„»û°ù’°Â
6
*crypto_transfer_send_receipt_network_label€öèŒœ÷¸µz
.
!crypto_transfer_unified_erc20_cta­ÔØÏâ£Ò×
)
crypto_enrollment_acknowledgeï’ô¤‹“ÆÌl
.
!crypto_enrollment_acknowledge_rhcĞÌíáğ¯¢
0
$crypto_enrollment_acknowledge_cancelÖï³¼Ì†€!
9
-crypto_transfer_send_network_selection_helperˆ‡ï¬›ˆ´Àk
9
,crypto_transfer_send_network_selection_titleˆˆœ´³¼ÈÚ¢
<
/crypto_transfer_send_network_selection_subtitle·ˆÏÃêèïÛ
?
3crypto_transfer_send_network_selection_subtitle_rhc¸ªèÉÖå²Å
@
4crypto_transfer_send_network_selection_network_titleõÖÃÎÚâ³÷
C
7crypto_transfer_send_network_selection_network_subtitleíÕ§şÂìÚ£c
1
%crypto_transfer_send_network_fallbackè®ˆâ™Íé`
:
.crypto_transfer_send_network_fallback_subtitle¨ÁˆÍåñˆé
?
2crypto_transfer_send_network_fallback_subtitle_rhc¦ğøØ¢°¨°µ
:
-crypto_transfer_send_network_fallback_cta_rhcŸ¡Ô·øñª‹
;
.crypto_transfer_review_multi_chain_sheet_titleØÈÔ‚ÚÂìã×
@
4crypto_transfer_review_multi_chain_sheet_descriptionÑÊØé·ÂÉ¶4
'
crypto_transfer_contact_us¤î²ÛŸÿ÷
4
(crypto_transfer_receive_memo_banner_bodyÂÆÏ¢Êğ‰¬
B
6crypto_transfer_receive_memo_warning_sheet_primary_ctaÖ§…È¼“&
E
8crypto_transfer_receive_memo_warning_sheet_secondary_ctaŞÿø‚æÃƒì
3
'crypto_transfer_receive_memo_banner_ctaÖ§…È¼“&
+
crypto_transfer_send_memo_titleï©ìÖÇõİ±/
.
"crypto_transfer_send_memo_subtitleÒ†ÍøòÀè
1
%crypto_transfer_send_memo_sheet_titleÊ’—½Ö¸Ñü
8
+crypto_transfer_send_memo_value_prop1_title³äŸ¢ëÔº›
7
*crypto_transfer_send_memo_value_prop1_body¡ëÎ¶¢Îàœî
7
+crypto_transfer_send_memo_value_prop2_title¶½¾Åâ°¡h
7
*crypto_transfer_send_memo_value_prop2_body¯ÑòØß™ßŸ¯
8
+crypto_transfer_send_memo_value_prop3_title·Ã €³Ô¶
7
*crypto_transfer_send_memo_value_prop3_bodyíÿ†Šîƒ…·•
8
+crypto_transfer_send_memo_value_prop4_title­òÄä›ÖŒÃ
7
*crypto_transfer_send_memo_value_prop4_bodyˆƒØäè•
1
$crypto_transfer_send_memo_skip_titleüÎ™²åõêúï
3
&crypto_transfer_send_memo_skip_message´êâÕ›¬Úà
2
&crypto_transfer_send_memo_positive_btnŸ³À¦¥ÃÚÙ~
2
&crypto_transfer_send_memo_negative_btnï©ìÖÇõİ±/
%
crypto_protect_learn_moreŞßÇ¼×¢º²)
*
crypto_protect_learn_more_rhcÛÄÒæµ«…ÜÕ
8
,crypto_enrollment_protect_value_prop_1_titleæ“¯ƒÄÚ½­
<
/crypto_enrollment_protect_value_prop_1_subtitle“ÀÄ©ê¾­·á
?
3crypto_enrollment_protect_value_prop_1_subtitle_rhc‹ïè÷ğ†‹ç.
8
,crypto_enrollment_protect_value_prop_2_title¢„æ¹Š™ôÊJ
<
/crypto_enrollment_protect_value_prop_2_subtitle’„€ß×î§ú
9
,crypto_enrollment_protect_value_prop_3_titleí«©öó‘²ä
;
/crypto_enrollment_protect_value_prop_3_subtitle›ˆóÉ²ÉÙÃM
1
$crypto_enrollment_protect_disclaimerø‰ğÍÒäŸ
"
crypto_selection_titleäö±È€¤Òı
)
crypto_selection_search_hintú¨’¬¥ÜŸ²
:
.crypto_unified_show_qr_tab_content_descriptionô‹²™éĞ›ËX
:
.crypto_unified_scan_qr_tab_content_descriptionŒõ¹¸æ¦‘ß[
,
crypto_unified_show_qr_tab_hintÛÙä±İü‘€š
+
crypto_unified_scan_qr_tab_hint‘¤ÁšÛ¬˜Œ
2
%crypto_transfer_continue_button_label‘§‘‚ §¿Ë
.
!crypto_transfer_done_button_labelî’Ü¢²øğøÙ
(
withdrawal_destination_title±ÒÕÈƒ´”/
%
deposit_destination_title·ÌÄĞ£ÔÆ°
)
withdrawal_destination_myselfÓêäŸò¾øE
'
deposit_destination_myself°¼Ã©ùö•Ãœ
/
#withdrawal_destination_someone_elseäù¢æä¿ş­1
,
 deposit_destination_someone_elseàÈÏûÇı­F
)
wallet_type_centralized_titleƒÈàö”®”€I
,
 wallet_type_centralized_subtitle•µµ†¯Îøm
,
wallet_type_decentralized_titleö€ı–ä˜ï×š
.
"wallet_type_decentralized_subtitleÿÜïÉéÅ·é'
:
-wallet_type_decentralized_disallowed_subtitleˆ“î—ğ‡ÓĞ
#
wallet_type_disclosureò”¨òˆ¥«º£
1
%wallet_type_disclosure_privacy_noticeˆ×¦³ĞÙƒã=
&
wallet_type_learn_more_urlÈ¨’¨ÚĞ¼
6
)wallet_type_disclosure_privacy_notice_urlƒ”æúõ›á«ò
0
$withdrawal_beneficiary_name_subtitleÜÊ«ÂÙòœ¦X
/
"withdrawal_beneficiary_name_hint_1š†¤¡‘Ìß½
.
"withdrawal_beneficiary_name_hint_2ÜèÛ‚…‡¾
-
 withdrawal_beneficiary_dob_title®ıüÏçèËÌ
+
withdrawal_beneficiary_dob_hintû¤§°Ë´ày
%
withdrawal_exchange_titleÚâåù­íÚ
$
withdrawal_exchange_hint»©£Â£„ÔÌG
&
withdrawal_exchange_emptyú¤æñöîÎ¬
(
result_pending_secondary_ctaş¨äÉë¶¼ñE
/
"result_contact_support_primary_ctaÆ¸­¾šªìåË
,
result_block_refund_primary_ctaÔ‡¬ãËŸöø
+
saved_address_row_remove_titleôÍ¹İ­ë¶´‰
4
'delete_saved_address_alert_dialog_title©—â—¯¿†¦
3
&delete_saved_address_alert_dialog_bodyûÉóÜ¡ùøô
?
3delete_saved_address_alert_dialog_body_allowlistingí»ô’Œ­ö¶
;
/delete_saved_address_alert_dialog_remove_buttonøşíÔ¹ô˜:
;
/delete_saved_address_alert_dialog_cancel_buttonÖï³¼Ì†€!
:
-delete_saved_address_alert_dialog_error_toastŸÉ•Œ”ß³€
3
&saved_addresses_paste_limit_error_textéôõ§ØŞç¾ß
1
%crypto_settings_saved_addresses_title¹¶ŒÑóíÿñy
<
0crypto_settings_saved_addresses_title_withdrawalãÿ†ªÕ¦›ß
=
1crypto_settings_saved_addresses_empty_state_titleïûøÈùÇı˜%
A
4crypto_settings_saved_addresses_empty_state_subtitleŠŠ¢’ÜÛúÉ¾
-
!crypto_settings_add_saved_addressüšÚŞ‚¥ó£-
5
(crypto_pending_addresses_section_headingĞù‡ñå·¤ä
<
0crypto_address_list_holding_period_warning_title‘§†¸şÄ›ƒ#
C
6crypto_address_list_holding_period_warning_subtitle_v2ĞàÆ¼“ïòëÇ
C
6crypto_address_list_holding_period_warning_primary_cta‘§‘‚ §¿Ë
D
8crypto_address_list_holding_period_warning_secondary_ctaÖï³¼Ì†€!
*
crypto_add_saved_address_titleèÑ­ÊÂ…á¾+
0
$crypto_add_saved_address_scan_actionÜËÃ°éĞæö
J
=crypto_add_saved_address_subtitle_short_address_and_timestamp —‰ô”ûÁƒ·
9
,crypto_add_saved_address_save_address_cta_v2‘§‘‚ §¿Ë
*
crypto_allowlist_primer_title¡‚ïø¾ĞÌ§í
-
 crypto_allowlist_primer_subtitleÕÂçÒÑ›Ô•‹
:
.crypto_transfer_enrollment_mfa_checklist_titleÊÏà¼÷­

>
2crypto_transfer_enrollment_mfa_checklist_title_rhcç½’â “ú'
@
3crypto_transfer_enrollment_mfa_checklist_title_doneÃ»Ä­¢±Íı
=
1crypto_transfer_enrollment_mfa_checklist_subtitle™¾¢©ö¸¤ŒE
A
5crypto_transfer_enrollment_mfa_checklist_subtitle_rhcÌ¸µƒô‰Á
B
6crypto_transfer_enrollment_mfa_checklist_subtitle_doneÏÇì”ñ›ø•H
F
:crypto_transfer_enrollment_mfa_checklist_phone_row_primary“‚ÄÉÅÆúU
K
>crypto_transfer_enrollment_mfa_checklist_phone_row_primary_rhcú¶Ğ­¤¬í€è
I
<crypto_transfer_enrollment_mfa_checklist_phone_row_secondary¤©Û’âÏ˜”ˆ
Q
Ecrypto_transfer_enrollment_mfa_checklist_phone_row_secondary_verified³×šùàâ£»Z
G
:crypto_transfer_enrollment_mfa_checklist_email_row_primaryğ‰Ö“±¼ö˜ï
K
>crypto_transfer_enrollment_mfa_checklist_email_row_primary_rhc×¸º¦»çø‹Ÿ
I
<crypto_transfer_enrollment_mfa_checklist_email_row_secondaryùÚà¦ˆË„Ëİ
Q
Ecrypto_transfer_enrollment_mfa_checklist_email_row_secondary_verified¶ÔÔø§—ÿ¨K
@
4crypto_transfer_enrollment_mfa_checklist_helper_doneÒ…Ã½¨¹v
E
8crypto_transfer_enrollment_mfa_checklist_helper_done_rhcë°ĞåòÆÍ¨¤
;
/crypto_transfer_enrollment_mfa_checklist_helper¶¡ââÆŸÕ»Z
>
1crypto_transfer_enrollment_mfa_checklist_continue‘§‘‚ §¿Ë