
5
(order_description_market_buy_with_symbolÏÑñî­öó–Â
=
1order_description_market_buy_to_close_with_symbol¢«²ĞçòÛœ
0
#order_description_market_short_sell±ËÆôàşù„¿
/
"order_description_limit_short_sellÛŞÖ¡¶›…Ö
5
)order_description_market_sell_with_symbolº‰èÈŞ¸ºœy
;
/order_description_market_short_sell_with_symbol‹á¥•Œòš
6
)order_state_partially_filled_rest_pendingœ×ªó¾˜ú
8
+order_state_partially_filled_rest_cancelledÓªú—‹¢²Ù¾
7
+order_description_limit_ipo_buy_with_symbol¸´Å«ˆ€àY
4
'order_description_limit_buy_with_symbol¤ßì†Ô°øäÊ
=
0order_description_limit_buy_to_close_with_symbolœ½ÊÂ‚øĞêÉ
4
(order_description_limit_sell_with_symbolÑÔğ½Ïõ’Û
:
.order_description_limit_short_sell_with_symbol…•õ¶Ú¨¨I
8
+order_description_stop_loss_buy_with_symbol±‹æÑ©êâÏÒ
@
4order_description_stop_loss_buy_to_close_with_symbol—Ñµİ¹ìŒÆg
8
,order_description_stop_loss_sell_with_symbol†¾ŞÀµ‘­è
?
2order_description_stop_loss_short_sell_with_symbolıÀ«¼å´Â²•
8
,order_description_stop_limit_buy_with_symbolèåÑèÅñÊˆ
A
5order_description_stop_limit_buy_to_close_with_symbol—ñ°¦Æ–œŒw
9
-order_description_stop_limit_sell_with_symbol‡˜¥Ñ·ñ”K
<
/order_description_trailing_stop_buy_with_symbol– —À€“ğ¹
D
8order_description_trailing_stop_buy_to_close_with_symbol²¨’üò€¸‡/
<
0order_description_trailing_stop_sell_with_symbolĞ÷ö¦¸¿®`
#
dividend_state_pendingĞù‡ñå·¤ä

dividend_state_paid¯â»½òû¢é|
!
dividend_state_voidedÕù´ø˜§ÛŠ
$
dividend_state_reversed¨œİÀÓÚì”Û
'
dividend_state_reinvesting‡Ñ¡Ò·–ÒïÚ
&
dividend_state_reinvested€ö°«² Œ¼
"
dividend_state_unknown™ø°Ÿ®÷o