
*
options_rolling_nux_title_text·óËğö¡ì¦
.
!options_rolling_nux_subtitle_text¸û¤Õ¡§½šË
0
#options_rolling_nux_get_started_btnÜë¨‘´­ÀÇ“
/
#options_rolling_nux_learn_more_text¹¯ÑªÒüî‹E
,
options_rolling_learn_more_text†ç¾§šñ€ôí
1
%options_rolling_current_position_textÀíëñ§Ş‚œ=
1
$options_rolling_time_left_title_textÏÌâÇˆ·©îã
5
(options_rolling_select_new_contract_textŒÑƒÈìêÀ
0
$options_rolling_net_debit_title_textì¹Ó‚úşÍ…C
1
%options_rolling_net_credit_title_text‰µ´õ«¨Ô–h
4
'options_rolling_total_credit_title_textİ‰¼İÛı—Áı
3
&options_rolling_total_debit_title_textÂéÙ®èöÔï
2
&options_rolling_time_change_title_textëâŠˆ ŞÙ¼P
&
options_rolling_title_textîÇ°¿Ú¬¾M
*
options_rolling_subtitle_textÁ®«ãú¾µ¯
.
!options_rolling_new_position_text¡Ú­¨ÈÑÜ¤
1
$options_rolling_bottom_sheet_go_backÜ’¦¼©ÂÅ«
/
"options_rolling_no_positions_titleõÌÌğ¢Ò´ç
4
(options_rolling_no_positions_description†Øäªğäñín
4
'options_rolling_positions_pending_titleÛó¥ö¯š—çü
9
-options_rolling_positions_pending_descriptionªõš‡õá±¡u
3
&options_rolling_secondary_button_title¿¥ë©¡Óó
0
$options_rolling_menu_disclosure_text©ã÷¬µˆÆv
*
options_rolling_no_change_text¢·…ÛÇÛƒ¼-
.
"options_rolling_cash_account_title¬‰ÊÛ¨‡«û#
>
2options_rolling_cash_account_brokerage_description»¹´€øº×ën
J
=options_rolling_cash_account_brokerage_secondary_button_title¬è…‹ªÎÉîé
8
,options_rolling_cash_account_ira_descriptionó•¡¿ôß»ÿ
C
7options_rolling_cash_account_ira_secondary_button_titleÒÛ›âè³Ó¤|
L
?options_rolling_cash_account_brokerage_description_instant_cash€ëìÀ†Ú¹è
V
Joptions_rolling_cash_account_brokerage_secondary_button_title_instant_cashµ¿ëÓ£æ¬R
F
9options_rolling_cash_account_ira_description_instant_cashŸÜ·üÊ‚¬Õõ
Q
Doptions_rolling_cash_account_ira_secondary_button_title_instant_cashÍÅŒ´‘­İ
*
options_rolling_time_left_text‹øÖÑ¶’Àº*