
"
options_setting_title ¼õ¤ğ÷è
)
options_setting_level_2_labeló³ä×Ü½Ææ"
*
options_setting_level_3_label¶€íÎøŞåòä
3
&options_setting_buy_calls_puts_summaryûÔ°€Ú¶ïˆÂ
6
*options_setting_sell_covered_calls_summaryÿ­µóøƒ¯¥
5
)options_setting_sell_covered_puts_summary•ê¯ÑÇ«·-
1
$options_setting_sell_spreads_summary ëÙ…ŞÖÉ†
5
(options_setting_exercise_options_summary†Ğò•ğ–¦›˜
2
%options_setting_remove_options_action×»¦¬¹¸Šğ³
5
)options_setting_downgrade_to_basic_action™¥’—»›”§m
6
*options_setting_upgrade_to_advanced_actionï²¹üÛÅ
3
(options_setting_downgrade_to_basic_titleâÇ€Š²Ğ¬s
6
*options_setting_downgrade_to_basic_summary¹¸–ÙÒˆÔÀ*
;
/options_setting_downgrade_to_basic_confirmationê±÷ÆÿÖ†õ+
6
*options_setting_downgrade_to_basic_successøØ¼ƒƒôğî/
6
*options_setting_downgrade_to_basic_pending‘„÷÷ñÖŸ¦a
7
*options_setting_retirement_account_warningÆƒçÆ€‰å†Á
3
&options_setting_remove_options_summary‚›´éº°£
E
8options_setting_remove_options_summary_with_account_typeŸîÿâ‰»…®¸
7
+options_setting_remove_options_confirmationÁ»ß½‡·ñ
2
&options_setting_remove_options_success–ÿ¤Ÿ¬÷Ó¢;
E
8options_setting_remove_options_success_with_account_typeìœ¹øÌîæÚÚ
2
&options_setting_remove_options_pendingÎìä¹››ù 
D
8options_setting_remove_options_pending_with_account_type¼ë»ê‚€¦Ée
6
)options_setting_trade_on_expiration_labelÓîÇ¢œÂÍŒÔ
C
7options_setting_extended_trade_on_expiration_disclaimerÎ¥Æ»ÆèÜc
X
Koptions_setting_extended_trade_on_expiration_disclaimer_sellout_improvement†İÃÎäãÏŠË
P
Doptions_setting_extended_trade_on_expiration_cash_account_disclaimer›˜”Â€Üª¸
e
Xoptions_setting_extended_trade_on_expiration_cash_account_disclaimer_sellout_improvementò‹€•¦Ì¢Øš
I
=gated_cash_options_setting_upgrade_cash_account_failure_titleÔÂ’ıı£øa
K
?gated_cash_options_setting_upgrade_cash_account_failure_message‹…©Ô˜šÙ]
J
>gated_cash_options_setting_upgrade_cash_account_failure_actionµ¿ëÓ£æ¬R
0
#options_setting_short_selling_title‡‘æÅ²¤ˆñ°
2
&options_setting_short_selling_subtitle™êÀœ£Ã¿H
C
6options_setting_short_selling_subtitle_margin_disabledæ™®šæƒªÜ
5
(options_setting_short_selling_disclosureıÁÎú¯ÅÛ