
$
market_data_dialog_titleüğûãí¶À
1
$market_data_dialog_title_with_symbolï™Òêˆ–Ê¨ü
7
*market_data_dialog_title_with_symbol_limit¯Œ’¡ÿı¤
&
market_data_dialog_header÷ş„­şÕÚ¹Ä
)
market_data_dialog_header_askŠèÄŒøòÅ¾a
)
market_data_dialog_header_bid¶İá¸¼’²ëU
%
market_data_dialog_valueÕâæ„ÓÓË¦
.
"market_data_dialog_last_sale_labelÃ©“‚³ˆßîk
7
+market_data_dialog_last_sale_label_with_micÔğâ¬ÓÄƒÈ+
.
"market_data_dialog_bid_price_label²Œï¼ëñÎQ
8
+market_data_dialog_bid_price_label_with_micáËÊÍéè¾¡ü
/
"market_data_dialog_ask_price_labelÙø‰›©¬îŸ‡
7
+market_data_dialog_ask_price_label_with_micº½ÄÕü·;
2
&market_data_dialog_footer_consolidatedë¥ªìıµÒ‹@
5
(market_data_dialog_footer_24_hour_marketôû‡²ªş¬±ş
:
-market_data_dialog_footer_link_24_hour_market¬ƒ…ûòÎ™·ß
3
&market_data_dialog_footer_link_bid_askÊäÕå’­­
1
%market_data_dialog_footer_qbbo_nasdaq¯ùìç±¬ê³k
2
&market_data_dialog_footer_qbbo_24_hourúÛïÿÒ’øb
7
+market_data_dialog_footer_qbbo_consolidatedµŠÙÓĞì§ôD