package rosetta.identi.agreements;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import kotlin.Deprecated;
import kotlin.Metadata;
import kotlin.enums.EnumEntries;
import kotlin.enums.EnumEntries2;
import kotlin.jvm.JvmField;
import kotlin.jvm.JvmStatic;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Reflection;
import kotlin.reflect.KClass;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: AgreementType.kt */
@Metadata(m3635d1 = {"\u0000\u0016\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0010\b\n\u0002\b\u007f\b\u0086\u0081\u0002\u0018\u0000 \u0082\u00012\u00020\u00012\b\u0012\u0004\u0012\u00020\u00000\u0002:\u0002\u0082\u0001B\u0011\b\u0002\u0012\u0006\u0010\u0003\u001a\u00020\u0004¢\u0006\u0004\b\u0005\u0010\u0006R\u0014\u0010\u0003\u001a\u00020\u0004X\u0096\u0004¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\btj\u0002\buj\u0002\bvj\u0002\bwj\u0002\bxj\u0002\byj\u0002\bzj\u0002\b{j\u0002\b|j\u0002\b}j\u0002\b~j\u0002\b\u007fj\u0003\b\u0080\u0001j\u0003\b\u0081\u0001¨\u0006\u0083\u0001"}, m3636d2 = {"Lrosetta/identi/agreements/AgreementType;", "Lcom/squareup/wire/WireEnum;", "", "value", "", "<init>", "(Ljava/lang/String;II)V", "getValue", "()I", "AGREEMENT_TYPE_UNSPECIFIED", "MARGIN_AGREEMENT", "MARKETING_CONSENT", "INSTANT_AGREEMENT", "BROKERAGE_AGREEMENT", "BROKERAGE_AGREEMENT_WITH_W8BEN", "EMAIL_VERIFICATION_AGREEMENT", "PHONE_VERIFICATION_AGREEMENT", "PERSONA_SELFIE_AGREEMENT", "RHY_USER_AGREEMENT", "SUTTON_DEBIT_CARD_AGREEMENT", "PINDROP_VOICE_VERIFICATION_AGREEMENT", "PINDROP_VOICE_ENROLLMENT_AGREEMENT", "CRYPTO_USER_AGREEMENT", "BENEFICIARY_GENERAL_AGREEMENT", "BENEFICIARY_SPOUSAL_CONSENT_AGREEMENT", "STOCK_LOAN_CUSTOMER_AGREEMENT_V2", "STOCK_LOAN_WELLS_FARGO_CUSTODIAN_AGREEMENT", "CASH_SWEEP_AGREEMENT", "RETIREMENT_IRA_ROTH_AGREEMENT", "RETIREMENT_IRA_TRADITIONAL_AGREEMENT", "RETIREMENT_MARGIN_AGREEMENT", "STOCK_LOAN_CUSTODIAN_AGREEMENT", "PAYCHECK_RECURRING_INVESTMENTS_CUSTOMER_AGREEMENT", "GOLD_AGREEMENT", "RAM_ADVISORY_AGREEMENT", "W8_AGREEMENT", "W8_AGREEMENT_IN_APP", "W9_AGREEMENT", "W9_AGREEMENT_IN_APP", "RHD_ONBOARDING", "JOINT_ACCOUNT_AGREEMENT", "RHD_ONBOARDING_ADDITIONAL_RISK", "RHD_ONBOARDING_ARBITRATION", "ROBINHOOD_LEGEND_AGREEMENT", "OPTION_AGREEMENT", "OPTION_INSTANT_AGREEMENT", "W8_AGREEMENT_ONBOARDING", "W9_AGREEMENT_IN_APP_PART1", "W9_AGREEMENT_IN_APP_PART2", "W9_AGREEMENT_ONBOARDING_PART1", "W9_AGREEMENT_ONBOARDING_PART2", "CRYPTO_ROUNDUP_AGREEMENT", "ACATS_IN_AGREEMENT", "STOCK_ROUNDUP_AGREEMENT", "DEBIT_CARD_AGREEMENT", "SLIP_BROKERAGE_AGREEMENT_ONBOARDING", "NCW_REWARDS_TOS", "RETIREMENT_IRA_ROTH_DRIP_AGREEMENT", "EU_CRYPTO_USER_AGREEMENT", "DRIP_AGREEMENT", "USER_ACCOUNT_AGREEMENT", "GOLD_DEBIT_AUTHORIZATION_AGREEMENT", "BROKERAGE_AGREEMENT_ONBOARDING", "WALLET_AGREEMENT", "RETIREMENT_IRA_TRADITIONAL_DRIP_AGREEMENT", "RHF_INSTANT_CUSTOMER_AGREEMENT_ONBOARDING", "INTERNAL_ASSET_TRANSFER_AGREEMENT", "MARGIN_AGREEMENT_ONBOARDING", "SLIP_AGREEMENT_ONBOARDING", "SWEEP_AGREEMENT_ONBOARDING", "RHD_EVENT_CONTRACT_ATTESTATION_ELECTION", "RETIREMENT_JOINT_ACCOUNT_REMEDIATION_AGREEMENT", "RAM_INDIVIDUAL_AGREEMENT", "RAM_IRA_ROTH_AGREEMENT", "RAM_IRA_TRADITIONAL_AGREEMENT", "RAM_SLIP_AGREEMENT_ONBOARDING", "RHY_PREPAID_DEBIT_AGREEMENT", "RHY_SPENDING_AGREEMENT", "RHD_EVENT_CONTRACT_ATTESTATION_GRIDIRON", "RAM_SLIP_NATIVE_ONBOARDING", "RHD_EVENT_CONTRACT_ATTESTATION_THIRD_MONTH_CHAOS", "RHD_EVENT_CONTRACT_ATTESTATION_ECONOMIC_INDICATOR", "RHD_EVENT_CONTRACT_ATTESTATION_PRO_BASKETBALL", "RHD_EVENT_CONTRACT_ATTESTATION_PRO_HOCKEY", "ACCOUNT_SCOPE_INDIVIDUAL_MARGIN_AGREEMENT_ONBOARDING", "ACCOUNT_SCOPE_INDIVIDUAL_SLIP_AGREEMENT_ONBOARDING", "ACCOUNT_SCOPE_INDIVIDUAL_SWEEP_AGREEMENT_ONBOARDING", "ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITH_MARGIN", "ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITHOUT_MARGIN", "COMMON_REPORTING_STANDARD_SELF_CERTIFICATION", "SAGE_AGREEMENT", "AUTO_SEND_EQUITIES_MOBILE_AGREEMENT", "CORTEX_DIGEST_AGREEMENT", "RHY_ELECTRONIC_COMMUNICATIONS_CONSENT", "RHY_TERMS_OF_USE", "RHY_DEPOSIT_ACCOUNT_AGREEMENT", "REICH_TANG_CUSTOMER_TERMS_AND_CONDITIONS", "RHY_ACCOUNT_AGGREGATION_AGREEMENT", "RHY_REMOTE_DEPOSIT_CAPTURE_AGREEMENT", "RHY_CASH_DELIVERY_TERMS", "RHY_DEBIT_CARD_AGREEMENT", "AUTO_SEND_LEGEND_AGREEMENT", "CRS_CARF_SELF_CERTIFICATION", "ACCOUNT_SCOPE_DRIP_AGREEMENT", "ACCOUNT_SCOPE_JA_DRIP_AGREEMENT", "CUSTODIAL_UGMA_AGREEMENT", "CUSTODIAL_UTMA_AGREEMENT", "ECBSV_AGREEMENT", "AUTO_SEND_CRYPTO_MOBILE_AGREEMENT", "RHD_EVENT_CONTRACT_ATTESTATION_UNIVERSAL_AGREEMENT", "CUSTODIAL_ACCOUNT_AGREEMENT", "ADVISOR_MARKETPLACE_ENROLLMENT_AGREEMENT", "RHUK_STOCKS_AND_SHARES_ISA_TERMS_AND_CONDITIONS", "RHUK_STOCKS_AND_SHARES_ISA_DECLARATION", "RHUK_STOCKS_AND_SHARES_ISA_PRODUCT_KEY_FEATURES", "ACCOUNT_SCOPE_INDIVIDUAL_MULTI_SLIP_AGREEMENT_ONBOARDING", "ROBINHOOD_SOCIAL_AGREEMENT", "CUSTODIAL_MINOR_W9_AGREEMENT", "MMF_AGREEMENT", "RHUK_ISA_CASH_TRANSFER_DECLARATION", "IRA_ROTH_CRYPTO_USER_AGREEMENT", "IRA_TRADITIONAL_CRYPTO_USER_AGREEMENT", "ACCOUNT_SCOPE_SLIP_AGREEMENT", "ACCOUNT_SCOPE_SWEEP_AGREEMENT", "ACCOUNT_SCOPE_BROKERAGE_AGREEMENT", "CORTEX_LEGEND_AGREEMENT", "ROBINHOOD_EMPLOYEE_SOCIAL_AGREEMENT", "ACCOUNT_SCOPE_MULTI_SLIP_AGREEMENT", "MINNESOTA_USER_CRYPTO_DISCLOSURES", "INVESTMENT_TRACKER_CONNECT_ACCOUNT_AGREEMENT", "Companion", "rosetta.identi.agreements_externalRelease"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
/* loaded from: classes23.dex */
public final class AgreementType implements WireEnum {
    private static final /* synthetic */ EnumEntries $ENTRIES;
    private static final /* synthetic */ AgreementType[] $VALUES;
    public static final AgreementType ACATS_IN_AGREEMENT;
    public static final AgreementType ACCOUNT_SCOPE_BROKERAGE_AGREEMENT;
    public static final AgreementType ACCOUNT_SCOPE_DRIP_AGREEMENT;
    public static final AgreementType ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITHOUT_MARGIN;
    public static final AgreementType ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITH_MARGIN;
    public static final AgreementType ACCOUNT_SCOPE_INDIVIDUAL_MARGIN_AGREEMENT_ONBOARDING;
    public static final AgreementType ACCOUNT_SCOPE_INDIVIDUAL_MULTI_SLIP_AGREEMENT_ONBOARDING;
    public static final AgreementType ACCOUNT_SCOPE_INDIVIDUAL_SLIP_AGREEMENT_ONBOARDING;
    public static final AgreementType ACCOUNT_SCOPE_INDIVIDUAL_SWEEP_AGREEMENT_ONBOARDING;
    public static final AgreementType ACCOUNT_SCOPE_JA_DRIP_AGREEMENT;
    public static final AgreementType ACCOUNT_SCOPE_MULTI_SLIP_AGREEMENT;
    public static final AgreementType ACCOUNT_SCOPE_SLIP_AGREEMENT;
    public static final AgreementType ACCOUNT_SCOPE_SWEEP_AGREEMENT;

    @JvmField
    public static final ProtoAdapter<AgreementType> ADAPTER;
    public static final AgreementType ADVISOR_MARKETPLACE_ENROLLMENT_AGREEMENT;
    public static final AgreementType AGREEMENT_TYPE_UNSPECIFIED;
    public static final AgreementType AUTO_SEND_CRYPTO_MOBILE_AGREEMENT;
    public static final AgreementType AUTO_SEND_EQUITIES_MOBILE_AGREEMENT;
    public static final AgreementType AUTO_SEND_LEGEND_AGREEMENT;
    public static final AgreementType BENEFICIARY_GENERAL_AGREEMENT;
    public static final AgreementType BENEFICIARY_SPOUSAL_CONSENT_AGREEMENT;
    public static final AgreementType BROKERAGE_AGREEMENT;
    public static final AgreementType BROKERAGE_AGREEMENT_ONBOARDING;
    public static final AgreementType BROKERAGE_AGREEMENT_WITH_W8BEN;
    public static final AgreementType CASH_SWEEP_AGREEMENT;
    public static final AgreementType COMMON_REPORTING_STANDARD_SELF_CERTIFICATION;
    public static final AgreementType CORTEX_DIGEST_AGREEMENT;
    public static final AgreementType CORTEX_LEGEND_AGREEMENT;
    public static final AgreementType CRS_CARF_SELF_CERTIFICATION;
    public static final AgreementType CRYPTO_ROUNDUP_AGREEMENT;
    public static final AgreementType CRYPTO_USER_AGREEMENT;
    public static final AgreementType CUSTODIAL_ACCOUNT_AGREEMENT;
    public static final AgreementType CUSTODIAL_MINOR_W9_AGREEMENT;

    @Deprecated
    public static final AgreementType CUSTODIAL_UGMA_AGREEMENT;

    @Deprecated
    public static final AgreementType CUSTODIAL_UTMA_AGREEMENT;

    /* renamed from: Companion, reason: from kotlin metadata */
    public static final Companion INSTANCE;
    public static final AgreementType DEBIT_CARD_AGREEMENT;
    public static final AgreementType DRIP_AGREEMENT;
    public static final AgreementType ECBSV_AGREEMENT;
    public static final AgreementType EMAIL_VERIFICATION_AGREEMENT;
    public static final AgreementType EU_CRYPTO_USER_AGREEMENT;
    public static final AgreementType GOLD_AGREEMENT;
    public static final AgreementType GOLD_DEBIT_AUTHORIZATION_AGREEMENT;
    public static final AgreementType INSTANT_AGREEMENT;
    public static final AgreementType INTERNAL_ASSET_TRANSFER_AGREEMENT;
    public static final AgreementType INVESTMENT_TRACKER_CONNECT_ACCOUNT_AGREEMENT;
    public static final AgreementType IRA_ROTH_CRYPTO_USER_AGREEMENT;
    public static final AgreementType IRA_TRADITIONAL_CRYPTO_USER_AGREEMENT;
    public static final AgreementType JOINT_ACCOUNT_AGREEMENT;
    public static final AgreementType MARGIN_AGREEMENT;
    public static final AgreementType MARGIN_AGREEMENT_ONBOARDING;
    public static final AgreementType MARKETING_CONSENT;
    public static final AgreementType MINNESOTA_USER_CRYPTO_DISCLOSURES;
    public static final AgreementType MMF_AGREEMENT;
    public static final AgreementType NCW_REWARDS_TOS;
    public static final AgreementType OPTION_AGREEMENT;
    public static final AgreementType OPTION_INSTANT_AGREEMENT;
    public static final AgreementType PAYCHECK_RECURRING_INVESTMENTS_CUSTOMER_AGREEMENT;
    public static final AgreementType PERSONA_SELFIE_AGREEMENT;
    public static final AgreementType PHONE_VERIFICATION_AGREEMENT;
    public static final AgreementType PINDROP_VOICE_ENROLLMENT_AGREEMENT;
    public static final AgreementType PINDROP_VOICE_VERIFICATION_AGREEMENT;
    public static final AgreementType RAM_ADVISORY_AGREEMENT;
    public static final AgreementType RAM_INDIVIDUAL_AGREEMENT;
    public static final AgreementType RAM_IRA_ROTH_AGREEMENT;
    public static final AgreementType RAM_IRA_TRADITIONAL_AGREEMENT;
    public static final AgreementType RAM_SLIP_AGREEMENT_ONBOARDING;
    public static final AgreementType RAM_SLIP_NATIVE_ONBOARDING;
    public static final AgreementType REICH_TANG_CUSTOMER_TERMS_AND_CONDITIONS;
    public static final AgreementType RETIREMENT_IRA_ROTH_AGREEMENT;
    public static final AgreementType RETIREMENT_IRA_ROTH_DRIP_AGREEMENT;
    public static final AgreementType RETIREMENT_IRA_TRADITIONAL_AGREEMENT;
    public static final AgreementType RETIREMENT_IRA_TRADITIONAL_DRIP_AGREEMENT;
    public static final AgreementType RETIREMENT_JOINT_ACCOUNT_REMEDIATION_AGREEMENT;
    public static final AgreementType RETIREMENT_MARGIN_AGREEMENT;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_ECONOMIC_INDICATOR;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_ELECTION;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_GRIDIRON;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_PRO_BASKETBALL;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_PRO_HOCKEY;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_THIRD_MONTH_CHAOS;
    public static final AgreementType RHD_EVENT_CONTRACT_ATTESTATION_UNIVERSAL_AGREEMENT;
    public static final AgreementType RHD_ONBOARDING;
    public static final AgreementType RHD_ONBOARDING_ADDITIONAL_RISK;
    public static final AgreementType RHD_ONBOARDING_ARBITRATION;
    public static final AgreementType RHF_INSTANT_CUSTOMER_AGREEMENT_ONBOARDING;
    public static final AgreementType RHUK_ISA_CASH_TRANSFER_DECLARATION;
    public static final AgreementType RHUK_STOCKS_AND_SHARES_ISA_DECLARATION;
    public static final AgreementType RHUK_STOCKS_AND_SHARES_ISA_PRODUCT_KEY_FEATURES;
    public static final AgreementType RHUK_STOCKS_AND_SHARES_ISA_TERMS_AND_CONDITIONS;
    public static final AgreementType RHY_ACCOUNT_AGGREGATION_AGREEMENT;
    public static final AgreementType RHY_CASH_DELIVERY_TERMS;
    public static final AgreementType RHY_DEBIT_CARD_AGREEMENT;
    public static final AgreementType RHY_DEPOSIT_ACCOUNT_AGREEMENT;
    public static final AgreementType RHY_ELECTRONIC_COMMUNICATIONS_CONSENT;
    public static final AgreementType RHY_PREPAID_DEBIT_AGREEMENT;
    public static final AgreementType RHY_REMOTE_DEPOSIT_CAPTURE_AGREEMENT;
    public static final AgreementType RHY_SPENDING_AGREEMENT;
    public static final AgreementType RHY_TERMS_OF_USE;
    public static final AgreementType RHY_USER_AGREEMENT;
    public static final AgreementType ROBINHOOD_EMPLOYEE_SOCIAL_AGREEMENT;
    public static final AgreementType ROBINHOOD_LEGEND_AGREEMENT;
    public static final AgreementType ROBINHOOD_SOCIAL_AGREEMENT;
    public static final AgreementType SAGE_AGREEMENT;
    public static final AgreementType SLIP_AGREEMENT_ONBOARDING;
    public static final AgreementType SLIP_BROKERAGE_AGREEMENT_ONBOARDING;
    public static final AgreementType STOCK_LOAN_CUSTODIAN_AGREEMENT;
    public static final AgreementType STOCK_LOAN_CUSTOMER_AGREEMENT_V2;
    public static final AgreementType STOCK_LOAN_WELLS_FARGO_CUSTODIAN_AGREEMENT;
    public static final AgreementType STOCK_ROUNDUP_AGREEMENT;
    public static final AgreementType SUTTON_DEBIT_CARD_AGREEMENT;
    public static final AgreementType SWEEP_AGREEMENT_ONBOARDING;
    public static final AgreementType USER_ACCOUNT_AGREEMENT;
    public static final AgreementType W8_AGREEMENT;
    public static final AgreementType W8_AGREEMENT_IN_APP;
    public static final AgreementType W8_AGREEMENT_ONBOARDING;
    public static final AgreementType W9_AGREEMENT;
    public static final AgreementType W9_AGREEMENT_IN_APP;
    public static final AgreementType W9_AGREEMENT_IN_APP_PART1;
    public static final AgreementType W9_AGREEMENT_IN_APP_PART2;
    public static final AgreementType W9_AGREEMENT_ONBOARDING_PART1;
    public static final AgreementType W9_AGREEMENT_ONBOARDING_PART2;
    public static final AgreementType WALLET_AGREEMENT;
    private final int value;

    private static final /* synthetic */ AgreementType[] $values() {
        return new AgreementType[]{AGREEMENT_TYPE_UNSPECIFIED, MARGIN_AGREEMENT, MARKETING_CONSENT, INSTANT_AGREEMENT, BROKERAGE_AGREEMENT, BROKERAGE_AGREEMENT_WITH_W8BEN, EMAIL_VERIFICATION_AGREEMENT, PHONE_VERIFICATION_AGREEMENT, PERSONA_SELFIE_AGREEMENT, RHY_USER_AGREEMENT, SUTTON_DEBIT_CARD_AGREEMENT, PINDROP_VOICE_VERIFICATION_AGREEMENT, PINDROP_VOICE_ENROLLMENT_AGREEMENT, CRYPTO_USER_AGREEMENT, BENEFICIARY_GENERAL_AGREEMENT, BENEFICIARY_SPOUSAL_CONSENT_AGREEMENT, STOCK_LOAN_CUSTOMER_AGREEMENT_V2, STOCK_LOAN_WELLS_FARGO_CUSTODIAN_AGREEMENT, CASH_SWEEP_AGREEMENT, RETIREMENT_IRA_ROTH_AGREEMENT, RETIREMENT_IRA_TRADITIONAL_AGREEMENT, RETIREMENT_MARGIN_AGREEMENT, STOCK_LOAN_CUSTODIAN_AGREEMENT, PAYCHECK_RECURRING_INVESTMENTS_CUSTOMER_AGREEMENT, GOLD_AGREEMENT, RAM_ADVISORY_AGREEMENT, W8_AGREEMENT, W8_AGREEMENT_IN_APP, W9_AGREEMENT, W9_AGREEMENT_IN_APP, RHD_ONBOARDING, JOINT_ACCOUNT_AGREEMENT, RHD_ONBOARDING_ADDITIONAL_RISK, RHD_ONBOARDING_ARBITRATION, ROBINHOOD_LEGEND_AGREEMENT, OPTION_AGREEMENT, OPTION_INSTANT_AGREEMENT, W8_AGREEMENT_ONBOARDING, W9_AGREEMENT_IN_APP_PART1, W9_AGREEMENT_IN_APP_PART2, W9_AGREEMENT_ONBOARDING_PART1, W9_AGREEMENT_ONBOARDING_PART2, CRYPTO_ROUNDUP_AGREEMENT, ACATS_IN_AGREEMENT, STOCK_ROUNDUP_AGREEMENT, DEBIT_CARD_AGREEMENT, SLIP_BROKERAGE_AGREEMENT_ONBOARDING, NCW_REWARDS_TOS, RETIREMENT_IRA_ROTH_DRIP_AGREEMENT, EU_CRYPTO_USER_AGREEMENT, DRIP_AGREEMENT, USER_ACCOUNT_AGREEMENT, GOLD_DEBIT_AUTHORIZATION_AGREEMENT, BROKERAGE_AGREEMENT_ONBOARDING, WALLET_AGREEMENT, RETIREMENT_IRA_TRADITIONAL_DRIP_AGREEMENT, RHF_INSTANT_CUSTOMER_AGREEMENT_ONBOARDING, INTERNAL_ASSET_TRANSFER_AGREEMENT, MARGIN_AGREEMENT_ONBOARDING, SLIP_AGREEMENT_ONBOARDING, SWEEP_AGREEMENT_ONBOARDING, RHD_EVENT_CONTRACT_ATTESTATION_ELECTION, RETIREMENT_JOINT_ACCOUNT_REMEDIATION_AGREEMENT, RAM_INDIVIDUAL_AGREEMENT, RAM_IRA_ROTH_AGREEMENT, RAM_IRA_TRADITIONAL_AGREEMENT, RAM_SLIP_AGREEMENT_ONBOARDING, RHY_PREPAID_DEBIT_AGREEMENT, RHY_SPENDING_AGREEMENT, RHD_EVENT_CONTRACT_ATTESTATION_GRIDIRON, RAM_SLIP_NATIVE_ONBOARDING, RHD_EVENT_CONTRACT_ATTESTATION_THIRD_MONTH_CHAOS, RHD_EVENT_CONTRACT_ATTESTATION_ECONOMIC_INDICATOR, RHD_EVENT_CONTRACT_ATTESTATION_PRO_BASKETBALL, RHD_EVENT_CONTRACT_ATTESTATION_PRO_HOCKEY, ACCOUNT_SCOPE_INDIVIDUAL_MARGIN_AGREEMENT_ONBOARDING, ACCOUNT_SCOPE_INDIVIDUAL_SLIP_AGREEMENT_ONBOARDING, ACCOUNT_SCOPE_INDIVIDUAL_SWEEP_AGREEMENT_ONBOARDING, ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITH_MARGIN, ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITHOUT_MARGIN, COMMON_REPORTING_STANDARD_SELF_CERTIFICATION, SAGE_AGREEMENT, AUTO_SEND_EQUITIES_MOBILE_AGREEMENT, CORTEX_DIGEST_AGREEMENT, RHY_ELECTRONIC_COMMUNICATIONS_CONSENT, RHY_TERMS_OF_USE, RHY_DEPOSIT_ACCOUNT_AGREEMENT, REICH_TANG_CUSTOMER_TERMS_AND_CONDITIONS, RHY_ACCOUNT_AGGREGATION_AGREEMENT, RHY_REMOTE_DEPOSIT_CAPTURE_AGREEMENT, RHY_CASH_DELIVERY_TERMS, RHY_DEBIT_CARD_AGREEMENT, AUTO_SEND_LEGEND_AGREEMENT, CRS_CARF_SELF_CERTIFICATION, ACCOUNT_SCOPE_DRIP_AGREEMENT, ACCOUNT_SCOPE_JA_DRIP_AGREEMENT, CUSTODIAL_UGMA_AGREEMENT, CUSTODIAL_UTMA_AGREEMENT, ECBSV_AGREEMENT, AUTO_SEND_CRYPTO_MOBILE_AGREEMENT, RHD_EVENT_CONTRACT_ATTESTATION_UNIVERSAL_AGREEMENT, CUSTODIAL_ACCOUNT_AGREEMENT, ADVISOR_MARKETPLACE_ENROLLMENT_AGREEMENT, RHUK_STOCKS_AND_SHARES_ISA_TERMS_AND_CONDITIONS, RHUK_STOCKS_AND_SHARES_ISA_DECLARATION, RHUK_STOCKS_AND_SHARES_ISA_PRODUCT_KEY_FEATURES, ACCOUNT_SCOPE_INDIVIDUAL_MULTI_SLIP_AGREEMENT_ONBOARDING, ROBINHOOD_SOCIAL_AGREEMENT, CUSTODIAL_MINOR_W9_AGREEMENT, MMF_AGREEMENT, RHUK_ISA_CASH_TRANSFER_DECLARATION, IRA_ROTH_CRYPTO_USER_AGREEMENT, IRA_TRADITIONAL_CRYPTO_USER_AGREEMENT, ACCOUNT_SCOPE_SLIP_AGREEMENT, ACCOUNT_SCOPE_SWEEP_AGREEMENT, ACCOUNT_SCOPE_BROKERAGE_AGREEMENT, CORTEX_LEGEND_AGREEMENT, ROBINHOOD_EMPLOYEE_SOCIAL_AGREEMENT, ACCOUNT_SCOPE_MULTI_SLIP_AGREEMENT, MINNESOTA_USER_CRYPTO_DISCLOSURES, INVESTMENT_TRACKER_CONNECT_ACCOUNT_AGREEMENT};
    }

    @JvmStatic
    public static final AgreementType fromValue(int i) {
        return INSTANCE.fromValue(i);
    }

    public static EnumEntries<AgreementType> getEntries() {
        return $ENTRIES;
    }

    private AgreementType(String str, int i, int i2) {
        this.value = i2;
    }

    @Override // com.squareup.wire.WireEnum
    public int getValue() {
        return this.value;
    }

    static {
        final AgreementType agreementType = new AgreementType("AGREEMENT_TYPE_UNSPECIFIED", 0, 0);
        AGREEMENT_TYPE_UNSPECIFIED = agreementType;
        MARGIN_AGREEMENT = new AgreementType("MARGIN_AGREEMENT", 1, 1);
        MARKETING_CONSENT = new AgreementType("MARKETING_CONSENT", 2, 2);
        INSTANT_AGREEMENT = new AgreementType("INSTANT_AGREEMENT", 3, 3);
        BROKERAGE_AGREEMENT = new AgreementType("BROKERAGE_AGREEMENT", 4, 4);
        BROKERAGE_AGREEMENT_WITH_W8BEN = new AgreementType("BROKERAGE_AGREEMENT_WITH_W8BEN", 5, 5);
        EMAIL_VERIFICATION_AGREEMENT = new AgreementType("EMAIL_VERIFICATION_AGREEMENT", 6, 6);
        PHONE_VERIFICATION_AGREEMENT = new AgreementType("PHONE_VERIFICATION_AGREEMENT", 7, 7);
        PERSONA_SELFIE_AGREEMENT = new AgreementType("PERSONA_SELFIE_AGREEMENT", 8, 8);
        RHY_USER_AGREEMENT = new AgreementType("RHY_USER_AGREEMENT", 9, 9);
        SUTTON_DEBIT_CARD_AGREEMENT = new AgreementType("SUTTON_DEBIT_CARD_AGREEMENT", 10, 10);
        PINDROP_VOICE_VERIFICATION_AGREEMENT = new AgreementType("PINDROP_VOICE_VERIFICATION_AGREEMENT", 11, 11);
        PINDROP_VOICE_ENROLLMENT_AGREEMENT = new AgreementType("PINDROP_VOICE_ENROLLMENT_AGREEMENT", 12, 12);
        CRYPTO_USER_AGREEMENT = new AgreementType("CRYPTO_USER_AGREEMENT", 13, 13);
        BENEFICIARY_GENERAL_AGREEMENT = new AgreementType("BENEFICIARY_GENERAL_AGREEMENT", 14, 14);
        BENEFICIARY_SPOUSAL_CONSENT_AGREEMENT = new AgreementType("BENEFICIARY_SPOUSAL_CONSENT_AGREEMENT", 15, 15);
        STOCK_LOAN_CUSTOMER_AGREEMENT_V2 = new AgreementType("STOCK_LOAN_CUSTOMER_AGREEMENT_V2", 16, 16);
        STOCK_LOAN_WELLS_FARGO_CUSTODIAN_AGREEMENT = new AgreementType("STOCK_LOAN_WELLS_FARGO_CUSTODIAN_AGREEMENT", 17, 17);
        CASH_SWEEP_AGREEMENT = new AgreementType("CASH_SWEEP_AGREEMENT", 18, 18);
        RETIREMENT_IRA_ROTH_AGREEMENT = new AgreementType("RETIREMENT_IRA_ROTH_AGREEMENT", 19, 19);
        RETIREMENT_IRA_TRADITIONAL_AGREEMENT = new AgreementType("RETIREMENT_IRA_TRADITIONAL_AGREEMENT", 20, 20);
        RETIREMENT_MARGIN_AGREEMENT = new AgreementType("RETIREMENT_MARGIN_AGREEMENT", 21, 21);
        STOCK_LOAN_CUSTODIAN_AGREEMENT = new AgreementType("STOCK_LOAN_CUSTODIAN_AGREEMENT", 22, 22);
        PAYCHECK_RECURRING_INVESTMENTS_CUSTOMER_AGREEMENT = new AgreementType("PAYCHECK_RECURRING_INVESTMENTS_CUSTOMER_AGREEMENT", 23, 23);
        GOLD_AGREEMENT = new AgreementType("GOLD_AGREEMENT", 24, 24);
        RAM_ADVISORY_AGREEMENT = new AgreementType("RAM_ADVISORY_AGREEMENT", 25, 25);
        W8_AGREEMENT = new AgreementType("W8_AGREEMENT", 26, 26);
        W8_AGREEMENT_IN_APP = new AgreementType("W8_AGREEMENT_IN_APP", 27, 27);
        W9_AGREEMENT = new AgreementType("W9_AGREEMENT", 28, 28);
        W9_AGREEMENT_IN_APP = new AgreementType("W9_AGREEMENT_IN_APP", 29, 29);
        RHD_ONBOARDING = new AgreementType("RHD_ONBOARDING", 30, 30);
        JOINT_ACCOUNT_AGREEMENT = new AgreementType("JOINT_ACCOUNT_AGREEMENT", 31, 31);
        RHD_ONBOARDING_ADDITIONAL_RISK = new AgreementType("RHD_ONBOARDING_ADDITIONAL_RISK", 32, 32);
        RHD_ONBOARDING_ARBITRATION = new AgreementType("RHD_ONBOARDING_ARBITRATION", 33, 33);
        ROBINHOOD_LEGEND_AGREEMENT = new AgreementType("ROBINHOOD_LEGEND_AGREEMENT", 34, 34);
        OPTION_AGREEMENT = new AgreementType("OPTION_AGREEMENT", 35, 35);
        OPTION_INSTANT_AGREEMENT = new AgreementType("OPTION_INSTANT_AGREEMENT", 36, 36);
        W8_AGREEMENT_ONBOARDING = new AgreementType("W8_AGREEMENT_ONBOARDING", 37, 37);
        W9_AGREEMENT_IN_APP_PART1 = new AgreementType("W9_AGREEMENT_IN_APP_PART1", 38, 38);
        W9_AGREEMENT_IN_APP_PART2 = new AgreementType("W9_AGREEMENT_IN_APP_PART2", 39, 39);
        W9_AGREEMENT_ONBOARDING_PART1 = new AgreementType("W9_AGREEMENT_ONBOARDING_PART1", 40, 40);
        W9_AGREEMENT_ONBOARDING_PART2 = new AgreementType("W9_AGREEMENT_ONBOARDING_PART2", 41, 41);
        CRYPTO_ROUNDUP_AGREEMENT = new AgreementType("CRYPTO_ROUNDUP_AGREEMENT", 42, 42);
        ACATS_IN_AGREEMENT = new AgreementType("ACATS_IN_AGREEMENT", 43, 43);
        STOCK_ROUNDUP_AGREEMENT = new AgreementType("STOCK_ROUNDUP_AGREEMENT", 44, 44);
        DEBIT_CARD_AGREEMENT = new AgreementType("DEBIT_CARD_AGREEMENT", 45, 45);
        SLIP_BROKERAGE_AGREEMENT_ONBOARDING = new AgreementType("SLIP_BROKERAGE_AGREEMENT_ONBOARDING", 46, 46);
        NCW_REWARDS_TOS = new AgreementType("NCW_REWARDS_TOS", 47, 47);
        RETIREMENT_IRA_ROTH_DRIP_AGREEMENT = new AgreementType("RETIREMENT_IRA_ROTH_DRIP_AGREEMENT", 48, 48);
        EU_CRYPTO_USER_AGREEMENT = new AgreementType("EU_CRYPTO_USER_AGREEMENT", 49, 49);
        DRIP_AGREEMENT = new AgreementType("DRIP_AGREEMENT", 50, 50);
        USER_ACCOUNT_AGREEMENT = new AgreementType("USER_ACCOUNT_AGREEMENT", 51, 51);
        GOLD_DEBIT_AUTHORIZATION_AGREEMENT = new AgreementType("GOLD_DEBIT_AUTHORIZATION_AGREEMENT", 52, 52);
        BROKERAGE_AGREEMENT_ONBOARDING = new AgreementType("BROKERAGE_AGREEMENT_ONBOARDING", 53, 53);
        WALLET_AGREEMENT = new AgreementType("WALLET_AGREEMENT", 54, 54);
        RETIREMENT_IRA_TRADITIONAL_DRIP_AGREEMENT = new AgreementType("RETIREMENT_IRA_TRADITIONAL_DRIP_AGREEMENT", 55, 55);
        RHF_INSTANT_CUSTOMER_AGREEMENT_ONBOARDING = new AgreementType("RHF_INSTANT_CUSTOMER_AGREEMENT_ONBOARDING", 56, 56);
        INTERNAL_ASSET_TRANSFER_AGREEMENT = new AgreementType("INTERNAL_ASSET_TRANSFER_AGREEMENT", 57, 57);
        MARGIN_AGREEMENT_ONBOARDING = new AgreementType("MARGIN_AGREEMENT_ONBOARDING", 58, 58);
        SLIP_AGREEMENT_ONBOARDING = new AgreementType("SLIP_AGREEMENT_ONBOARDING", 59, 59);
        SWEEP_AGREEMENT_ONBOARDING = new AgreementType("SWEEP_AGREEMENT_ONBOARDING", 60, 60);
        RHD_EVENT_CONTRACT_ATTESTATION_ELECTION = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_ELECTION", 61, 61);
        RETIREMENT_JOINT_ACCOUNT_REMEDIATION_AGREEMENT = new AgreementType("RETIREMENT_JOINT_ACCOUNT_REMEDIATION_AGREEMENT", 62, 62);
        RAM_INDIVIDUAL_AGREEMENT = new AgreementType("RAM_INDIVIDUAL_AGREEMENT", 63, 63);
        RAM_IRA_ROTH_AGREEMENT = new AgreementType("RAM_IRA_ROTH_AGREEMENT", 64, 64);
        RAM_IRA_TRADITIONAL_AGREEMENT = new AgreementType("RAM_IRA_TRADITIONAL_AGREEMENT", 65, 65);
        RAM_SLIP_AGREEMENT_ONBOARDING = new AgreementType("RAM_SLIP_AGREEMENT_ONBOARDING", 66, 66);
        RHY_PREPAID_DEBIT_AGREEMENT = new AgreementType("RHY_PREPAID_DEBIT_AGREEMENT", 67, 67);
        RHY_SPENDING_AGREEMENT = new AgreementType("RHY_SPENDING_AGREEMENT", 68, 68);
        RHD_EVENT_CONTRACT_ATTESTATION_GRIDIRON = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_GRIDIRON", 69, 69);
        RAM_SLIP_NATIVE_ONBOARDING = new AgreementType("RAM_SLIP_NATIVE_ONBOARDING", 70, 70);
        RHD_EVENT_CONTRACT_ATTESTATION_THIRD_MONTH_CHAOS = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_THIRD_MONTH_CHAOS", 71, 71);
        RHD_EVENT_CONTRACT_ATTESTATION_ECONOMIC_INDICATOR = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_ECONOMIC_INDICATOR", 72, 72);
        RHD_EVENT_CONTRACT_ATTESTATION_PRO_BASKETBALL = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_PRO_BASKETBALL", 73, 73);
        RHD_EVENT_CONTRACT_ATTESTATION_PRO_HOCKEY = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_PRO_HOCKEY", 74, 74);
        ACCOUNT_SCOPE_INDIVIDUAL_MARGIN_AGREEMENT_ONBOARDING = new AgreementType("ACCOUNT_SCOPE_INDIVIDUAL_MARGIN_AGREEMENT_ONBOARDING", 75, 75);
        ACCOUNT_SCOPE_INDIVIDUAL_SLIP_AGREEMENT_ONBOARDING = new AgreementType("ACCOUNT_SCOPE_INDIVIDUAL_SLIP_AGREEMENT_ONBOARDING", 76, 76);
        ACCOUNT_SCOPE_INDIVIDUAL_SWEEP_AGREEMENT_ONBOARDING = new AgreementType("ACCOUNT_SCOPE_INDIVIDUAL_SWEEP_AGREEMENT_ONBOARDING", 77, 77);
        ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITH_MARGIN = new AgreementType("ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITH_MARGIN", 78, 78);
        ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITHOUT_MARGIN = new AgreementType("ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITHOUT_MARGIN", 79, 79);
        COMMON_REPORTING_STANDARD_SELF_CERTIFICATION = new AgreementType("COMMON_REPORTING_STANDARD_SELF_CERTIFICATION", 80, 80);
        SAGE_AGREEMENT = new AgreementType("SAGE_AGREEMENT", 81, 81);
        AUTO_SEND_EQUITIES_MOBILE_AGREEMENT = new AgreementType("AUTO_SEND_EQUITIES_MOBILE_AGREEMENT", 82, 82);
        CORTEX_DIGEST_AGREEMENT = new AgreementType("CORTEX_DIGEST_AGREEMENT", 83, 83);
        RHY_ELECTRONIC_COMMUNICATIONS_CONSENT = new AgreementType("RHY_ELECTRONIC_COMMUNICATIONS_CONSENT", 84, 84);
        RHY_TERMS_OF_USE = new AgreementType("RHY_TERMS_OF_USE", 85, 85);
        RHY_DEPOSIT_ACCOUNT_AGREEMENT = new AgreementType("RHY_DEPOSIT_ACCOUNT_AGREEMENT", 86, 86);
        REICH_TANG_CUSTOMER_TERMS_AND_CONDITIONS = new AgreementType("REICH_TANG_CUSTOMER_TERMS_AND_CONDITIONS", 87, 87);
        RHY_ACCOUNT_AGGREGATION_AGREEMENT = new AgreementType("RHY_ACCOUNT_AGGREGATION_AGREEMENT", 88, 88);
        RHY_REMOTE_DEPOSIT_CAPTURE_AGREEMENT = new AgreementType("RHY_REMOTE_DEPOSIT_CAPTURE_AGREEMENT", 89, 89);
        RHY_CASH_DELIVERY_TERMS = new AgreementType("RHY_CASH_DELIVERY_TERMS", 90, 90);
        RHY_DEBIT_CARD_AGREEMENT = new AgreementType("RHY_DEBIT_CARD_AGREEMENT", 91, 91);
        AUTO_SEND_LEGEND_AGREEMENT = new AgreementType("AUTO_SEND_LEGEND_AGREEMENT", 92, 92);
        CRS_CARF_SELF_CERTIFICATION = new AgreementType("CRS_CARF_SELF_CERTIFICATION", 93, 93);
        ACCOUNT_SCOPE_DRIP_AGREEMENT = new AgreementType("ACCOUNT_SCOPE_DRIP_AGREEMENT", 94, 94);
        ACCOUNT_SCOPE_JA_DRIP_AGREEMENT = new AgreementType("ACCOUNT_SCOPE_JA_DRIP_AGREEMENT", 95, 95);
        CUSTODIAL_UGMA_AGREEMENT = new AgreementType("CUSTODIAL_UGMA_AGREEMENT", 96, 96);
        CUSTODIAL_UTMA_AGREEMENT = new AgreementType("CUSTODIAL_UTMA_AGREEMENT", 97, 97);
        ECBSV_AGREEMENT = new AgreementType("ECBSV_AGREEMENT", 98, 98);
        AUTO_SEND_CRYPTO_MOBILE_AGREEMENT = new AgreementType("AUTO_SEND_CRYPTO_MOBILE_AGREEMENT", 99, 99);
        RHD_EVENT_CONTRACT_ATTESTATION_UNIVERSAL_AGREEMENT = new AgreementType("RHD_EVENT_CONTRACT_ATTESTATION_UNIVERSAL_AGREEMENT", 100, 100);
        CUSTODIAL_ACCOUNT_AGREEMENT = new AgreementType("CUSTODIAL_ACCOUNT_AGREEMENT", 101, 101);
        ADVISOR_MARKETPLACE_ENROLLMENT_AGREEMENT = new AgreementType("ADVISOR_MARKETPLACE_ENROLLMENT_AGREEMENT", 102, 102);
        RHUK_STOCKS_AND_SHARES_ISA_TERMS_AND_CONDITIONS = new AgreementType("RHUK_STOCKS_AND_SHARES_ISA_TERMS_AND_CONDITIONS", 103, 103);
        RHUK_STOCKS_AND_SHARES_ISA_DECLARATION = new AgreementType("RHUK_STOCKS_AND_SHARES_ISA_DECLARATION", 104, 104);
        RHUK_STOCKS_AND_SHARES_ISA_PRODUCT_KEY_FEATURES = new AgreementType("RHUK_STOCKS_AND_SHARES_ISA_PRODUCT_KEY_FEATURES", 105, 105);
        ACCOUNT_SCOPE_INDIVIDUAL_MULTI_SLIP_AGREEMENT_ONBOARDING = new AgreementType("ACCOUNT_SCOPE_INDIVIDUAL_MULTI_SLIP_AGREEMENT_ONBOARDING", 106, 106);
        ROBINHOOD_SOCIAL_AGREEMENT = new AgreementType("ROBINHOOD_SOCIAL_AGREEMENT", 107, 107);
        CUSTODIAL_MINOR_W9_AGREEMENT = new AgreementType("CUSTODIAL_MINOR_W9_AGREEMENT", 108, 108);
        MMF_AGREEMENT = new AgreementType("MMF_AGREEMENT", 109, 109);
        RHUK_ISA_CASH_TRANSFER_DECLARATION = new AgreementType("RHUK_ISA_CASH_TRANSFER_DECLARATION", 110, 110);
        IRA_ROTH_CRYPTO_USER_AGREEMENT = new AgreementType("IRA_ROTH_CRYPTO_USER_AGREEMENT", 111, 111);
        IRA_TRADITIONAL_CRYPTO_USER_AGREEMENT = new AgreementType("IRA_TRADITIONAL_CRYPTO_USER_AGREEMENT", 112, 112);
        ACCOUNT_SCOPE_SLIP_AGREEMENT = new AgreementType("ACCOUNT_SCOPE_SLIP_AGREEMENT", 113, 113);
        ACCOUNT_SCOPE_SWEEP_AGREEMENT = new AgreementType("ACCOUNT_SCOPE_SWEEP_AGREEMENT", 114, 114);
        ACCOUNT_SCOPE_BROKERAGE_AGREEMENT = new AgreementType("ACCOUNT_SCOPE_BROKERAGE_AGREEMENT", 115, 115);
        CORTEX_LEGEND_AGREEMENT = new AgreementType("CORTEX_LEGEND_AGREEMENT", 116, 116);
        ROBINHOOD_EMPLOYEE_SOCIAL_AGREEMENT = new AgreementType("ROBINHOOD_EMPLOYEE_SOCIAL_AGREEMENT", 117, 117);
        ACCOUNT_SCOPE_MULTI_SLIP_AGREEMENT = new AgreementType("ACCOUNT_SCOPE_MULTI_SLIP_AGREEMENT", 118, 118);
        MINNESOTA_USER_CRYPTO_DISCLOSURES = new AgreementType("MINNESOTA_USER_CRYPTO_DISCLOSURES", 119, 119);
        INVESTMENT_TRACKER_CONNECT_ACCOUNT_AGREEMENT = new AgreementType("INVESTMENT_TRACKER_CONNECT_ACCOUNT_AGREEMENT", 120, 120);
        AgreementType[] agreementTypeArr$values = $values();
        $VALUES = agreementTypeArr$values;
        $ENTRIES = EnumEntries2.enumEntries(agreementTypeArr$values);
        INSTANCE = new Companion(null);
        final KClass orCreateKotlinClass = Reflection.getOrCreateKotlinClass(AgreementType.class);
        final Syntax syntax = Syntax.PROTO_3;
        ADAPTER = new EnumAdapter<AgreementType>(orCreateKotlinClass, syntax, agreementType) { // from class: rosetta.identi.agreements.AgreementType$Companion$ADAPTER$1
            /* JADX INFO: Access modifiers changed from: protected */
            @Override // com.squareup.wire.EnumAdapter
            public AgreementType fromValue(int value) {
                return AgreementType.INSTANCE.fromValue(value);
            }
        };
    }

    /* compiled from: AgreementType.kt */
    @Metadata(m3635d1 = {"\u0000\u001e\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\b\n\u0000\b\u0086\u0003\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003J\u0012\u0010\u0007\u001a\u0004\u0018\u00010\u00062\u0006\u0010\b\u001a\u00020\tH\u0007R\u0016\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000¨\u0006\n"}, m3636d2 = {"Lrosetta/identi/agreements/AgreementType$Companion;", "", "<init>", "()V", "ADAPTER", "Lcom/squareup/wire/ProtoAdapter;", "Lrosetta/identi/agreements/AgreementType;", "fromValue", "value", "", "rosetta.identi.agreements_externalRelease"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
    public static final class Companion {
        public /* synthetic */ Companion(DefaultConstructorMarker defaultConstructorMarker) {
            this();
        }

        private Companion() {
        }

        @JvmStatic
        public final AgreementType fromValue(int value) {
            switch (value) {
                case 0:
                    return AgreementType.AGREEMENT_TYPE_UNSPECIFIED;
                case 1:
                    return AgreementType.MARGIN_AGREEMENT;
                case 2:
                    return AgreementType.MARKETING_CONSENT;
                case 3:
                    return AgreementType.INSTANT_AGREEMENT;
                case 4:
                    return AgreementType.BROKERAGE_AGREEMENT;
                case 5:
                    return AgreementType.BROKERAGE_AGREEMENT_WITH_W8BEN;
                case 6:
                    return AgreementType.EMAIL_VERIFICATION_AGREEMENT;
                case 7:
                    return AgreementType.PHONE_VERIFICATION_AGREEMENT;
                case 8:
                    return AgreementType.PERSONA_SELFIE_AGREEMENT;
                case 9:
                    return AgreementType.RHY_USER_AGREEMENT;
                case 10:
                    return AgreementType.SUTTON_DEBIT_CARD_AGREEMENT;
                case 11:
                    return AgreementType.PINDROP_VOICE_VERIFICATION_AGREEMENT;
                case 12:
                    return AgreementType.PINDROP_VOICE_ENROLLMENT_AGREEMENT;
                case 13:
                    return AgreementType.CRYPTO_USER_AGREEMENT;
                case 14:
                    return AgreementType.BENEFICIARY_GENERAL_AGREEMENT;
                case 15:
                    return AgreementType.BENEFICIARY_SPOUSAL_CONSENT_AGREEMENT;
                case 16:
                    return AgreementType.STOCK_LOAN_CUSTOMER_AGREEMENT_V2;
                case 17:
                    return AgreementType.STOCK_LOAN_WELLS_FARGO_CUSTODIAN_AGREEMENT;
                case 18:
                    return AgreementType.CASH_SWEEP_AGREEMENT;
                case 19:
                    return AgreementType.RETIREMENT_IRA_ROTH_AGREEMENT;
                case 20:
                    return AgreementType.RETIREMENT_IRA_TRADITIONAL_AGREEMENT;
                case 21:
                    return AgreementType.RETIREMENT_MARGIN_AGREEMENT;
                case 22:
                    return AgreementType.STOCK_LOAN_CUSTODIAN_AGREEMENT;
                case 23:
                    return AgreementType.PAYCHECK_RECURRING_INVESTMENTS_CUSTOMER_AGREEMENT;
                case 24:
                    return AgreementType.GOLD_AGREEMENT;
                case 25:
                    return AgreementType.RAM_ADVISORY_AGREEMENT;
                case 26:
                    return AgreementType.W8_AGREEMENT;
                case 27:
                    return AgreementType.W8_AGREEMENT_IN_APP;
                case 28:
                    return AgreementType.W9_AGREEMENT;
                case 29:
                    return AgreementType.W9_AGREEMENT_IN_APP;
                case 30:
                    return AgreementType.RHD_ONBOARDING;
                case 31:
                    return AgreementType.JOINT_ACCOUNT_AGREEMENT;
                case 32:
                    return AgreementType.RHD_ONBOARDING_ADDITIONAL_RISK;
                case 33:
                    return AgreementType.RHD_ONBOARDING_ARBITRATION;
                case 34:
                    return AgreementType.ROBINHOOD_LEGEND_AGREEMENT;
                case 35:
                    return AgreementType.OPTION_AGREEMENT;
                case 36:
                    return AgreementType.OPTION_INSTANT_AGREEMENT;
                case 37:
                    return AgreementType.W8_AGREEMENT_ONBOARDING;
                case 38:
                    return AgreementType.W9_AGREEMENT_IN_APP_PART1;
                case 39:
                    return AgreementType.W9_AGREEMENT_IN_APP_PART2;
                case 40:
                    return AgreementType.W9_AGREEMENT_ONBOARDING_PART1;
                case 41:
                    return AgreementType.W9_AGREEMENT_ONBOARDING_PART2;
                case 42:
                    return AgreementType.CRYPTO_ROUNDUP_AGREEMENT;
                case 43:
                    return AgreementType.ACATS_IN_AGREEMENT;
                case 44:
                    return AgreementType.STOCK_ROUNDUP_AGREEMENT;
                case 45:
                    return AgreementType.DEBIT_CARD_AGREEMENT;
                case 46:
                    return AgreementType.SLIP_BROKERAGE_AGREEMENT_ONBOARDING;
                case 47:
                    return AgreementType.NCW_REWARDS_TOS;
                case 48:
                    return AgreementType.RETIREMENT_IRA_ROTH_DRIP_AGREEMENT;
                case 49:
                    return AgreementType.EU_CRYPTO_USER_AGREEMENT;
                case 50:
                    return AgreementType.DRIP_AGREEMENT;
                case 51:
                    return AgreementType.USER_ACCOUNT_AGREEMENT;
                case 52:
                    return AgreementType.GOLD_DEBIT_AUTHORIZATION_AGREEMENT;
                case 53:
                    return AgreementType.BROKERAGE_AGREEMENT_ONBOARDING;
                case 54:
                    return AgreementType.WALLET_AGREEMENT;
                case 55:
                    return AgreementType.RETIREMENT_IRA_TRADITIONAL_DRIP_AGREEMENT;
                case 56:
                    return AgreementType.RHF_INSTANT_CUSTOMER_AGREEMENT_ONBOARDING;
                case 57:
                    return AgreementType.INTERNAL_ASSET_TRANSFER_AGREEMENT;
                case 58:
                    return AgreementType.MARGIN_AGREEMENT_ONBOARDING;
                case 59:
                    return AgreementType.SLIP_AGREEMENT_ONBOARDING;
                case 60:
                    return AgreementType.SWEEP_AGREEMENT_ONBOARDING;
                case 61:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_ELECTION;
                case 62:
                    return AgreementType.RETIREMENT_JOINT_ACCOUNT_REMEDIATION_AGREEMENT;
                case 63:
                    return AgreementType.RAM_INDIVIDUAL_AGREEMENT;
                case 64:
                    return AgreementType.RAM_IRA_ROTH_AGREEMENT;
                case 65:
                    return AgreementType.RAM_IRA_TRADITIONAL_AGREEMENT;
                case 66:
                    return AgreementType.RAM_SLIP_AGREEMENT_ONBOARDING;
                case 67:
                    return AgreementType.RHY_PREPAID_DEBIT_AGREEMENT;
                case SDK_ASSET_ICON_HOME_VALUE:
                    return AgreementType.RHY_SPENDING_AGREEMENT;
                case 69:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_GRIDIRON;
                case 70:
                    return AgreementType.RAM_SLIP_NATIVE_ONBOARDING;
                case SDK_ASSET_ICON_GUIDE_VALUE:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_THIRD_MONTH_CHAOS;
                case SDK_ASSET_ICON_GLOBE_VALUE:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_ECONOMIC_INDICATOR;
                case 73:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_PRO_BASKETBALL;
                case 74:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_PRO_HOCKEY;
                case 75:
                    return AgreementType.ACCOUNT_SCOPE_INDIVIDUAL_MARGIN_AGREEMENT_ONBOARDING;
                case 76:
                    return AgreementType.ACCOUNT_SCOPE_INDIVIDUAL_SLIP_AGREEMENT_ONBOARDING;
                case 77:
                    return AgreementType.ACCOUNT_SCOPE_INDIVIDUAL_SWEEP_AGREEMENT_ONBOARDING;
                case 78:
                    return AgreementType.ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITH_MARGIN;
                case 79:
                    return AgreementType.ACCOUNT_SCOPE_INDIVIDUAL_BROKERAGE_AGREEMENT_WITHOUT_MARGIN;
                case 80:
                    return AgreementType.COMMON_REPORTING_STANDARD_SELF_CERTIFICATION;
                case 81:
                    return AgreementType.SAGE_AGREEMENT;
                case 82:
                    return AgreementType.AUTO_SEND_EQUITIES_MOBILE_AGREEMENT;
                case 83:
                    return AgreementType.CORTEX_DIGEST_AGREEMENT;
                case 84:
                    return AgreementType.RHY_ELECTRONIC_COMMUNICATIONS_CONSENT;
                case 85:
                    return AgreementType.RHY_TERMS_OF_USE;
                case 86:
                    return AgreementType.RHY_DEPOSIT_ACCOUNT_AGREEMENT;
                case 87:
                    return AgreementType.REICH_TANG_CUSTOMER_TERMS_AND_CONDITIONS;
                case 88:
                    return AgreementType.RHY_ACCOUNT_AGGREGATION_AGREEMENT;
                case 89:
                    return AgreementType.RHY_REMOTE_DEPOSIT_CAPTURE_AGREEMENT;
                case 90:
                    return AgreementType.RHY_CASH_DELIVERY_TERMS;
                case 91:
                    return AgreementType.RHY_DEBIT_CARD_AGREEMENT;
                case 92:
                    return AgreementType.AUTO_SEND_LEGEND_AGREEMENT;
                case 93:
                    return AgreementType.CRS_CARF_SELF_CERTIFICATION;
                case 94:
                    return AgreementType.ACCOUNT_SCOPE_DRIP_AGREEMENT;
                case 95:
                    return AgreementType.ACCOUNT_SCOPE_JA_DRIP_AGREEMENT;
                case 96:
                    return AgreementType.CUSTODIAL_UGMA_AGREEMENT;
                case 97:
                    return AgreementType.CUSTODIAL_UTMA_AGREEMENT;
                case 98:
                    return AgreementType.ECBSV_AGREEMENT;
                case 99:
                    return AgreementType.AUTO_SEND_CRYPTO_MOBILE_AGREEMENT;
                case 100:
                    return AgreementType.RHD_EVENT_CONTRACT_ATTESTATION_UNIVERSAL_AGREEMENT;
                case 101:
                    return AgreementType.CUSTODIAL_ACCOUNT_AGREEMENT;
                case 102:
                    return AgreementType.ADVISOR_MARKETPLACE_ENROLLMENT_AGREEMENT;
                case 103:
                    return AgreementType.RHUK_STOCKS_AND_SHARES_ISA_TERMS_AND_CONDITIONS;
                case 104:
                    return AgreementType.RHUK_STOCKS_AND_SHARES_ISA_DECLARATION;
                case 105:
                    return AgreementType.RHUK_STOCKS_AND_SHARES_ISA_PRODUCT_KEY_FEATURES;
                case 106:
                    return AgreementType.ACCOUNT_SCOPE_INDIVIDUAL_MULTI_SLIP_AGREEMENT_ONBOARDING;
                case 107:
                    return AgreementType.ROBINHOOD_SOCIAL_AGREEMENT;
                case 108:
                    return AgreementType.CUSTODIAL_MINOR_W9_AGREEMENT;
                case 109:
                    return AgreementType.MMF_AGREEMENT;
                case 110:
                    return AgreementType.RHUK_ISA_CASH_TRANSFER_DECLARATION;
                case 111:
                    return AgreementType.IRA_ROTH_CRYPTO_USER_AGREEMENT;
                case 112:
                    return AgreementType.IRA_TRADITIONAL_CRYPTO_USER_AGREEMENT;
                case 113:
                    return AgreementType.ACCOUNT_SCOPE_SLIP_AGREEMENT;
                case 114:
                    return AgreementType.ACCOUNT_SCOPE_SWEEP_AGREEMENT;
                case 115:
                    return AgreementType.ACCOUNT_SCOPE_BROKERAGE_AGREEMENT;
                case 116:
                    return AgreementType.CORTEX_LEGEND_AGREEMENT;
                case 117:
                    return AgreementType.ROBINHOOD_EMPLOYEE_SOCIAL_AGREEMENT;
                case 118:
                    return AgreementType.ACCOUNT_SCOPE_MULTI_SLIP_AGREEMENT;
                case 119:
                    return AgreementType.MINNESOTA_USER_CRYPTO_DISCLOSURES;
                case 120:
                    return AgreementType.INVESTMENT_TRACKER_CONNECT_ACCOUNT_AGREEMENT;
                default:
                    return null;
            }
        }
    }

    public static AgreementType valueOf(String str) {
        return (AgreementType) Enum.valueOf(AgreementType.class, str);
    }

    public static AgreementType[] values() {
        return (AgreementType[]) $VALUES.clone();
    }
}
