
2
%deposit_schedule_review_amount_headerü•Ä¬İšÆÿ
4
(deposit_schedule_review_frequency_headeráØÌÕŸïîç	
4
(deposit_schedule_review_next_date_headerÆ¾õÀšÃ¢ßF
8
+deposit_schedule_review_bank_account_header‚¢Ï¯Âö‹…
(
deposit_schedule_edit_titleÏ˜Å’ñüìÏı

ach_transfer_titlešÌ¡ß´÷¡³˜
,
 recurring_deposit_transfer_title«é×ŒÖ‰†ò0
 
ach_transfer_header®ÜÀœ®š”ù
3
&ach_transfer_error_exceeds_max_depositçµã¦•¢úé
=
0ach_transfer_error_potentially_exceeds_availableÍÆÑòíÚĞ
.
!ach_transfer_error_invalid_amount™àõÀ®„¡ıÿ
5
(ach_transfer_change_ach_relationship_btn´šÊé…Ô”½Ò
;
/ach_transfer_change_ach_relationship_btn_revampâ«˜Ë÷ï°»
=
0ach_transfer_convert_to_automatic_deposit_action¤¯ô§®Çö©
2
&ach_transfer_robinhood_account_balanceàÜ«üÑ’
B
6ach_transfer_robinhood_account_balance_content_cleanupĞÎ÷·»÷é£
6
)ach_transfer_error_not_enough_funds_title„İ°ëÇçªµ
&
ach_transfer_error_genericÄûƒÆÍ¶½èJ
.
!ach_transfer_error_pending_orders×±š²›õıÉÑ
4
(ach_transfer_error_pending_orders_actionİ×úøËˆàÇ(
(
ach_transfer_error_gold_tierÍí§œ…ñ·èJ
/
#ach_transfer_error_gold_tier_action®’ü—Ø¸Z
F
:gated_gold_ach_transfer_error_pending_orders_and_gold_tier³‚Àé¯°¨-
%
ach_transfer_review_title…÷ò¹¸®äÍ
/
#ach_recurring_deposit_review_actionÉ÷‡ãñ¥ÜT
.
"ach_recurring_deposit_screen_title©ğ–¢ÎØ·Ø-
8
+ach_recurring_deposit_screen_frequency_icon£ÔñÍ±è——°
3
'ach_transfer_confirmation_deposit_title¤şÙİ¦ÑšŸL
5
(ach_transfer_confirmation_withdraw_titleäÕ©‡ÏÆŞì
<
/ach_transfer_confirmation_auto_deposit_title_v2è–ŠÌ‹‹Šˆß
9
,ach_transfer_confirmation_auto_deposit_titleÊ³Ë¦Å´¤Œø
@
3ach_transfer_confirmation_auto_deposit_title_revampÙïÑàŞã•ö
D
7ach_transfer_confirmation_queued_deposit_title_approved×÷‘®ŒõİüŒ
A
4ach_transfer_confirmation_deposit_not_approved_title–ÆÊÔìğ
H
;ach_transfer_confirmation_queued_deposit_title_not_approved¯Ñ…åüÊêæâ
6
)ach_transfer_confirmation_disclaimer_text€Áºğ¸èÿ·¾
N
Bach_transfer_confirmation_recurring_disclaimer_when_exceed_instant×‹‰±¸»¢¨
_
Sach_transfer_confirmation_disclaimer_cleanup_approved_with_all_instant_deposit_text¦›—ë´¨û
d
Wach_transfer_confirmation_disclaimer_cleanup_approved_with_partial_instant_deposit_textÃñ¿²ÆáïÔå
I
<ach_transfer_confirmation_disclaimer_cleanup_unapproved_textÓáş“Ğâšé¸
H
<ach_transfer_confirmation_view_deposit_transfer_detail_label·è²ÃĞŸ˜%
J
=ach_transfer_confirmation_view_withdraw_transfer_detail_labelçşñ±Š¹­§ä
8
+ach_transfer_confirmation_view_checkmark_idÒ¦ß×ÕÖğ¼£
5
)ach_transfer_confirmation_queued_approvedîúõ¸ß¶¤‹
[
Oach_transfer_confirmation_detail_text_revamp_approved_with_all_instant_depositsˆ¹‰•ßïÊé
H
<queued_deposit_transfer_exceeds_current_balance_dialog_titleÄÏæÁ¤ÆŠ¥~
H
;queued_deposit_transfer_exceeds_current_balance_dialog_text™…„êÓÜ’¨Ï
G
:queued_deposit_transfer_exceeds_current_balance_dialog_ctañƒ”öÛ”ùü
:
-ach_transfer_confirmation_queued_not_approved©—Óåà»ı’
F
9ach_transfer_confirmation_detail_text_revamp_not_approved†äıİä¦ŸÈÛ
0
$ach_transfer_confirmation_withdrawal‡…ÊÚãî÷®~
1
%ach_transfer_confirmation_single_cash¥õÏá°¤úş;
@
3ach_transfer_confirmation_single_instant_restrictedĞ¨îï­úæÙ
:
.ach_transfer_confirmation_single_instant_whole§Ñ·–”¿—¯*
=
0ach_transfer_confirmation_single_instant_partial¦ÓÓÇÉ¿¬±
<
0ach_transfer_confirmation_automatic_deposit_onceºğ‰·¦–àB
<
0ach_transfer_confirmation_automatic_deposit_week»´ÒÊöúÇ¯}
A
5ach_transfer_confirmation_automatic_deposit_two_weeks´êŞø±‚êÙ
>
1ach_transfer_confirmation_automatic_deposit_monthù„…•Í·
@
3ach_transfer_confirmation_automatic_deposit_quarter÷€ÚîÙ°¦«
L
@ach_transfer_confirmation_recurring_frequency_explanation_weeklyˆŞ˜“¦—Ÿb
O
Bach_transfer_confirmation_recurring_frequency_explanation_biweeklyËôŸœŞ°üüŞ
N
Aach_transfer_confirmation_recurring_frequency_explanation_monthlyÇçç„óÉò‡
O
Cach_transfer_confirmation_recurring_frequency_explanation_quarterly‰İèŒŞä±Ğ
4
(ach_transfer_confirmation_recurring_cashÆõŸ£ÓÙ–$
F
9ach_transfer_confirmation_recurring_instant_restricted_v2ÄŞ’¶Ôä²
B
6ach_transfer_confirmation_recurring_instant_restricted©ÃˆÅ¤¸?
L
@gated_instant_ach_transfer_confirmation_recurring_revamp_initialÃö´³Ê£3
Q
Egated_instant_ach_transfer_confirmation_recurring_revamp_account_infoå—¦úÕ©¡‘X
Q
Dgated_instant_ach_transfer_confirmation_recurring_revamp_explanationÏÎ¡¾ÿ­’à°
@
4ach_transfer_confirmation_recurring_instant_whole_v2·áÁï§¯ç›#
=
1ach_transfer_confirmation_recurring_instant_wholeÆõŸ£ÓÙ–$
8
,recurring_automatic_deposit_frequency_weekly³ÓÄÎœ¦…Ë&
;
.recurring_automatic_deposit_frequency_biweekly¿ŒÚ­¾—Á§‘
9
-recurring_automatic_deposit_frequency_monthlyœ³ Ñ‘ì«ı
<
/recurring_automatic_deposit_frequency_quarterlyë‰ö‘ß†ˆç
D
7ach_transfer_confirmation_instant_in_review_explanationÕÆŞôš“øÄÉ
I
=ach_transfer_confirmation_instant_pending_deposit_explanationóß¢™Ñ£u
D
7ach_transfer_confirmation_instant_suspended_explanation¬Ïòø¯´€™’
B
6ach_transfer_confirmation_instant_view_reversal_actionÛñ¦á¤ÉàÁN
3
'ach_transfer_confirmation_instant_title„Ìñ” è‡ÕT
6
*ach_transfer_instant_deposit_title_cleanup¼ïîÁ‰ê–¹D
0
$ach_transfer_instant_deposit_cleanup×æ¥úòÎ½v
0
#ach_transfer_instant_deposit_cryptoñ„¥…‰Ñ®òš
A
4ach_transfer_instant_deposit_bigger_instant_depositsÄ±Èƒö¶Šä
5
)ach_transfer_instant_deposit_restrictionsœ©ù¨÷ãÃ1
@
4ach_transfer_instant_deposit_restrictions_learn_moreæÿü’‹ ãw
4
(ach_transfer_relationship_selector_title×Á”Ãİ¼·åY
:
-ach_relationship_error_unverified_but_no_path¹½¸ğ¥¨å–÷
.
"ach_relationship_error_must_verifyçÕ˜™°ÉŸˆ*
+
ach_relationship_action_verifyïò®ôşš‰ò­
#
ach_list_empty_messageÌú ˆ‡Íº”
4
(ach_relationship_add_content_descriptionäÍ³Áİú•%
2
&ach_transfer_automatic_deposit_summaryÀŸüğÒÚ¡ğ
8
+schedule_automatic_deposit_v2_toolbar_titleï¸£®óÚø¹å
>
2schedule_automatic_deposit_v2_toolbar_title_revamp«é×ŒÖ‰†ò0
/
#schedule_automatic_deposit_v2_titleºæ®‘ï°§(
2
&schedule_automatic_deposit_v2_subtitle¶Œ—Š«’ÏÚ.
6
)schedule_automatic_deposit_v2_primary_ctaáüŒáî…ÆÜË
5
)schedule_automatic_deposit_v2_description»˜ì®Àíš&
<
/schedule_automatic_deposit_v2_skip_dialog_title½›éŠşÌ”ù
=
1schedule_automatic_deposit_v2_skip_dialog_message¡³©©ò¦¾ñn
'
set_deposit_schedule_title ·ˆÀÙÏ²¡
)
deposit_schedules_start_labelÜ›–©Öá¹ùt
4
'set_deposit_schedule_next_deposit_label„Ò¯Ôüÿ®ã
?
2deposit_schedule_end_of_month_warning_dialog_titleçä­òÛ˜
A
4deposit_schedule_end_of_month_warning_dialog_message„áÿ¬Œ¢Èà
C
7deposit_schedule_end_of_month_warning_dialog_edit_labelÊÉÊå¢²™‹[
4
'ach_transfer_timeline_deposit_initiated×÷‘®ŒõİüŒ
3
'ach_transfer_timeline_deposit_in_review÷‘ãÔ´ŸÆ“{
,
 ach_transfer_timeline_date_todayóÕ¸†çı³¶V
<
/ach_transfer_timeline_deposit_initiated_primary×÷‘®ŒõİüŒ
;
/ach_transfer_timeline_deposit_in_review_primary÷‘ãÔ´ŸÆ“{
<
0ach_transfer_timeline_deposit_in_review_metadataëÎŞúıà¤,
8
+ach_transfer_timeline_earn_interest_primaryÅá÷»Ç×¸
8
,ach_transfer_timeline_earn_interest_metadata©±Ë»¨Î›·
C
6ach_transfer_timeline_earn_interest_remaining_metadata˜¡ÃÿŒ‹–Ñø
;
/ach_transfer_timeline_deposit_completed_primaryÛÛõË”È¥Â@
=
0ach_transfer_timeline_deposit_completed_metadata¨ü±£“¤ŠŞÙ
M
@ach_transfer_timeline_deposit_completed_cash_management_metadataÔä“«›İµƒ©
8
+ach_transfer_timeline_covers_margin_primaryæş‘ØÏòÖˆ
9
,ach_transfer_timeline_covers_deficit_primary‹¬¶À«ƒÓÖ
8
,ach_transfer_timeline_covers_margin_metadataìÔÔ¥À¡=
?
3ach_transfer_timeline_covers_margin_amount_metadata¶°¾ô –“Åp
A
4ach_transfer_timeline_covers_deficit_amount_metadata ÁåÔš½ûÈ
(
ach_transfer_timeline_amount¢ºğıôŸ®ĞD
(
ach_transfer_timeline_detail­ëÿ€À»‡P
,
deposit_schedule_timeline_titleŞ‡Ë˜€ûşÈ
?
2deposit_schedule_timeline_schedule_created_primaryáÄ®•ÊÃîìŠ
<
/deposit_schedule_timeline_first_deposit_primary¾Ü÷¼îñÛŞ•
=
0deposit_schedule_timeline_first_deposit_metadatašØãö¾Ğ†Ö
@
3deposit_schedule_timeline_deposit_completes_primary¥‰ÜÎâë²Ñ®
:
.deposit_schedule_timeline_next_deposit_primaryÆ¾õÀšÃ¢ßF
,
 deposit_schedule_timeline_detail†ÙÃ½ıÎŠ
3
&deposit_schedule_timeline_bank_account‚½óëÄêğºô
5
(next_deposit_timeline_description_weeklyšéàÁè¹«Ş÷
6
*next_deposit_timeline_description_biweeklyòÄ”˜÷èÜÿ[
6
)next_deposit_timeline_description_monthlyšêãùøúìÉ
8
+next_deposit_timeline_description_bimonthly»ãÒÓÜ’¼‘ú
7
+next_deposit_timeline_description_quarterlyóºìşêƒ®=