
*
option_order_type_limit_order³ÙØÛ…µı÷
.
"option_order_type_stop_limit_orderí¶ñİÆèŞ¡d
/
#option_order_type_stop_market_orderÑªæëÇÏ
+
option_order_type_market_order“ÕöØããÉÛù
'
option_order_available_cashàÜ«üÑ’
/
#order_status_prompt_with_cancel_new™ÚÏ³şÿõÑ
7
+order_status_prompt_previous_order_canceled¸Ğéş¡ãÛÇJ
=
0order_status_prompt_previous_order_also_canceledÔ¢·ìˆçº–—
>
2order_status_prompt_before_previous_order_canceledŸÉÑ‰ƒÌØÇ3
(
order_status_prompt_pendingÁ·•åÃßÑñç
&
order_status_prompt_queued·¾İ‰‚“ê 
'
order_status_prompt_placedÂŸğ–ìÓœÁ·
1
$order_status_prompt_partially_filled¶·¢ÉûÕÔ–ı
'
order_status_prompt_filledØô£ÈÕó…Óå
(
order_status_prompt_rejected¤¹ÌßîÕ•Ş
'
order_status_prompt_failedØÎáÁ›€º‡á
C
6order_status_prompt_failed_previous_order_not_canceled¼çÇÿù‚€Í
/
"order_status_prompt_pending_cancelŸ»†²ÒÖ‡†
)
order_status_prompt_canceled‡ú‡ğºİúÌ¯
'
order_status_prompt_voided¬Ğ’­èş¬‚
6
+option_position_instrument_detail_row_titleº€şø¢ÍŠo
*
option_instrument_detail_title´ïèšó‘ëÖe
+
option_position_row_title_fullµí¥Ø”—ïÚÅ
:
-option_position_row_title_full_settle_on_openÚ±†Ğ€³Æ¿©
5
(option_position_row_title_with_side_full©æ•í€ÿçÃ
D
7option_position_row_title_with_side_full_settle_on_open´àÉÑ´ûş­»
&
option_position_row_titleòÛ­ëç—„
5
)option_position_row_title_vertical_spreadäÍè–ë
?
3option_position_row_title_vertical_spread_no_symbol³ß«Ñœä€ÛH
6
)option_position_row_title_calendar_spreadòÛ­ëç—„
@
3option_position_row_title_calendar_spread_no_symbol½úÕ‚‹ÁÖ°
/
"option_position_row_title_straddleèö»Ëâ£ÒÜ
9
,option_position_row_title_straddle_no_symbolşïÄî˜ğ„Ü¦
.
"option_position_row_title_strangleğ—¬æé×®v
9
,option_position_row_title_strangle_no_symbol·Ñ¨Ûğàµµ¢
1
%option_position_row_title_iron_condor·…¦éí¦›ù~
<
/option_position_row_title_iron_condor_no_symbolößäÎÆ¯Ì“
1
$option_position_row_title_single_legòÛ­ëç—„
;
.option_position_row_title_single_leg_no_symbol½úÕ‚‹ÁÖ°
-
 option_position_row_title_customœÂÃ¢Êû‚êâ
6
*option_position_row_title_custom_no_symbolÍú¦Ÿ°–¿£v
<
/option_expiration_date_tab_title_settle_on_openèàÖÂŞ°‰àË
2
&option_number_of_days_until_expirationì‘ÍåŞ¢Ú³\
8
,option_number_of_days_until_expiration_rangeªÁÀìõÂºÑ
$
regulatory_fees_display¢¨÷ßøìš
-
 gated_regulatory_fees_display_sg²Ó¬ñ«òÅê·
&
index_options_fees_display‰êáƒ£Óíî5
&
apply_for_options_level_3ïÓô²¤Êí
8
+apply_for_options_level_3_incentive_summaryÖÂ´–Ñøªğ
B
5option_portfolio_risk_analyzer_simulate_all_positionsÛ¼úó¹òõ¹¢
9
,option_portfolio_risk_analyzer_risk_analyzerˆÓš¶ÿ™ß‰
5
)option_trade_action_generic_roll_positionÜÂ¥¢Ó˜Ï‚A
6
)option_trade_action_generic_open_position¬ğıÕ±ıˆ¾
7
*option_trade_action_generic_close_position«ûáÄ¢¬ß
6
*option_order_available_number_of_contractsß«î¢Ò§Å¥
4
'option_order_available_number_of_sharesßš–ûÉ£›
)
number_of_shares_with_symbolÂ¢¼´©å¹–
=
0sell_to_close_call_stop_market_single_underlying¦ å†šü Ô¬
;
/sell_to_close_put_stop_market_single_underlyingÁ¬êÃÃ™°¯
G
;sell_to_close_call_stop_market_single_underlying_cancel_newÈ‘Õñ¶ÊËám
G
:sell_to_close_put_stop_market_single_underlying_cancel_new¬ÑéÉƒ‡¡şÄ
X
Lsell_to_close_call_stop_market_single_underlying_cancel_new_partially_filled‘®ÉÕ®Í”ÚA
X
Ksell_to_close_put_stop_market_single_underlying_cancel_new_partially_filledåÍ×şø´¸–
$
sell_call_gfd_stop_limitÙˆ¦Éëç§ÿ
$
sell_call_gtc_stop_limit²Ì³´¢Œóû|
$
sell_put_gfd_stop_limit“Ÿ“Ÿ½¸€˜
$
sell_put_gtc_stop_limit‘…¦ô®õñ·ÿ
0
#sell_call_gfd_stop_limit_cancel_newïÀÅ «òˆÖ
/
#sell_call_gtc_stop_limit_cancel_new®Èû’äÀşù(
.
"sell_put_gfd_stop_limit_cancel_newíæ‡’¦û£+
/
"sell_put_gtc_stop_limit_cancel_newºšıÇÏ×‡
A
4sell_call_gfd_stop_limit_cancel_new_partially_filledõ™õ½èõÇ›œ
@
4sell_call_gtc_stop_limit_cancel_new_partially_filledûâ÷æ†š«
?
3sell_put_gfd_stop_limit_cancel_new_partially_filled‘Ÿ¶‘‹ÎÿîA
?
3sell_put_gtc_stop_limit_cancel_new_partially_filledª„Ê¿ŠÆØ
$
buy_call_gfd_stop_limitß¶æâ×Ô†É
$
buy_call_gtc_stop_limit˜§¡ÌÃÄÿîü
"
buy_put_gfd_stop_limitúÓßÜë´…,
"
buy_put_gtc_stop_limit‡¨Ø–²¾Šè
/
"buy_call_gfd_stop_limit_cancel_newö¢Â³¨Â‡ÿÂ
/
"buy_call_gtc_stop_limit_cancel_new‘İÓ²æÓó’ê
.
!buy_put_gfd_stop_limit_cancel_newº ÄÓ¹öò—
-
!buy_put_gtc_stop_limit_cancel_newššÈœ¾ÓÄÏ|
@
3buy_call_gfd_stop_limit_cancel_new_partially_filled¸»Ê…¾·ÉÀí
?
3buy_call_gtc_stop_limit_cancel_new_partially_filled–ÿÜÉ–Åé
?
2buy_put_gfd_stop_limit_cancel_new_partially_filled¼—¾ó¹áÉàå
?
2buy_put_gtc_stop_limit_cancel_new_partially_filledïœï’¢æÙÇÌ
$
sell_to_open_call_marketÑŞ”£ßÔ÷÷}
$
sell_to_open_put_marketŸÑÀÚ©ùıèå
0
#sell_to_open_call_market_cancel_newÂáÃà¯á¨ô
/
"sell_to_open_put_market_cancel_newÿ›Í²¾Ù¸¨Ö
A
4sell_to_open_call_market_cancel_new_partially_filledŠ«ÇÊãş’›…
@
3sell_to_open_put_market_cancel_new_partially_filled¹ÿïñœÌ×ä©
7
+sell_to_close_call_market_single_underlyingøñú¨‚ß²Òt
7
*sell_to_close_put_market_single_underlyingø¬…•ÂğÑ”±
C
6sell_to_close_call_market_single_underlying_cancel_new´•æ°šğïÀÒ
B
5sell_to_close_put_market_single_underlying_cancel_newÎ„š¦å©º‰¦
T
Gsell_to_close_call_market_single_underlying_cancel_new_partially_filled·Ê×“©Ÿäú€
S
Fsell_to_close_put_market_single_underlying_cancel_new_partially_filled™êæû…êÓÕÉ
7
*sell_to_close_call_market_multi_underlyingóõİ¹Íš¤æ¦
5
)sell_to_close_put_market_multi_underlyingè½ÿ•Ø½ñt
A
5sell_to_close_call_market_multi_underlying_cancel_newÅ”Åš¿‹÷«u
@
4sell_to_close_put_market_multi_underlying_cancel_newì÷¼¤ƒ¢Ö¹u
S
Fsell_to_close_call_market_multi_underlying_cancel_new_partially_filledüŒŞêû¿“¿
Q
Esell_to_close_put_market_multi_underlying_cancel_new_partially_filled… ÏíöƒÚF
.
"buy_to_open_call_market_cancel_new”ô¬®ÇÑî¨S
.
!buy_to_open_put_market_cancel_newÄ‚€ò€ïÅ
@
3buy_to_open_call_market_cancel_new_partially_filled‰¦œ€®˜°Šª
>
2buy_to_open_put_market_cancel_new_partially_filled¶º”¡Ï¬‰3
#
buy_to_open_call_marketãûÛ¡†“õ·L
"
buy_to_open_put_marketß½•“¹ïï¥G
6
*buy_to_close_call_market_single_underlyingÊÚŸ„Ô«ùÀ`
5
)buy_to_close_put_market_single_underlying¯¹ÚÔº«…²
B
5buy_to_close_call_market_single_underlying_cancel_newèÄÁÌÇº’ ÷
@
4buy_to_close_put_market_single_underlying_cancel_newÌáŒ‰´ˆ X
R
Fbuy_to_close_call_market_single_underlying_cancel_new_partially_filled‹½ÌÇÿÛ™€
Q
Ebuy_to_close_put_market_single_underlying_cancel_new_partially_filled‚Àë™Ÿ¥º
5
)buy_to_close_call_market_multi_underlying¸º“ÈœÍˆ~
5
(buy_to_close_put_market_multi_underlying»ˆûÜÜòïÂš
A
4buy_to_close_call_market_multi_underlying_cancel_newõØ¦ß™ºƒö‚
?
3buy_to_close_put_market_multi_underlying_cancel_newÛØ¢¶ÙÑüáZ
Q
Ebuy_to_close_call_market_multi_underlying_cancel_new_partially_filled„÷‰Å±µùk
P
Dbuy_to_close_put_market_multi_underlying_cancel_new_partially_filledİ¤ÚŠêÏ†÷(
$
sell_to_open_call_limitÕóÅáĞ¥¾í»
#
sell_to_open_put_limitôØ—…Íğø©
.
"sell_to_open_call_limit_cancel_new“­Ğ´ÜŒ”¹1
-
!sell_to_open_put_limit_cancel_new‘ò‘ôÆÒëÜG
@
3sell_to_open_call_limit_cancel_new_partially_filledâé¬ê’Ñµ“ì
>
2sell_to_open_put_limit_cancel_new_partially_filled¹Î’¥–¤¿}
7
*sell_to_close_call_limit_single_underlying‹Şœäÿááíã
6
)sell_to_close_put_limit_single_underlying®ÿÀÍî Êä•
B
5sell_to_close_call_limit_single_underlying_cancel_new™ƒ¤ÄµÕ©Ÿ
A
4sell_to_close_put_limit_single_underlying_cancel_new‘¢§­»æĞì™
S
Fsell_to_close_call_limit_single_underlying_cancel_new_partially_filled„ÇôÖ¾°¾áÛ
R
Esell_to_close_put_limit_single_underlying_cancel_new_partially_filledƒÃ¶ÖÕÔ‡Ò
6
)sell_to_close_call_limit_multi_underlyingÄò·üƒÊî¿‡
5
(sell_to_close_put_limit_multi_underlying¾ĞÍÂô¤šâÎ
A
4sell_to_close_call_limit_multi_underlying_cancel_new´± êÔ˜íˆ
@
3sell_to_close_put_limit_multi_underlying_cancel_newø‚ãºÛÆ¤Š
Q
Esell_to_close_call_limit_multi_underlying_cancel_new_partially_filledİÊëª¿ÛÑª
Q
Dsell_to_close_put_limit_multi_underlying_cancel_new_partially_filledî’¶ğÏ”ì¾â
.
!buy_to_open_call_limit_cancel_newÅ¯İç’ø†äÕ
-
 buy_to_open_put_limit_cancel_newÑ£ƒ”È€ÿÕ
>
2buy_to_open_call_limit_cancel_new_partially_filled™¯Û¿š—À³=
>
1buy_to_open_put_limit_cancel_new_partially_filled©æ»ÀŠûù›Ó
#
buy_to_open_call_limitº¥¢ùãŸ™€Ô
!
buy_to_open_put_limitÉ„æ÷ÙÁ‘H
6
)buy_to_close_call_limit_single_underlyingÊí´¢Îš ¼
5
(buy_to_close_put_limit_single_underlying¿ÙÀ“å•ÎŒÁ
@
4buy_to_close_call_limit_single_underlying_cancel_new¿§•§Š¸æ½
@
3buy_to_close_put_limit_single_underlying_cancel_new¢äÕœ®ò‹œµ
Q
Ebuy_to_close_call_limit_single_underlying_cancel_new_partially_filled¥â“Á£÷2
P
Dbuy_to_close_put_limit_single_underlying_cancel_new_partially_filledØìÀŸä ÈŞC
4
(buy_to_close_call_limit_multi_underlyingä÷×ÀÁ‘‹ò[
3
'buy_to_close_put_limit_multi_underlying¯ï´Œüœˆ²9
@
3buy_to_close_call_limit_multi_underlying_cancel_new®Å£Œ˜Ë€ˆú
?
2buy_to_close_put_limit_multi_underlying_cancel_newˆ€ÆŒÒ¶šš™
Q
Dbuy_to_close_call_limit_multi_underlying_cancel_new_partially_filledî»Ë´ß‚¼’Ê
O
Cbuy_to_close_put_limit_multi_underlying_cancel_new_partially_filledÄóïÓı“•¯4
+
cancel_new_optional_new_string¼ğ§üáÍŞÍ’
3
'index_options_stop_market_order_summaryÀ§ ’¿û«[
2
%index_options_stop_limit_good_for_dayôœÅ»óá¦Û¨
7
+index_options_stop_limit_good_till_canceled©Ê²ÂÒ¤è
.
"index_options_stop_limit_order_buy¸ ¢ûÔÉ

/
#index_options_stop_limit_order_sellê‹óÃ‡·g
3
&index_options_market_order_buy_to_open˜“åª™µï²
;
.index_options_market_order_buy_to_open_shorten­ô¬ÉñÕ‰·
3
'index_options_market_order_sell_to_open¿§³š³úñ‹3
3
'index_options_market_order_buy_to_closeûÁ©Ô‡Í]
5
(index_options_market_order_sell_to_closešºÏÏşãùÀ
-
 index_options_am_expiration_timeáåòƒ‘ÛÄ»®
-
 index_options_pm_expiration_timeáÆõ¢ËèŠÜ
;
.cancel_new_replace_order_partially_filled_text£¸õ·†ñ°È®
?
2cancel_new_replace_order_non_partially_filled_textÉ¶ÜŸ¾Œ»œê
F
:settlement_value_compare_to_strike_for_call_to_take_profit±ÕŒ†…Öj
E
9settlement_value_compare_to_strike_for_put_to_take_profitú»‹ÿ×·ïb
2
%index_options_limit_order_buy_to_openö‚è€©ó¢‘
9
-index_options_limit_order_buy_to_open_shorten…—È€¡ËÄ¡
2
&index_options_limit_order_sell_to_open¿§³š³úñ‹3
3
&index_options_limit_order_buy_to_closeˆÆé¿¬¤ÿï¦
4
'index_options_limit_order_sell_to_closeà…‚îû°¸×
1
$option_side_by_side_chain_metric_bidÉ‚¤À«œûó
1
%option_side_by_side_chain_metric_sellš•Î¾Úâh
0
$option_side_by_side_chain_metric_ask¸¢ã»Øòáş
0
$option_side_by_side_chain_metric_buy¥¨×÷¢·˜£m
1
%option_side_by_side_chain_metric_markôôôø…ïÓğ
7
+option_side_by_side_chain_metric_last_tradeÕ”×¿Øí 8
;
/option_side_by_side_chain_metric_previous_closeÃÿÆ´¼¡»³
1
%option_side_by_side_chain_metric_highØåÊ¸¼ƒ[
1
$option_side_by_side_chain_metric_low°†¦Ş¿Ó¶Íï
8
+option_side_by_side_chain_metric_net_change¶íÿéÊ•»Ğ©
;
/option_side_by_side_chain_metric_percent_change éœ«íƒ $
5
)option_side_by_side_chain_metric_bid_sizeÄû¦ûö‚È]
6
)option_side_by_side_chain_metric_ask_size×‡·„›åŸ¨æ
3
'option_side_by_side_chain_metric_volumeÒÒòÔ—÷ì0
:
.option_side_by_side_chain_metric_open_interest¹şÍĞ”ïş_
3
&option_side_by_side_chain_metric_deltaÓ‡„±ù‘Œ²ë
3
&option_side_by_side_chain_metric_gammaõ¦ÓÙñã‘ü
2
&option_side_by_side_chain_metric_theta§ôÒôƒÇË6
2
%option_side_by_side_chain_metric_vega¿ÛğËÈòÎí
1
$option_side_by_side_chain_metric_rho¾Ö©½ˆà¿ÿÿ
@
3option_side_by_side_chain_metric_implied_volatility€²èœ¾šıÁ
6
*option_side_by_side_chain_metric_breakevençûƒñö¹¢Ü,
:
-option_side_by_side_chain_metric_to_breakeven”§ş×õŠµØ—
C
6option_side_by_side_chain_metric_chance_of_profit_longÙüîÿì‡‘Å—
D
7option_side_by_side_chain_metric_chance_of_profit_short”Ç‰•¶õ˜Ë
B
5option_side_by_side_chain_metric_short_previous_close†ÿ­ñ¯ÊıÏ
A
4option_side_by_side_chain_metric_short_open_interest¦Ì¤Ù°ÁéÒ
E
9option_side_by_side_chain_metric_short_implied_volatilityË¤¡³è½‘A
?
3option_side_by_side_chain_metric_short_to_breakevenĞÖ–æ©¥›ó
I
<option_side_by_side_chain_metric_short_chance_of_profit_longÊù«êäˆİÖË
J
=option_side_by_side_chain_metric_short_chance_of_profit_short¶©æÊë±÷Ò‰
#
order_direction_credit«ª‚§¶—Ôğ
!
order_direction_debitãè¢ø£«Õ˜\

option_effect_open¬ğıÕ±ıˆ¾
 
option_effect_close«ûáÄ¢¬ß

option_effect_rollşü‚ÉØÉä—
;
.option_position_instrument_detail_row_subtitleêü«ğ½ö ñœ
X
Loption_position_instrument_detail_expiration_date_settle_on_open_field_labelúİÚ‡µ ´›f
D
7option_position_instrument_detail_expiration_date_labelÔ˜Ï…†ëÖ¾½
R
Foption_position_instrument_detail_expiration_date_settle_on_open_labelŒŞñÚí²æ¾	
$
option_expiration_today§Ë‘œåè’Û–
9
,option_position_row_subtitle_vertical_spread“ºõé¶ò«˜
J
=partially_filled_option_position_row_subtitle_vertical_spreadËœö¨ãÒ‡¿Í
9
,option_position_row_subtitle_calendar_spread²¡¬†Ã©ÙàÉ
I
=partially_filled_option_position_row_subtitle_calendar_spread×‘¤óÁ“¯Z
1
%option_position_row_subtitle_straddleà–”äºòÔ!
C
6partially_filled_option_position_row_subtitle_straddle’òˆ®ïÌâ¯
5
(option_position_row_subtitle_iron_condorÂÀíƒ¹¨õÇ¹
E
9partially_filled_option_position_row_subtitle_iron_condorŒéÜçñ›ÄÌ
8
+option_position_row_subtitle_iron_butterflyÍÈÍÓš©éç
H
<partially_filled_option_position_row_subtitle_iron_butterflyßø´ËÜŠ…ãn
5
)partially_filled_option_roll_row_subtitleºªØô¬¨¯âM
*
option_position_roll_subtitleœÛšî¾ëŞ™ª
8
+option_position_row_subtitle_custom_pendingÚ¶°Éí±ÚÆ½
7
*option_position_pending_quantity_buy_labelÂ›˜ûé´¥¦
8
+option_position_pending_quantity_sell_labelªß¨ú´ÜåŒ»
A
5option_position_instrument_detail_sell_quantity_labelã¥®ˆÚµËÉ/
@
4option_position_instrument_detail_buy_quantity_labelè±­Õ…íëO
%
option_strategy_side_buy€í«ÑÀåú°£
&
option_strategy_side_sell³çã¼Øíƒ–Á
$
option_strategy_calendarø”ÉëÅìà *
'
option_strategy_iron_condor™ª›¬•î”©=
*
option_strategy_iron_butterfly½‰›ûµÇöë
'
option_strategy_type_creditÿĞØµº½£¤_
'
option_strategy_type_debit°¼ÜÂ½î†¹§
"
option_strategy_spreadÂ§—¾Ø€”Ô:
 
option_strategy_roll›ôÕÒà® æ&
(
option_strategy_custom_order€‘„’óğ‰©z
4
'option_chain_shopping_cart_row_subtitle’ƒÛßàéÎØ
7
*option_chain_shopping_cart_row_subtitle_amûıŞàÿ¾Š
7
*options_history_title_single_leg_no_symbolÚ×¼”¬÷çé
,
 options_history_title_single_legçÏ±ÑİÍ¢ñ1
*
option_history_title_multi_legª§õæ”üši
/
#option_history_title_settle_on_openúİÚ‡µ ´›f
0
$combo_order_history_row_primary_textïñôú’Å]
-
 option_strategy_roll_with_symbolæãÙØ«øªÙâ
0
#option_strategy_roll_without_symbol“‘²ÍôŸ­™
'
option_order_quantity_labelğ±È“ÍÇP
0
#option_order_entered_quantity_label‚¶”ˆÇîé¤
/
"option_order_filled_quantity_valueŠºëÿí¨…Áº
,
options_history_detail_subtitleåÁıÊ—Õ÷§
4
(options_history_detail_subtitle_no_priceáÀÖ¿«¼Ù8
Y
Lgated_cash_options_setting_upgrade_cash_account_failure_title_margin_routingÆ¹ûã¡‘´Ï
Z
Ngated_cash_options_setting_upgrade_cash_account_failure_message_margin_routingŒÒğÈÉ¿„u
V
Jgated_cash_options_setting_upgrade_cash_account_failure_cta_margin_routingµ¿ëÓ£æ¬R
]
Pgated_cash_options_setting_upgrade_cash_account_failure_secondary_margin_routingûÒãİ“êÂ™ü
*
history_row_title_option_event½îŸ¨ÃœâŒs
)
option_event_type_expirationÙõ¨ìÉÛÉ›ü
'
option_event_type_exerciseŠö²Œ×Îƒ´¡
(
option_event_type_assignmentŸ¤×Æ­©•¸l
%
option_event_type_genericÍ¼û«Ö¿Ÿÿa
%
option_event_state_voidedÕù´ø˜§ÛŠ
(
option_event_state_canceled’Ï“¢ÍÌ½îš
(
option_event_state_reversed¨œİÀÓÚì”Û
0
#option_event_equity_component_title¶’Œ–¤»¶üÇ
&
option_event_detail_titleûÚªİêÍ÷…
6
*option_event_detail_alert_early_assignmentĞÌ¥óóî²*
@
3option_event_detail_alert_early_assignment_help_urlëñ‹Åó¢öÀ¶
1
$option_event_detail_number_contractsÑ±Ğˆ¡ÛüÏ„
4
'option_event_detail_price_at_expirationˆ×½æ¶› “÷
%
option_event_detail_date³ëıÚß—‰ÏĞ
&
option_event_detail_status±‰ë”ï÷
'
option_event_detail_credit«ª‚§¶—Ôğ
%
option_event_detail_costŸ°©ˆ´®¤‰
/
#option_event_detail_realized_profitçäŞ‹¿ô™É
.
!option_event_detail_realized_lossæœ¸¨õ„ØÁÆ
G
;option_event_detail_price_at_expiration_multiple_underlyingÒÿ¯‰§Ş?
-
!order_detail_time_in_force_headerÊ¦éĞ›¸¹õ
*
order_detail_submitted_header·¯Ìò¥š—•ü
'
option_event_state_pendingĞù‡ñå·¤ä
)
option_event_state_confirmed¯‘Ø‘ ·œ†
>
1option_event_detail_supplementary_generic_pendingÂòóªÓÄïÚæ
A
4option_event_detail_supplementary_expiration_pendingæ¹æîÔ€ó¿Í
@
3option_event_detail_supplementary_expiration_voidedŞ£¹¿†ƒŒû˜
I
<option_event_detail_supplementary_expiration_voided_multipleêâ—äâ°• ë
A
4option_event_detail_supplementary_assignment_pendingˆ†°‚åšşÕ›
>
2option_event_detail_supplementary_exercise_pending®“º†©ƒÑ…2
E
8option_event_detail_supplementary_assignment_voided_call§¨Âµ€Ø²œİ
D
7option_event_detail_supplementary_assignment_voided_put™ÿ¤†üÔ‰
,
 option_event_detail_equity_label†«Ó¤ÓãÖ­:
-
 option_event_detail_equity_value“î°Ç¬Ø¥ªÄ
1
$option_event_detail_settlement_value››‰£“¼¿¿²