
'
contribution_section_header¡Å÷ú–Ë¡‰&
5
(contribution_section_allowance_row_labeláüœÓ¿ºÛ­
#
contribution_hub_header¡Å÷ú–Ë¡‰&
'
contribution_hub_remainingšÏ‡Ğ›‰”
$
contribution_hub_unused¸€ôúáõ™§
>
1contribution_hub_no_contribution_info_banner_text½‘ä­“×·êÃ
C
6contribution_hub_no_contribution_info_banner_link_text©¤áè›½àµ¢
?
3contribution_hub_some_contribution_info_banner_textÇÒáçø§®V
E
8contribution_hub_some_contribution_info_banner_link_text©¤áè›½àµ¢
:
-contribution_hub_max_contribution_helper_text½‘ä­“×·êÃ
1
$contribution_hub_history_section_ctaä“ÃÉÆÍÔ«Ó
+
contribution_hub_cta_add_moneyéİã©‰£íäÌ
0
#contribution_hub_cta_start_transferÖÏÔíœÀ«Ç¬
,
contribution_bottom_sheet_titleûéœ³ó¥îûÙ
1
%contribution_bottom_sheet_description¥¦éÂ©ß•Äq
7
+contribution_bottom_sheet_contributed_label¡Å÷ú–Ë¡‰&
6
)contribution_bottom_sheet_remaining_label Ããûáş’£
3
&contribution_bottom_sheet_close_button«ûáÄ¢¬ß
:
-contribution_confirmation_view_details_action‚Ù¢¹å¤ñÚ
8
+contribution_confirmation_standard_subtitle­¼¤’µÕ°
7
+contribution_confirmation_standard_metadata®åªäÒùìØ,
1
%contribution_confirmation_maxed_title¼Ø¼ïô²ûéi
4
(contribution_confirmation_maxed_metadata¥ÜòÖÃ££ãp
0
$contribution_confirmation_disclosure’‚‚‰œ•ÿ,
:
.contribution_confirmation_find_investments_ctaˆ†Óçª¿–‰L
7
*contribution_confirmation_invest_later_ctaİ«ØªÖÄ•