
8
+crypto_order_create_summary_disclosures_url³ˆôÀÛÂáÆñ
;
.crypto_order_create_summary_market_buy_rebrand‘ÈæİÔó¿°¼
<
/crypto_order_create_summary_market_sell_rebrandèÑÅ«×¸È
?
3crypto_order_create_summary_market_buy_fees_rebrandÇ¾û§Ïäñ)
@
4crypto_order_create_summary_market_sell_fees_rebrandø•Ä¦ºû³ ^
:
-crypto_order_create_summary_limit_buy_rebrand²ìıÂŞûÏ¹²
;
.crypto_order_create_summary_limit_sell_rebrand„‰Ôé‘‹›Âğ
>
2crypto_order_create_summary_limit_buy_rebrand_feesğûÛ©Ç¡j
@
3crypto_order_create_summary_limit_sell_rebrand_feesÂªà³¦òãÛş
=
1crypto_order_create_summary_stop_loss_buy_rebrandáÔŞ‹²ñøÄS
?
2crypto_order_create_summary_stop_loss_sell_rebrand†ã‰¸Í«ÁÛ±
B
6crypto_order_create_summary_stop_loss_buy_rebrand_feesªşİ…¨®Ğ‘/
C
7crypto_order_create_summary_stop_loss_sell_rebrand_feesñ•¢®Ş 
?
2crypto_order_create_summary_stop_limit_buy_rebrandñÅ§”‹ÀŞ„
?
3crypto_order_create_summary_stop_limit_sell_rebrandàşšóŞØœÖ-
C
7crypto_order_create_summary_stop_limit_buy_rebrand_feesÛ£¦›ïé©x
E
8crypto_order_create_summary_stop_limit_sell_rebrand_feesòÖŠ¶‡íÜ÷
7
*crypto_order_create_summary_default_suffix‚û¾ä£ç”°Æ
K
>crypto_order_create_summary_integration_fees_disclosure_suffixÌÏÄ«ÜÛŞˆ¢
3
'crypto_order_check_margin_minimum_titleéóä³À‡—í
2
&crypto_order_check_margin_buying_power‘¿„ìüî²Ø\
.
!crypto_order_check_deposit_action¯¿µ¾ÉŞşÛÆ
(
crypto_order_check_pdt_title·ÓèÎ±„Çän
*
crypto_order_check_pdt_messageÒ¢‘¥ô—Ïv
,
crypto_order_check_pdt_continueŞÿø‚æÃƒì
/
#crypto_trading_coin_list_info_title£ıÌìà‡Ì*
.
"crypto_trading_coin_list_info_body¢¸©Ó‘Æğ¦x
;
.crypto_trading_coin_list_info_dismiss_cta_textŞÿø‚æÃƒì
8
+crypto_trading_coin_list_info_tax_lots_bodyëŒ¯ÃõÁÀŒ
9
,crypto_order_collar_explanation_dialog_titleæëª¿ÏÓÊ–
?
2crypto_order_collar_explanation_dialog_message_buyèˆ›³àû®…—
?
3crypto_order_collar_explanation_dialog_message_sellÄâä®öıÑ;
8
,crypto_collar_explanation_dialog_message_buy¤ãèç¢—Ÿü 
9
-crypto_collar_explanation_dialog_message_sell¹·¿¼Õÿ6
?
3crypto_recurring_vt_collar_explanation_dialog_title§¥ÁêËÀ¢Õ

F
9crypto_recurring_vt_collar_explanation_dialog_message_buyôË§ÒÙµÈÅÿ
6
)crypto_recurring_vt_collar_learn_more_urlâÖŞˆèÒ„ñÓ
/
#crypto_order_detail_disclaimer_textÔ™¥»„«Æ
;
/crypto_order_detail_disclaimer_disclosures_textÿ‡õóßÃõğ
<
/crypto_order_detail_disclaimer_disclosures_link³ˆôÀÛÂáÆñ
6
)crypto_order_detail_amount_canceled_label‰èÂÛø÷·üë
4
'crypto_order_detail_date_canceled_labelÄ›Ëï¬ìÈ‚Š
2
&crypto_order_detail_account_name_label´­øû±éQ
5
(crypto_fee_order_submission_failed_title£¼Åô¸ôÛÚÅ
?
3crypto_fee_order_submission_failed_body_volume_tierÙ‚ëÒ…¬ÁY
P
Ccrypto_fee_order_submission_failed_convert_to_rebate_order_cta_text‘§‘‚ §¿Ë
>
2crypto_fee_order_submission_failed_cancel_cta_textÖï³¼Ì†€!
9
-crypto_fee_definition_body_without_executions†˜ÿ£ªïs
6
*crypto_fee_definition_body_with_executions¼ÏÀˆ¹ã¤ºo
G
;crypto_fee_definition_body_without_executions_volume_tieredÑ‰è’À½`
E
8crypto_fee_definition_body_with_executions_volume_tieredıùôáòòÑ“
J
=crypto_fee_definition_banner_without_executions_volume_tieredÈ­†²¼û­Œô
G
:crypto_fee_definition_banner_with_executions_volume_tieredî›ÆÎ—á‘¡
)
crypto_fee_definition_got_itŞÿø‚æÃƒì
A
4crypto_monetization_model_preference_toggle_title_on¤Î‹åİ¬£›Ï
B
5crypto_monetization_model_preference_toggle_title_offç‡ÖÚïÁëñ
?
3crypto_monetization_model_preference_toggle_text_on…’Ş£Òş‡ê#
A
4crypto_monetization_model_preference_toggle_text_offùÓÛ€€‘‘“‘
[
Ocrypto_monetization_model_preference_unsupported_currency_pair_text_volume_tierÛÊ§üÂ‚†¯G
e
Ycrypto_monetization_model_pref_unsupported_no_market_maker_currency_pair_text_volume_tierÓÙ™Â“‡»
:
.crypto_fee_unsupported_banner_text_volume_tier–õ¿óœ²¤À
M
@crypto_fee_unsupported_non_market_makers_banner_text_volume_tier£—ÁÃ–Ä£’¹
3
&crypto_fee_unsupported_banner_cta_text¬ƒ…ûòÎ™·ß
K
?crypto_order_fee_unsupported_for_currency_pair_text_volume_tier–õ¿óœ²¤À
Y
Lcrypto_order_fee_unsupported_non_market_maker_currency_pair_text_volume_tier£—ÁÃ–Ä£’¹
@
3crypto_order_fee_unsupported_for_currency_pair_link¬ƒ…ûòÎ™·ß
+
order_type_sell_tax_lots_titleÑÀ‹ä”ŸŞ´Ã
.
!order_type_sell_tax_lots_subtitleŒöüˆ¢ŞÆìè
 
order_type_tax_lotsÑÀ‹ä”ŸŞ´Ã
8
+crypto_tax_lot_order_input_order_type_label‰±“ÚÌİş¬¿
>
2crypto_tax_lot_order_input_order_type_market_labelé‰È¿„˜é6
=
1crypto_tax_lot_order_input_order_type_limit_label±¹“œÏ€Íl
B
5crypto_tax_lot_order_input_order_type_stop_loss_labeläÕºØ·ÔÑéË
B
6crypto_tax_lot_order_input_order_type_stop_limit_labelÌüµÜØ…5
;
.crypto_tax_lot_order_input_lot_selection_labelì’ú•Ô·»è
5
)crypto_tax_lot_order_input_footer_messageè®ĞôÆ^
)
crypto_tax_lot_order_input_cta¦¼Ï™üï
?
3crypto_tax_lot_order_input_limit_price_primary_textÛ€é‹ò¨í|
H
<crypto_tax_lot_order_input_limit_price_secondary_text_prefix”–—íÛ‰ü°
@
4crypto_tax_lot_order_input_asset_amount_primary_text˜³ÕËÎŞÒË)
:
-crypto_tax_lot_order_input_total_credit_labelİ‰¼İÛı—Áı
=
1crypto_tax_lot_order_input_estimated_credit_labelñÓ÷«¥™ÓŒA
6
)crypto_tax_lot_order_input_est_gain_label§‰áÆŒÚ®ÉÄ
5
)crypto_tax_lot_order_input_est_loss_labeléöçÄ„ÄÀà{
/
"crypto_tax_lot_custom_display_nameÿ˜ùğÂŞ Ì
0
$crypto_tax_lot_first_in_display_nameªªÌÃçÀY
/
#crypto_tax_lot_last_in_display_name¿«ï£úåëï
4
(crypto_tax_lot_highest_cost_display_nameÂ Û­»Û
4
'crypto_tax_lot_lowest_cost_display_nameèŒÈ ÙÌ¢˜£
@
4crypto_tax_lot_strategy_selection_bottom_sheet_titleõ——Üë­º¥R
B
5crypto_tax_lot_strategy_selection_bottom_sheet_footer Ø¬…Œ”Š±“
?
2crypto_tax_lot_strategy_selection_bottom_sheet_cta‘§‘‚ §¿Ë
J
>crypto_tax_lot_strategy_selection_bottom_sheet_est_gain_prefix›ıéã»Šãşf
J
>crypto_tax_lot_strategy_selection_bottom_sheet_est_loss_prefixÍæË¹€ŠùX
1
%crypto_tax_lot_selection_header_titleæëÛŸÅÑg
;
/crypto_tax_lot_selection_header_subtitle_marketöàÛ¿ªşëÕ]
;
.crypto_tax_lot_selection_header_subtitle_limitÍ¾¶Ì˜œã¨Ï
?
2crypto_tax_lot_selection_header_subtitle_stop_loss‡èµ°Ïí ã
@
3crypto_tax_lot_selection_header_subtitle_stop_limitÍ¾¶Ì˜œã¨Ï
?
2crypto_tax_lot_selection_footer_total_credit_labelİ‰¼İÛı—Áı
?
3crypto_tax_lot_selection_footer_est_gain_loss_label®éáøäê}
:
.crypto_tax_lot_selection_footer_quantity_labelğ±È“ÍÇP
0
#crypto_tax_lot_selection_footer_cta‘§‘‚ §¿Ë
4
(crypto_tax_lot_selection_footer_max_text“ì¼¤ü´š÷;
U
Icrypto_tax_lot_selection_footer_input_quantity_exceeds_available_quantityÀß‰ù‚ë¤½~
8
,crypto_tax_lot_selection_table_not_availableØà“×Ë”Æ§
D
8crypto_tax_lot_selection_table_term_type_lt_display_name¤›ëÆ¨£üK
E
8crypto_tax_lot_selection_table_term_type_st_display_nameïúŒ–µû£Šî
I
=crypto_tax_lot_selection_table_term_type_unknown_display_nameÂí²íëÍù“g
3
&crypto_tax_lot_reviewing_edit_cta_text¸–¡ÛÎ„™úó
>
2crypto_tax_lot_reviewing_asset_amount_primary_text˜³ÕËÎŞÒË)
F
9crypto_tax_lot_reviewing_lot_terms_label_gain_loss_amountÓù¤‚ĞÁ²Ÿ
4
(crypto_tax_lot_reviewing_est_loss_prefixö•¬•›öíúK
5
(crypto_tax_lot_reviewing_est_gain_prefixÙ£çºˆ¥®¼
=
1crypto_tax_lot_reviewing_asset_price_primary_textÙÉ€©¾…©ßI
=
1crypto_tax_lot_reviewing_limit_price_primary_textÛ€é‹ò¨í|
<
0crypto_tax_lot_reviewing_stop_price_primary_text†  ÷³×ÏÒ^
.
"crypto_tax_lot_reviewing_bid_labelÚÉª‹å‰¡[
/
#crypto_tax_lot_reviewing_stop_labelŞÃ©ŸùÌíÏ{
7
*crypto_tax_lot_reviewing_sell_spread_label÷À•Ÿ¤«×ŒÚ
A
4crypto_tax_lot_reviewing_sell_spread_secondary_labelÁ¥øĞñÃ¢Ù
8
+crypto_tax_lot_reviewing_total_credit_labelİ‰¼İÛı—Áı
;
/crypto_tax_lot_reviewing_estimated_credit_labelñÓ÷«¥™ÓŒA
1
$crypto_tax_lot_mixed_term_lots_labelòÿêò”Ş¥ş
B
5crypto_tax_lot_selection_work_loss_alert_dialog_titleö•¡ØÁ÷Û
D
8crypto_tax_lot_selection_work_loss_alert_dialog_subtitleÒÍÒ› Éé›h
L
@crypto_tax_lot_selection_work_loss_alert_dialog_leave_screen_ctaùÈ‘³æÁÓ
O
Bcrypto_tax_lot_selection_work_loss_alert_dialog_stay_on_screen_cta»Ç¼¹•·Ò»
=
0crypto_order_detail_tax_lots_title_lots_selectedâçØÛ²È˜Ã
;
.crypto_order_detail_tax_lots_title_lots_filledĞñæ¦Î¶÷¡
E
9crypto_order_detail_tax_lots_total_estimated_gain_or_lossúª¹ø¢æ¶˜ 
=
1crypto_order_detail_tax_lots_total_estimated_gain™ÓÍô½îç„
=
1crypto_order_detail_tax_lots_total_estimated_lossİ–ÔÌŸÁŠU
D
8crypto_order_detail_tax_lots_total_realized_gain_or_loss›¼‰Í×ûÙe
=
0crypto_order_detail_tax_lots_total_realized_gain¼ŒÓšºìõÇ€
=
0crypto_order_detail_tax_lots_total_realized_lossªåÇÍàËæŠ
C
7crypto_order_detail_tax_lots_gain_or_loss_not_availableØà“×Ë”Æ§
5
(crypto_order_detail_tax_lots_date_header³ëıÚß—‰ÏĞ
=
1crypto_order_detail_tax_lots_cost_per_unit_headeräı×ÂòàŒ»]
:
-crypto_order_detail_tax_lots_gain_loss_headerû¨—ë—äŒ‡
8
,crypto_order_detail_tax_lots_quantity_headerğ±È“ÍÇP
0
$crypto_order_detail_tax_lots_info_naØà“×Ë”Æ§
B
6crypto_tax_lot_selection_dismissable_alert_dismiss_cta«ÆµµÀîĞâ)
<
0crypto_tax_lot_order_input_lot_limit_alert_titleˆ®–·Å“Ìi
;
/crypto_tax_lot_order_input_lot_limit_alert_bodyÎ’Õ¼ƒ© ª[
C
6crypto_tax_lot_order_input_lot_limit_alert_primary_cta¬ÕµÍ„ì²Ô
B
6crypto_tax_lot_order_input_lot_limit_alert_dismiss_cta«ÆµµÀîĞâ)
G
:crypto_tax_lot_selection_validation_failure_edit_order_cta“„Ò¬ª–ıëÆ
A
4crypto_tax_lot_selection_order_precision_check_titleé ÓšõßË¦¥
.
!crypto_tax_lot_order_tooltip_text—æË˜êñ°“
(
crypto_order_type_buy_ordersÓÌ¢‚î‚×k
)
crypto_order_type_sell_orders—Úüİ×ÍÊÀi
1
$crypto_order_type_market_order_title·Ú¢®ÑÆğæ
4
'crypto_billing_error_order_failed_title€·¤À·¿
6
)crypto_billing_error_order_failed_message‹ä¾ÎØÙº€ı
6
)crypto_billing_error_deposit_failed_title¬î•™¶½À‹À
<
/crypto_billing_error_deposit_failed_dcf_messageŒÔë—ÚäİÔ
;
/crypto_billing_error_deposit_failed_ach_messageäöÆıŒÖŞÍ+
0
$crypto_order_details_realized_profitçäŞ‹¿ô™É
C
7crypto_order_details_realized_profit_excludes_transfers‚•…äù“ÿëW
/
"crypto_order_details_realized_lossæœ¸¨õ„ØÁÆ
A
5crypto_order_details_realized_loss_excludes_transfers§³Ì¬Ô¶é½i
:
-crypto_order_details_realized_profit_and_lossÄ·ó…ÜòÀÛ¯
J
>crypto_order_details_realized_profit_and_loss_unavailable_textØà“×Ë”Æ§
?
2crypto_fee_upsell_bottom_sheet_maybe_later_tooltip–°¯úøå«×
=
1crypto_order_create_low_stop_price_dialog_body_us˜ÔÔòÊ§âÓp
?
2crypto_order_create_high_stop_price_dialog_body_us¹ üÕ–¥ã¶¹
0
$crypto_tax_lot_short_term_lots_labelîÀ¤Ú±å7
0
#crypto_tax_lot_long_term_lots_labelÅ˜œÌşû÷ë
3
&crypto_tax_lot_unknown_term_lots_labelÍ’Šû“¥ÆÜ£
C
6crypto_tax_lot_selection_order_precision_check_message²ÚÓœàö˜Ç‡
<
/crypto_order_create_price_label_with_symbol_askÖá©ÀşÂò
;
/crypto_order_create_price_label_with_symbol_bid¶†»™“åÉœh
I
<crypto_order_create_price_label_v2_with_symbol_and_value_askŞÖ—·º«íû§
I
<crypto_order_create_price_label_v2_with_symbol_and_value_bidâä³»óµÅÁ
1
%crypto_order_create_limit_price_labelÛ€é‹ò¨í|
-
 crypto_order_create_amount_label¶¿˜ôÑÈèŸ
+
crypto_order_create_total_labelôÏ–†ä´ğåo
+
crypto_order_total_amount_labelÇ¾óù‡‰ØßZ
9
,crypto_order_create_advanced_limit_price_buyÙ¿öôÀòÁ€‰
:
-crypto_order_create_advanced_limit_price_sellÁÄÿšĞ‚îÚ¿
L
?crypto_order_create_advanced_limit_price_buy_prompt_limit_order‡â«»£Ñêöâ
L
@crypto_order_create_advanced_limit_price_sell_prompt_limit_orderŒã´“¡°Ä‹v
2
&crypto_order_create_result_label_asset’ìÂŸºÕœ‘S
8
,crypto_order_create_result_label_total_assetÔ”á”˜¸êî6
*
crypto_order_create_result_m2¿ûû”èòêõÙ
4
(crypto_order_result_label_estimated_costè…˜œáµ±¦
0
$crypto_order_result_label_total_cost£ºè—íñ¥œ
3
&crypto_order_result_label_total_creditİ‰¼İÛı—Áı
6
*crypto_order_result_label_estimated_creditñÓ÷«¥™ÓŒA
=
0crypto_order_result_label_estimated_total_credit«¬¬©Øå¾®€
7
*crypto_order_edit_limit_price_button_label¸–¡ÛÎ„™úó
-
!crypto_order_create_summary_titleÆ”£²¨‘ '
6
*rhc_crypto_order_create_summary_market_buyµÅÈ’‚–½ÿ$
7
+rhc_crypto_order_create_summary_market_sellØçŸÇî„§©`
;
.rhc_crypto_order_create_summary_market_buy_feeëû©ÙüáÀÆ¯
;
/rhc_crypto_order_create_summary_market_sell_feeÚÇºŸ‚Ó­Â[
-
!crypto_order_price_best_bid_label ¾ØöÈËÚ`
.
!crypto_order_price_best_ask_labelà«À’ïŸ«ÿÃ
1
%crypto_order_price_order_expiry_labelĞ×Äú€­­©D
7
*crypto_order_create_tick_size_dialog_titleûóÃ‹úü‰·
9
,crypto_order_create_tick_size_dialog_message¦ğâŸüú¶€°
7
*crypto_order_review_swipe_to_submit_promptÒÆãÀ×…÷ËÇ
4
'crypto_order_check_create_account_titleã·ÇÀÅšŸÚõ
6
)crypto_order_check_create_account_messageì¿¬ÅÀÄ»Û
4
(crypto_order_check_create_account_action¢ñ¦ò¶®Ğ¨q
1
%crypto_order_check_buying_power_titleœòü±¢¹È®
A
5crypto_order_check_buying_power_choose_payment_methodé‡ĞèÑö¯ˆZ
.
"crypto_limit_order_amount_in_labelûŞ”æ‡ö³r
.
"crypto_limit_order_estimated_assetúº¥¶é±Ê
:
-crypto_limit_order_header_subtitle_sell_quoteŸŸÕ±­çÆ•ç
9
-crypto_limit_order_header_subtitle_sell_assetÜíöš¬±’u
<
0crypto_limit_order_reviewing_state_toolbar_title¼Ü¦İ¹Ö†Ö{
6
)crypto_limit_order_create_summary_buy_rhcŠú÷òŒ“ï–ò
7
*crypto_limit_order_create_summary_sell_rhc£Æ—¹¶ìú
:
-rhc_crypto_order_create_summary_stop_loss_buyÒŞÈ˜ê«àû
;
.rhc_crypto_order_create_summary_stop_loss_sellŸÇ‡–’¸¤¡¿
;
.rhc_crypto_order_create_summary_stop_limit_buyé™­òª‘ö”Ì
;
/rhc_crypto_order_create_summary_stop_limit_sell†“­É”¾Òß?
1
%crypto_trade_bonus_bottom_sheet_titleÑ°†Òéê€`
?
2crypto_trade_bonus_bottom_sheet_text_order_pendingÙğµµ”¹™È
>
2crypto_trade_bonus_bottom_sheet_text_bonus_pendingıÇ¥Î¸ğµ‘@
@
4crypto_trade_bonus_bottom_sheet_text_bonus_finalizedÑÜ•ò¶ª‰Ñ/
8
+crypto_trade_bonus_bottom_sheet_dismiss_ctaŸ¡Ô·øñª‹
9
,crypto_trade_bonus_bottom_sheet_amount_label¤’Œåû»Úæß
>
1crypto_trade_bonus_bottom_sheet_review_order_text«èÄ®ù¨×ğ
;
.crypto_trade_bonus_bottom_sheet_learn_more_cta¬ƒ…ûòÎ™·ß
J
=crypto_trade_bonus_bottom_sheet_review_order_bonus_percentage—®—¬Ê¾ô·
>
2crypto_trade_bonus_bottom_sheet_review_order_totalÌØãŞí…Èx
F
9crypto_trade_bonus_order_review_bonus_percentage_includedöâœÃÉ¹òÎ€
+
crypto_trade_bonus_support_url»´ÏìÀ Ï·
I
=crypto_order_create_advanced_stop_price_buy_prompt_stop_order×¡…¡´ºœÕY
J
>crypto_order_create_advanced_stop_price_sell_prompt_stop_order–øµ—²Çå
P
Ccrypto_order_create_advanced_stop_price_buy_prompt_stop_limit_orderçÉ‹êè¸Ï„
P
Dcrypto_order_create_advanced_stop_price_sell_prompt_stop_limit_order±•—ÿÚ×™‹

P
Dcrypto_order_create_advanced_limit_price_buy_prompt_stop_limit_orderĞ¯¬Ï÷ÑŸ
Q
Ecrypto_order_create_advanced_limit_price_sell_prompt_stop_limit_orderçËõóÂ®³Ü
-
!crypto_order_label_stop_price_set“«‚‚¥„Ãòk
=
0crypto_order_create_high_stop_price_dialog_titleˆ½•ó«Ë¥Ÿ†
;
/crypto_order_create_low_stop_price_dialog_titleæÉÓÀ©¯¯
:
.crypto_order_create_low_stop_price_dialog_bodyâ“¼¤“‡ß|
<
/crypto_order_create_high_stop_price_dialog_bodyÊôÀıÓ˜ëò¥
6
*crypto_order_create_edit_stop_price_actionÔ¼Š÷ÔšÜçi
0
$crypto_order_create_stop_price_label†  ÷³×ÏÒ^
8
+crypto_order_create_advanced_stop_price_buyÙ¿öôÀòÁ€‰
9
,crypto_order_create_advanced_stop_price_sellÁÄÿšĞ‚îÚ¿
/
"crypto_order_price_dialog_continue‘§‘‚ §¿Ë
!
order_type_stop_lossĞïæûãıÍ§
!
order_type_stop_limití¶ñİÆèŞ¡d
"
time_in_force_24_hours…×ª”½·®ö2
 
time_in_force_7_daysæİ°²­£´„q
!
time_in_force_30_days¢²Ñ‹Òïôõ#
!
time_in_force_90_days¡Ü®ÂËø‡J
)
crypto_order_stop_price_labelË®Í°˜´ÔÕ3
0
$crypto_order_detail_stop_price_label†  ÷³×ÏÒ^
4
'crypto_order_eu_advanced_orders_tooltip›Ïîëó¬Şè
)
crypto_eu_fee_definition_bodyªŸ¶—”¬Æ}
(
crypto_eu_fee_definition_okŸ¡Ô·øñª‹
-
!crypto_order_recurring_hook_titleìğÛˆïÈÂ¦&
4
'crypto_order_recurring_hook_description¹¦â›‰í¬‘
:
.crypto_order_recurring_hook_row_one_time_titleºĞ«ÌŠ¯ÕŸ5
A
4crypto_order_recurring_hook_row_one_time_descriptionÇŸÛæ‡®¾ÍÃ
/
"crypto_order_recurring_hook_footerĞÎ¦û¬¨ªô
7
*crypto_order_buying_power_alert_sell_title¿‡Š˜ø‡“óÓ
=
0crypto_order_buying_power_alert_sell_got_it_textŞÿø‚æÃƒì
;
.crypto_quote_order_sell_power_alert_message_v2‡äÒµÊÅ—ÿ§
;
.crypto_asset_order_sell_power_alert_message_v2ÿ¨Êğë‹‘–é
/
"crypto_order_check_too_large_titleç…ù®Á†ÄùŸ
7
*crypto_order_check_too_large_asset_messageºê¹¦ı§ñ¦
6
*crypto_order_check_too_large_quote_messageŒÆÿ½ëÑ£w
0
$crypto_order_check_too_large_set_max•ÀØ÷¹İæí#
)
crypto_order_status_too_largeËÑ€Í•–£™g
,
 crypto_order_check_holding_title¹íåºæ„ÿ

4
(crypto_order_check_holding_message_quote¶Ç¢ò°ôÓ©
5
(crypto_order_check_holding_message_asset âÃåÜŠÕ
B
5crypto_order_check_holding_message_with_pending_quoteœ„éÇé²Ğ‹ò
B
5crypto_order_check_holding_message_with_pending_assetŞë’æúé°¬ó
.
!crypto_order_check_min_size_title·¨†”¶ğª×ñ
3
&crypto_order_check_min_size_buy_action÷º–ì­åÖ´Ç
3
'crypto_order_check_min_size_sell_actionüÕÌ¨¿ØÄI
(
crypto_order_check_min_sizeŸöä«éğÆß’
2
%crypto_order_check_min_size_fee_quoteóšÛ½Œ©˜øé
2
%crypto_order_check_min_size_fee_assetí¸ì±³øâ³ô
1
$crypto_order_check_limit_price_titleõÙêÓÇÃ£œİ
2
&crypto_order_check_limit_price_message³ˆØòûŸÃŞ
B
5crypto_order_check_aggressive_low_limit_price_message²Ïú·±©é‚
$
order_type_market_plural´“çıÃ±0
"
order_type_conditionalˆ¬Õáóıº—

order_type_buy_in…´¸Š®ˆ¹¿

order_type_sell_in¤¾‡ë‘Ã ¥>
'
rhc_order_type_description‘ÓÔ‚—»è®è
0
$order_type_buy_in_dollar_descriptionÆ¾ÃÉ‘™Æá^
/
"order_type_buy_in_coin_descriptionÌÜ¦˜¬œ†‹ç
1
%order_type_sell_in_dollar_descriptionÇ­ˆåÔ·âÓs
0
#order_type_sell_in_coin_description¸Ù à•×º¡

order_type_limit³ÙØÛ…µı÷
$
order_type_market_order“ÕöØããÉÛù
!
order_type_recurring£ÏĞ™âòÎŒÈ
,
 order_type_limit_description_buyº¤…±ˆæ¥ä
-
!order_type_limit_description_sellüÑæ±‰–Ä3
1
$order_type_recurring_description_buy£üÓÿò Çå
"
order_type_stop_titleĞïæûãıÍ§
+
order_type_stop_description_buy­ıóåùô³¾|
,
 order_type_stop_description_sellªì«ßÿÊ«ğ!
'
order_type_stop_limit_titleí¶ñİÆèŞ¡d
1
%order_type_stop_limit_description_buy›ğé×Œ¿“Ì/
3
&order_type_stop_limit_description_sell¶¸ª±ƒñšˆ

order_sell_allªÅ•‰±İõÂA
'
crypto_quote_order_sell_allÔÍ®»Å»­ÎV
)
crypto_order_spread_label_buy‘İ¬ßÎøŒ¿
+
crypto_order_spread_label_sell´ÿ‰¡áèë²™
2
&crypto_order_spread_secondary_includedşöèøú”»'
3
&crypto_order_confirmation_cta_continue‘§‘‚ §¿Ë
;
.crypto_order_confirmation_your_fee_tier_status½ğšáä‘üâÙ
G
:crypto_order_confirmation_fee_tier_status_current_fee_tierãÚ³Å¿˜ôËŸ
C
7crypto_order_confirmation_fee_tier_status_next_fee_tier“¿ôœ±‹ÎË>
V
Icrypto_order_confirmation_fee_tier_status_trading_volume_amount_in_periodü®ã¦ˆ•³éø
D
7crypto_order_confirmation_your_fee_tier_status_cta_doneî’Ü¢²øğøÙ
H
;crypto_order_confirmation_your_fee_tier_status_cta_continue‘§‘‚ §¿Ë
T
Hcrypto_order_confirmation_your_fee_tier_status_cta_view_fee_tier_detailsÁÉÕÊâ§®şx
G
:crypto_order_confirmation_your_fee_tier_status_error_titleúÔƒÕÌûÃÜö
L
@crypto_order_confirmation_your_fee_tier_status_error_description­ú›”Á¨¥–8
J
=crypto_order_confirmation_your_fee_tier_status_error_cta_exitÆ°­œ¯¡ÜÉ
N
Bcrypto_order_confirmation_your_fee_tier_status_error_cta_try_againàº²Û½‚‘Ça
>
1crypto_order_confirmation_fee_tier_upgraded_titleÈô©œ×Î’Ó¥
=
0crypto_order_confirmation_fee_tier_upgraded_desc”½êğú¶¤
I
<crypto_order_confirmation_fee_tier_upgraded_current_fee_tierãÚ³Å¿˜ôËŸ
E
9crypto_order_confirmation_fee_tier_upgraded_next_fee_tier“¿ôœ±‹ÎË>
K
?crypto_order_confirmation_fee_tier_upgraded_guaranteed_for_daysçè¸Œéæ£‘-
I
<crypto_order_confirmation_fee_tier_upgraded_primary_cta_doneî’Ü¢²øğøÙ
M
@crypto_order_confirmation_fee_tier_upgraded_primary_cta_continue‘§‘‚ §¿Ë
H
<crypto_order_confirmation_your_fee_tier_upgraded_error_titleàÅ¹»†…äİ
N
Bcrypto_order_confirmation_your_fee_tier_upgraded_error_description­ú›”Á¨¥–8
L
?crypto_order_confirmation_your_fee_tier_upgraded_error_cta_exitÆ°­œ¯¡ÜÉ
P
Dcrypto_order_confirmation_your_fee_tier_upgraded_error_cta_try_againàº²Û½‚‘Ça
5
)crypto_fee_tier_notification_primer_titleáÖò¤İ°çé=
5
(crypto_fee_tier_notification_primer_descİÈ§½èğâÿ°
7
*crypto_fee_tier_notification_primer_helperàÃ”·Ã¹ì’Ç
B
5crypto_fee_tier_notification_primer_helper_learn_more¬ƒ…ûòÎ™·ß
<
/crypto_fee_tier_notification_primer_cta_turn_on´÷å¼†ü£‡Ğ
@
3crypto_fee_tier_notification_primer_cta_maybe_lateräœ€Ê¬‡…²
E
8crypto_fee_tier_notification_primer_toast_updates_are_on­ÜŠÚøŒÍÅ
;
/crypto_fee_tier_notification_primer_error_titleàÅ¹»†…äİ
A
5crypto_fee_tier_notification_primer_error_descriptionôáÉ£™é÷÷J
A
5crypto_fee_tier_notification_primer_error_cta_dismiss«ÆµµÀîĞâ)
C
7crypto_fee_tier_notification_primer_error_cta_try_againàº²Û½‚‘Ça
=
0order_confirmation_crypto_recurring_upsell_title»’‡ô¡…Ùô
B
6order_confirmation_crypto_recurring_upsell_description”Óê®˜Ğ¬²J
C
6order_confirmation_crypto_recurring_upsell_get_started©¤áè›½àµ¢
F
9order_confirmation_crypto_action_set_recurring_investmentè¶Íï¢“äì¸
C
6order_confirmation_rhc_action_set_recurring_investmentß‡Ïşÿê“ğ
3
&crypto_order_price_details_total_asset ¡±ÍÔÓª ö
3
'crypto_order_price_details_asset_amountéÔ¬Ù¿ç¹á
1
%crypto_order_price_details_total_cost£ºè—íñ¥œ
-
!crypto_order_price_details_amountéÔ¬Ù¿ç¹á
4
'crypto_order_price_details_total_creditİ‰¼İÛı—Áı
,
 crypto_trade_time_in_force_titleÛÎ®…«õì£`
2
&crypto_trade_time_in_force_description¶ìñ¸»®Ü†
B
6crypto_trade_create_time_in_force_gfd_summary_tomorrow¡Ãğ¹êæÜ­
>
1crypto_trade_create_time_in_force_gfd_description–‘šÀ¬¦ùÑ
=
1crypto_trade_create_time_in_force_gfw_descriptionª–„îşÅÖ„W
=
1crypto_trade_create_time_in_force_gfm_descriptionÓøËÈÀÚŠ¼&
>
1crypto_trade_create_time_in_force_gtc_descriptionÑ÷íĞÕ¤´Ê¯
(
crypto_trade_label_continue‘§‘‚ §¿Ë
,
 crypto_coin_list_selection_titleäö±È€¤Òı
3
&crypto_coin_list_selection_search_hintú¨’¬¥ÜŸ²
@
3crypto_coin_list_selection_info_content_description²İÏñ½¦ÈÃ›
-
 crypto_ask_price_secondary_labelÀôÓ•Å¢£¬
-
 crypto_bid_price_secondary_labelÿ¢ü„Ÿ£°ˆ‘
*
eu_crypto_fee_help_center_urlØÅ Ñîî°§±
)
us_crypto_fee_help_center_urlµŒ¸Ó¥ó Ã
1
$crypto_order_detail_linked_app_labelû˜‘•ã¦´Şñ
4
(crypto_order_detail_date_submitted_labelÌ¦Ì°âİªÎ
3
'crypto_order_detail_time_in_force_labelÊ¦éĞ›¸¹õ
+
crypto_order_detail_state_label«æÃã¸€©Œ&
1
%crypto_order_detail_limit_price_labelÛ€é‹ò¨í|
1
%crypto_order_detail_date_filled_label®¡’Ôá¤é]
4
'crypto_order_detail_amount_filled_labelÓÍ¯¡ì¶¬ø†
?
2crypto_order_detail_estimated_notional_value_label·ûÈÎ‹Ê¨¸ß
:
/crypto_order_detail_filled_notional_value_labelèè¨ÅÊğ+
7
*crypto_order_detail_estimated_amount_labelƒ¶ß½ĞıŒ
5
(crypto_order_detail_amount_entered_label¾ªàÏ…©…Ï“
4
(crypto_order_detail_estimated_cost_labelè…˜œáµ±¦
;
.crypto_order_detail_estimated_total_cost_label£š’ò¢›ğÑ
*
crypto_order_detail_fee_label»êÀÅ‰‚´¬©
4
'crypto_order_detail_estimated_fee_label†ıç†ÜäÛˆ
0
$crypto_order_detail_total_cost_label£ºè—íñ¥œ
6
*crypto_order_detail_estimated_credit_labelñÓ÷«¥™ÓŒA
=
0crypto_order_detail_estimated_total_credit_label«¬¬©Øå¾®€
3
&crypto_order_detail_total_credit_labelİ‰¼İÛı—Áı
0
$gated_crypto_order_detail_disclaimerûğ²Ú€…Œ=
.
"crypto_order_detail_order_canceledÜ”Š»Ê”º‡?
3
'crypto_order_detail_cancel_sent_messageîìÇ«‡é Ü)
+
crypto_order_detail_bonus_labelÈ–Şö…Ï‹@
4
'crypto_order_detail_bonus_pending_labelĞù‡ñå·¤ä
4
'crypto_order_detail_lots_selected_labelâçØÛ²È˜Ã
2
%crypto_order_detail_lots_filled_labelĞñæ¦Î¶÷¡
=
0crypto_order_detail_estimated_gain_or_loss_labeläÛ’çê„ôÓÚ
5
(crypto_order_detail_estimated_gain_labelÕ«™€°Æ¾ñ
4
(crypto_order_detail_estimated_loss_label™Ì¿ÃÈ…Ğê9
;
/crypto_order_detail_realized_gain_or_loss_label÷Œß‘Ÿ‡¨Ó
4
'crypto_order_detail_realized_gain_labelò×äõÙƒ¤ß
4
'crypto_order_detail_realized_loss_labelæœ¸¨õ„ØÁÆ
>
2crypto_order_detail_gain_or_loss_unavailable_valueØà“×Ë”Æ§
6
*crypto_order_detail_quantity_entered_labelïİö¾‚ÒĞ¾=
5
)crypto_order_detail_estimated_price_labelì¸¡»»¿¤½u
.
!crypto_order_detail_fx_rate_label’ÁŸÖ†ïÀ´¼
.
!crypto_order_detail_fx_rate_value—€âƒõµìú
,
 crypto_order_detail_fx_fee_label¢ÆÕ¶Ò¾ë‰
-
!crypto_order_detail_banner_queued¼”³œ¡êŠÏ
7
+order_detail_view_trade_confirmation_actionŸš‡™¤ÇÒ*
<
0order_detail_order_canceled_confirmation_messageÜ”Š»Ê”º‡?
(
crypto_fee_definition_title»êÀÅ‰‚´¬©
-
 crypto_fee_definition_learn_more¬ƒ…ûòÎ™·ß
/
"rhc_order_recurring_hook_footer_v2„Ø½¨À«Öµ
9
-rhc_recurring_amount_buying_power_alert_titleœòü±¢¹È®
8
,rhc_recurring_amount_buying_power_alert_bodyõïœ›Š¾—
6
*rhc_recurring_amount_min_order_alert_title·îš£æäÑ
5
)rhc_recurring_amount_min_order_alert_body³àÔòË¹îØ*
6
*rhc_recurring_amount_max_order_alert_title¨ÖäßŞ˜ıĞ{
5
)rhc_recurring_amount_max_order_alert_body›ã­µóÄ¸‘
-
!rhc_recurring_generic_cta_dismiss«ÆµµÀîĞâ)
3
'rhc_recurring_generic_cta_deposit_fundsÄùğÀÂ¶§à(
/
"rhc_recurring_generic_cta_continue‘§‘‚ §¿Ë
.
"crypto_quick_trade_amount_in_label»Ã˜ Åûòe
0
#crypto_quick_trade_max_amount_assetÏé÷‰´¡™û
&
crypto_order_row_ask_priceöèö¶¿Ñõ¡9
&
crypto_order_row_bid_price×”»ğŸôÁ7
.
"crypto_order_row_ask_price_updated‡È½ıÒ”õÂ
/
"crypto_order_row_bid_price_updatedˆÎ£æ¾…„
-
 crypto_order_row_includes_spreadŒÅ­Àå†­ûõ
.
"crypto_quick_trade_disclosure_text»€ ê£óÆå.
3
'crypto_quick_trade_disclosure_link_textÿ‡õóßÃõğ
-
!crypto_quick_trade_buy_max_button‘î€¦ÚÄ²ˆ:
3
'crypto_quick_trade_buy_max_button_short“ì¼¤ü´š÷;
.
"crypto_quick_trade_swipe_to_submitô…©Ÿë”Ñµ5