
(
option_exercise_title_label¶ì³ï¬Å¯Ú
<
/option_exercise_selected_account_label_subtitle¥Â „Ì²ÛÔì
,
 option_exercise_multiplier_label…®Íœ¦À¶´
(
option_exercise_strike_labelÃœÛ¨ê„Û°\
3
&option_exercise_number_contracts_label§Â¤ì‚ú—å§
,
 option_exercise_description_callìıë”âÁe
B
6option_exercise_description_call_negative_buying_powerÔÕËõãÃäë
,
option_exercise_description_putğÇéÑå¤…Í
C
7option_exercise_description_short_position_with_pendingé¯ƒ¢¼¢äV
3
&option_exercise_swipe_to_submit_promptÒÆãÀ×…÷ËÇ
)
option_exercise_summary_label…â“Ü€ò—<
,
 exercise_confirmation_view_label„Ñ×Çââƒ`
1
%exercise_confirmation_title_completedÁàÓí·g
0
#exercise_confirmation_title_pendingËÊíÇÆŒ§‘ò
=
0exercise_confirmation_description_call_completed•æùšşßÃèğ
<
/exercise_confirmation_description_put_completed²¦í£³¤ÿèâ
6
)exercise_confirmation_description_pendingÿ›ÁÅ³˜ÏËŠ
)
option_exercise_quantity_hintüşáğ­ÂĞş

4
'option_exercise_short_position_subtitle¤³‰ˆšÖĞøø
/
#option_exercise_borrow_fee_subtitleÒÚéÓš”ä:
:
-option_exercise_borrow_fee_subtitle_link_text¸Ò„åç°ÏşÅ
8
+option_exercise_borrow_fee_subtitle_defaultã¸‘™óŠû°
B
5option_exercise_borrow_fee_subtitle_default_link_text‰ÙÓ°Ù²ò‚‚
6
)option_exercise_borrow_fee_inline_tooltipûíä¹¸Ö¦‹
<
/option_exercise_short_detail_bottom_sheet_title„³ö¿Œš £
>
2option_exercise_short_detail_bottom_sheet_subtitle—Ö´Á—ô¾‡}
N
Aoption_exercise_short_detail_bottom_sheet_share_to_exercise_label™Ô½¬ÏçÂÿß
N
Boption_exercise_short_detail_bottom_sheet_share_you_can_sell_labelºŒë‚†èç—
K
>option_exercise_short_detail_bottom_sheet_short_position_label„³ö¿Œš £
.
!option_exercise_corp_action_title¢Õ¹Æğ„“Ë«
4
'option_exercise_corp_action_descriptioníÜˆèó‘ÁíÌ
!
exercise_splash_titleßÁŒúÆëâû0
,
 exercise_splash_description_callÈíüß°ÜË
9
,exercise_splash_description_call_without_etfâÄÎü—ø¾åß
,
exercise_splash_description_put‡ÁÙ‡¬ùÀÊ¬
7
+exercise_splash_description_put_without_etf“§Ú˜•úĞ¤U
+
exercise_splash_learn_more_urlëñ‹Åó¢öÀ¶
,
 exercise_market_data_error_titleº±¥Ğœæ× 
2
&exercise_market_data_error_descriptionä²ùİÛÿªt
6
)exercise_market_data_error_description_gbèÕó³‹„—ñ
*
early_assignment_splash_title‘«å¢§×ş½
0
#early_assignment_splash_description¢”•‹Ù—ÈÄ
0
$early_assignment_option_picker_title¦Á·Ã”®¬¡6
7
*early_assignment_option_picker_descriptionÂÌşªº“×´¢
6
*early_assignment_option_picker_error_titleµ—§¥ÚÊm
=
0early_assignment_option_picker_error_description÷®ÍÕÄêÒĞ‰
*
early_assignment_action_titleëÏÃèç×”íÅ
0
#early_assignment_action_descriptionµ½Ò“ªË¨Ş“
2
&early_assignment_action_description_gb½İÒáÿ±ÿår
2
&early_assignment_action_exercise_titleßÁŒúÆëâû0
9
,early_assignment_action_exercise_descriptionã’ÓÑüÚæˆÂ
8
,early_assignment_action_buy_underlying_title¸ùÎÅ‚ù™Á|
:
-early_assignment_action_sell_underlying_title¤ íî¸¹ô¥±
A
4early_assignment_action_trade_underlying_description§¬“ÌüÍˆÈÓ
2
%early_assignment_see_comparison_labelæœıå£®¦Ö
4
(early_assignment_see_comparison_label_gb÷œŸÿÛ„øĞ<
;
.early_assignment_action_contact_support_prefixÒ¿õíãø¡ÜÜ
>
1early_assignment_action_contact_support_link_textÙ“¯öãî”Ó¬
2
%early_assignment_comparison_buy_title°Ï©Ë¾¦‰Ñ
3
&early_assignment_comparison_sell_title˜Ô«óŠÎ›Âı
4
'early_assignment_comparison_descriptionöİ‘°¹øèĞ“
6
*early_assignment_comparison_description_gb’•Ì¢á
7
+early_assignment_comparison_exercise_headerÆœê€úÓÆ"
7
+early_assignment_comparison_exercise_detail³ÄŸ—ˆ‹§M
;
.early_assignment_comparison_exercise_detail_gbŒ´¥Á˜ª™­•
=
1early_assignment_comparison_buy_underlying_headeršæ´Ç›Ãàá"
=
1early_assignment_comparison_buy_underlying_detailÖ«¸î˜Ü˜‰)
A
4early_assignment_comparison_buy_underlying_detail_gbº±œ§Ğˆó¨ß
>
2early_assignment_comparison_sell_underlying_header‰‚šúâı‚{
?
2early_assignment_comparison_sell_underlying_detailÿÑ¸×æÎŠ‡
B
5early_assignment_comparison_sell_underlying_detail_gbš¼­ÄÑ¿Û
-
 early_assignment_comparison_prosÀ»Ç™ñ³¶ñµ
-
 early_assignment_comparison_cons†ğÊ€ö˜Š´
9
,early_assignment_comparison_guaranteed_priceŠÁ «ÈÏñ£
=
0early_assignment_comparison_guaranteed_executionŞ˜Š€óÅúŸ¦
5
(early_assignment_comparison_exercise_conù—…¦ôˆõá¢
<
0early_assignment_comparison_trade_underlying_pro‘²Ãüë¡é„R
<
/early_assignment_comparison_no_guaranteed_priceÑ¡”™ïÓ£ÓÊ
?
3early_assignment_comparison_no_guaranteed_executionÍóÈ‚îƒèñ8
7
+early_assignment_comparison_incomplete_selläì¯»“Ÿ‡£=
+
exercise_education_reason_title¾õÂÀƒ¡¯
/
#exercise_education_assignment_labelòğ”ˆ´ßóòP
5
)exercise_education_assignment_descriptionàŸŸ¡¶ıô
.
"exercise_education_liquidity_label¶–ËÖÍ—‚
5
(exercise_education_liquidity_description¿òø§º•”»®
3
'exercise_education_call_execution_labelûÆ¼éæšÍ¼

:
-exercise_education_call_execution_descriptionÂú”£×¸¿¼Ö
F
9exercise_education_call_execution_description_without_etféÔßÈ¥Ş æÔ
3
&exercise_education_put_execution_label¦€êò¬ò²
8
,exercise_education_put_execution_description·ûûÍÂ¼ÄM
E
8exercise_education_put_execution_description_without_etfØä‰Ì­×€•Ÿ

exercise_psa_titleó…›Ü€õÉÊ
%
exercise_psa_descriptionüçšÔ„´Öà™
"
exercise_psa_otm_labelŒè»ŸîÈ‹â
-
!exercise_psa_otm_description_callê¥Á¹êíİÛ
-
 exercise_psa_otm_description_put¢µÙ”ÇÔÁÑ
)
exercise_psa_time_value_labelîûÌ—Ë›ˆák
0
#exercise_psa_time_value_descriptionË•’ñÑÉ“Ã½
)
exercise_psa_cost_label_call¬ˆ‘¸É¹ ˆ”
.
"exercise_psa_cost_description_call”»ğº‰©©
(
exercise_psa_cost_label_put¬ˆ‘¸É¹ ˆ”
-
!exercise_psa_cost_description_putÍÉñ—Ï¡øë
-
!exercise_psa_execution_disclaimer¤¨ØòÒø×Ãf
-
 exercise_psa_short_selling_titleÓÙßÆ¥ÑĞÙ
3
&exercise_psa_short_selling_descriptioné†ÓòÂÉì
'
exercise_warning_otm_titleÄÉå÷éò§Ù¯
,
 exercise_warning_otm_description¸ğÛÌãÁ¾‡L
.
!exercise_warning_almost_otm_title’˜¹‘É¶ó¤û
3
'exercise_warning_almost_otm_descriptionÁ˜ë°×ìİ\
0
#exercise_warning_high_premium_titleäƒ§µÙ‡ ‹
5
)exercise_warning_high_premium_descriptionî©ó˜ş¥õV
.
!exercise_warning_high_premium_urlĞ¨Á²çè£¤š
0
#exercise_warning_last_updated_labelÂ€…ÃàÍŞ¶ 
7
+exercise_warning_visualization_strike_labelÃœÛ¨ê„Û°\
7
*exercise_warning_visualization_share_label‹ß’“²ÿñ¦
5
(exercise_warning_visualization_otm_label›ĞşÍƒ•—¾½
4
(exercise_warning_visualization_itm_labelúŸÀÿÄ÷ô[
;
/exercise_warning_visualization_contract_premium¯œ¯ˆ‘—µ§^
:
.exercise_warning_visualization_extrinsic_label¶ÉÈŒ³÷Öå>
;
.exercise_warning_visualization_intrinsic_labelÃÖ°ò†È¸Êê
?
3option_exercise_error_not_enough_buying_power_titleœòü±¢¹È®
B
5option_exercise_error_not_enough_buying_power_message¬£ÉØ÷ÑÂµš
S
Goption_exercise_error_not_enough_buying_power_message_multiple_accounts½Úáö¿ò§ H
=
1option_exercise_error_negative_buying_power_titleÉÊÆ–Û‚¹Š
@
3option_exercise_error_negative_buying_power_messageÙê’Öƒ¡òì
8
,option_exercise_error_buying_power_row_labelæªÀÙ¡ÿ¬ÖM
<
0option_exercise_error_cost_to_exercise_row_labelÊ™ªŞßÌïö
7
*option_exercise_error_difference_row_labelŠŠ§—óÑÇõ½
:
-option_exercise_error_not_enough_shares_title§àÑù€Î¯œ
<
/option_exercise_error_not_enough_shares_messageíóÃÍÁóÏİÇ
N
Aoption_exercise_error_not_enough_shares_message_multiple_accountsİ¢Á™ïö×Ú
;
/option_exercise_error_sellable_shares_row_labelºŒë‚†èç—
A
4option_exercise_error_quantity_to_exercise_row_label™Ô½¬ÏçÂÿß
<
/option_exercise_error_account_deactivated_title”ˆÔ°‡øµ
=
1option_exercise_error_account_deactivated_message×¯ŠÎ·òöÈ0
F
9option_exercise_error_account_position_closing_only_title´Ñú…‚âË†
G
;option_exercise_error_account_position_closing_only_message©÷ùğÎ“†è<
Z
Moption_exercise_error_account_position_closing_only_message_multiple_accountsºÒô¨À
D
8option_exercise_error_account_not_enough_contracts_title¶ó½Ã€ãà˜%
G
:option_exercise_error_account_not_enough_contracts_messageƒ¯€ÔãéÉ
Y
Loption_exercise_error_account_not_enough_contracts_message_multiple_accounts’ÑûŠı¡Í†˜
E
9option_exercise_error_pdt_block_message_multiple_accountsĞÉµ„„üÃ
J
=mcw_option_exercise_error_pdt_block_message_multiple_accountsê¡ªõ­ˆ³Ë•
4
'option_exercise_error_pdt_block_messageØ£É‹€Œê¨à
7
+mcw_option_exercise_error_pdt_block_message”¼ù‰Â©Ñ¯(
G
;option_exercise_error_pdt_block_message_cash_sweep_appendixáƒ¤¨äÇæ¾u
,
option_exercise_pdt_help_center¸‰¸ù´¾°‚ñ
8
,option_exercise_day_trade_block_by_pdt_titleÕ¹²’‰éÜ…_
J
=option_exercise_day_trade_multiple_account_block_by_pdt_titleŒı£øÓ¼ô¶Ä
;
.option_exercise_day_trade_block_by_pdt_messageÆŸÖİº’·Å„
?
2mcw_option_exercise_day_trade_block_by_pdt_messageéãêïşİÀ©Á
K
?option_exercise_day_trade_block_by_pdt_multiple_account_message­Ûîı²ô¥Öz
P
Cmcw_option_exercise_day_trade_block_by_pdt_multiple_account_messageÖı«¥Û¦ÑŸÆ
6
*option_exercise_day_trade_restricted_titleğ¼ª  â¦`
9
,option_exercise_day_trade_restricted_message¿ …½¹Ü±
A
4option_exercise_day_trade_restricted_positive_buttonÜ’¦¼©ÂÅ«
@
4option_exercise_day_trade_restricted_negative_buttonÍäö÷¸çÏ¸_
6
*option_exercise_cta_disable_pdt_protection±Ó²ÿüÚá
6
*option_exercise_description_short_position ¡ş®ú‹ˆò>
5
(option_exercise_summary_call_after_hoursıãøŸŞ¹Í¤
4
'option_exercise_summary_put_after_hoursÓä°ÃŸô†üô
5
)option_exercise_summary_call_market_hoursıÍ¬–Ë­¶
5
(option_exercise_summary_put_market_hoursĞÑßÒ™âï•