
(
crypto_acats_label_continue‘§‘‚ §¿Ë
"
crypto_acats_label_okŸ¡Ô·øñª‹
(
crypto_acats_label_show_more½•Î¿éÆÚ•+
)
crypto_acats_label_show_lessµ´•âØçº‚¥
.
"crypto_acats_migration_intro_title„Æ±…‘ë˜-
4
(crypto_acats_migration_intro_descriptionÉİ«”ø·•Æ:
4
'crypto_acats_migration_ineligible_titleæ²›‚¶¨ôœ
9
-crypto_acats_migration_explainer_appbar_titleõ×µÀ…Ò¬©+
2
&crypto_acats_migration_explainer_titleÙÃİ¾ÈËµßl
5
)crypto_acats_migration_explainer_subtitle‘‹Ú®î•çú
8
,crypto_acats_migration_explainer_step1_titleò¤Â•Şú÷p
8
+crypto_acats_migration_explainer_step1_bodyÆ´åí“‚¤Øİ
9
,crypto_acats_migration_explainer_step2_titleş­ºûûà½¡¤
7
+crypto_acats_migration_explainer_step2_bodyºÇ†íÆúñ>
8
,crypto_acats_migration_explainer_step3_titlešÃ¤‰ï°Ìµ-
8
+crypto_acats_migration_explainer_step3_body…õêù½”È‰³
3
'crypto_acats_migration_explainer_footerÄäÁÊ¡ğã
*
crypto_acats_label_learn_more¬ƒ…ûòÎ™·ß
4
(crypto_acats_migration_assets_list_titleÎò¨àÃú±¿
8
+crypto_acats_migration_assets_list_subtitleò¹¨ã‹ÔÜêÓ
0
$crypto_acats_transferable_cash_titleØÎ®†¡Šîj
4
'crypto_acats_transferable_cash_subtitle«ÃíÔæ”¥«Š
3
&crypto_acats_transferable_crypto_titleæğØ¬Áö‘Â×
5
)crypto_acats_transferable_crypto_subtitleë‘¥ò—ÇÕşJ
4
(crypto_acats_non_transferable_cash_title³Ò­«Ó·Y
8
+crypto_acats_non_transferable_cash_subtitle›Â™¶ÄË½›”
6
*crypto_acats_non_transferable_crypto_title¬—Éù±¾¨‘
9
-crypto_acats_non_transferable_crypto_subtitleÒ”³ï®¦Äb
6
*crypto_acats_migration_submit_assets_titleö½ßªâ¬ß
:
-crypto_acats_migration_submit_assets_subtitle×’ñã±ˆü£
D
7crypto_acats_migration_submit_assets_transferable_titleÀÑËÌâ²ãæ
G
;crypto_acats_migration_submit_assets_non_transferable_titleäÎ¸ÎÒ‹¿F
=
0crypto_acats_migration_submit_asset_label_cryptoÇŞÄè’”•½
;
.crypto_acats_migration_submit_asset_label_cashòî€å¸œÚÓ
<
0crypto_acats_migration_submit_asset_label_assetsç¿•œÎ‡çõQ
.
"crypto_acats_label_submit_transferö½ßªâ¬ß
?
2crypto_acats_assets_list_transferable_crypto_titleæğØ¬Áö‘Â×
A
5crypto_acats_assets_list_transferable_crypto_subtitleë‘¥ò—ÇÕşJ
@
4crypto_acats_assets_list_non_transferable_cash_title³Ò­«Ó·Y
D
7crypto_acats_assets_list_non_transferable_cash_subtitle›Â™¶ÄË½›”
B
6crypto_acats_assets_list_non_transferable_crypto_title¬—Éù±¾¨‘
E
9crypto_acats_assets_list_non_transferable_crypto_subtitleÒ”³ï®¦Äb
,
crypto_acats_confirmation_titleŒ†“ºœ¦Î¿
1
%crypto_acats_confirmation_descriptionæ®«¸úùú¹V
2
%crypto_acats_confirmation_button_doneî’Ü¢²øğøÙ
9
-crypto_acats_confirmation_button_view_detailsş¨äÉë¶¼ñE
;
.crypto_acats_confirmation_fallback_error_titleæ²›‚¶¨ôœ
F
:crypto_acats_confirmation_fallback_error_message_try_againÕÒ¿àÕ¦³¡
&
crypto_acats_failure_titleàÅ¹»†…äİ
=
0crypto_acats_failure_contact_support_descriptionĞ–Ìÿ„Î®®
6
*crypto_acats_failure_try_again_description•õÛÑÓÆèy
7
+crypto_acats_failure_button_contact_supportÓà¹üÁãÕ
-
 crypto_acats_failure_button_doneî’Ü¢²øğøÙ