
4
(options_profit_loss_chart_analysis_titleñœ”·Äö»Ê+
-
 options_profit_loss_chart_profitÑÈ¡ÿŒıç„†
*
options_profit_loss_chart_lossÁƒ‹¨©²Y
/
#options_profit_loss_chart_breakevençûƒñö¹¢Ü,
/
"options_profit_loss_chart_expectedüü¬†î»º‰Î
1
$options_profit_loss_chart_learn_more––ÒÙ±‹éì
1
$options_profit_loss_chart_profit_nowò™÷À²ËØş
0
#options_profit_loss_chart_value_nowĞĞÅô¥Ÿï¨é
4
'options_profit_loss_chart_profit_at_exp‹êéÔÿ‚³÷œ
3
&options_profit_loss_chart_value_at_exp‚÷Æá½íÔ„Ÿ
A
5options_profit_loss_chart_condensed_value_at_exp_fullßòÃÎÕ¨²‚%
B
6options_profit_loss_chart_condensed_value_at_exp_label¹ªğº…¦öĞ
D
7options_profit_loss_chart_scrubbed_price_and_percentile‰şÚ¥ÔëÕ´œ
/
#options_profit_loss_chart_unlimited†×ıø£¬ìÍR
5
(options_profit_loss_chart_breakeven_joinÇ¼Ç¦ÒèÚï»