
=
1options_simulated_return_slider_symbol_price_textÖ×éÖ¹¤İ¸U
=
1options_simulated_return_slider_symbol_value_textíªÃ°Ä»‘Ç
E
9options_simulated_return_slider_current_symbol_price_textâ…ìø‚¡Ñ[
F
9options_simulated_return_slider_current_symbol_value_text·í¿íˆ®˜‚
>
1options_simulated_return_time_slider_primary_text‘Ÿ“Ê¡ò¤Û°
D
7options_simulated_return_time_slider_empty_primary_text¹Øİİ£«ÁÈı
K
>options_simulated_return_time_slider_secondary_text_expirationÙõ¨ìÉÛÉ›ü
M
@options_simulated_return_time_slider_secondary_text_current_timeÊóßŸÏ£Ä–
E
8options_simulated_return_time_slider_secondary_text_timeòœÃ„ÖÏ¸·ş
>
2options_simulated_return_time_slider_pill_text_nowáåÂşØÖÀÍ
>
2options_simulated_return_time_slider_pill_text_expåÓœ‘“Ïšì
C
7options_simulated_return_time_slider_pill_text_last_expÊÔ´¶©…^
;
/options_simulated_return_header_est_profit_lossÁê—â±üà-
>
2options_simulated_return_header_est_contract_price“™ÕÅ”Çµ÷y
>
2options_simulated_return_header_est_strategy_price¿çà»Š£ÈH
<
/options_profit_and_loss_header_max_profit_labelÑÈ¡ÿŒıç„†
9
-options_profit_and_loss_header_max_loss_labelÁƒ‹¨©²Y
:
.options_profit_and_loss_header_breakeven_labelçûƒñö¹¢Ü,
?
2options_profit_and_loss_header_breakeven_separatorÇ¼Ç¦ÒèÚï»
>
1options_simulated_return_estimated_contract_priceÀŞøæŒÓèï
=
1options_simulated_return_estimated_strategy_price¥Éİô“Ñù?
B
5options_simulated_return_switch_unit_icon_description†õ¬€Ó©ó
7
*options_simulated_return_learn_more_footerú±‘ôÍî¬áî
3
'options_profit_and_loss_unlimited_label†×ıø£¬ìÍR
9
,options_simulated_return_chart_general_error°è™À€®âÖ
P
Coptions_simulated_return_time_slider_secondary_text_num_of_positionİÙ°ÄÓ¡«ë¶