
*
order_type_dollar_based_titleõ±¹øÚ£¦è¼
)
order_type_share_based_titleúÔÚáùíš™ƒ
7
*order_create_error_sell_title_dollar_based·ùç„ü†şÓğ
=
0order_create_error_sell_no_amount_pending_orders”î öùÿÁœì
?
2order_create_error_sell_some_amount_pending_ordersÕÓóĞ–şß
:
.order_create_error_sell_no_amount_stock_grantsËĞ‡”©Üâc
<
0order_create_error_sell_some_amount_stock_grantsËÜù²³ÎêÌ 
=
0order_create_error_sell_no_amount_options_eventsˆ½ÙÂ¢†„ãÂ
?
2order_create_error_sell_some_amount_options_eventsÚèÇˆÛÌîÅç
I
=order_create_error_sell_no_amount_no_pending_multiple_reasons—Ù¾Ş•ŞÈ
J
>order_create_error_sell_no_amount_has_pending_multiple_reasons·à³š“°D
L
?order_create_error_sell_some_amount_no_pending_multiple_reasonsÔ”ŒıÇä‚
M
@order_create_error_sell_some_amount_has_pending_multiple_reasonsŞÊäé”ÌçÑ©
A
4order_create_fractional_input_error_below_one_dollarÁ½§™…¥¹¼é
9
-order_create_fractional_input_error_max_value¡ä´İÖƒã¤W
1
%not_enough_shares_pending_sells_label‰´ì±›ûè†
2
%not_enough_shares_stock_rewards_label¶‡‘Òÿ¯Öµ
7
*not_enough_shares_options_collateral_labelôÊöº¥‚ –
5
(not_enough_shares_pending_exercise_label©°©Ú³ÖñÌŞ
3
'not_enough_shares_sellable_shares_label®”¸¼”Îøl
-
!order_type_buy_orders_header_textÓÌ¢‚î‚×k
.
"order_type_sell_orders_header_text—Úüİ×ÍÊÀi
5
)order_type_conditional_orders_header_textˆ¬Õáóıº—
3
&order_type_limit_24_hour_market_header¾¦£Îâ™Ûİß
7
*order_type_limit_24_hour_market_header_sepèöÒÃŞáù‚Ò
2
%order_type_generic_orders_header_textã×Àæ€¥ˆ¥

side_label_short‡©¥´Î‚˜—d
#
side_label_buy_to_close˜´·«•ùì
%
order_extended_hours_yesºÀØ€«ÉùÿŞ
#
order_extended_hours_no…§èäïÕü½~
>
1order_create_advanced_current_estimated_ipo_priceä¸ÕÉÕ³ø§à
/
#order_create_advanced_ipo_bid_label×”»ğŸôÁ7
6
*order_create_advanced_ipo_bid_label_formatñµõÒ§‚Û®d
3
'order_create_trailing_amount_percentage«±™ÊÕŒü¡9
.
"order_create_trailing_amount_price«ĞîÔÁŒå×J
;
.order_create_trailing_amount_percentage_symbol“ï¼¾šì›
H
;order_create_trailing_amount_initial_stop_price_placeholderò‘šÎ¨¤¼µÆ
<
/order_create_trailing_amount_initial_stop_priceå¯şËä°©
2
%order_create_backup_withholding_labelóÆØ‰îçé»´
'
order_create_tax_lot_labelì’ú•Ô·»è
1
$order_create_edit_order_button_label“„Ò¬ª–ıëÆ
1
$order_create_advanced_ipo_bid_promptûì¢Õ‡…¶ÚÛ
0
#order_create_tick_size_dialog_titleöÙ×è‰ÆÙÏ
2
%order_create_tick_size_dialog_message·ñÁÅœâ´á
4
'order_create_trailing_type_dialog_titleÆÉ‚‰şù½èİ
D
8order_create_trailing_percentage_sell_dialog_description›ÚÉè“‰ V
@
3order_create_trailing_price_sell_dialog_description½ñ´¿ãß–ÿ
D
7order_create_trailing_percentage_buy_dialog_descriptionÕ”¹èË­é‚É
>
2order_create_trailing_price_buy_dialog_descriptionó×ÄÿæŞ°

order_create_titleÔ®ı¢‰ô…³
4
(order_create_gfd_expiration_suffix_today úÂ×ûû®E
8
+order_create_gfd_expiration_suffix_tomorrowşè ÙŞ–İĞ
0
$order_create_gfd_expiration_fallback÷Øš¿´¬İùR
(
order_create_gtc_expiration†ò„ƒªÓ³í
.
"order_create_trailing_amount_label«ĞîÔÁŒå×J
2
&order_create_trailing_percentage_label«±™ÊÕŒü¡9
*
order_create_error_sell_title§àÑù€Î¯œ
3
'order_create_error_sell_title_no_sharesùñ¥ç²úŞ°P
<
0order_create_error_sell_no_shares_pending_orders¶çÒ¨¶äµR
:
.order_create_error_sell_no_shares_stock_grantsÎó§ÔŠŸN
J
>gated_options_order_create_error_sell_no_shares_options_events“ıƒîĞ±¸
>
2order_create_error_sell_no_shares_multiple_reasonsçà÷Æóòˆ#
!
order_create_sell_allÔÍ®»Å»­ÎV
&
order_create_shares_labelÇŞ•¾í¨§¼å
*
order_create_total_cost_emptyâ°¯¹èˆÖ
,
 order_create_order_summary_labelÆ”£²¨‘ '
1
$order_create_queued_market_executionäƒÔ¡„èÙïÛ
6
)order_create_limit_market_hours_executionêÇîËéá±
7
+order_create_limit_extended_hours_execution£ç±¿úÇ›q
6
*order_create_limit_all_day_hours_executionš¯¬‚’»š´1
3
'order_create_stop_limit_price_execution›ÇêóïŸäÕ
8
+order_create_trailing_stop_amount_execution¨²Öı¦·®ı¨
2
&order_create_up_to_shares_with_pendingé¯ƒ¢¼¢äV
=
1order_create_info_sell_view_pending_orders_actionİ×úøËˆàÇ(
2
&order_create_info_sell_sell_all_actionÔÍ®»Å»­ÎV
/
"order_create_sell_all_button_labelÒ¥Â¹ŠŠÿ¶
&
order_create_warning_labelç„Î°¶û”d
+
order_create_warning_label_nra„¬˜¾ìÀ°
/
#order_create_warning_label_fallbackø˜¤üéé¥W
0
$order_confirmation_action_view_order•à§´ªÔÌ”
4
(order_confirmation_action_view_new_order ²ÕÜ¨›™~
?
2order_confirmation_action_set_recurring_investmentè¶Íï¢“äì¸
3
'order_confirmation_estimated_cost_labelè…˜œáµ±¦
5
)order_confirmation_estimated_credit_labelñÓ÷«¥™ÓŒA
/
#order_confirmation_estimated_shares¤´ÿ±ºèƒ§
7
*order_confirmation_average_price_per_shareÀöĞÌ—û‘á—
-
!order_confirmation_pending_sharesÔß«ú·ÏÛ“t
1
%order_confirmation_pending_cost_label±ÂøòòÔ»i
4
'order_confirmation_pending_credit_label±ëõŒ‹‡÷ˆ±
C
6order_confirmation_estimated_backup_withhholding_labelóÆØ‰îçé»´
G
:order_confirmation_estimated_backup_withhholding_label_nra²ù‰Ì´ìÎƒ
L
?order_confirmation_estimated_backup_withhholding_label_fallbackŠê¯¶Ã£³
8
,order_confirmation_backup_withhholding_label÷ÿÙÜÎŞ²Ñ7
<
0order_confirmation_backup_withhholding_label_nraº¹…÷úóßÿd
A
5order_confirmation_backup_withhholding_label_fallbackùìÃıûˆÑ7
-
 margin_upsell_negative_button_gbûÒãİ“êÂ™ü
$
order_notification_title¥ì¯­Ÿ´““>
%
order_notification_error£¼Åô¸ôÛÚÅ
(
order_review_status_received‡ŸøµÊ™Óøy
.
"option_order_view_education_actionÂÃİ¶¶£û­7
7
+twenty_four_hour_market_shares_dialog_titleŞË—ùüÙÙŞ	
D
7twenty_four_hour_market_shares_dialog_body_pacific_time÷ëÅ‚÷ô™ğ
7
*twenty_four_hour_market_shares_dialog_body¥Ğ¸§İÃ°Ş°
<
0twenty_four_hour_market_shares_dialog_pos_buttonÙ×Œ÷Ø’­l
<
0twenty_four_hour_market_shares_dialog_neg_button­Ó½Şşï½9
2
&limit_price_fragment_market_data_alertô‰îºéï½Ğ]
@
3limit_price_fragment_market_data_not_available_dashïäÁˆ‚É ˆˆ
G
;limit_price_fragment_market_data_not_available_dialog_title™£óßóÂ¨
I
=limit_price_fragment_market_data_not_available_dialog_messageÛ¯²µìúş‘1
+
only_limit_orders_dialog_titleÃàŠââ¯äÙ
,
 only_limit_orders_dialog_messageçáÒš£ö¹õc
/
"order_create_advanced_market_price‘è–³¿üÊŠ
+
order_create_advanced_bid_priceœ§ÊÓò…¨Ği
+
order_create_advanced_ask_price€öèê¦ªÊÑ
/
"market_buy_onboarding_tooltip_textäèÆÕóğÛğå
2
%market_buy_onboarding_tooltip_text_v2ÇéË¬‘÷‡¸ú


learn_more¬ƒ…ûòÎ™·ß
.
"upsell_enable_margin_enable_buttonÃßëÓ•øœ¡
/
"market_buy_onboarding_tooltip_link…Ÿ›Ê¾Õ²Äı
,
 tax_lots_onboarding_tooltip_text®»åáÖ°úP
$
trade_settings_row_titleÚªæ„Ààª|
2
%short_selling_unavailable_alert_title¢®‡ş¯ÂÅò
3
'short_selling_unavailable_alert_messageë†°§„È¡¬
?
2order_create_error_sell_some_shares_pending_ordersıöÇÙ…¨¦€
<
0order_create_error_sell_some_shares_stock_grantsß³ÙØ¬“¡=
>
2order_create_error_sell_some_shares_options_eventsë‰±×ÕÍ
A
4order_create_error_sell_some_shares_multiple_reasons£áŠŠÀ€±èû
%
order_create_up_to_shares ¡ş®ú‹ˆò>