
.
"settings_investment_schedule_title›§ éûøšÌ
9
,settings_investment_schedule_title_no_symbol£ÏĞ™âòÎŒÈ
8
,settings_investment_schedule_frequency_labeláØÌÕŸïîç	
>
2settings_investment_schedule_source_of_funds_label’ß„ãÒ±»÷
6
)settings_investment_schedule_amount_labelü•Ä¬İšÆÿ
5
)settings_investment_schedule_toggle_labelÂ€·¸ù…¢
?
3settings_investment_schedule_delete_investment_textµüÖªí¿Ö‚1
;
/settings_investment_schedule_delete_alert_title‹Ü°®ñó’‹U
E
9settings_investment_schedule_delete_alert_title_no_symbol‚ÏÕ´ş¬(
=
1settings_investment_schedule_delete_alert_messageÜ û·ô÷Úí,
C
6settings_investment_schedule_change_payment_method_cta€æÊ¯½œÜ®À
8
+settings_investment_schedule_update_now_ctaÈ•†âéÒú¦
:
.settings_investment_schedule_data_price_changeù‡Ë­Ë‘óÑL
D
7settings_investment_schedule_data_first_investment_date·«ñ‹¼Ü˜
7
+settings_investment_schedule_data_next_date–‚£©¬…¢ö7
F
:settings_paycheck_investment_schedule_data_next_date_valueÄ­†ãìüÃÓy
<
0settings_investment_schedule_data_total_investedòĞœ¸ğ¼âû
6
)settings_investment_schedule_state_active„İÜšÿ¬íˆ
8
+settings_investment_schedule_state_inactiveÿ‹í˜Ô§”öû
/
"settings_investment_schedule_savedöÖİ»»•îØ¬
B
6settings_investment_schedule_price_change_dialog_titleáá·¹ûüÈçS
[
Nsettings_investment_schedule_price_change_dialog_description_null_price_changeÏ¢–šë¥áÆ£
O
Csettings_investment_schedule_price_change_dialog_description_cryptoÕœ“¤¿¯£)
I
<settings_investment_schedule_price_change_dialog_description¹åÉ§ö‹üÊ‚
H
<settings_investment_schedule_insufficient_funds_dialog_title¿ÿ›òÆ¢
O
Bsettings_investment_schedule_insufficient_funds_dialog_descriptionŸÂ÷œ‹ÂŒ‰û
\
Psettings_investment_schedule_insufficient_funds_dialog_deposit_funds_button_textÄùğÀÂ¶§à(
e
Ysettings_investment_schedule_insufficient_funds_dialog_deposit_update_payment_method_textšÕôïº•ã
7
+settings_investment_schedule_backup_paymentÕ‘¥°“Û› 
<
/settings_investment_schedule_add_backup_paymentÅç¦ÎÚöúŸÑ
<
0settings_investment_schedule_edit_backup_paymentÈö˜ù˜†Ù’D
8
,settings_investment_schedule_retirement_typeÂâò–‘ƒû
>
1settings_investment_schedule_retirement_type_valeäå°µğ–šá
D
8settings_investment_schedule_retirement_tax_year_primary“ŠÛŒŞÎä¡4
F
:settings_investment_schedule_retirement_tax_year_secondary¾âüáú×Ï
"
past_investments_titleÖ¸·’„‰è
7
+settings_investment_schedule_insights_titleìâÇµ¬Ğİñ
A
5settings_investment_schedule_insights_title_no_symbol·½¬ç²ú¥
4
(settings_investment_pause_investment_btnê€ÕÃôƒÆ®O
7
*settings_investment_unpause_investment_btn³ÈÚÕ€µœí
3
&settings_investment_end_investment_btnÔÌ±áòò‰­§
=
1settings_investment_schedule_title_brokerage_cashÍ©°’Ë†²†%
M
Asettings_investment_schedule_title_traditional_ira_brokerage_cashÀòğ›ê÷„*
G
:settings_investment_schedule_title_roth_ira_brokerage_cash›âÜ¦‡®ÜÅ¸
>
1settings_investment_schedule_delete_transfer_textñ³ÕÀïîĞßÖ
A
5settings_investment_schedule_delete_contribution_textÊ²¾ÜÚ…µO
H
<settings_investment_schedule_delete_contribution_dialog_textŸ¡¨ëû÷‘V
L
?settings_investment_schedule_delete_transfer_dialog_cancel_text÷Áç©Öñş¢Œ
O
Csettings_investment_schedule_delete_contribution_dialog_cancel_text«ÆµµÀîĞâ)
:
-settings_transfer_schedule_delete_alert_titleğ·“¨¸Öè
=
1settings_contribution_schedule_delete_alert_titleÛâµè¡Ğë£F
;
/settings_transfer_schedule_delete_alert_messageŞíø®ÚİÑn
?
3settings_contribution_schedule_delete_alert_message§ò¹­ğ©„}
F
:settings_investment_schedule_insights_title_brokerage_cashğ¶ÔÀ×«Òş
V
Jsettings_investment_schedule_insights_title_traditional_ira_brokerage_cashœ£ĞáÚè« 
O
Csettings_investment_schedule_insights_title_roth_ira_brokerage_cashÕøÖ–¡¤¹À5