
2
&order_type_limit_order_buy_descriptionûé°ùÌ¥±Ÿv
9
-order_type_limit_option_order_buy_description£óÄÒ—¢š¾~
:
.order_type_trailing_stop_order_buy_description³Á‘®±ƒü÷l
1
%order_type_stop_order_buy_descriptionÇ¼®¬ªÙ¿Œa
9
,order_type_stop_order_sell_short_descriptionÂÈ·îƒ™ÙğÉ
7
+order_type_stop_limit_order_buy_description¯ìù‰¿¤îìT
>
2order_type_stop_limit_option_order_buy_description¤’Ì¥‡™£˜*
3
'order_type_limit_order_sell_descriptionÛ¦°©½­ŒØD
9
-order_type_limit_order_sell_short_descriptionÚÂ‚²çÛ¥é
:
.order_type_limit_option_order_sell_description‹ğÃï…Û>
M
@order_type_trailing_stop_order_sell_description_collaring_memberú¥”ÏÂ÷ÑÆ 
C
7order_type_stop_order_sell_description_collaring_memberŸâ’ïÔ„ƒÁM
8
,order_type_stop_limit_order_sell_descriptionäğ”§æ™C
?
3order_type_stop_limit_option_order_sell_descriptionÛ×‡Çıá„:
=
0order_type_disabled_stop_limit_order_descriptionØÎ¸êóÛÑİË
6
*order_type_recurring_order_buy_description¹¢³ôÈ™ÿá$
B
6order_type_recurring_order_buy_coming_soon_description±×öè ïÙå0
$
order_type_market_title“ÕöØããÉÛù
#
order_type_limit_title³ÙØÛ…µı÷
"
order_type_stop_titleĞïæûãıÍ§
'
order_type_stop_limit_titleí¶ñİÆèŞ¡d
*
order_type_trailing_stop_titleı®ä ²ÇäQ
+
order_type_market_title_optionsé‰È¿„˜é6
*
order_type_limit_title_options±¹“œÏ€Íl
/
#order_type_stop_limit_title_optionsÌüµÜØ…5
-
 order_type_recurring_order_title£ÏĞ™âòÎŒÈ
.
"order_type_shares_market_buy_title…İĞÎÙ½F
8
+order_type_shares_market_buy_to_close_title“ÕöØããÉÛù
4
(order_type_shares_market_buy_descriptionªÌ Çæ¼´>
=
1order_type_shares_market_buy_to_close_description©’Ñ¸‹Õ¢%
0
#order_type_shares_market_sell_title±…ã·çÆñˆ¾
6
)order_type_shares_market_sell_short_title“ÕöØããÉÛù
6
)order_type_shares_market_sell_descriptionëËÛ÷û‚–¾
;
/order_type_shares_market_sell_short_descriptionš£„–âı†T
+
order_type_tax_lot_title_shortì’ú•Ô·»è
$
order_type_tax_lot_title²Õçò©…˜‰
+
order_type_tax_lot_descriptionÜı¶Æ›û‘¤
1
%order_radio_button_good_for_day_titleÀßˆúªõ©
5
(order_radio_button_good_for_day_subtitleÌ’ªë½‘×
I
<order_radio_button_good_for_day_subtitle_with_extended_hours”ù”ÌëÈÚ
5
)order_radio_button_good_till_cancel_title„¸á£àù»ŒX
8
,order_radio_button_good_till_cancel_subtitle¥ôñîÛ‡’r
,
 disabled_order_type_dialog_titleºŸş„œ·ïª.
8
+recurring_disabled_error_dialog_description‹¿ô‘¹æ´Æ“
4
'short_position_error_dialog_description’á˜êÎÌ›°
4
(order_type_dollar_based_market_buy_titleîËƒïø¿ˆş)
2
&order_type_cash_based_market_buy_title‹å¢Ê•³ÿ·
5
)order_type_dollar_based_market_sell_titleë¹Ã‹í½â¹Q
4
'order_type_cash_based_market_sell_title´çºòÈÇÛ³”
:
-order_type_dollar_based_order_buy_description›šƒúß«¦òå
;
.order_type_dollar_based_order_sell_descriptionû¹Ì¨Û‚›è
3
&gated_options_order_options_hook_titleî£Å‚¶îû´
0
$gated_options_order_options_hook_ctaÚ’Âú¾q
4
'gated_options_uk_order_options_hook_cta¶ø¾ «ñ»”Œ
7
*order_configuration_stop_market_disclosure¢™ÏÛØõ©¾
@
3order_configuration_stop_market_disclosure_link_cta¬ƒ…ûòÎ™·ß

new_chipèÂûüÅå‡3