
3
&options_graph_late_close_info_tag_textšü­íŠ¾®Ôé
*
options_late_close_info_title÷Ç¦Çó¢ˆ—ñ
0
#options_late_close_info_descriptionøïÎƒŠÊóòÈ
2
%options_late_close_info_view_list_cta›Í¶ú¯äŞ
/
"options_late_close_info_disclosure†„¶ÏÑªüë·
3
&options_late_close_info_default_symbol¿Üšè’·ú
7
*options_late_close_info_default_late_close¢‘£¯Í‡“½ê
A
4options_late_close_info_default_extension_in_minutesî»ÍÕû°šĞ¾
9
,options_late_close_info_default_sellout_timeİø’áï¦ÆŒ
6
)options_late_close_announcement_card_textø–îıÜ•‰
8
+options_late_close_announcement_card_action²ñ¬ÄÓÜµ‹
7
*options_detail_page_position_section_title°öé†Åí‚¸
A
4options_detail_page_watchlist_position_section_titleùë´˜Ë¨õ¸
D
7options_detail_page_watchlist_position_section_subtitleôŠÂ°éÆ†ş
H
;options_detail_page_watchlist_learn_more_bottom_sheet_titleÕÅçâÓµÊ•«
J
=options_detail_page_watchlist_learn_more_bottom_sheet_messageê£ï±‰ìçÜ®
B
6options_detail_page_single_leg_position_quantity_label§éş’Ú©ê·M
A
5options_detail_page_multi_leg_position_quantity_labelğ±È“ÍÇP
<
0options_detail_page_position_current_price_labelÎØçõè™¨¹Q
<
/options_detail_page_position_average_cost_labelñ¸ŸášĞë¤µ
E
8options_detail_page_position_average_cost_label_asterisk’Õ„Ä¬º±
=
1options_detail_page_position_average_credit_label½Ò½Å£ß”ç"
G
:options_detail_page_position_average_credit_label_asteriskËÔòâí„°†
A
4options_detail_page_position_credit_when_added_labelìˆçß›ûª‘
>
2options_detail_page_position_cost_when_added_label¼¢÷óäé¾V
;
/options_detail_page_position_market_value_label„Î©¬¼Í²+
;
.options_detail_page_position_date_bought_label°ŸóıîŸ÷¢
9
,options_detail_page_position_date_sold_label‚ÓÆì¤àø¼¹
;
.options_detail_page_position_date_opened_label–Í“ìïûÓò
9
-options_detail_page_position_date_added_labelñ’½Æ‚³™û.
A
4options_detail_page_position_single_expiration_labelĞì©â–ç²ÌŞ
B
6options_detail_page_position_multiple_expiration_labelä­¹×†ã‹ŒT
?
2options_detail_page_position_breakeven_price_label®òÔçÿ›ıÌù
?
2options_detail_page_position_breakeven_value_labelğ„Û¸ÃšÄ°„
<
/options_detail_page_position_equity_price_labelµ›¤ÿ©Â®Ã
<
/options_detail_page_position_equity_value_label£‘ö“Â…£×é
<
/options_detail_page_position_today_return_label¯—Î¿áûİ
<
/options_detail_page_position_total_return_label×êˆ³ÎãÖó–
:
-options_detail_page_position_simulated_returnŸí‘Ÿ¨†Öô½
2
%options_detail_page_position_exerciseŠö²Œ×Îƒ´¡
A
4options_detail_page_position_portfolio_risk_analyzer—Û†‹Şµ§ñæ
4
'options_detail_page_stats_section_titleİø‡ßĞóÁŸ¨
*
options_detail_page_stats_markôôôø…ïÓğ
1
$options_detail_page_stats_last_tradeçŸÜå—Î¯›Ğ
(
options_detail_page_stats_ivË¤¡³è½‘A
5
(options_detail_page_stats_previous_close†ÿ­ñ¯ÊıÏ
*
options_detail_page_stats_highØåÊ¸¼ƒ[
*
options_detail_page_stats_low°†¦Ş¿Ó¶Íï
,
 options_detail_page_stats_volumeÒÒòÔ—÷ì0
3
'options_detail_page_stats_open_interest¹şÍĞ”ïş_
5
(options_detail_page_greeks_section_titleÈ¶ ‹ßš½éÄ
-
 options_detail_page_greeks_deltaÓ‡„±ù‘Œ²ë
-
 options_detail_page_greeks_gammaõ¦ÓÙñã‘ü
,
 options_detail_page_greeks_theta§ôÒôƒÇË6
,
options_detail_page_greeks_vega¿ÛğËÈòÎí
+
options_detail_page_greeks_rho¾Ö©½ˆà¿ÿÿ
6
)options_detail_page_options_section_titleõİñâ¬Ë¬•¿
6
)options_detail_page_history_section_title¸Âğ¨À¸è¶„
G
:gated_options_options_detail_page_index_curb_hours_tooltip°Â”µüÓÛÕò
.
!chart_settings_bottom_sheet_labelïÿÇ¼ò‚¬‚
*
chart_settings_type_label_adtşşŸ½ÂÏ¯·Ú
$
chart_settings_type_line¯ÄºŠå«ÓP
+
chart_settings_type_candlestickúâÆ‰Îô¯»O
1
%chart_settings_more_options_label_adtÊÈˆ˜¿ÚÕ'
3
'chart_settings_extended_hours_label_adtæ§‘«³ÕÁU