
+
crypto_tax_lot_short_term_labelïÃšƒÁ¿‚Ôa
+
crypto_tax_lot_long_term_labelÈ¶’›¤˜›“Ó
,
crypto_tax_lot_mixed_term_labelê²•ğÈìĞ…Ñ
.
!crypto_tax_lot_unknown_term_label…êàö¦¿†Úñ
C
6crypto_home_tab_fee_tier_status_current_fee_tier_title˜üÁÅüæĞ¬‡
@
3crypto_home_tab_fee_tier_status_next_fee_tier_title¿Ñ½ÖÚÆóéµ
@
3crypto_home_tab_fee_tier_status_lowest_current_tier˜üÁÅüæĞ¬‡
6
*crypto_home_tab_fee_tier_status_lowest_fee•”—½Ó½öÛ0
J
=crypto_home_tab_fee_tier_status_current_trading_volume_periodŞ¡Ê‡êéªç…
K
>crypto_home_tab_fee_tier_status_required_trading_volume_periodÔê×ï·ù“Ô“
8
,crypto_order_confirmation_account_name_label´­øû±éQ
U
Hcrypto_order_confirmation_buy_partially_filled_rest_canceled_description¸À¼ü¤ä¤œ²
U
Icrypto_order_confirmation_sell_partially_filled_rest_canceled_descriptionóµ¢Ãªğ±ÇG
C
6crypto_home_tab_fee_tier_status_expiration_banner_text¶’³¥„³³Âğ
M
@crypto_home_tab_fee_tier_status_projected_expiration_banner_text¶‹‰“¸™Ìÿş

general_label_buy¥¨×÷¢·˜£m

general_label_sellš•Î¾Úâh
*
crypto_order_type_market_labelé‰È¿„˜é6
)
crypto_order_type_limit_label±¹“œÏ€Íl
.
!crypto_order_type_stop_loss_labeläÕºØ·ÔÑéË
.
"crypto_order_type_stop_limit_labelÌüµÜØ…5
.
!crypto_order_type_recurring_label›Ş¢Ü›ì¨
-
 crypto_order_type_tax_lots_labelì’ú•Ô·»è
!
switch_currency_input“ÂÒø’ŞÜ¡.
9
-crypto_address_text_input_content_description·•¿¢ü¢ˆøP
@
3crypto_fee_unsupported_recurring_alert_dialog_title½×ÙÌò„¹Ç
K
>crypto_fee_unsupported_recurring_alert_dialog_text_volume_tierÇ„¡¹‘ÒÛ‰ÿ
C
6crypto_fee_unsupported_recurring_alert_dialog_continue‘§‘‚ §¿Ë
@
4crypto_fee_unsupported_recurring_alert_dialog_cancelÖï³¼Ì†€!
!
description_show_more½•Î¿éÆÚ•+
"
description_show_lessµ´•âØçº‚¥
-
!crypto_order_create_summary_titleÆ”£²¨‘ '
6
)crypto_order_header_negative_buying_powerÇëí™‹«Ú¬
3
&crypto_order_header_quote_buying_power•â³¨ÑÆöÊ¾
3
'crypto_order_header_asset_selling_power·Ûäóß“µŒq
4
'crypto_order_header_quote_selling_poweröœÒıˆ§Ö¤Â
,
 crypto_general_label_disclosuresÿ‡õóßÃõğ
/
"crypto_order_confirmation_cta_doneî’Ü¢²øğøÙ
8
,crypto_order_confirmation_view_order_details±Á…¼ûÑÃ¨I
3
'crypto_order_confirmation_status_queued¬„•Ğ‰†³,
9
-crypto_order_confirmation_status_queued_plainï€Â Èˆ…·
8
,crypto_order_confirmation_status_unconfirmedÿôÏ‡¹„â
?
2crypto_order_confirmation_status_unconfirmed_plain»æñªØ™á–
6
*crypto_order_confirmation_status_confirmed¹ìÜÔ†ˆ’
<
0crypto_order_confirmation_status_confirmed_plain¹¢º‡•ÿğ˜[
=
1crypto_order_confirmation_status_partially_filled€­ÿÂì¬"
M
@crypto_order_confirmation_status_partially_filled_rest_cancelled‚êÔ×ÕŒ€±¥
C
7crypto_order_confirmation_status_partially_filled_plainÜı˜êç£«‡
<
/crypto_order_confirmation_status_pending_cancelŸÕ€ğà‹ìë
A
5crypto_order_confirmation_status_pending_cancel_plainÙŠÖÊ‰Â…Ú#
3
'crypto_order_confirmation_status_filledÛä„½ÆÒ¢É`
:
-crypto_order_confirmation_status_filled_plainÂÀ²¯òÃëß
5
)crypto_order_confirmation_status_rejectedª ôòĞ¨¨æ&
<
/crypto_order_confirmation_status_rejected_plainœÏ¤Ì«Õ¨ŸÈ
5
)crypto_order_confirmation_status_canceled÷˜¾­Ÿõæˆ!
;
/crypto_order_confirmation_status_canceled_plainÜ”Š»Ê”º‡?
3
'crypto_order_confirmation_status_failedªÙòİ»ˆÄô
:
-crypto_order_confirmation_status_failed_plain€·¤À·¿
3
'crypto_order_confirmation_status_voidedÓ¦û’ÿÌŸİ
:
-crypto_order_confirmation_status_voided_plain²è¡Áø³½¬°
<
0crypto_order_confirmation_buy_queued_descriptionòª¿èÃÿÙÙ~
B
5crypto_order_confirmation_buy_unconfirmed_description¾ôŒ¤åŠº”¥
@
3crypto_order_confirmation_buy_confirmed_description³ğ¬‰Ï…†
E
9crypto_order_confirmation_buy_confirmed_description_limitğÂç¿†¢Ûâc
J
>crypto_order_confirmation_buy_confirmed_description_stop_limitÅë¼±ÅõÄÈ
F
:crypto_order_confirmation_buy_partially_filled_descriptionÑØÁÍĞ€ï®E
=
0crypto_order_confirmation_buy_filled_descriptionÕ“¸¸Ñ´È³Ñ
?
2crypto_order_confirmation_buy_rejected_description£³™¶¨ó«í
?
2crypto_order_confirmation_buy_canceled_description´·ùÉšİœ£ˆ
=
0crypto_order_confirmation_buy_failed_description¡İ¬åË©ÿÅ¡
>
1crypto_order_confirmation_sell_queued_description™×ĞòºÆ‰˜‚
C
6crypto_order_confirmation_sell_unconfirmed_descriptionşú”šù‚‹„€
A
4crypto_order_confirmation_sell_confirmed_descriptionÜ”‹ªëôµ€ê
G
:crypto_order_confirmation_sell_confirmed_description_limitÀ¸ıíóŒÂ
L
?crypto_order_confirmation_sell_confirmed_description_stop_limit‘Œ‹É«ÚÃÚ¿
H
;crypto_order_confirmation_sell_partially_filled_description«áİö¨’
=
1crypto_order_confirmation_sell_filled_descriptionïşßéõÓüÁ
@
3crypto_order_confirmation_sell_rejected_descriptionÃñèß™Ê‚‡¤
?
3crypto_order_confirmation_sell_canceled_description‹½¡¦Ã¨ÂÈB
=
1crypto_order_confirmation_sell_failed_descriptionİüúĞÔ¤Ü¯U
8
+crypto_order_confirmation_amount_label_costŸ°©ˆ´®¤‰
=
1crypto_order_confirmation_amount_label_total_cost£ºè—íñ¥œ
@
3crypto_order_confirmation_amount_label_total_creditİ‰¼İÛı—Áı
:
-crypto_order_confirmation_amount_label_credit«ª‚§¶—Ôğ
9
,crypto_order_confirmation_buy_quantity_labelîæë¸ÏÙÍ­¨
;
.crypto_order_confirmation_total_purchased_sold ¡±ÍÔÓª ö
6
*crypto_order_confirmation_estimated_crypto’ìÂŸºÕœ‘S
6
*crypto_order_confirmation_est_total_cryptoÄØêÍ¦Ç–À
3
'crypto_order_confirmation_average_priceÚÌï«îéÓÇo
6
)crypto_order_confirmation_estimated_priceö“€¥éÕÀ·†
1
%crypto_order_confirmation_limit_priceÛ€é‹ò¨í|
5
(crypto_order_confirmation_pending_cryptoòŠÎÆŞËúßª
6
*crypto_order_confirmation_bonus_percentageÃË¶ˆíšŠÎ
9
-crypto_order_confirmation_sell_quantity_labelÚ—µí¼€…ò9
<
/crypto_order_confirmation_partial_fill_quantityŠÊõİ¶Ûö£Î
:
.crypto_order_confirmation_estimated_cost_labelè…˜œáµ±¦
;
.crypto_order_confirmation_est_total_cost_label£š’ò¢›ğÑ
<
0crypto_order_confirmation_estimated_credit_labelñÓ÷«¥™ÓŒA
=
0crypto_order_confirmation_est_total_credit_label«¬¬©Øå¾®€
4
'crypto_order_confirmation_lots_selectedâçØÛ²È˜Ã
2
%crypto_order_confirmation_lots_filledĞñæ¦Î¶÷¡
.
"crypto_order_confirmation_est_gainü¿®²ÎÆû¸(
4
'crypto_order_confirmation_realized_gainŸ«îÌÆ¼şÉ£
.
"crypto_order_confirmation_est_loss°âöú¿ßŒ{
4
'crypto_order_confirmation_realized_loss©ùÉãŞ¦°˜Î
D
7crypto_order_confirmation_description_order_type_marketï¬Â ¥‰–İ´
C
6crypto_order_confirmation_description_order_type_limitÁöÇü˜¥Ú´
0
$crypto_order_confirmation_stop_price†  ÷³×ÏÒ^
F
:crypto_order_confirmation_description_order_type_stop_loss‰èª™…¶ò0
H
;crypto_order_confirmation_description_order_type_stop_limit•ä´×°á¨¸ò
J
=crypto_order_confirmation_buy_confirmed_description_stop_lossÇÔÓ¢¾ÂÍó˜
K
>crypto_order_confirmation_sell_confirmed_description_stop_lossğÆÍ¥´½ÒÙ£
4
(crypto_order_confirmation_quantity_labelğ±È“ÍÇP
5
)crypto_order_confirmation_purchased_label±¤¤¥à®ô¨T
0
$crypto_order_confirmation_sold_label­È¡‹Ø¿š£"
;
/crypto_order_confirmation_estimated_price_labelì¸¡»»¿¤½u
1
%crypto_order_confirmation_price_labelÂöÛ²Åâ±’j
;
.crypto_order_confirmation_estimated_total_cost£š’ò¢›ğÑ
0
$crypto_order_confirmation_total_cost£ºè—íñ¥œ
=
0crypto_order_confirmation_estimated_total_credit«¬¬©Øå¾®€
3
&crypto_order_confirmation_total_creditİ‰¼İÛı—Áı
2
&crypto_order_confirmation_fx_fee_labelºÏ‹…šñ¶ª(
,
 crypto_order_robinhood_fee_label–¨ã›ˆ›½“!
#
crypto_order_fee_label»êÀÅ‰‚´¬©
-
!crypto_order_fee_percentage_label¢¸¹ó´½ÓÀs
8
+crypto_order_estimated_fee_percentage_label‘Ô’¢÷¥•ñŒ
%
order_type_new_pill_labelèÂûüÅå‡3
.
!crypto_quick_trade_button_buy_allóéÑùî´…Çñ
.
"crypto_quick_trade_button_sell_allÔÍ®»Å»­ÎV
M
@saved_addresses_clipboard_icon_address_entry_content_description†É¼«‰éó‡
?
2crypto_settings_page_allowlisting_section_title_v2ãç´´Ş¿¢íÉ
B
5crypto_settings_page_allowlisting_section_subtitle_v2ëŞ„ÍÅ†ê±Ò
B
5crypto_settings_page_allowlisting_section_descriptionÒ‰‹âñí­”Ï
2
&enable_allowlisting_bottom_sheet_titleÜíûäèÆå
;
.enable_allowlisting_bottom_sheet_enable_button´÷å¼†ü£‡Ğ
3
'allowlisting_bottom_sheet_cancel_buttonÖï³¼Ì†€!
3
'disable_allowlisting_bottom_sheet_titleğòñ”ºª›ÜO
9
-disable_allowlisting_bottom_sheet_description¥ÁêÆ°«ííX
=
0disable_allowlisting_bottom_sheet_disable_button§¬ ÷ö‹–ıš
"
order_create_buy_title§†óË”ó¢
$
order_create_sell_title£ÇçÊºˆÊë