
0
#card_transaction_fraud_prompt_title¨£œ²ìî™¬È
1
%card_transaction_fraud_prompt_messageáÊ–”âéø!
:
-card_transaction_fraud_prompt_action_positiveÅî¡õËÇ…
:
-card_transaction_fraud_prompt_action_negative”æĞ˜™ÚÄ¼­
J
=card_transaction_fraud_action_result_card_locked_dialog_title˜»ÚÊ“¨ ¡Æ
K
?card_transaction_fraud_action_result_card_locked_dialog_messageïÿ´¬…Í®
Q
Ecard_transaction_fraud_action_result_card_locked_action_report_stolená¿‚ã‚Àö L
O
Bcard_transaction_fraud_action_result_purchase_enabled_dialog_title¥¡·â®ÕÊÇ
P
Dcard_transaction_fraud_action_result_purchase_enabled_dialog_messageäÅ¢ı£úˆ¦5
V
Jcard_transaction_fraud_action_result_purchase_enabled_action_card_settingsğÌ«œÈÃç¾N
0
#card_transaction_detail_view_reward•ÙØñÔà¢’
1
$card_transaction_detail_view_rewardsô°ç¼ºŒ¡íÄ
7
+card_transaction_detail_dispute_transactionÇÊŸış¾À5
2
&card_transaction_detail_dispute_cancelßÄ´ƒë­ºĞE
@
3card_transaction_detail_dispute_cancel_confirmation—°ÓÂèõ¾èÕ
8
,card_transaction_detail_dispute_cancel_error´Ññó—Éy
>
1card_transaction_detail_dispute_cancel_error_desc»¹ûöŒëèå
?
3card_transaction_detail_dispute_transaction_pendingË€†€ÑååÉH
D
8card_transaction_detail_dispute_transaction_pending_desc³í´ùÂ†æ¾
$
dispute_state_submitted·¯Ìò¥š—•ü
%
dispute_state_processingï³Í—ÃóÁÜŒ
.
"dispute_state_provisional_credited—™ÍŒĞµá;
'
dispute_state_not_creditedƒÛ™±óÑ½– 
#
dispute_state_credited§î‹‚èäÀ‹±
#
dispute_state_canceled’Ï“¢ÍÌ½îš
3
'dispute_state_desc_submitted_processing¦¨óı¡âƒ²
4
'dispute_state_desc_provisional_creditedöşÉûÉ·òš
,
dispute_state_desc_not_creditedÖ‹”¹¿òŞÕŒ
(
dispute_state_desc_creditedíŠÏŸï¥·ñõ
(
dispute_state_desc_canceledìîÔ˜•°«˜«
=
0dispute_reason_timeline_unauthorized_transaction¢ãğ¥÷ôÅå®
8
+dispute_reason_timeline_funds_not_dispensedÌÆ­ù’°µ„Ï
,
 dispute_reason_timeline_standard¡Ü®ÂËø‡J
.
"dispute_reason_funds_not_dispensedÆ†ÍÎÓ®ìÀ
+
dispute_reason_duplicate_chargeö€¶œ‡Óãh
.
!dispute_reason_incorrectly_billed‚óÔã½¡©ªå
'
dispute_reason_already_paid‘½»¥šßáµf
/
"dispute_reason_cancelled_recurringµå¯„Ñ¨â‡
-
!dispute_reason_goods_not_receivedş„äÖ´ÚâË+
%
dispute_reason_defectiveëáÚØ­€€¶
/
#dispute_reason_credit_not_processedªÂÃÑ”©¥9
3
'dispute_reason_unauthorized_transactionÒ†ßû¥İü¤
"
dispute_reason_unknown™ø°Ÿ®÷o
2
&dispute_row_view_single_section_headerã‹Ä´‰êóé
5
(dispute_row_view_multiple_section_header¬’Ö÷ğ”¸¶Ë
+
merchant_change_category_titleÀÆİ—š­öÒù
)
merchant_category_agricultureÍÉœ„Õ¼èq
0
#merchant_category_business_servicesıÑÆË›×Ê²Ì
$
merchant_category_diningÓˆõŞ»‡•÷O
+
merchant_category_entertainmentªÔÀšÕïZ
0
$merchant_category_financial_servicesË”‹ñ’¡Œ&
(
merchant_category_government°Ş‹’Õ¬•ºy
'
merchant_category_groceries¨¡Šİâ¿e
(
merchant_category_healthcare‚ééæ°ğØ„ 
#
merchant_category_otherËïçªâÆËç
&
merchant_category_shoppingŒ¹ˆ©‚¹ò
%
merchant_category_travelêùÚ°ü½Æı´
,
 merchant_category_transportationè¹ûû®ş£3
'
merchant_category_utilitiesÈŞœºñÂïc
 
rewards_sheet_titleä²“¥ØŞ‹ï
!
force_post_card_titleµ°®Úº³£ün
?
3force_post_card_before_deactivation_notice_physicalØ²ä½¢¼Ám
?
2force_post_card_before_deactivation_notice_virtualäªø–ıŞÍ‡”
5
)force_post_card_after_deactivation_noticeãâ³íŞÊçÂ3
-
!force_post_card_add_to_google_payïõ×Œà‚ÛS
*
force_post_card_use_google_pay‚æ‘â¤¹ËßI
-
 force_post_card_show_card_numberÕåôèÖ©Üí‘
"
days_remaining_default¡ò­¥éü„Ùb
*
rhy_transaction_detail_credit«ª‚§¶—Ôğ
(
rhy_transaction_detail_debitãè¢ø£«Õ˜\
-
 rhy_transaction_detail_completed¥ğ·äûĞş±
-
 rhy_transaction_detail_cancelled ¯º”¾ûİ¢
+
rhy_transaction_detail_pendingĞù‡ñå·¤ä
/
#rhy_transaction_detail_status_label±‰ë”ï÷
8
,rhy_transaction_detail_adjustment_type_labelÁÙÖ’ŞİŸ¾"
;
/rhy_transaction_detail_transaction_amount_labelòéóñƒì&
=
1rhy_transaction_detail_original_transaction_labelí»Ç‚¹¬‰•4
.
!rhy_transaction_detail_date_label³ëıÚß—‰ÏĞ
;
/rhy_transaction_detail_original_transaction_ctaªåä×òù¿’ 

days_remaining‚¡öŞÀ±’Û