
!
chart_settings_titleïÿÇ¼ò‚¬‚
(
chart_settings_style_headerşşŸ½ÂÏ¯·Ú
&
chart_settings_style_info¬ƒ…ûòÎ™·ß
-
 chart_settings_style_performanceÀ§ô„³Üµ¶
-
!chart_settings_style_contribution¶À×¥”ß×¨<
*
chart_settings_all_hours_headerş™š«áéÛ|
0
$chart_settings_all_hours_descriptionæ§‘«³ÕÁU
,
 chart_settings_benchmarks_headerç‘ØŞ³œ²„y
1
%chart_settings_benchmarks_header_info‘±÷ÿË¬Ñn
0
$chart_settings_benchmarks_header_newèÂûüÅå‡3
2
%chart_settings_benchmarks_header_edit¸–¡ÛÎ„™úó
6
*chart_settings_benchmarks_ftux_descriptionışÓ¤¥İ¯d
/
"chart_settings_benchmarks_ftux_cta©¤áè›½àµ¢
/
#chart_settings_benchmarks_empty_ctaî‘´†áÑŠR
"
benchmark_intro_title§Óª¤­™Û­í
>
1benchmark_intro_description_with_stock_etf_crypto¥©é¢³Ş™İİ
6
*benchmark_intro_description_with_stock_etf­‹¯ä‘Ø¨´
:
-benchmark_intro_description_with_stock_cryptoğÑğöıçğ±¾
2
&benchmark_intro_description_with_stock±Õí…¿¶öŒ
4
'benchmark_intro_description_with_cryptoŠçğ¿ã²ª†ÿ
'
benchmark_intro_disclosuresÿ‡õóßÃõğ

benchmark_intro_cta¯ùÊÎ¦Ô¤¡"
"
benchmark_search_save‘çÅİó±è ¨
7
+benchmark_search_hint_with_stock_etf_crypto‚Õ‚Õ¤ôËÿE
1
$benchmark_search_hint_with_stock_etfü¥”›Ú²ŒÍ
4
'benchmark_search_hint_with_stock_cryptoŠäÓ¹Ê›²—Í
,
 benchmark_search_hint_with_stock”¨ˆÜª»Ñî
#
benchmark_search_clearô½ïÿÀØ†ë
&
benchmark_search_selectedß¹‹ÒÊÓ§›
'
benchmark_search_select_rowı‰¥©úÄ½ŸM
)
benchmark_search_deselect_rowÃ˜ª¼î±«Ø%
"
benchmark_search_titleã«ì¤á¤³7
>
2gated_crypto_rhc_benchmark_search_hint_with_crypto—¢’áé¤ê…+
 
sort_positions_titleø²®„ÅŒP
%
sort_positions_ascending¥œÜÏî‡Å”‰
%
sort_positions_descendingŒÇüëºÏş