
*
backup_code_verification_title¶¢ƒøÚî€¾:
6
*backup_code_verification_input_placeholder˜ŸÒáêüÊ±S
4
'backup_code_verification_input_templateºãìë§ê£Ã¾
:
-challenge_verification_title_auth_app_default—éêİ‡µİÜ
.
"challenge_verification_title_emailƒ§›”í–Ñ¿1
=
0challenge_verification_subtitle_auth_app_default•˜²óòë ¯ú
5
(challenge_verification_input_placeholderÍ ¿†¼Ãª
C
6challenge_verification_auth_app_accessibility_talkback€¥œıœî¬±ã
2
%challenge_verification_input_templateŠÓ¥¬¸¼ÿÄõ
>
2challenge_verification_dialog_resend_message_email–ôÌßÁŞ£A
B
5challenge_verification_dialog_wrong_backup_code_titleï’Ÿ²´Ï×È¬
@
3challenge_verification_dialog_wrong_backup_code_msgÄ¿ëõ×¹¸ó¢
=
2uar_challenge_verification_help_bottom_sheet_titleõş°›—¥B
B
6challenge_verification_help_bottom_sheet_auth_subtitleÑ¸Ï§¦ê  Y
G
:uar_challenge_verification_help_bottom_sheet_auth_subtitleÂªğÏÎ
E
9uar_challenge_verification_help_bottom_sheet_sms_subtitleğ‹ŠĞ€‡ùî
S
Guar_challenge_verification_help_bottom_sheet_auth_recovery_sms_subtitleëÉıíæ’à&
C
7challenge_verification_help_bottom_sheet_email_subtitleëÉıíæ’à&
7
+challenge_verification_help_use_backup_codeô­ËÒ÷’«u
<
/uar_challenge_verification_help_use_backup_codeâš®Å™˜”æÙ
8
+challenge_verification_help_contact_supportÆ¸­¾šªìåË
@
4challenge_verification_help_update_authenticator_app„ß·çÜ³«ıo
;
/challenge_verification_help_update_phone_numberœÔÀ¼±ˆ•Öq
$
update_mfa_method_titleØ¾§¦ÀÅÇçÚ
'
update_mfa_method_subtitle¼°à§™¥šß›
0
#update_mfa_method_authenticator_appÊğÅ¾¦¡’ºÁ
+
update_mfa_method_text_messageÉÁ±äÉıÕã×
&
uar_log_out_dialog_messageÒ©Ğ»¿ŞÅ®>
2
%prompts_untrusted_need_help_btn_labelì—ù¸²¸•ã
7
*prompts_untrusted_challenge_complete_titleÀ™Íåè½Ò
.
"prompts_verification_waiting_title ™ÿØí¬ÙÔp
.
!prompts_verification_waiting_body¶¨…î¼ùâ÷Ñ
?
2gated_crypto_prompts_verification_waiting_body_rhc“Íœìö×èÔ
-
 prompts_verification_error_title©¶©ó×´§™›
+
prompts_verification_error_bodyúóã›ØåŞ!
/
"prompts_verification_timeout_title¼—ºß¢Î„„á
.
!prompts_verification_timeout_bodyÂÓê†ñ–¨¿Ó
-
!prompts_verification_denied_titleÜ´¾’ı‘\
,
 prompts_verification_denied_body¶ÀÅÙ›Ïì¶$
3
&prompts_verification_denied_login_bodyÛ€Öüş©±šî
2
&prompts_verification_your_other_device¾½ŞÃêË¼F
-
 prompts_verification_helper_textòìË²½ãî×
3
&prompts_verification_send_sms_cta_textË×¤„¶ÏÅµ
%
challenge_response_titleÈ“¹êåƒæ
3
'challenge_response_dialog_unknown_titleãÀ´û“õ¢«U
5
)challenge_response_dialog_unknown_messageù—¦·üœ’Ş6
5
(challenge_response_dialog_unknown_updateùô’¨Á“¼ä
&
challenge_response_summary˜Ä—¾½×ĞD
6
)challenge_response_summary_unauthed_email’•íÊ×®ˆ¸©
(
challenge_response_need_help»àÂ×–ïã¼2
2
&challenge_response_dialog_resend_titleâÚÊãË½©s
4
(challenge_response_dialog_resend_message¡¹¯œñ†£öG
C
7challenge_response_dialog_resend_message_unauthed_email™²úÀî˜ÿ§=
B
5challenge_response_dialog_resend_message_unauthed_smsÑ®èîÛÖæŠ¸
6
*challenge_response_dialog_wrong_code_titleÕÉ‚Æ¢û¡Ú]
8
,challenge_response_dialog_wrong_code_messageÂ´´îÆšá;
0
#challenge_response_replace_as_emailƒÉ«Òƒí‡‚¼
.
!challenge_response_replace_as_sms…½•Õÿ­ªÉœ
/
"challenge_response_no_access_emailÃÃõ¬•ç¼€¥
,
 challenge_response_no_access_smsŞåÇ§¡¤÷Ì
>
2challenge_response_dialog_attempts_exhausted_titleİİ¹¾Äçƒ
A
4challenge_response_dialog_attempts_exhausted_messageÒ·œßÚÙ‡ª¯
I
<challenge_response_dialog_attempts_exhausted_contact_supportÆ¸­¾šªìåË
3
'challenge_response_dialog_timeout_titleú£¿˜¼³Ğæf
6
)challenge_response_dialog_timeout_messageÁ½—Û½ÑñŞ‚
/
"email_sms_challenge_input_templateŠÓ¥¬¸¼ÿÄõ
2
%email_sms_challenge_input_placeholderÍ ¿†¼Ãª
3
&email_sms_challenge_bottom_sheet_titleì—ù¸²¸•ã
9
-email_sms_challenge_bottom_sheet_sms_subtitleºÍš°İÈ¤™
;
/email_sms_challenge_bottom_sheet_email_subtitle·ÊÀ°¹¸İàL
,
email_sms_challenge_resend_code’¢÷Öğçµ¬Ë
4
'email_sms_challenge_update_phone_numberÍìÛ­ÿ‰Ê
,
 email_sms_challenge_update_emailŒ¦ÖÎ€º©•L
7
*email_sms_challenge_phone_number_alternate…½•Õÿ­ªÉœ
0
#email_sms_challenge_email_alternateƒÉ«Òƒí‡‚¼
&
email_sms_challenge_cancelÖï³¼Ì†€!
,
 challenge_verification_title_smsê‡¨õÔ˜§ïD
:
-challenge_verification_subtitle_sms_logged_in›ªîí‘»…Ùô
;
.challenge_verification_subtitle_sms_logged_outæµÙÊúØ–ï·
5
)challenge_verification_response_need_help»àÂ×–ïã¼2
6
*challenge_verification_dialog_resend_titleâÚÊãË½©s
9
,challenge_verification_dialog_resend_message¸×€ÿ™ÇÍ›¾
F
9challenge_verification_dialog_resend_message_unauthed_smsÑ®èîÛÖæŠ¸
=
1challenge_verification_sms_accessibility_talkback€×‹ğäÕÀê.
C
7challenge_verification_dialog_resend_rate_limit_message¸º×Ç¦ãó§
:
.challenge_verification_dialog_wrong_code_titleÕÉ‚Æ¢û¡Ú]
8
,challenge_verification_dialog_wrong_code_msgÂ´´îÆšá;
B
6challenge_verification_dialog_attempts_exhausted_titleİİ¹¾Äçƒ
A
4challenge_verification_dialog_attempts_exhausted_msgÒ·œßÚÙ‡ª¯
7
+challenge_verification_dialog_timeout_titleú£¿˜¼³Ğæf
6
)challenge_verification_dialog_timeout_msgÁ½—Û½ÑñŞ‚
;
.challenge_verification_help_bottom_sheet_titleì—ù¸²¸•ã
4
'challenge_verification_help_resend_code’¢÷Öğçµ¬Ë
6
*device_approvals_challenge_resend_cta_textÅß§ç‡ÊÍß