
#
support_chat_list_titleêœÓ‹Ö´á£
0
#support_chat_list_empty_state_title³Äªä½ş–á…
3
&support_chat_list_empty_state_subtitleŒÓĞ˜µÂşÔ
2
&support_chat_list_static_preview_image¦û“¯ÒÕ_
2
%support_chat_list_static_preview_linkØê‚–ñæ†È
5
(support_chat_list_static_preview_loading÷´—ÌôäûØŠ
3
&support_chat_list_static_preview_error°ßçÇ˜şÈÛä
2
&support_chat_list_static_preview_empty€Ó÷ôñ–€õ>
#
a11y_support_chat_agent‹ÏİøÅÿİx
%
a11y_support_chat_chatbotèö²åÀœÎ6
)
a11y_support_chat_user_online¨İ”ø÷Êú½2
+
a11y_support_chat_user_offlineµ™œšöºıº–
+
support_chat_thread_input_hint°éêìÜ›Ö¦¦
9
-support_chat_thread_cancel_retry_dialog_titleàÅ¹»†…äİ
=
0support_chat_thread_cancel_retry_dialog_subtitleá¬Â§´’ºË×
A
5support_chat_thread_cancel_retry_dialog_positive_textàº²Û½‚‘Ça
A
5support_chat_thread_cancel_retry_dialog_negative_text¸ğ²ş°]
1
%support_chat_list_generic_error_titleàÅ¹»†…äİ
G
;support_chat_list_generic_error_no_support_chat_descriptionÛş¡­Ì…˜5
9
-support_chat_list_generic_error_positive_textàº²Û½‚‘Ça
F
9support_chat_thread_image_picker_icon_content_description­İòÒÚ¯‡¥
9
-support_chat_image_viewer_content_description¹ŞËàáƒğÀI
1
%support_chat_thread_push_prompt_title‡á¢›î”æ¶
4
(support_chat_thread_push_prompt_subtitle®½ÚáÑâé±7
9
-support_chat_thread_push_prompt_positive_text–òìÖ§î‘
:
-support_chat_thread_push_prompt_negative_textûÒãİ“êÂ™ü
,
 support_chat_thread_push_enabledïåâ™å·ÔÜK
"
chat_error_no_internet³šÅò×¥»
(
support_chat_resend_messageßÌ´éÉñ¬®
:
-support_chat_image_upload_option_image_picker÷˜×ˆÛ¢ÔÄ
4
'support_chat_image_upload_option_cameraãüï¶ıÔ‚×Ì
8
,support_chat_thread_image_error_dialog_titleàÅ¹»†…äİ
<
/support_chat_thread_image_error_dialog_subtitleÿ–‰¥ÚÉ‚›å
;
.support_chat_image_cropper_confirm_button_textØ³°ºá“Ş
B
5support_chat_thread_camera_access_denied_dialog_titleı‡” îôÄé°
E
8support_chat_thread_camera_access_denied_dialog_subtitleŸ¸¨¬±ìŠœ
J
=support_chat_thread_camera_access_denied_dialog_positive_text“à÷”ó°ƒ–É
>
1support_chat_thread_image_size_error_dialog_titleÜ‘¯Ô—Ô©Ú
A
4support_chat_thread_image_size_error_dialog_subtitleˆšËÆĞå’Ô
F
9support_chat_thread_image_size_error_dialog_positive_textºô»ìçËø…²
E
9support_chat_thread_image_size_error_dialog_negative_textÏéú¡¹Áö–
:
-support_chat_thread_original_image_fail_title£½áÏïåÌ½º
?
3support_chat_thread_original_image_fail_description­ƒßšäÊò­B
/
#support_chat_fullscreen_error_titleàÅ¹»†…äİ
6
*support_chat_error_retryable_error_messageøª‰úº½ıÛp
-
 support_chat_general_error_toast–¢ÖœŠ¨äÅĞ
3
'support_chat_thread_cancel_dialog_titleû‘Š•æ¨¬ÌJ
7
*support_chat_thread_cancel_dialog_subtitle¿­Ğã——×µä
;
/support_chat_thread_cancel_dialog_positive_textÿïÊë†éş£t
<
/support_chat_thread_cancel_dialog_negative_textÎ©Éò²Ì´
0
$support_chat_char_limit_dialog_titleÏ‰İı·¥é»X
/
#support_chat_char_limit_dialog_bodyë¬‡ÈœÉ©&
8
+support_chat_char_limit_dialog_primary_textŞÿø‚æÃƒì
(
support_chat_error_try_againàº²Û½‚‘Ça
%
support_chat_error_close«ûáÄ¢¬ß

support_chat_cancelÖï³¼Ì†€!
#
support_chat_nevermindçÂÆÏ¶•øÈ¶
(
chatbot_message_update_error­ÒûèİÚ®ıX
5
(chatbot_unrecoverable_error_dialog_titleÛ¼Ğ’øæÙà
4
'chatbot_unrecoverable_error_dialog_bodyí¿İÍŠ…–ÀË
<
/chatbot_unrecoverable_error_dialog_primary_text¦Ì—É²—ƒ–
>
1chatbot_unrecoverable_error_dialog_secondary_textÉº¸ú¿ƒûâÉ