
%
referral_detail_subtitle’ÂŠõ…Ì€úè
'
referral_detail_state_label±‰ë”ï÷
.
"referral_detail_reward_value_labelÄáê•®şŞ8
4
(referral_detail_backup_withholding_label÷ÿÙÜÎŞ²Ñ7
,
 referral_detail_net_credit_label‰µ´õ«¨Ô–h
'
referral_detail_date_label³ëıÚß—‰ÏĞ
'
referral_detail_cost_labelŸ°©ˆ´®¤‰
%
referral_detail_cost_freeŸ¡è©šØéĞg
1
$referral_detail_unsettled_disclosure°ñ—£è°Êé
+
acats_transfer_detail_subtitleøÄâ´á¸ãœ
'
acats_transfer_detail_titleò·Ö¤¹ñ½°S
1
$acats_transfer_detail_title_residualØ´‚Å¯»Üş
0
#acats_transfer_detail_title_reclaim¢ÓÇ‚¸¤¿‚±
.
"acats_transfer_detail_status_label±‰ë”ï÷
.
"acats_transfer_detail_broker_label³ª“Œ·²Ûš
6
*acats_transfer_detail_account_number_label©–ÆÆúó˜Æ$
,
acats_transfer_detail_eta_labelŠÃÊ¹ËÃ´‹ü
4
(acats_transfer_detail_arrival_date_label‡¼œ–üæè–)
8
+acats_transfer_detail_fees_reimbursed_labelèÆ ŒŸÑ³›·
6
*acats_transfer_detail_failure_reason_labelÊÄİê­–îñc
0
$acats_transfer_detail_reclaim_footerÓìÒ¹ÃñºÖ4
0
#acats_transfer_detail_cancel_actionŸÅÔ“˜ÚÍ•
0
$acats_transfer_detail_cancel_success‡áìüŞÓ…=
/
#acats_transfer_detail_cancel_failed¾¡ãâÆÄï=
4
'acats_transfer_detail_transferred_label…Û•‚Ï”Äç»
>
1acats_transfer_detail_transferred_label_reclaimed§¾¾Ö©§×…İ
4
(acats_transfer_detail_transferring_labelŠúò··Œ¾¢5
>
2acats_transfer_detail_transferring_label_reclaimedÁÒ¶ÔµË¬œl
9
,acats_transfer_detail_transferred_cash_labelòî€å¸œÚÓ
6
*order_detail_regulatory_fee_disclaimer_urlÅû§ˆëó¢z
1
%options_corporate_action_detail_titleõâÍ™½¸“‰C
0
#options_corporate_action_date_label³ëıÚß—‰ÏĞ
1
$options_corporate_action_state_labelôßµ‡ÖèŠóÿ
9
,options_corporate_action_num_contracts_labelÑ±Ğˆ¡ÛüÏ„
<
0options_corporate_action_num_contracts_label_old›ëæÓ©€Ò¹X
=
0options_corporate_action_num_contracts_label_new ¥³“«´“¸ì
7
+options_corporate_action_strike_price_labelÃœÛ¨ê„Û°\
<
/options_corporate_action_strike_price_label_oldÖ¦üÌ¤ÅÂá
<
/options_corporate_action_strike_price_label_newœàÕÚ‘Ğ‡Í
6
)options_corporate_action_expiration_labelĞì©â–ç²ÌŞ
9
-options_corporate_action_expiration_label_old°’ŒÔŸúÏ‰"
:
-options_corporate_action_expiration_label_new„¬¦òÄÁØ
5
(options_corporate_action_underlier_label¤Ìªó¥í‹³ò
9
,options_corporate_action_underlier_label_old§‡àÿËÃóÌÔ
9
,options_corporate_action_underlier_label_newİ‹…¼€Ã«é
:
-options_corporate_action_cash_component_labelÛãñİé‚ê¹
>
1options_corporate_action_cash_component_label_oldğÜ—“íª©°½
>
1options_corporate_action_cash_component_label_new²¸²ÇÉ¾™
5
)options_corporate_action_multiplier_labelŞ¤õ”îáÌ®w
9
-options_corporate_action_multiplier_label_oldı¾óïÿüÂõx
9
-options_corporate_action_multiplier_label_newçï‘Ë±àÜ¡!
6
)margin_subscription_fee_detail_date_label­Ø¤á±µãâ
6
)margin_subscription_fee_detail_cost_labelŸ°©ˆ´®¤‰
8
+margin_subscription_fee_detail_credit_label«ª‚§¶—Ôğ
6
*margin_subscription_fee_detail_total_labelÌØãŞí…Èx
=
0margin_subscription_fee_refund_detail_date_label³ëıÚß—‰ÏĞ
?
2margin_subscription_fee_refund_detail_amount_labelü•Ä¬İšÆÿ
6
)margin_interest_charge_payment_date_labelãôİºè‰Ö…ø
6
*margin_interest_charge_billing_cycle_label¾öÁùàÏp
1
$margin_interest_charge_billing_cycle°¶Ãˆä®îè
9
,margin_interest_charge_avg_margin_used_labelÑŸ‡ƒüÛ’
>
1margin_interest_charge_yearly_interest_rate_labelª×îâüËÙä½
7
+margin_interest_charge_total_interest_label’ˆ§¥²ˆ­“
0
#margin_interest_charge_credit_label«ª‚§¶—Ôğ
3
'margin_interest_charge_total_paid_label†»Ãùì«°øn
/
"margin_interest_charge_description®ûÁ‡‚–€ˆ
/
"ach_transfer_detail_instant_headerğ¡—İˆî°îø
7
*ach_transfer_detail_instant_header_managedğÎ‘šøÀ¶¶ã
6
)ach_transfer_detail_initiated_date_header­Ø¤á±µãâ
>
1ach_transfer_detail_estimated_availability_headerŠÃÊ¹ËÃ´‹ü
4
'ach_transfer_detail_last_updated_headerÙÅ†û¾¨Ê
4
(ach_transfer_detail_bonus_removal_header‰â´“¡ÓÄ§
-
!ach_transfer_detail_status_header±‰ë”ï÷
.
!ach_transfer_detail_cancel_actionŸÅÔ“˜ÚÍ•
B
5ach_transfer_detail_pending_recurring_instant_summary¸ÏÃ¤ŞÑ¦Ï›
@
4ach_transfer_detail_pending_cancellable_deposit_infoäœ½½ÜÏæ@
M
@ach_transfer_detail_deposit_pending_not_cancellable_deposit_infoàí†¥•‘¥®”
6
)ach_transfer_detail_canceled_confirmation¸²õÄÔœ…†
1
$ach_transfer_detail_reversal_messageŸïù‚—Äš£í
7
*ach_transfer_detail_reversal_reason_suffix«Ò©…ƒ¼ûøË
;
.ach_transfer_detail_reversal_suspended_summaryùüÊÉ­íŞö†
@
4ach_transfer_detail_reversal_pending_deposit_summaryûóÎ’ÈùÓ)
;
.ach_transfer_detail_reversal_in_review_summaryïĞ’¯³§±ô
9
,ach_transfer_detail_reversal_revoked_summaryÄÙ¸óğ„Âõ¼
1
%ach_transfer_detail_in_review_summaryá¬§µ“Ô­ÆO
7
+ach_transfer_detail_action_required_summaryé¦× š°›Ã	
6
*non_orig_ach_transfer_history_title_creditÁ§ïÛÎ£d
6
)non_orig_ach_transfer_history_title_debit•¬ÍÀ­ÆÏÏñ
7
*non_orig_ach_transfer_detail_amount_headerü•Ä¬İšÆÿ
4
(non_orig_ach_transfer_detail_from_headerœØŒ˜¤Ü®*
3
&non_orig_ach_transfer_detail_to_header¾„»û°ù’°Â
<
0non_orig_ach_transfer_detail_granted_date_headerÙ·Œı»­ìj
?
2non_orig_ach_transfer_detail_initiated_date_header­Ø¤á±µãâ
B
5non_orig_ach_transfer_detail_last_updated_date_headerÙÅ†û¾¨Ê
6
*non_orig_ach_transfer_detail_reason_headerœ›‘­¨Š˜¯Y
6
*non_orig_ach_transfer_detail_status_header±‰ë”ï÷
8
+non_orig_ach_transfer_detail_status_pendingĞù‡ñå·¤ä
:
-non_orig_ach_transfer_detail_status_completed¯‘Ø‘ ·œ†
9
,non_orig_ach_transfer_detail_status_rejected¼ÆÜŞÙ×ğ®ê
9
,non_orig_ach_transfer_detail_status_reversed¨œİÀÓÚì”Û
0
#dividend_drip_status_enabled_buttonÃß¦æ€åÔö¾
0
$dividend_drip_status_disabled_buttonš€Ÿ¦ôöé$
%
drip_history_upsell_titleš€Ÿ¦ôöé$
+
drip_history_upsell_descriptionÁ»íïÕÂª®|
0
#drip_history_upsell_positive_buttonƒ”çÿüğû°Ÿ
(
drip_history_help_center_urlŠÃ Ø™™Àào
*
drip_history_learn_article_url­¡¡ßóÆÖÇ
&
sweep_payment_detail_titleö¹ğşİ¡™‹
/
#sweep_payment_detail_account_header´­øû±éQ
/
"sweep_payment_detail_amount_headerü•Ä¬İšÆÿ
:
.sweep_payment_detail_amount_backup_withholding÷ÿÙÜÎŞ²Ñ7
2
&sweep_payment_detail_amount_net_credit‰µ´õ«¨Ô–h
0
$sweep_payment_detail_pay_date_headerˆ©¹©Îçï÷i
7
*sweep_payment_detail_payment_reason_headerÀÕº¹ÀÅè±ª
(
sweep_payment_detail_footerë‡¥çÌéÂª
5
)sweep_payment_reason_end_of_month_payment¯ÿñù€ğ´«

7
*sweep_payment_reason_sweep_program_opt_outÊíƒÊŠ´ğÌ
5
)sweep_payment_reason_program_bank_opt_out»®©¶á³ß…
E
8sweep_payment_reason_unidentified_early_interest_paymentÀ‹ …ŞšÑˆµ
8
,sweep_payment_reason_payment_reversal_credit¬åæĞ²›Î˜$
7
+sweep_payment_reason_payment_reversal_debitü…Œ—à°Â”,
E
9investment_schedule_event_ach_reversed_and_order_executedÑÂÍõ›–¯\
9
,investment_schedule_event_ach_order_canceled¹†ğÀªÚì÷°
'
check_payment_primary_title‚²®ã¡¸ÄS
0
$check_payment_detail_label_recipienté¦¡Ö‰€‡är
7
*check_payment_detail_label_mailing_addressÜñÖƒàª†¡
-
!check_payment_detail_label_status±‰ë”ï÷
1
$check_payment_detail_label_submitted·¯Ìò¥š—•ü
9
,check_payment_detail_label_estimated_arrivalá§ÌÉÒ­âƒ„
4
'check_payment_detail_label_check_amountÀŒŸ©äéå’
+
check_payment_detail_label_memoÆ´¢·¢ĞÒ”9
.
!check_payment_detail_cancel_checkß§³‚¯½»£
2
&server_driven_order_detail_edit_buttonşÚíÎÈÉ­ªl
5
(server_driven_order_detail_cancel_buttonš‡ŞØ¥ĞĞå
@
4server_driven_order_detail_trade_confirmation_buttonŸš‡™¤ÇÒ*
?
3instrument_split_payment_detail_date_recieved_label–ª°ë³Ëõ>
@
4instrument_split_payment_detail_split_quantity_labelÎ›Ö©ª‰‚7
B
5instrument_split_payment_detail_previous_shares_labelØ—Ä¼•ÏÓ–½
=
0instrument_split_payment_detail_new_shares_labelÔ–”ğş˜®ìí
6
)instrument_split_payment_detail_info_text«ĞØ“ºòà–¤
:
.instrument_split_payment_detail_info_link_text©öŠÈóÁd
:
-instrument_split_payment_detail_info_link_urlÖ†½„š¶Ô¶š
 
roundup_detail_title©ŞÆáá±é>
)
roundup_detail_roundup_periodÑ–¯¾ÚÄˆÙ
0
#roundup_detail_roundup_period_value÷Ö‹ğ®Í‰Ü
)
roundup_detail_roundup_amountîóÇğÆ““ÿo
)
roundup_detail_total_investedòĞœ¸ğ¼âû
(
roundup_detail_bonus_percentì¨îÁ˜ÒÕb
/
"roundup_detail_bonus_percent_value·²©ˆÈóºí
$
roundup_detail_bonus_maxÓéÂ™ğ¦îÀL
'
roundup_detail_bonus_amountÏÖæ¨³š¿ğb
,
 roundup_detail_view_transactionsúŞ³¤šèûç)
3
&roundup_detail_skip_order_dialog_titleÍÏö¤³Š¦‘¡
5
(roundup_detail_skip_order_dialog_messageÀ–§ÅìÛì‡
;
/roundup_detail_skip_order_dialog_primary_actionéûØùñûî~
9
-roundup_detail_bonus_amount_info_dialog_titleÏÖæ¨³š¿ğb
;
/roundup_detail_bonus_amount_info_dialog_messageƒ«¸Öƒ¢á+
*
instant_transfer_detail_titleŸ´€Ğ¡ÃĞŞ
,
instant_transfer_debit_subtitle¿ÀÙ€üÈüÁ¨
,
 instant_transfer_credit_subtitleÏ£å“Â½Şíf
(
debit_card_amount_row_titleÓâÍÃ•ûú»

rfp_title_pendingá¸ò©Í°ìı.
(
rfp_sending_payment_requestÅÂåÓÛËÄ
*
rfp_complete_transfer_at_bank“½‹¼Ê˜Âò¹
2
&rfp_complete_transfer_at_bank_metadata©şßìÂªù(
!
rfp_deposit_completedÛÛõË”È¥Â@
*
rfp_deposit_completed_metadataÃø†ÇĞ¯¿×H
 
rfp_disclaimer_text‰Òµÿ½†³—
$
rfp_payment_request_sentÔ­­ç×Ü‡?

rfp_status_header±‰ë”ï÷

rfp_from_headerœØŒ˜¤Ü®*

rfp_to_header¾„»û°ù’°Â
'
rfp_requested_amount_headerÈÂÇ¦Ç¹î›<
!
rfp_initiated_header­Ø¤á±µãâ
$
rfp_last_updated_headerÙÅ†û¾¨Ê
#
rfp_sub_header_details›Ï“öù…¨ğô
0
#rfp_multiple_acceptances_disclosure¬È¹Ê€Š”
=
0rfp_multiple_acceptances_view_transfer_clickableÆñÉ€İ£°”ä
"
rfp_expired_disclosureÁÎÙĞôØ,
+
rfp_requested_amount_disclosureŠëñº’¶£ám
/
"dividend_detail_short_charge_alert¯»¿†èî˜”
9
,dividend_detail_short_charge_learn_more_link½ÔøµÀ„­¶Ş
7
*history_detail_menu_item_title_view_symbolå…¯á„¸˜ç—
&
history_account_used_title´­øû±éQ
&
order_detail_cancel_actioné†Éï‹•Îù~
7
+order_detail_view_trade_confirmation_actionŸš‡™¤ÇÒ*
<
0order_detail_order_canceled_confirmation_messageÜ”Š»Ê”º‡?
)
merchant_reward_detail_status±‰ë”ï÷
/
#merchant_reward_detail_amount_title¦èœÕ±·ˆ
0
$merchant_reward_detail_percent_titleƒÄ¢²ŠíìD
1
$merchant_reward_detail_unknown_titleÿô‹‰æâÊ¶ë
3
'merchant_reward_detail_view_transactionı•µáµ‰q
/
"merchant_reward_detail_view_reward•ÙØñÔà¢’
-
!merchant_reward_detail_view_offer´„£ô‚¡÷ğ
1
$merchant_reward_detail_state_pendingĞù‡ñå·¤ä
1
%merchant_reward_detail_state_completeıÈŠ»æÉÍ
=
1merchant_reward_detail_state_pending_dialog_titleÛåÃ—ÄãŸĞq
@
3merchant_reward_detail_state_pending_dialog_message¨ôšã¬Î‘Ú“
0
$dividend_detail_scheduled_date_labelÉÑı…ßˆµ
(
dividend_detail_status_label±‰ë”ï÷
/
#dividend_detail_num_of_shares_labelËãñàÆôW
3
&dividend_detail_amount_per_share_label›•ôóçµ—ªƒ
.
"dividend_detail_backup_withholding÷ÿÙÜÎŞ²Ñ7
+
dividend_detail_amount_withheldÿÌà”‚šÎ¹u
.
"dividend_detail_total_amount_labelï´ÊÃåÎğ{
6
)dividend_detail_reinvestment_amount_labelš÷Ê»”òÖ¡ü
6
)dividend_detail_reinvestment_amount_valueõ ³Âç§Àƒ¤
1
%dividend_detail_timeline_announcement•¥ô’Ş¬ÆñL
6
)dividend_detail_timeline_dividend_paymentå‰¯ŠªåÔ´Å
;
.dividend_detail_timeline_dividend_reinvestment–·¾Ç´©…§
5
)dividend_detail_timeline_status_confirmedû°¼·Å”âÇO
4
'dividend_detail_timeline_status_pendingĞù‡ñå·¤ä
0
$dividend_detail_timeline_status_paid¯â»½òû¢é|
2
&dividend_detail_timeline_status_voidedÕù´ø˜§ÛŠ
5
(dividend_detail_timeline_status_reversed¨œİÀÓÚì”Û
3
&dividend_detail_timeline_status_filledåãÓáºµ¨Îæ
6
)dividend_detail_timeline_status_cancelled ¯º”¾ûİ¢
4
'dividend_detail_timeline_status_skipped â˜„ÙàÊôø
)
dividend_detail_reverted_desc«¤™ú•Ñˆy
-
!dividend_detail_drip_alert_headerìŞªœô²ï€J
-
!dividend_detail_drip_alert_voidedÔ¢ßÆÑœ†v
0
#dividend_detail_drip_alert_reversedƒÓÌÕè‰Ëçù
?
2dividend_detail_drip_alert_reversed_drip_cancelled®ê®•½°ºáÍ
5
)dividend_detail_drip_alert_drip_cancelledš×”ÑîÑä«l
I
=dividend_detail_drip_alert_drip_cancelled_account_restriction«™áûªšğøI
M
@dividend_detail_drip_alert_drip_cancelled_fractional_tradabilityÛÛ¯²£·µ‚Ö
P
Cdividend_detail_drip_alert_drip_cancelled_insufficient_buying_power½¡¹Àæ®ôÖü