package kotlinx.parcelize;

import kotlin.Metadata;
import kotlin.Standard2;

/* compiled from: Parceler.kt */
@Metadata(m3635d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0000\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002¨\u0006\u0003"}, m3636d2 = {"Lkotlinx/parcelize/Parceler;", "T", "", "parcelize-runtime"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
/* loaded from: classes14.dex */
public interface Parceler<T> {

    /* compiled from: Parceler.kt */
    @Metadata(m3637k = 3, m3638mv = {2, 1, 0}, m3640xi = 48)
    public static final class DefaultImpls {
        public static <T> T[] newArray(Parceler<T> parceler, int i) {
            throw new Standard2("Generated by Android Extensions automatically");
        }
    }
}
