package com.robinhood.android.debug.registry.provisions;

import android.net.Uri;
import com.plaid.internal.EnumC7081g;
import com.robinhood.android.acats.contracts.AcatsIn;
import com.robinhood.android.ach.contracts.AchRelationshipDocumentRequestSource;
import com.robinhood.android.ach.contracts.AchRelationshipDocumentVerification;
import com.robinhood.android.crypto.contracts.CryptoOrderIntentKey;
import com.robinhood.android.cryptogifting.contracts.CryptoGifting;
import com.robinhood.android.navigation.app.keys.LegacyIntentKey;
import com.robinhood.android.navigation.app.keys.data.ChooseAddressSource;
import com.robinhood.android.navigation.keys.IntentKey;
import com.robinhood.android.onboarding.contracts.GenericSdFlowIntentKey;
import com.robinhood.android.onboarding.contracts.OnboardingUpsellIntentKey;
import com.robinhood.android.onboarding.contracts.PostSignUpIntentKey;
import com.robinhood.android.onboarding.contracts.PostUserCreationShimIntentKey;
import com.robinhood.android.productupsell.contracts.ProductUpsellKey;
import com.robinhood.android.questionnaire.p219db.QuestionnaireContexts;
import com.robinhood.android.resumeapplication.ResumeApplication;
import com.robinhood.android.resumeapplication.ResumeApplicationFixtures;
import com.robinhood.android.transfers.contracts.AchTransferIntentKey;
import com.robinhood.android.transfers.contracts.Transfer;
import com.robinhood.android.transfers.contracts.TransferConfiguration;
import com.robinhood.android.transfers.contracts.TransferV2;
import com.robinhood.android.transfers.contracts.transfercontext.TransferContext;
import com.robinhood.iso.countrycode.CountryCode;
import com.robinhood.models.api.ColorTheme;
import com.robinhood.models.api.ReferralLandingSdui;
import com.robinhood.models.api.bonfire.ApiTransferAccount;
import com.robinhood.models.api.bonfire.ResumeApplicationResponse8;
import com.robinhood.models.api.bonfire.transfer.TransferDirectionV2;
import com.robinhood.models.api.identi.ApiDocumentRequest;
import com.robinhood.models.crypto.p314db.CurrencyPair;
import com.robinhood.models.p320db.EquityOrderSide;
import com.robinhood.models.p320db.TransferDirection;
import com.robinhood.models.p355ui.DocumentRequest;
import com.robinhood.models.serverdriven.experimental.api.AccessibilityModifier;
import com.robinhood.models.serverdriven.experimental.api.AspectRatioRemoteImage;
import com.robinhood.models.serverdriven.experimental.api.BookCoverText;
import com.robinhood.models.serverdriven.experimental.api.BookCoverTextStyle;
import com.robinhood.models.serverdriven.experimental.api.Button;
import com.robinhood.models.serverdriven.experimental.api.ButtonType;
import com.robinhood.models.serverdriven.experimental.api.Decorator;
import com.robinhood.models.serverdriven.experimental.api.DeeplinkAction;
import com.robinhood.models.serverdriven.experimental.api.Font;
import com.robinhood.models.serverdriven.experimental.api.GoldShimmer;
import com.robinhood.models.serverdriven.experimental.api.GutterBehavior;
import com.robinhood.models.serverdriven.experimental.api.Icon;
import com.robinhood.models.serverdriven.experimental.api.InfoTag;
import com.robinhood.models.serverdriven.experimental.api.InfoTagType;
import com.robinhood.models.serverdriven.experimental.api.OnboardingWelcomeTakeoverAction;
import com.robinhood.models.serverdriven.experimental.api.PlainText;
import com.robinhood.models.serverdriven.experimental.api.RegexValidator;
import com.robinhood.models.serverdriven.experimental.api.Size;
import com.robinhood.models.serverdriven.experimental.api.Sizing;
import com.robinhood.models.serverdriven.experimental.api.SubmitFormAction;
import com.robinhood.models.serverdriven.experimental.api.Text;
import com.robinhood.models.serverdriven.experimental.api.TextAlignment;
import com.robinhood.models.serverdriven.experimental.api.TextInput;
import com.robinhood.models.serverdriven.experimental.api.TextInputValidators;
import com.robinhood.models.serverdriven.experimental.api.TextStyle;
import com.robinhood.models.serverdriven.experimental.api.TextValidationType;
import com.robinhood.models.serverdriven.experimental.api.Tooltip;
import com.robinhood.models.serverdriven.experimental.api.UIComponent;
import com.robinhood.referral.OnboardingTakeoverIntentKey;
import com.robinhood.shared.crypto.contracts.CryptoTransferIntentKey;
import com.robinhood.shared.crypto.contracts.CryptoTransferSelectionIntentKey;
import com.robinhood.shared.crypto.contracts.lib.TradeAction;
import com.robinhood.shared.debug.lib.registry.config.Configuration;
import com.robinhood.shared.documents.contracts.DocUploadAssistant;
import com.robinhood.shared.questionnaire.contracts.Questionnaire;
import com.withpersona.sdk2.inquiry.network.core.HttpStatusCode;
import java.math.BigDecimal;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import kotlin.Metadata;
import kotlin.Tuples2;
import kotlin.Tuples4;
import kotlin.collections.CollectionsKt;
import kotlin.collections.SetsKt;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;
import kotlin.jvm.internal.Reflection;
import kotlin.reflect.KClass;

/* compiled from: IntentKeyRegistry.kt */
@Metadata(m3635d1 = {"\u00000\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\"\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\bÀ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0016\u0010\u0004\u001a\n \u0006*\u0004\u0018\u00010\u00050\u0005X\u0082\u0004¢\u0006\u0002\n\u0000R1\u0010\u0007\u001a\"\u0012\u001e\u0012\u001c\u0012\f\u0012\n\u0012\u0006\b\u0001\u0012\u00020\u000b0\n\u0012\n\u0012\b\u0012\u0004\u0012\u00020\r0\f0\t0\b8F¢\u0006\u0006\u001a\u0004\b\u000e\u0010\u000f¨\u0006\u0010"}, m3636d2 = {"Lcom/robinhood/android/debug/registry/provisions/IntentKeyRegistry;", "", "<init>", "()V", "dummyUuid", "Ljava/util/UUID;", "kotlin.jvm.PlatformType", "MAPPING", "", "Lkotlin/Pair;", "Lkotlin/reflect/KClass;", "Lcom/robinhood/android/navigation/keys/IntentKey;", "", "Lcom/robinhood/shared/debug/lib/registry/config/Configuration$Intent;", "getMAPPING", "()Ljava/util/Set;", "lib-debug-drawer-registry-provisions_externalDebug"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
/* loaded from: classes2.dex */
public final class IntentKeyRegistry {
    public static final IntentKeyRegistry INSTANCE = new IntentKeyRegistry();
    private static final UUID dummyUuid = UUID.fromString("00000000-0000-0000-0000-00000000000");

    private IntentKeyRegistry() {
    }

    /* JADX WARN: Multi-variable type inference failed */
    public final Set<Tuples2<KClass<? extends IntentKey>, List<Configuration.Intent>>> getMAPPING() {
        Tuples2 tuples2M3642to = Tuples4.m3642to(Reflection.getOrCreateKotlinClass(AcatsIn.class), CollectionsKt.listOf(new Configuration.Intent("AcatsIn", new AcatsIn("debug_navigator", false, false, null, false, 30, null))));
        KClass orCreateKotlinClass = Reflection.getOrCreateKotlinClass(AchRelationshipDocumentVerification.class);
        UUID uuidRandomUUID = UUID.randomUUID();
        Intrinsics.checkNotNullExpressionValue(uuidRandomUUID, "randomUUID(...)");
        ApiDocumentRequest.Type type2 = ApiDocumentRequest.Type.BANK_STATEMENT;
        AchRelationshipDocumentRequestSource achRelationshipDocumentRequestSource = AchRelationshipDocumentRequestSource.IAV;
        ColorTheme colorTheme = ColorTheme.DEFAULT;
        Configuration.Intent intent = new Configuration.Intent("AchRelationshipDocumentVerification with default theme", new AchRelationshipDocumentVerification(uuidRandomUUID, type2, achRelationshipDocumentRequestSource, false, colorTheme, 8, null));
        UUID uuidRandomUUID2 = UUID.randomUUID();
        Intrinsics.checkNotNullExpressionValue(uuidRandomUUID2, "randomUUID(...)");
        int i = 8;
        DefaultConstructorMarker defaultConstructorMarker = null;
        boolean z = false;
        Configuration.Intent intent2 = new Configuration.Intent("AchRelationshipDocumentVerification with device theme", new AchRelationshipDocumentVerification(uuidRandomUUID2, type2, achRelationshipDocumentRequestSource, z, ColorTheme.DEVICE, i, defaultConstructorMarker));
        UUID uuidRandomUUID3 = UUID.randomUUID();
        Intrinsics.checkNotNullExpressionValue(uuidRandomUUID3, "randomUUID(...)");
        Tuples2 tuples2M3642to2 = Tuples4.m3642to(orCreateKotlinClass, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent, intent2, new Configuration.Intent("AchRelationshipDocumentVerification with dark theme", new AchRelationshipDocumentVerification(uuidRandomUUID3, type2, achRelationshipDocumentRequestSource, z, ColorTheme.DARK, i, defaultConstructorMarker))}));
        KClass orCreateKotlinClass2 = Reflection.getOrCreateKotlinClass(ProductUpsellKey.class);
        ProductUpsellKey.Companion companion = ProductUpsellKey.INSTANCE;
        Tuples2 tuples2M3642to3 = Tuples4.m3642to(orCreateKotlinClass2, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("Notification Upsell (post equity trade)", companion.getUpsellNotificationPostEquityTrade()), new Configuration.Intent("Notification Upsell (post crypto trade)", companion.getUpsellNotificationPostCryptoTrade())}));
        KClass orCreateKotlinClass3 = Reflection.getOrCreateKotlinClass(AchTransferIntentKey.class);
        Configuration.Intent intent3 = new Configuration.Intent("Automatic Deposit", new AchTransferIntentKey(new TransferContext.AutomaticDeposit(false, 1, null), false, false, false, null, 30, null));
        TransferDirection transferDirection = TransferDirection.DEPOSIT;
        DefaultConstructorMarker defaultConstructorMarker2 = null;
        Configuration.Intent intent4 = new Configuration.Intent("Normal Deposit", new AchTransferIntentKey(new TransferContext.Normal(transferDirection, null, null, 6, null), false, false, false, null, 30, defaultConstructorMarker2));
        TransferDirection transferDirection2 = TransferDirection.WITHDRAW;
        boolean z2 = false;
        ColorTheme colorTheme2 = null;
        Tuples2 tuples2M3642to4 = Tuples4.m3642to(orCreateKotlinClass3, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent3, intent4, new Configuration.Intent("Normal Withdrawal", new AchTransferIntentKey(new TransferContext.Normal(transferDirection2, null, null, 6, null), false, false, z2, colorTheme2, 30, defaultConstructorMarker2)), new Configuration.Intent("Onboarding Automatic Deposit", new AchTransferIntentKey(new TransferContext.RecurringDepositFromOnboarding(BigDecimal.valueOf(10L)), true, true, z2, colorTheme2, 24, defaultConstructorMarker2))}));
        KClass orCreateKotlinClass4 = Reflection.getOrCreateKotlinClass(CryptoGifting.CryptoGiftDetails.class);
        UUID uuidFromString = UUID.fromString("00000000-0000-0000-0000-000000000000");
        Intrinsics.checkNotNullExpressionValue(uuidFromString, "fromString(...)");
        Tuples2 tuples2M3642to5 = Tuples4.m3642to(orCreateKotlinClass4, CollectionsKt.listOf(new Configuration.Intent("Show crypto gift details", new CryptoGifting.CryptoGiftDetails(uuidFromString))));
        Tuples2 tuples2M3642to6 = Tuples4.m3642to(Reflection.getOrCreateKotlinClass(LegacyIntentKey.EquityOrderWithSymbol.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("BUY AAPL", new LegacyIntentKey.EquityOrderWithSymbol("AAPL", EquityOrderSide.BUY, null, false, null, 28, null)), new Configuration.Intent("SELL AAPL", new LegacyIntentKey.EquityOrderWithSymbol("AAPL", EquityOrderSide.SELL, null, false, null, 28, null))}));
        KClass orCreateKotlinClass5 = Reflection.getOrCreateKotlinClass(LegacyIntentKey.ChooseAddress.class);
        ChooseAddressSource chooseAddressSource = ChooseAddressSource.SETTINGS_MODIFY_RESIDENTIAL;
        CountryCode.Supported.UnitedStates unitedStates = CountryCode.Supported.UnitedStates.INSTANCE;
        Tuples2 tuples2M3642to7 = Tuples4.m3642to(orCreateKotlinClass5, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("Choose Address Green", new LegacyIntentKey.ChooseAddress(chooseAddressSource, unitedStates, null, null, false, 28, null)), new Configuration.Intent("Choose Address Monochrome", new LegacyIntentKey.ChooseAddress(chooseAddressSource, unitedStates, null, null, true, 12, null))}));
        KClass orCreateKotlinClass6 = Reflection.getOrCreateKotlinClass(DocUploadAssistant.class);
        UUID uuid = dummyUuid;
        ApiDocumentRequest.Type type3 = ApiDocumentRequest.Type.PHOTO_ID;
        ApiDocumentRequest.State state = ApiDocumentRequest.State.PENDING_UPLOAD;
        Configuration.Intent intent5 = new Configuration.Intent("Photo ID", new DocUploadAssistant(CollectionsKt.listOf(new DocumentRequest(null, null, uuid, type3, false, state, null, null, null, null, null, 2003, null)), false, false, true, colorTheme, 6, null));
        ApiDocumentRequest.Type type4 = ApiDocumentRequest.Type.PERMANENT_RESIDENT_CARD;
        ApiDocumentRequest.State state2 = ApiDocumentRequest.State.RE_REQUESTED;
        Configuration.Intent intent6 = new Configuration.Intent("Permanent Resident Card", new DocUploadAssistant(CollectionsKt.listOf(new DocumentRequest(null, null, uuid, type4, false, state2, null, null, null, null, null, 2003, null)), false, false, true, colorTheme, 6, null));
        DocumentRequest documentRequest = new DocumentRequest(null, null, UUID.randomUUID(), ApiDocumentRequest.Type.NATIONAL_ID, false, state, null, null, null, null, null, 2003, null);
        DocumentRequest documentRequest2 = new DocumentRequest(null, null, UUID.randomUUID(), ApiDocumentRequest.Type.LETTER_407, false, state2, null, null, null, null, null, 2003, null);
        UUID uuidRandomUUID4 = UUID.randomUUID();
        ApiDocumentRequest.State state3 = ApiDocumentRequest.State.UPLOADED;
        Tuples2 tuples2M3642to8 = Tuples4.m3642to(orCreateKotlinClass6, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent5, intent6, new Configuration.Intent("National ID & 407 Letter & Bank Statement", new DocUploadAssistant(CollectionsKt.listOf((Object[]) new DocumentRequest[]{documentRequest, documentRequest2, new DocumentRequest(null, null, uuidRandomUUID4, type2, false, state3, null, null, null, null, null, 2003, null)}), false, false, true, colorTheme, 6, null)), new Configuration.Intent("Photo ID & Permanent Resident Card", new DocUploadAssistant(CollectionsKt.listOf((Object[]) new DocumentRequest[]{new DocumentRequest(null, null, UUID.randomUUID(), type3, false, state, null, null, null, null, null, 2003, null), new DocumentRequest(null, null, UUID.randomUUID(), type4, false, state3, null, null, null, null, null, 2003, null)}), false, false, true, colorTheme, 6, null))}));
        KClass orCreateKotlinClass7 = Reflection.getOrCreateKotlinClass(CryptoOrderIntentKey.class);
        UUID uuidFromString2 = UUID.fromString("3d961844-d360-45fc-989b-f6fca761d511");
        Intrinsics.checkNotNullExpressionValue(uuidFromString2, "fromString(...)");
        TradeAction tradeAction = TradeAction.BUY;
        Configuration.Intent intent7 = new Configuration.Intent("Buy BTC", new CryptoOrderIntentKey(uuidFromString2, tradeAction, null, null, null, 28, null));
        UUID uuidFromString3 = UUID.fromString("3d961844-d360-45fc-989b-f6fca761d511");
        Intrinsics.checkNotNullExpressionValue(uuidFromString3, "fromString(...)");
        TradeAction tradeAction2 = TradeAction.SELL;
        Configuration.Intent intent8 = new Configuration.Intent("Sell BTC", new CryptoOrderIntentKey(uuidFromString3, tradeAction2, null, null, null, 28, null));
        UUID uuidFromString4 = UUID.fromString("76637d50-c702-4ed1-bcb5-5b0732a81f48");
        Intrinsics.checkNotNullExpressionValue(uuidFromString4, "fromString(...)");
        Configuration.Intent intent9 = new Configuration.Intent("Buy ETH", new CryptoOrderIntentKey(uuidFromString4, tradeAction, null, null, null, 28, null));
        UUID uuidFromString5 = UUID.fromString("76637d50-c702-4ed1-bcb5-5b0732a81f48");
        Intrinsics.checkNotNullExpressionValue(uuidFromString5, "fromString(...)");
        Configuration.Intent intent10 = new Configuration.Intent("Sell ETH", new CryptoOrderIntentKey(uuidFromString5, tradeAction2, null, null, null, 28, null));
        UUID uuidFromString6 = UUID.fromString("1ef78e1b-049b-4f12-90e5-555dcf2fe204");
        Intrinsics.checkNotNullExpressionValue(uuidFromString6, "fromString(...)");
        Configuration.Intent intent11 = new Configuration.Intent("Buy DOGE", new CryptoOrderIntentKey(uuidFromString6, tradeAction, null, null, null, 28, null));
        UUID uuidFromString7 = UUID.fromString("1ef78e1b-049b-4f12-90e5-555dcf2fe204");
        Intrinsics.checkNotNullExpressionValue(uuidFromString7, "fromString(...)");
        Tuples2 tuples2M3642to9 = Tuples4.m3642to(orCreateKotlinClass7, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent7, intent8, intent9, intent10, intent11, new Configuration.Intent("Sell DOGE", new CryptoOrderIntentKey(uuidFromString7, tradeAction2, null, null, null, 28, null))}));
        KClass orCreateKotlinClass8 = Reflection.getOrCreateKotlinClass(CryptoTransferIntentKey.class);
        CurrencyPair.Companion companion2 = CurrencyPair.INSTANCE;
        UUID id_btcusd = companion2.getID_BTCUSD();
        CryptoTransferIntentKey.Action action = CryptoTransferIntentKey.Action.RECEIVE;
        Configuration.Intent intent12 = new Configuration.Intent("Receive Bitcoins", new CryptoTransferIntentKey(action, id_btcusd, null, false, null, 28, null));
        UUID id_btcusd2 = companion2.getID_BTCUSD();
        CryptoTransferIntentKey.Action action2 = CryptoTransferIntentKey.Action.SEND;
        Tuples2 tuples2M3642to10 = Tuples4.m3642to(orCreateKotlinClass8, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent12, new Configuration.Intent("Send Bitcoins", new CryptoTransferIntentKey(action2, id_btcusd2, null, false, null, 28, null)), new Configuration.Intent("Force Open Enrollment", new CryptoTransferIntentKey(CryptoTransferIntentKey.Action.ENROLL, null, null, false, null, 28, null))}));
        KClass orCreateKotlinClass9 = Reflection.getOrCreateKotlinClass(ResumeApplication.class);
        ResumeApplicationResponse8 resumeApplicationResponse8 = ResumeApplicationResponse8.CHURNED;
        Tuples2 tuples2M3642to11 = Tuples4.m3642to(orCreateKotlinClass9, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("Resume application flow with welcome back", new ResumeApplication(resumeApplicationResponse8, true, "Anton", "Add money to start investing", "One last step before you're ready to get back to investing on Robinhood.", null, null, null, null, null, null, null, null, 8032, null)), new Configuration.Intent("Resume application flow without welcome back", new ResumeApplication(resumeApplicationResponse8, false, "Anton", "Add money to start investing", "One last step before you're ready to get back to investing on Robinhood.", 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, null, 8032, null)), new Configuration.Intent("Resume application flow for churned and zero funded user with M3A variant2", ResumeApplicationFixtures.createResumeApplicationChurnedV2IntentKey()), new Configuration.Intent("Resume application flow crypto transfer", ResumeApplicationFixtures.createResumeApplicationCryptoTransferIntentKey())}));
        Tuples2 tuples2M3642to12 = Tuples4.m3642to(Reflection.getOrCreateKotlinClass(OnboardingUpsellIntentKey.class), CollectionsKt.listOf(new Configuration.Intent("Onboarding Upsell", new OnboardingUpsellIntentKey("debug_drawer", null, false, false, null, 30, null))));
        KClass orCreateKotlinClass10 = Reflection.getOrCreateKotlinClass(OnboardingTakeoverIntentKey.class);
        ReferralLandingSdui.TitleBar titleBar = new ReferralLandingSdui.TitleBar(null, new ReferralLandingSdui.ActionTextButton("robinhood://log_in", "Login"));
        Font font = Font.CAPSULE;
        BookCoverTextStyle bookCoverTextStyle = BookCoverTextStyle.MEDIUM;
        TextAlignment textAlignment = TextAlignment.CENTER;
        Object[] objArr = 0 == true ? 1 : 0;
        Object[] objArr2 = 0 == true ? 1 : 0;
        Object[] objArr3 = 0 == true ? 1 : 0;
        Object[] objArr4 = 0 == true ? 1 : 0;
        Object[] objArr5 = 0 == true ? 1 : 0;
        Object[] objArr6 = 0 == true ? 1 : 0;
        Object[] objArr7 = 0 == true ? 1 : 0;
        Object[] objArr8 = 0 == true ? 1 : 0;
        List listListOf = CollectionsKt.listOf((Object[]) new UIComponent[]{new BookCoverText("Sign up, get $5-$200 of stock", font, null, bookCoverTextStyle, textAlignment, 4, null), new Text(new PlainText("Limitations apply"), null, textAlignment, null, null, 26, null), new Decorator(null, new AspectRatioRemoteImage("https://cdn.robinhood.com/app_assets/onboarding_welcome_screen/welcome_blocks.png", new Size(375, 283), null, 4, null), null, 0 == true ? 1 : 0, null, objArr8, 0, objArr, objArr2, objArr3, objArr4, new GutterBehavior(true), objArr5, objArr7, null, objArr6, null, null, null, null, null, null, 4192253, null)});
        Text text = new Text(new PlainText("98% of rewards are $5-$10. See terms"), null, textAlignment, null, null, 26, null);
        ButtonType buttonType = ButtonType.PRIMARY;
        Configuration.Intent intent13 = new Configuration.Intent("Onboarding Takeover organic without email", new OnboardingTakeoverIntentKey(new ReferralLandingSdui(titleBar, listListOf, CollectionsKt.listOf((Object[]) new UIComponent[]{text, new Button("Get your stock", buttonType, new OnboardingWelcomeTakeoverAction.Deeplink(new DeeplinkAction("robinhood://sign_up")), false, null, null, null, null, null, null, 1016, null)}), null, false, null, false, 112, null)));
        ReferralLandingSdui.TitleBar titleBar2 = new ReferralLandingSdui.TitleBar(null, new ReferralLandingSdui.ActionTextButton("robinhood://log_in", "Login"));
        InfoTagType infoTagType = InfoTagType.INLINE;
        Icon icon = Icon.EMAIL_FILLED_24;
        InfoTag infoTag = new InfoTag("Amelia invited you", infoTagType, null, "", icon, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_BUBBLES_QUESTION_VALUE, null);
        BookCoverTextStyle bookCoverTextStyle2 = BookCoverTextStyle.SMALL;
        TextAlignment textAlignment2 = TextAlignment.START;
        int i2 = 4192253;
        DefaultConstructorMarker defaultConstructorMarker3 = null;
        int i3 = 0;
        Integer num = null;
        AccessibilityModifier accessibilityModifier = null;
        GoldShimmer goldShimmer = null;
        Sizing sizing = null;
        Integer num2 = null;
        Float f = null;
        Tooltip tooltip = null;
        String str = null;
        Object[] objArr9 = 0 == true ? 1 : 0;
        Object[] objArr10 = 0 == true ? 1 : 0;
        Configuration.Intent intent14 = new Configuration.Intent("Onboarding Takeover referred without email", new OnboardingTakeoverIntentKey(new ReferralLandingSdui(titleBar2, CollectionsKt.listOf((Object[]) new UIComponent[]{infoTag, new BookCoverText("Sign up, get $5-$200 of stock", font, null, bookCoverTextStyle2, textAlignment2, 4, null), new Text(new PlainText("Amelia will earn stock, too! Limitations apply."), null, textAlignment2, null, null, 26, null), new Decorator(objArr9, new AspectRatioRemoteImage("https://cdn.robinhood.com/app_assets/onboarding_welcome_screen/welcome_blocks.png", new Size(375, 283), null, 4, null), 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, i3, num, objArr10, null, null, new GutterBehavior(true), null, accessibilityModifier, goldShimmer, null, sizing, null, num2, f, tooltip, str, i2, defaultConstructorMarker3)}), CollectionsKt.listOf((Object[]) new UIComponent[]{new Text(new PlainText("98% of rewards are $5-$10. See terms"), null, textAlignment, null, null, 26, null), new Button("Get your stock", buttonType, new OnboardingWelcomeTakeoverAction.Deeplink(new DeeplinkAction("robinhood://sign_up")), false, null, null, null, null, null, null, 1016, null)}), null, false, null, false, 112, null)));
        ReferralLandingSdui.TitleBar titleBar3 = new ReferralLandingSdui.TitleBar(null, new ReferralLandingSdui.ActionTextButton("robinhood://log_in", "Login"));
        PlainText plainText = new PlainText("Sign up, get $5-$200 of stock");
        TextStyle textStyle = TextStyle.DISPLAY_LARGE;
        Text text2 = new Text(plainText, textStyle, textAlignment, null, null, 24, null);
        Text text3 = new Text(new PlainText("Limitations apply"), null, textAlignment, null, null, 26, null);
        Decorator decorator = new Decorator(0 == true ? 1 : 0, new AspectRatioRemoteImage("https://cdn.robinhood.com/app_assets/onboarding_welcome_screen/welcome_blocks_row.png", new Size(375, 53), null, 4, 0 == true ? 1 : 0), 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, i3, num, 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, new GutterBehavior(true), 0 == true ? 1 : 0, accessibilityModifier, goldShimmer, 0 == true ? 1 : 0, sizing, 0 == true ? 1 : 0, num2, f, tooltip, str, i2, defaultConstructorMarker3);
        TextValidationType textValidationType = TextValidationType.DELAYED;
        String str2 = null;
        boolean z3 = false;
        Tuples2 tuples2M3642to13 = Tuples4.m3642to(orCreateKotlinClass10, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent13, intent14, new Configuration.Intent("Onboarding Takeover organic with email", new OnboardingTakeoverIntentKey(new ReferralLandingSdui(titleBar3, CollectionsKt.listOf((Object[]) new UIComponent[]{text2, text3, decorator, new TextInput("email", 0 == true ? 1 : 0, 0 == true ? 1 : 0, 0 == true ? 1 : 0, false, str2, z3, new TextInputValidators(null, null, null, CollectionsKt.listOf(new RegexValidator("email", "Please enter a valid email address", textValidationType, "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$")), 7, null), 0 == true ? 1 : 0, 0 == true ? 1 : 0, null, 0 == true ? 1 : 0, false, 8062, 0 == true ? 1 : 0)}), CollectionsKt.listOf((Object[]) new UIComponent[]{new Text(new PlainText("98% of rewards are $5-$10. See terms"), null, textAlignment, null, null, 26, null), new Button("Get your stock", buttonType, new OnboardingWelcomeTakeoverAction.SubmitForm(new SubmitFormAction("email", CollectionsKt.listOf("email"))), false, null, null, null, null, null, null, 1016, null)}), null, false, null, false, 112, null))), new Configuration.Intent("Onboarding Takeover referred with email", new OnboardingTakeoverIntentKey(new ReferralLandingSdui(new ReferralLandingSdui.TitleBar(null, new ReferralLandingSdui.ActionTextButton("robinhood://log_in", "Login")), CollectionsKt.listOf((Object[]) new UIComponent[]{new InfoTag("Amelia invited you", infoTagType, null, "", icon, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_BUBBLES_QUESTION_VALUE, null), new Text(new PlainText("Sign up, get $5-$200 of stock"), textStyle, textAlignment2, null, null, 24, null), new Text(new PlainText("Limitations apply"), null, textAlignment2, null, null, 26, null), new Decorator(null, new AspectRatioRemoteImage("https://cdn.robinhood.com/app_assets/onboarding_welcome_screen/welcome_blocks_row.png", new Size(375, 53), null, 4, null), null, null, null, null, 0, null, null, null, null, new GutterBehavior(true), null, null, null, null, null, null, null, null, null, null, 4192253, null), new TextInput("email", 0 == true ? 1 : 0, null, str2, z3, null, false, new TextInputValidators(null, null, null, CollectionsKt.listOf(new RegexValidator("email", "Please enter a valid email address", textValidationType, "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$")), 7, null), 0 == true ? 1 : 0, 0 == true ? 1 : 0, null, null, false, 8062, 0 == true ? 1 : 0)}), CollectionsKt.listOf((Object[]) new UIComponent[]{new Text(new PlainText("98% of rewards are $5-$10. See terms"), null, textAlignment, null, null, 26, null), new Button("Get your stock", buttonType, new OnboardingWelcomeTakeoverAction.SubmitForm(new SubmitFormAction("email", CollectionsKt.listOf("email"))), false, null, null, null, null, null, null, 1016, null)}), null, false, null, false, 112, null)))}));
        KClass orCreateKotlinClass11 = Reflection.getOrCreateKotlinClass(Transfer.class);
        Configuration.Intent intent15 = new Configuration.Intent("RHS deposit", new Transfer(new TransferContext.Normal(transferDirection, null, null, 6, null)));
        Configuration.Intent intent16 = new Configuration.Intent("RHS withdrawal", new Transfer(new TransferContext.Normal(transferDirection2, null, null, 6, null)));
        long j = 10;
        BigDecimal bigDecimalValueOf = BigDecimal.valueOf(j);
        Intrinsics.checkNotNullExpressionValue(bigDecimalValueOf, "valueOf(...)");
        Configuration.Intent intent17 = new Configuration.Intent("Day trade call", new Transfer(new TransferContext.DayTradeCall(bigDecimalValueOf)));
        BigDecimal bigDecimalValueOf2 = BigDecimal.valueOf(50);
        Intrinsics.checkNotNullExpressionValue(bigDecimalValueOf2, "valueOf(...)");
        BigDecimal bigDecimalValueOf3 = BigDecimal.valueOf(j);
        Intrinsics.checkNotNullExpressionValue(bigDecimalValueOf3, "valueOf(...)");
        return SetsKt.setOf((Object[]) new Tuples2[]{tuples2M3642to, tuples2M3642to2, tuples2M3642to3, tuples2M3642to4, tuples2M3642to5, tuples2M3642to6, tuples2M3642to7, tuples2M3642to8, tuples2M3642to9, tuples2M3642to10, tuples2M3642to11, tuples2M3642to12, tuples2M3642to13, Tuples4.m3642to(orCreateKotlinClass11, CollectionsKt.listOf((Object[]) new Configuration.Intent[]{intent15, intent16, intent17, new Configuration.Intent("Margin deposit", new Transfer(new TransferContext.MarginDeposit(bigDecimalValueOf2, bigDecimalValueOf3)))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(PostSignUpIntentKey.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("RHF", new PostSignUpIntentKey(ApiTransferAccount.TransferAccountType.RHS, false, null, 6, null)), new Configuration.Intent("RHY", new PostSignUpIntentKey(ApiTransferAccount.TransferAccountType.RHY, false, null, 6, null))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(GenericSdFlowIntentKey.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("rhy upgrade", new GenericSdFlowIntentKey("rhy_upgrade", false, null, null, null, null, false, null, null, 510, null)), new Configuration.Intent("rhy upgrade with exit deeplink redirect", new GenericSdFlowIntentKey("rhy_upgrade", false, null, Uri.parse("robinhood://cash_management"), null, null, false, null, null, HttpStatusCode.BAD_GATEWAY_502, null)), new Configuration.Intent("brokerage (rhf) onboarding", new PostUserCreationShimIntentKey(false, Uri.parse("robinhood://cash_management"), "rhy-round-up", false, null, 25, null))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(LegacyIntentKey.RewardsOnboarding.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("sign up", new LegacyIntentKey.RewardsOnboarding(LegacyIntentKey.RewardsOnboarding.Action.CREATE_ENROLLMENT)), new Configuration.Intent("resume", new LegacyIntentKey.RewardsOnboarding(LegacyIntentKey.RewardsOnboarding.Action.RESUME_ENROLLMENT)), new Configuration.Intent("change investment", new LegacyIntentKey.RewardsOnboarding(LegacyIntentKey.RewardsOnboarding.Action.CHANGE_INVESTMENT))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(LegacyIntentKey.RoundupRewardsAccountCreated.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("brokerage", new LegacyIntentKey.RoundupRewardsAccountCreated(LegacyIntentKey.RoundupRewardsAccountCreated.Type.BROKERAGE_ACCOUNT)), new Configuration.Intent("spending", new LegacyIntentKey.RoundupRewardsAccountCreated(LegacyIntentKey.RoundupRewardsAccountCreated.Type.SPENDING_ACCOUNT))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(Questionnaire.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("Suitability questionnaire", new Questionnaire(true, QuestionnaireContexts.SUITABILITY, null, null, null, null, false, false, false, false, false, null, null, false, false, false, false, false, null, null, 1048568, null)), new Configuration.Intent("Recommendations retirement questionnaire", new Questionnaire(true, QuestionnaireContexts.RETIREMENT_RECS_TRADITIONAL_IRA, null, null, null, null, false, false, false, false, true, null, null, false, false, false, false, false, null, null, 1047544, null)), new Configuration.Intent("Futures UK suitability questionnaire", new Questionnaire(true, QuestionnaireContexts.FUTURES_UK_SUITABILITY, null, null, null, null, false, false, false, false, true, null, null, false, true, false, false, false, null, null, 965496, null))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(CryptoTransferSelectionIntentKey.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("Choose crypto to receive", new CryptoTransferSelectionIntentKey(null, action, false, null, 12, null)), new Configuration.Intent("Choose crypto to send", new CryptoTransferSelectionIntentKey(null, action2, false, null, 12, null))})), Tuples4.m3642to(Reflection.getOrCreateKotlinClass(TransferV2.class), CollectionsKt.listOf((Object[]) new Configuration.Intent[]{new Configuration.Intent("Deposit", new TransferV2(TransferDirectionV2.DEPOSIT, new TransferConfiguration.Standard(null, null, false, null, null, null, null, null, false, false, null, null, false, 8191, null), null, 4, null)), new Configuration.Intent("Withdraw", new TransferV2(TransferDirectionV2.WITHDRAW, new TransferConfiguration.Standard(null, null, false, null, null, null, null, null, false, false, null, null, false, 8191, null), null, 4, null))}))});
    }
}
