package com.robinhood.shared.recurring.p392ui.edit;

import androidx.compose.p011ui.tooling.preview.PreviewParameterProvider;
import com.plaid.internal.EnumC7081g;
import com.robinhood.android.libdesignsystem.serverui.ServerToBentoAssetMapper2;
import com.robinhood.android.transfers.p271ui.p272v2.CreateTransferV2StateProvider2;
import com.robinhood.compose.bento.component.BentoButtons;
import com.robinhood.compose.bento.component.BentoIcon4;
import com.robinhood.shared.crypto.p375ui.trade.view.CryptoOrderReviewRowState;
import com.robinhood.utils.resource.StringResource;
import kotlin.Metadata;
import kotlin.sequences.Sequence;
import kotlin.sequences.SequencesKt;
import kotlinx.collections.immutable.ImmutableList3;
import kotlinx.collections.immutable.extensions2;

/* compiled from: RecurringSettingsEditComposable.kt */
@Metadata(m3635d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u0003\b\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007¢\u0006\u0004\b\u0003\u0010\u0004R\u001a\u0010\u0005\u001a\b\u0012\u0004\u0012\u00020\u00020\u00068VX\u0096\u0004¢\u0006\u0006\u001a\u0004\b\u0007\u0010\b¨\u0006\t"}, m3636d2 = {"Lcom/robinhood/shared/recurring/ui/edit/RecurringSettingsEditStatePreviewParameterProvider;", "Landroidx/compose/ui/tooling/preview/PreviewParameterProvider;", "Lcom/robinhood/shared/recurring/ui/edit/RecurringSettingsEditState;", "<init>", "()V", "values", "Lkotlin/sequences/Sequence;", "getValues", "()Lkotlin/sequences/Sequence;", "lib-recurring-ui_externalDebug"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
/* renamed from: com.robinhood.shared.recurring.ui.edit.RecurringSettingsEditStatePreviewParameterProvider, reason: use source file name */
/* loaded from: classes6.dex */
public final class RecurringSettingsEditComposable8 implements PreviewParameterProvider<RecurringSettingsEditState> {
    public static final int $stable = 0;

    @Override // androidx.compose.p011ui.tooling.preview.PreviewParameterProvider
    public /* bridge */ /* synthetic */ int getCount() {
        return super.getCount();
    }

    @Override // androidx.compose.p011ui.tooling.preview.PreviewParameterProvider
    public Sequence<RecurringSettingsEditState> getValues() {
        StringResource.Companion companion = StringResource.INSTANCE;
        StringResource stringResourceInvoke = companion.invoke("Edit recurring investment");
        CryptoOrderReviewRowState.TextContent textContent = new CryptoOrderReviewRowState.TextContent(companion.invoke("Amount"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null);
        StringResource stringResourceInvoke2 = companion.invoke("€50,00");
        ServerToBentoAssetMapper2 serverToBentoAssetMapper2 = ServerToBentoAssetMapper2.CARET_RIGHT_16;
        BentoIcon4.Size16 size16 = new BentoIcon4.Size16(serverToBentoAssetMapper2);
        CryptoOrderReviewRowState.ColorOverride colorOverride = CryptoOrderReviewRowState.ColorOverride.FG_3;
        RecurringSettingsEditState recurringSettingsEditState = new RecurringSettingsEditState(stringResourceInvoke, extensions2.persistentListOf(new CryptoOrderReviewRowState(textContent, new CryptoOrderReviewRowState.TextContent(stringResourceInvoke2, null, new CryptoOrderReviewRowState.IconContent(size16, colorOverride), null, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, null), null, null, null, false, null, false, null, null, 1020, null), new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke(CreateTransferV2StateProvider2.FrequencyRowTag), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("Weekly"), null, new CryptoOrderReviewRowState.IconContent(new BentoIcon4.Size16(serverToBentoAssetMapper2), colorOverride), null, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, null), null, extensions2.persistentListOf(new CryptoOrderReviewRowState.SecondaryTextRow(null, new CryptoOrderReviewRowState.TextContent(companion.invoke("Next: 24 Apr, 2025"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), 1, null)), null, false, null, false, null, null, 1012, null), new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke("Payment"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("Buying power"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), null, extensions2.persistentListOf(new CryptoOrderReviewRowState.SecondaryTextRow(null, new CryptoOrderReviewRowState.TextContent(companion.invoke("€1,000.00 available"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), 1, null)), null, false, null, false, null, null, 1012, null)), companion.invoke("Pause investment"), null, companion.invoke("Cancel investment"), false, true, 8, null);
        StringResource stringResourceInvoke3 = companion.invoke("Edit recurring investment");
        ImmutableList3 immutableList3PersistentListOf = extensions2.persistentListOf(new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke("Amount"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("€50,00"), null, new CryptoOrderReviewRowState.IconContent(new BentoIcon4.Size16(serverToBentoAssetMapper2), colorOverride), null, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, null), null, null, null, false, null, false, null, null, 892, null), new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke(CreateTransferV2StateProvider2.FrequencyRowTag), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("Weekly"), null, new CryptoOrderReviewRowState.IconContent(new BentoIcon4.Size16(serverToBentoAssetMapper2), colorOverride), null, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, null), null, extensions2.persistentListOf(new CryptoOrderReviewRowState.SecondaryTextRow(null, new CryptoOrderReviewRowState.TextContent(companion.invoke("Next: 24 Apr, 2025"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), 1, null)), null, false, null, false, null, null, 884, null), new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke("Payment"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("Buying power"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), null, extensions2.persistentListOf(new CryptoOrderReviewRowState.SecondaryTextRow(null, new CryptoOrderReviewRowState.TextContent(companion.invoke("€1,000.00 available"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), 1, null)), null, false, null, false, null, null, 884, null));
        StringResource stringResourceInvoke4 = companion.invoke("Resume investment");
        BentoButtons.Type type2 = BentoButtons.Type.Primary;
        return SequencesKt.sequenceOf(recurringSettingsEditState, new RecurringSettingsEditState(stringResourceInvoke3, immutableList3PersistentListOf, stringResourceInvoke4, type2, companion.invoke("Cancel investment"), false, true), new RecurringSettingsEditState(companion.invoke("Edit recurring investment"), extensions2.persistentListOf(new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke("Amount"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("€50,00"), null, new CryptoOrderReviewRowState.IconContent(new BentoIcon4.Size16(serverToBentoAssetMapper2), colorOverride), null, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, null), null, null, null, false, null, false, null, null, 892, null), new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke(CreateTransferV2StateProvider2.FrequencyRowTag), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("Weekly"), null, new CryptoOrderReviewRowState.IconContent(new BentoIcon4.Size16(serverToBentoAssetMapper2), colorOverride), null, null, null, false, EnumC7081g.SDK_ASSET_ILLUSTRATION_DEPOSIT_VALUE, null), null, extensions2.persistentListOf(new CryptoOrderReviewRowState.SecondaryTextRow(null, new CryptoOrderReviewRowState.TextContent(companion.invoke("Next: 24 Apr, 2025"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), 1, null)), null, false, null, false, null, null, 884, null), new CryptoOrderReviewRowState(new CryptoOrderReviewRowState.TextContent(companion.invoke("Payment"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), new CryptoOrderReviewRowState.TextContent(companion.invoke("Buying power"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), null, extensions2.persistentListOf(new CryptoOrderReviewRowState.SecondaryTextRow(null, new CryptoOrderReviewRowState.TextContent(companion.invoke("€1,000.00 available"), null, null, null, null, null, false, EnumC7081g.SDK_ASSET_PLAID_LOGO_BLACK_BG_VALUE, null), 1, null)), null, false, null, false, null, null, 884, null)), companion.invoke("Resume investment"), type2, companion.invoke("Cancel investment"), false, false));
    }
}
