package androidx.media3.p014ui;

import android.R;
import com.robinhood.android.C7371R;

/* loaded from: classes4.dex */
public final class R$styleable {
    public static int AspectRatioFrameLayout_resize_mode = 0;
    public static int DefaultTimeBar_ad_marker_color = 0;
    public static int DefaultTimeBar_ad_marker_width = 1;
    public static int DefaultTimeBar_bar_gravity = 2;
    public static int DefaultTimeBar_bar_height = 3;
    public static int DefaultTimeBar_buffered_color = 4;
    public static int DefaultTimeBar_played_ad_marker_color = 5;
    public static int DefaultTimeBar_played_color = 6;
    public static int DefaultTimeBar_scrubber_color = 7;
    public static int DefaultTimeBar_scrubber_disabled_size = 8;
    public static int DefaultTimeBar_scrubber_dragged_size = 9;
    public static int DefaultTimeBar_scrubber_drawable = 10;
    public static int DefaultTimeBar_scrubber_enabled_size = 11;
    public static int DefaultTimeBar_touch_target_height = 12;
    public static int DefaultTimeBar_unplayed_color = 13;
    public static int PlayerControlView_animation_enabled = 2;
    public static int PlayerControlView_controller_layout_id = 6;
    public static int PlayerControlView_fastforward_icon = 7;
    public static int PlayerControlView_fullscreen_enter_icon = 8;
    public static int PlayerControlView_fullscreen_exit_icon = 9;
    public static int PlayerControlView_next_icon = 10;
    public static int PlayerControlView_pause_icon = 11;
    public static int PlayerControlView_play_icon = 12;
    public static int PlayerControlView_previous_icon = 15;
    public static int PlayerControlView_repeat_all_icon = 16;
    public static int PlayerControlView_repeat_off_icon = 17;
    public static int PlayerControlView_repeat_one_icon = 18;
    public static int PlayerControlView_repeat_toggle_modes = 19;
    public static int PlayerControlView_rewind_icon = 20;
    public static int PlayerControlView_show_fastforward_button = 26;
    public static int PlayerControlView_show_next_button = 27;
    public static int PlayerControlView_show_previous_button = 28;
    public static int PlayerControlView_show_rewind_button = 29;
    public static int PlayerControlView_show_shuffle_button = 30;
    public static int PlayerControlView_show_subtitle_button = 31;
    public static int PlayerControlView_show_timeout = 32;
    public static int PlayerControlView_show_vr_button = 33;
    public static int PlayerControlView_shuffle_off_icon = 34;
    public static int PlayerControlView_shuffle_on_icon = 35;
    public static int PlayerControlView_subtitle_off_icon = 36;
    public static int PlayerControlView_subtitle_on_icon = 37;
    public static int PlayerControlView_time_bar_min_update_interval = 38;
    public static int PlayerControlView_vr_icon = 41;
    public static int PlayerView_artwork_display_mode = 3;
    public static int PlayerView_auto_show = 4;
    public static int PlayerView_default_artwork = 9;
    public static int PlayerView_hide_during_ads = 13;
    public static int PlayerView_hide_on_touch = 14;
    public static int PlayerView_image_display_mode = 15;
    public static int PlayerView_keep_content_on_player_reset = 16;
    public static int PlayerView_player_layout_id = 22;
    public static int PlayerView_resize_mode = 28;
    public static int PlayerView_show_buffering = 35;
    public static int PlayerView_show_timeout = 38;
    public static int PlayerView_shutter_background_color = 42;
    public static int PlayerView_surface_type = 45;
    public static int PlayerView_use_artwork = 49;
    public static int PlayerView_use_controller = 50;
    public static int[] AspectRatioFrameLayout = {C7371R.attr.resize_mode};
    public static int[] Capability = {C7371R.attr.queryPatterns, C7371R.attr.shortcutMatchRequired};
    public static int[] ColorStateListItem = {R.attr.color, R.attr.alpha, R.attr.lStar, C7371R.attr.alpha, C7371R.attr.lStar};
    public static int[] DefaultTimeBar = {C7371R.attr.ad_marker_color, C7371R.attr.ad_marker_width, C7371R.attr.bar_gravity, C7371R.attr.bar_height, C7371R.attr.buffered_color, C7371R.attr.played_ad_marker_color, C7371R.attr.played_color, C7371R.attr.scrubber_color, C7371R.attr.scrubber_disabled_size, C7371R.attr.scrubber_dragged_size, C7371R.attr.scrubber_drawable, C7371R.attr.scrubber_enabled_size, C7371R.attr.touch_target_height, C7371R.attr.unplayed_color};
    public static int[] FontFamily = {C7371R.attr.fontProviderAuthority, C7371R.attr.fontProviderCerts, C7371R.attr.fontProviderFallbackQuery, C7371R.attr.fontProviderFetchStrategy, C7371R.attr.fontProviderFetchTimeout, C7371R.attr.fontProviderPackage, C7371R.attr.fontProviderQuery, C7371R.attr.fontProviderSystemFontFamily};
    public static int[] FontFamilyFont = {R.attr.font, R.attr.fontWeight, R.attr.fontStyle, R.attr.ttcIndex, R.attr.fontVariationSettings, C7371R.attr.font, C7371R.attr.fontStyle, C7371R.attr.fontVariationSettings, C7371R.attr.fontWeight, C7371R.attr.ttcIndex};
    public static int[] GradientColor = {R.attr.startColor, R.attr.endColor, R.attr.type, R.attr.centerX, R.attr.centerY, R.attr.gradientRadius, R.attr.tileMode, R.attr.centerColor, R.attr.startX, R.attr.startY, R.attr.endX, R.attr.endY};
    public static int[] GradientColorItem = {R.attr.color, R.attr.offset};
    public static int[] LegacyPlayerControlView = {C7371R.attr.ad_marker_color, C7371R.attr.ad_marker_width, C7371R.attr.bar_gravity, C7371R.attr.bar_height, C7371R.attr.buffered_color, C7371R.attr.controller_layout_id, C7371R.attr.played_ad_marker_color, C7371R.attr.played_color, C7371R.attr.repeat_toggle_modes, C7371R.attr.scrubber_color, C7371R.attr.scrubber_disabled_size, C7371R.attr.scrubber_dragged_size, C7371R.attr.scrubber_drawable, C7371R.attr.scrubber_enabled_size, C7371R.attr.show_fastforward_button, C7371R.attr.show_next_button, C7371R.attr.show_previous_button, C7371R.attr.show_rewind_button, C7371R.attr.show_shuffle_button, C7371R.attr.show_timeout, C7371R.attr.time_bar_min_update_interval, C7371R.attr.touch_target_height, C7371R.attr.unplayed_color};
    public static int[] PlayerControlView = {C7371R.attr.ad_marker_color, C7371R.attr.ad_marker_width, C7371R.attr.animation_enabled, C7371R.attr.bar_gravity, C7371R.attr.bar_height, C7371R.attr.buffered_color, C7371R.attr.controller_layout_id, C7371R.attr.fastforward_icon, C7371R.attr.fullscreen_enter_icon, C7371R.attr.fullscreen_exit_icon, C7371R.attr.next_icon, C7371R.attr.pause_icon, C7371R.attr.play_icon, C7371R.attr.played_ad_marker_color, C7371R.attr.played_color, C7371R.attr.previous_icon, C7371R.attr.repeat_all_icon, C7371R.attr.repeat_off_icon, C7371R.attr.repeat_one_icon, C7371R.attr.repeat_toggle_modes, C7371R.attr.rewind_icon, C7371R.attr.scrubber_color, C7371R.attr.scrubber_disabled_size, C7371R.attr.scrubber_dragged_size, C7371R.attr.scrubber_drawable, C7371R.attr.scrubber_enabled_size, C7371R.attr.show_fastforward_button, C7371R.attr.show_next_button, C7371R.attr.show_previous_button, C7371R.attr.show_rewind_button, C7371R.attr.show_shuffle_button, C7371R.attr.show_subtitle_button, C7371R.attr.show_timeout, C7371R.attr.show_vr_button, C7371R.attr.shuffle_off_icon, C7371R.attr.shuffle_on_icon, C7371R.attr.subtitle_off_icon, C7371R.attr.subtitle_on_icon, C7371R.attr.time_bar_min_update_interval, C7371R.attr.touch_target_height, C7371R.attr.unplayed_color, C7371R.attr.vr_icon};
    public static int[] PlayerView = {C7371R.attr.ad_marker_color, C7371R.attr.ad_marker_width, C7371R.attr.animation_enabled, C7371R.attr.artwork_display_mode, C7371R.attr.auto_show, C7371R.attr.bar_gravity, C7371R.attr.bar_height, C7371R.attr.buffered_color, C7371R.attr.controller_layout_id, C7371R.attr.default_artwork, C7371R.attr.fastforward_icon, C7371R.attr.fullscreen_enter_icon, C7371R.attr.fullscreen_exit_icon, C7371R.attr.hide_during_ads, C7371R.attr.hide_on_touch, C7371R.attr.image_display_mode, C7371R.attr.keep_content_on_player_reset, C7371R.attr.next_icon, C7371R.attr.pause_icon, C7371R.attr.play_icon, C7371R.attr.played_ad_marker_color, C7371R.attr.played_color, C7371R.attr.player_layout_id, C7371R.attr.previous_icon, C7371R.attr.repeat_all_icon, C7371R.attr.repeat_off_icon, C7371R.attr.repeat_one_icon, C7371R.attr.repeat_toggle_modes, C7371R.attr.resize_mode, C7371R.attr.rewind_icon, C7371R.attr.scrubber_color, C7371R.attr.scrubber_disabled_size, C7371R.attr.scrubber_dragged_size, C7371R.attr.scrubber_drawable, C7371R.attr.scrubber_enabled_size, C7371R.attr.show_buffering, C7371R.attr.show_shuffle_button, C7371R.attr.show_subtitle_button, C7371R.attr.show_timeout, C7371R.attr.show_vr_button, C7371R.attr.shuffle_off_icon, C7371R.attr.shuffle_on_icon, C7371R.attr.shutter_background_color, C7371R.attr.subtitle_off_icon, C7371R.attr.subtitle_on_icon, C7371R.attr.surface_type, C7371R.attr.time_bar_min_update_interval, C7371R.attr.touch_target_height, C7371R.attr.unplayed_color, C7371R.attr.use_artwork, C7371R.attr.use_controller, C7371R.attr.vr_icon};
    public static int[] RecyclerView = {R.attr.orientation, R.attr.clipToPadding, R.attr.descendantFocusability, C7371R.attr.fastScrollEnabled, C7371R.attr.fastScrollHorizontalThumbDrawable, C7371R.attr.fastScrollHorizontalTrackDrawable, C7371R.attr.fastScrollVerticalThumbDrawable, C7371R.attr.fastScrollVerticalTrackDrawable, C7371R.attr.layoutManager, C7371R.attr.peekMargin, C7371R.attr.reverseLayout, C7371R.attr.spanCount, C7371R.attr.stackFromEnd};
}
