package rosetta.order;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import kotlin.Metadata;
import kotlin.enums.EnumEntries;
import kotlin.enums.EnumEntries2;
import kotlin.jvm.JvmField;
import kotlin.jvm.JvmStatic;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Reflection;
import kotlin.reflect.KClass;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: AlertType.kt */
@Metadata(m3635d1 = {"\u0000\u0016\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0010\b\n\u0002\bm\b\u0086\u0081\u0002\u0018\u0000 p2\u00020\u00012\b\u0012\u0004\u0012\u00020\u00000\u0002:\u0001pB\u0011\b\u0002\u0012\u0006\u0010\u0003\u001a\u00020\u0004¢\u0006\u0004\b\u0005\u0010\u0006R\u0014\u0010\u0003\u001a\u00020\u0004X\u0096\u0004¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\bo¨\u0006q"}, m3636d2 = {"Lrosetta/order/AlertType;", "Lcom/squareup/wire/WireEnum;", "", "value", "", "<init>", "(Ljava/lang/String;II)V", "getValue", "()I", "UNDEFINED", "EQUITY_UNTRADABLE", "EQUITY_NOT_ENOUGH_BP_DOLLAR_BASED", "RHS_CONVERSION", "EQUITY_PDT_BLOCK_NOT_EXEMPT", "EQUITY_DAY_TRADE_BLOCK_WARNING", "EQUITY_NOT_ENOUGH_SHARES", "EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_BUY", "EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_SELL", "EQUITY_DAY_TRADE_BLOCK_DUE_TO_PDT", "EQUITY_DAY_TRADE_BLOCK_ERROR", "EQUITY_DAY_TRADE_BLOCK_WITH_CANCELABLE_ORDER", "EQUITY_NO_QUOTE", "EQUITY_HIGH_VOLATILITY", "EQUITY_LIQUIDITY", "EQUITY_DOLLAR_BASED_SELL_ALL_ERROR", "EQUITY_SHORT_POSITION_QUANTITY_WITH_PENDING_ERROR", "EQUITY_SHORT_POSITION_QUANTITY_ERROR", "EQUITY_NOT_ENOUGH_BP_CONVERT_TO_LIMIT", "EQUITY_NOT_ENOUGH_BP", "EQUITY_SELL_CAUSES_CASH_COLLATERAL", "EQUITY_LARGE_ORDER", "EQUITY_DOLLAR_BASED_MINIMUM_AMOUNT_ERROR", "EQUITY_ZERO_QUANTITY", "EQUITY_SUITABILITY", "EQUITY_LIMIT_PRICE_OUTSIDE_SOFT_RANGE", "EQUITY_STOP_PRICE_OUTSIDE_SOFT_RANGE", "EQUITY_REWARDS_MUST_BE_HELD", "EQUITY_MAX_SELL_DOLLARS_EXCEEDED", "EQUITY_MAX_SELL_SHARES_EXCEEDED", "EQUITY_ETP_WARNING", "EQUITY_TSPP_LIMIT_PRICE", "EQUITY_TSPP_STOP_PRICE", "EQUITY_IPO_FLIPPING_POLICY", "EQUITY_INITIAL_TRAILING_STOP_PRICE", "EQUITY_EXTREMELY_MARKETABLE_LIMIT_PRICE", "EQUITY_EXTREMELY_MARKETABLE_STOP_PRICE", "EQUITY_EXTREMELY_UNMARKETABLE_LIMIT_PRICE", "EQUITY_EXTREMELY_UNMARKETABLE_STOP_PRICE", "EQUITY_MAX_PRICE_EXCEEDED", "EQUITY_MAX_NOTIONAL_EXCEEDED", "EQUITY_MAX_QUANTITY_EXCEEDED", "EQUITY_TOO_LARGE_ORDER", "EQUITY_UNTRADABLE_EXTENDED_HOURS_FRAC_INSTRUMENT", "EQUITY_DELAYED_EXTENDED_HOURS", "EQUITY_VALIDATION_ERROR", "EQUITY_IRA_BLOCK_UBTI", "EQUITY_ALL_DAY_TRADING_ERROR", "EQUITY_UPDATE_FOR_HYPER_EX", "EQUITY_UPDATE_FOR_HYPER_EX_BLOCKING", "EQUITY_INVALID_SIMPLE_LIMIT_ORDER", "EQUITY_INSTRUMENT_HALT", "EQUITY_MAX_SELL_DOLLARS_LIMIT_ORDER_EXCEEDED", "EQUITY_NOT_ENOUGH_BP_LIMIT_PRICE", "EQUITY_CONVERT_TO_MARKET_ORDER", "EQUITY_CONVERT_TO_SIMPLE_LIMIT_ORDER", "EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED", "EQUITY_NOT_ENOUGH_BP_CANCEL_CRYPTO_PENDING_ORDERS", "EQUITY_ALL_DAY_TRADING_FRACTIONAL_ORDER_PROMOTION", "EQUITY_ALL_DAY_TRADING_SESSION_KILL_SWITCH_ENABLED", "EQUITY_EXTENDED_HOURS_SESSION_KILL_SWITCH_ENABLED", "EQUITY_ADT_AND_EH_SESSION_KILL_SWITCH_ENABLED", "EQUITY_COLLARED_ORDER_DISABLED", "EQUITY_SLIPPAGE_RISK_FROM_OPTION_ASSIGNMENT", "EQUITY_TRADING_WINDOW_CLOSED_FOR_HOOD_EMPLOYEES", "EQUITY_CONCENTRATED_MAINTENANCE_CALL_WARNING", "EQUITY_ORDER_REPLACEMENT_NO_CHANGE", "EQUITY_ORDER_REPLACEMENT_ORDER_NOT_REPLACEABLE", "EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED_SHARE_BASED_MARKET_BUY", "EQUITY_INSTRUMENT_EXTERNAL_HALT", "EQUITY_TEXAS_CRYPTO_CANCEL_PENDING_ORDER_DISCLOSURE", "EQUITY_OVERNIGHT_MARKET_BUY_FTUX_POPUP", "EQUITY_STALE_MARKETDATA", "EQUITY_TAX_LOT_INVALID_ORDER", "EQUITY_TAX_LOT_TOO_MANY_SELECTED", "EQUITY_TAX_LOT_STALE", "EQUITY_TAX_LOT_OUT_OF_SYNC", "EQUITY_EXTREMELY_MARKETABLE_STOP_LIMIT_PRICE", "EQUITY_EXTREMELY_UNMARKETABLE_STOP_LIMIT_PRICE", "EQUITY_LIMIT_PRICE_OUTSIDE_PRICEBAND", "EQUITY_TAX_LOT_CONDITIONAL_ORDER_FRACTIONALLY_UNTRADABLE", "EQUITY_SELL_ORDER_OUTSTANDING_TAX_LOT_ORDER_WARNING", "EQUITY_SELL_TO_OPEN_MARGIN_LEVERAGE_DISABLED", "EQUITY_SELL_TO_OPEN_SUBJECT_TO_TAX_WITHHOLDING", "EQUITY_SELL_TO_OPEN_HOOD_EMPLOYEE_RESTRICTED", "EQUITY_BORROW_FEE_CHANGED", "EQUITY_SUB_DOLLAR_SHARE_BASED_ORDER", "EQUITY_NOT_ENOUGH_BP_CONVERSION_NEEDED", "EQUITY_SELL_TO_OPEN_INVALID_SESSION", "EQUITY_NOT_ENOUGH_BP_MARKET_ORDER_SHARES_CONVERSION_NEEDED", "EQUITY_EMPLOYEE_SYMBOLS_RESTRICTED_FOR_TRADING", "EQUITY_NOT_ENOUGH_BP_SHARES_PERCENT_RESERVED_CONVERSION_NEEDED", "EQUITY_SELL_TO_OPEN_CASH_ACCOUNT_UPGRADABLE_TO_MARGIN", "EQUITY_SELL_TO_OPEN_LOCATE_UNAVAILABLE", "RECURRING_CRYPTO_MIN_2K", "RECURRING_CRYPTO_MIN_25K", "RECURRING_CRYPTO_SIGNUP", "RECURRING_FRACTIONALLY_UNTRADABLE", "RECURRING_MAX_AMOUNT", "RECURRING_MIN_AMOUNT", "RECURRING_RHS_CONVERSION", "RECURRING_SUFFICIENT_BUYING_POWER", "CAR_ELIGIBILITY_NOT_VALID", "Companion", "rosetta.order_externalRelease"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
/* loaded from: classes25.dex */
public final class AlertType implements WireEnum {
    private static final /* synthetic */ EnumEntries $ENTRIES;
    private static final /* synthetic */ AlertType[] $VALUES;

    @JvmField
    public static final ProtoAdapter<AlertType> ADAPTER;
    public static final AlertType CAR_ELIGIBILITY_NOT_VALID;

    /* renamed from: Companion, reason: from kotlin metadata */
    public static final Companion INSTANCE;
    public static final AlertType EQUITY_ADT_AND_EH_SESSION_KILL_SWITCH_ENABLED;
    public static final AlertType EQUITY_ALL_DAY_TRADING_ERROR;
    public static final AlertType EQUITY_ALL_DAY_TRADING_FRACTIONAL_ORDER_PROMOTION;
    public static final AlertType EQUITY_ALL_DAY_TRADING_SESSION_KILL_SWITCH_ENABLED;
    public static final AlertType EQUITY_BORROW_FEE_CHANGED;
    public static final AlertType EQUITY_COLLARED_ORDER_DISABLED;
    public static final AlertType EQUITY_CONCENTRATED_MAINTENANCE_CALL_WARNING;
    public static final AlertType EQUITY_CONVERT_TO_MARKET_ORDER;
    public static final AlertType EQUITY_CONVERT_TO_SIMPLE_LIMIT_ORDER;
    public static final AlertType EQUITY_DAY_TRADE_BLOCK_DUE_TO_PDT;
    public static final AlertType EQUITY_DAY_TRADE_BLOCK_ERROR;
    public static final AlertType EQUITY_DAY_TRADE_BLOCK_WARNING;
    public static final AlertType EQUITY_DAY_TRADE_BLOCK_WITH_CANCELABLE_ORDER;
    public static final AlertType EQUITY_DELAYED_EXTENDED_HOURS;
    public static final AlertType EQUITY_DOLLAR_BASED_MINIMUM_AMOUNT_ERROR;
    public static final AlertType EQUITY_DOLLAR_BASED_SELL_ALL_ERROR;
    public static final AlertType EQUITY_EMPLOYEE_SYMBOLS_RESTRICTED_FOR_TRADING;
    public static final AlertType EQUITY_ETP_WARNING;
    public static final AlertType EQUITY_EXTENDED_HOURS_SESSION_KILL_SWITCH_ENABLED;
    public static final AlertType EQUITY_EXTREMELY_MARKETABLE_LIMIT_PRICE;
    public static final AlertType EQUITY_EXTREMELY_MARKETABLE_STOP_LIMIT_PRICE;
    public static final AlertType EQUITY_EXTREMELY_MARKETABLE_STOP_PRICE;
    public static final AlertType EQUITY_EXTREMELY_UNMARKETABLE_LIMIT_PRICE;
    public static final AlertType EQUITY_EXTREMELY_UNMARKETABLE_STOP_LIMIT_PRICE;
    public static final AlertType EQUITY_EXTREMELY_UNMARKETABLE_STOP_PRICE;
    public static final AlertType EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_BUY;
    public static final AlertType EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_SELL;
    public static final AlertType EQUITY_HIGH_VOLATILITY;
    public static final AlertType EQUITY_INITIAL_TRAILING_STOP_PRICE;
    public static final AlertType EQUITY_INSTRUMENT_EXTERNAL_HALT;
    public static final AlertType EQUITY_INSTRUMENT_HALT;
    public static final AlertType EQUITY_INVALID_SIMPLE_LIMIT_ORDER;
    public static final AlertType EQUITY_IPO_FLIPPING_POLICY;
    public static final AlertType EQUITY_IRA_BLOCK_UBTI;
    public static final AlertType EQUITY_LARGE_ORDER;
    public static final AlertType EQUITY_LIMIT_PRICE_OUTSIDE_PRICEBAND;
    public static final AlertType EQUITY_LIMIT_PRICE_OUTSIDE_SOFT_RANGE;
    public static final AlertType EQUITY_LIQUIDITY;
    public static final AlertType EQUITY_MAX_NOTIONAL_EXCEEDED;
    public static final AlertType EQUITY_MAX_PRICE_EXCEEDED;
    public static final AlertType EQUITY_MAX_QUANTITY_EXCEEDED;
    public static final AlertType EQUITY_MAX_SELL_DOLLARS_EXCEEDED;
    public static final AlertType EQUITY_MAX_SELL_DOLLARS_LIMIT_ORDER_EXCEEDED;
    public static final AlertType EQUITY_MAX_SELL_SHARES_EXCEEDED;
    public static final AlertType EQUITY_NOT_ENOUGH_BP;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_CANCEL_CRYPTO_PENDING_ORDERS;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_CONVERSION_NEEDED;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_CONVERT_TO_LIMIT;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_DOLLAR_BASED;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_LIMIT_PRICE;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_MARKET_ORDER_SHARES_CONVERSION_NEEDED;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED_SHARE_BASED_MARKET_BUY;
    public static final AlertType EQUITY_NOT_ENOUGH_BP_SHARES_PERCENT_RESERVED_CONVERSION_NEEDED;
    public static final AlertType EQUITY_NOT_ENOUGH_SHARES;
    public static final AlertType EQUITY_NO_QUOTE;
    public static final AlertType EQUITY_ORDER_REPLACEMENT_NO_CHANGE;
    public static final AlertType EQUITY_ORDER_REPLACEMENT_ORDER_NOT_REPLACEABLE;
    public static final AlertType EQUITY_OVERNIGHT_MARKET_BUY_FTUX_POPUP;
    public static final AlertType EQUITY_PDT_BLOCK_NOT_EXEMPT;
    public static final AlertType EQUITY_REWARDS_MUST_BE_HELD;
    public static final AlertType EQUITY_SELL_CAUSES_CASH_COLLATERAL;
    public static final AlertType EQUITY_SELL_ORDER_OUTSTANDING_TAX_LOT_ORDER_WARNING;
    public static final AlertType EQUITY_SELL_TO_OPEN_CASH_ACCOUNT_UPGRADABLE_TO_MARGIN;
    public static final AlertType EQUITY_SELL_TO_OPEN_HOOD_EMPLOYEE_RESTRICTED;
    public static final AlertType EQUITY_SELL_TO_OPEN_INVALID_SESSION;
    public static final AlertType EQUITY_SELL_TO_OPEN_LOCATE_UNAVAILABLE;
    public static final AlertType EQUITY_SELL_TO_OPEN_MARGIN_LEVERAGE_DISABLED;
    public static final AlertType EQUITY_SELL_TO_OPEN_SUBJECT_TO_TAX_WITHHOLDING;
    public static final AlertType EQUITY_SHORT_POSITION_QUANTITY_ERROR;
    public static final AlertType EQUITY_SHORT_POSITION_QUANTITY_WITH_PENDING_ERROR;
    public static final AlertType EQUITY_SLIPPAGE_RISK_FROM_OPTION_ASSIGNMENT;
    public static final AlertType EQUITY_STALE_MARKETDATA;
    public static final AlertType EQUITY_STOP_PRICE_OUTSIDE_SOFT_RANGE;
    public static final AlertType EQUITY_SUB_DOLLAR_SHARE_BASED_ORDER;
    public static final AlertType EQUITY_SUITABILITY;
    public static final AlertType EQUITY_TAX_LOT_CONDITIONAL_ORDER_FRACTIONALLY_UNTRADABLE;
    public static final AlertType EQUITY_TAX_LOT_INVALID_ORDER;
    public static final AlertType EQUITY_TAX_LOT_OUT_OF_SYNC;
    public static final AlertType EQUITY_TAX_LOT_STALE;
    public static final AlertType EQUITY_TAX_LOT_TOO_MANY_SELECTED;
    public static final AlertType EQUITY_TEXAS_CRYPTO_CANCEL_PENDING_ORDER_DISCLOSURE;
    public static final AlertType EQUITY_TOO_LARGE_ORDER;
    public static final AlertType EQUITY_TRADING_WINDOW_CLOSED_FOR_HOOD_EMPLOYEES;
    public static final AlertType EQUITY_TSPP_LIMIT_PRICE;
    public static final AlertType EQUITY_TSPP_STOP_PRICE;
    public static final AlertType EQUITY_UNTRADABLE;
    public static final AlertType EQUITY_UNTRADABLE_EXTENDED_HOURS_FRAC_INSTRUMENT;
    public static final AlertType EQUITY_UPDATE_FOR_HYPER_EX;
    public static final AlertType EQUITY_UPDATE_FOR_HYPER_EX_BLOCKING;
    public static final AlertType EQUITY_VALIDATION_ERROR;
    public static final AlertType EQUITY_ZERO_QUANTITY;
    public static final AlertType RECURRING_CRYPTO_MIN_25K;
    public static final AlertType RECURRING_CRYPTO_MIN_2K;
    public static final AlertType RECURRING_CRYPTO_SIGNUP;
    public static final AlertType RECURRING_FRACTIONALLY_UNTRADABLE;
    public static final AlertType RECURRING_MAX_AMOUNT;
    public static final AlertType RECURRING_MIN_AMOUNT;
    public static final AlertType RECURRING_RHS_CONVERSION;
    public static final AlertType RECURRING_SUFFICIENT_BUYING_POWER;
    public static final AlertType RHS_CONVERSION;
    public static final AlertType UNDEFINED;
    private final int value;

    private static final /* synthetic */ AlertType[] $values() {
        return new AlertType[]{UNDEFINED, EQUITY_UNTRADABLE, EQUITY_NOT_ENOUGH_BP_DOLLAR_BASED, RHS_CONVERSION, EQUITY_PDT_BLOCK_NOT_EXEMPT, EQUITY_DAY_TRADE_BLOCK_WARNING, EQUITY_NOT_ENOUGH_SHARES, EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_BUY, EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_SELL, EQUITY_DAY_TRADE_BLOCK_DUE_TO_PDT, EQUITY_DAY_TRADE_BLOCK_ERROR, EQUITY_DAY_TRADE_BLOCK_WITH_CANCELABLE_ORDER, EQUITY_NO_QUOTE, EQUITY_HIGH_VOLATILITY, EQUITY_LIQUIDITY, EQUITY_DOLLAR_BASED_SELL_ALL_ERROR, EQUITY_SHORT_POSITION_QUANTITY_WITH_PENDING_ERROR, EQUITY_SHORT_POSITION_QUANTITY_ERROR, EQUITY_NOT_ENOUGH_BP_CONVERT_TO_LIMIT, EQUITY_NOT_ENOUGH_BP, EQUITY_SELL_CAUSES_CASH_COLLATERAL, EQUITY_LARGE_ORDER, EQUITY_DOLLAR_BASED_MINIMUM_AMOUNT_ERROR, EQUITY_ZERO_QUANTITY, EQUITY_SUITABILITY, EQUITY_LIMIT_PRICE_OUTSIDE_SOFT_RANGE, EQUITY_STOP_PRICE_OUTSIDE_SOFT_RANGE, EQUITY_REWARDS_MUST_BE_HELD, EQUITY_MAX_SELL_DOLLARS_EXCEEDED, EQUITY_MAX_SELL_SHARES_EXCEEDED, EQUITY_ETP_WARNING, EQUITY_TSPP_LIMIT_PRICE, EQUITY_TSPP_STOP_PRICE, EQUITY_IPO_FLIPPING_POLICY, EQUITY_INITIAL_TRAILING_STOP_PRICE, EQUITY_EXTREMELY_MARKETABLE_LIMIT_PRICE, EQUITY_EXTREMELY_MARKETABLE_STOP_PRICE, EQUITY_EXTREMELY_UNMARKETABLE_LIMIT_PRICE, EQUITY_EXTREMELY_UNMARKETABLE_STOP_PRICE, EQUITY_MAX_PRICE_EXCEEDED, EQUITY_MAX_NOTIONAL_EXCEEDED, EQUITY_MAX_QUANTITY_EXCEEDED, EQUITY_TOO_LARGE_ORDER, EQUITY_UNTRADABLE_EXTENDED_HOURS_FRAC_INSTRUMENT, EQUITY_DELAYED_EXTENDED_HOURS, EQUITY_VALIDATION_ERROR, EQUITY_IRA_BLOCK_UBTI, EQUITY_ALL_DAY_TRADING_ERROR, EQUITY_UPDATE_FOR_HYPER_EX, EQUITY_UPDATE_FOR_HYPER_EX_BLOCKING, EQUITY_INVALID_SIMPLE_LIMIT_ORDER, EQUITY_INSTRUMENT_HALT, EQUITY_MAX_SELL_DOLLARS_LIMIT_ORDER_EXCEEDED, EQUITY_NOT_ENOUGH_BP_LIMIT_PRICE, EQUITY_CONVERT_TO_MARKET_ORDER, EQUITY_CONVERT_TO_SIMPLE_LIMIT_ORDER, EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED, EQUITY_NOT_ENOUGH_BP_CANCEL_CRYPTO_PENDING_ORDERS, EQUITY_ALL_DAY_TRADING_FRACTIONAL_ORDER_PROMOTION, EQUITY_ALL_DAY_TRADING_SESSION_KILL_SWITCH_ENABLED, EQUITY_EXTENDED_HOURS_SESSION_KILL_SWITCH_ENABLED, EQUITY_ADT_AND_EH_SESSION_KILL_SWITCH_ENABLED, EQUITY_COLLARED_ORDER_DISABLED, EQUITY_SLIPPAGE_RISK_FROM_OPTION_ASSIGNMENT, EQUITY_TRADING_WINDOW_CLOSED_FOR_HOOD_EMPLOYEES, EQUITY_CONCENTRATED_MAINTENANCE_CALL_WARNING, EQUITY_ORDER_REPLACEMENT_NO_CHANGE, EQUITY_ORDER_REPLACEMENT_ORDER_NOT_REPLACEABLE, EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED_SHARE_BASED_MARKET_BUY, EQUITY_INSTRUMENT_EXTERNAL_HALT, EQUITY_TEXAS_CRYPTO_CANCEL_PENDING_ORDER_DISCLOSURE, EQUITY_OVERNIGHT_MARKET_BUY_FTUX_POPUP, EQUITY_STALE_MARKETDATA, EQUITY_TAX_LOT_INVALID_ORDER, EQUITY_TAX_LOT_TOO_MANY_SELECTED, EQUITY_TAX_LOT_STALE, EQUITY_TAX_LOT_OUT_OF_SYNC, EQUITY_EXTREMELY_MARKETABLE_STOP_LIMIT_PRICE, EQUITY_EXTREMELY_UNMARKETABLE_STOP_LIMIT_PRICE, EQUITY_LIMIT_PRICE_OUTSIDE_PRICEBAND, EQUITY_TAX_LOT_CONDITIONAL_ORDER_FRACTIONALLY_UNTRADABLE, EQUITY_SELL_ORDER_OUTSTANDING_TAX_LOT_ORDER_WARNING, EQUITY_SELL_TO_OPEN_MARGIN_LEVERAGE_DISABLED, EQUITY_SELL_TO_OPEN_SUBJECT_TO_TAX_WITHHOLDING, EQUITY_SELL_TO_OPEN_HOOD_EMPLOYEE_RESTRICTED, EQUITY_BORROW_FEE_CHANGED, EQUITY_SUB_DOLLAR_SHARE_BASED_ORDER, EQUITY_NOT_ENOUGH_BP_CONVERSION_NEEDED, EQUITY_SELL_TO_OPEN_INVALID_SESSION, EQUITY_NOT_ENOUGH_BP_MARKET_ORDER_SHARES_CONVERSION_NEEDED, EQUITY_EMPLOYEE_SYMBOLS_RESTRICTED_FOR_TRADING, EQUITY_NOT_ENOUGH_BP_SHARES_PERCENT_RESERVED_CONVERSION_NEEDED, EQUITY_SELL_TO_OPEN_CASH_ACCOUNT_UPGRADABLE_TO_MARGIN, EQUITY_SELL_TO_OPEN_LOCATE_UNAVAILABLE, RECURRING_CRYPTO_MIN_2K, RECURRING_CRYPTO_MIN_25K, RECURRING_CRYPTO_SIGNUP, RECURRING_FRACTIONALLY_UNTRADABLE, RECURRING_MAX_AMOUNT, RECURRING_MIN_AMOUNT, RECURRING_RHS_CONVERSION, RECURRING_SUFFICIENT_BUYING_POWER, CAR_ELIGIBILITY_NOT_VALID};
    }

    @JvmStatic
    public static final AlertType fromValue(int i) {
        return INSTANCE.fromValue(i);
    }

    public static EnumEntries<AlertType> getEntries() {
        return $ENTRIES;
    }

    private AlertType(String str, int i, int i2) {
        this.value = i2;
    }

    @Override // com.squareup.wire.WireEnum
    public int getValue() {
        return this.value;
    }

    static {
        final AlertType alertType = new AlertType("UNDEFINED", 0, 0);
        UNDEFINED = alertType;
        EQUITY_UNTRADABLE = new AlertType("EQUITY_UNTRADABLE", 1, 1);
        EQUITY_NOT_ENOUGH_BP_DOLLAR_BASED = new AlertType("EQUITY_NOT_ENOUGH_BP_DOLLAR_BASED", 2, 2);
        RHS_CONVERSION = new AlertType("RHS_CONVERSION", 3, 3);
        EQUITY_PDT_BLOCK_NOT_EXEMPT = new AlertType("EQUITY_PDT_BLOCK_NOT_EXEMPT", 4, 4);
        EQUITY_DAY_TRADE_BLOCK_WARNING = new AlertType("EQUITY_DAY_TRADE_BLOCK_WARNING", 5, 5);
        EQUITY_NOT_ENOUGH_SHARES = new AlertType("EQUITY_NOT_ENOUGH_SHARES", 6, 6);
        EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_BUY = new AlertType("EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_BUY", 7, 7);
        EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_SELL = new AlertType("EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_SELL", 8, 8);
        EQUITY_DAY_TRADE_BLOCK_DUE_TO_PDT = new AlertType("EQUITY_DAY_TRADE_BLOCK_DUE_TO_PDT", 9, 9);
        EQUITY_DAY_TRADE_BLOCK_ERROR = new AlertType("EQUITY_DAY_TRADE_BLOCK_ERROR", 10, 10);
        EQUITY_DAY_TRADE_BLOCK_WITH_CANCELABLE_ORDER = new AlertType("EQUITY_DAY_TRADE_BLOCK_WITH_CANCELABLE_ORDER", 11, 11);
        EQUITY_NO_QUOTE = new AlertType("EQUITY_NO_QUOTE", 12, 12);
        EQUITY_HIGH_VOLATILITY = new AlertType("EQUITY_HIGH_VOLATILITY", 13, 13);
        EQUITY_LIQUIDITY = new AlertType("EQUITY_LIQUIDITY", 14, 14);
        EQUITY_DOLLAR_BASED_SELL_ALL_ERROR = new AlertType("EQUITY_DOLLAR_BASED_SELL_ALL_ERROR", 15, 15);
        EQUITY_SHORT_POSITION_QUANTITY_WITH_PENDING_ERROR = new AlertType("EQUITY_SHORT_POSITION_QUANTITY_WITH_PENDING_ERROR", 16, 16);
        EQUITY_SHORT_POSITION_QUANTITY_ERROR = new AlertType("EQUITY_SHORT_POSITION_QUANTITY_ERROR", 17, 17);
        EQUITY_NOT_ENOUGH_BP_CONVERT_TO_LIMIT = new AlertType("EQUITY_NOT_ENOUGH_BP_CONVERT_TO_LIMIT", 18, 18);
        EQUITY_NOT_ENOUGH_BP = new AlertType("EQUITY_NOT_ENOUGH_BP", 19, 19);
        EQUITY_SELL_CAUSES_CASH_COLLATERAL = new AlertType("EQUITY_SELL_CAUSES_CASH_COLLATERAL", 20, 20);
        EQUITY_LARGE_ORDER = new AlertType("EQUITY_LARGE_ORDER", 21, 21);
        EQUITY_DOLLAR_BASED_MINIMUM_AMOUNT_ERROR = new AlertType("EQUITY_DOLLAR_BASED_MINIMUM_AMOUNT_ERROR", 22, 22);
        EQUITY_ZERO_QUANTITY = new AlertType("EQUITY_ZERO_QUANTITY", 23, 23);
        EQUITY_SUITABILITY = new AlertType("EQUITY_SUITABILITY", 24, 24);
        EQUITY_LIMIT_PRICE_OUTSIDE_SOFT_RANGE = new AlertType("EQUITY_LIMIT_PRICE_OUTSIDE_SOFT_RANGE", 25, 25);
        EQUITY_STOP_PRICE_OUTSIDE_SOFT_RANGE = new AlertType("EQUITY_STOP_PRICE_OUTSIDE_SOFT_RANGE", 26, 26);
        EQUITY_REWARDS_MUST_BE_HELD = new AlertType("EQUITY_REWARDS_MUST_BE_HELD", 27, 27);
        EQUITY_MAX_SELL_DOLLARS_EXCEEDED = new AlertType("EQUITY_MAX_SELL_DOLLARS_EXCEEDED", 28, 28);
        EQUITY_MAX_SELL_SHARES_EXCEEDED = new AlertType("EQUITY_MAX_SELL_SHARES_EXCEEDED", 29, 29);
        EQUITY_ETP_WARNING = new AlertType("EQUITY_ETP_WARNING", 30, 30);
        EQUITY_TSPP_LIMIT_PRICE = new AlertType("EQUITY_TSPP_LIMIT_PRICE", 31, 31);
        EQUITY_TSPP_STOP_PRICE = new AlertType("EQUITY_TSPP_STOP_PRICE", 32, 32);
        EQUITY_IPO_FLIPPING_POLICY = new AlertType("EQUITY_IPO_FLIPPING_POLICY", 33, 33);
        EQUITY_INITIAL_TRAILING_STOP_PRICE = new AlertType("EQUITY_INITIAL_TRAILING_STOP_PRICE", 34, 34);
        EQUITY_EXTREMELY_MARKETABLE_LIMIT_PRICE = new AlertType("EQUITY_EXTREMELY_MARKETABLE_LIMIT_PRICE", 35, 35);
        EQUITY_EXTREMELY_MARKETABLE_STOP_PRICE = new AlertType("EQUITY_EXTREMELY_MARKETABLE_STOP_PRICE", 36, 36);
        EQUITY_EXTREMELY_UNMARKETABLE_LIMIT_PRICE = new AlertType("EQUITY_EXTREMELY_UNMARKETABLE_LIMIT_PRICE", 37, 37);
        EQUITY_EXTREMELY_UNMARKETABLE_STOP_PRICE = new AlertType("EQUITY_EXTREMELY_UNMARKETABLE_STOP_PRICE", 38, 38);
        EQUITY_MAX_PRICE_EXCEEDED = new AlertType("EQUITY_MAX_PRICE_EXCEEDED", 39, 39);
        EQUITY_MAX_NOTIONAL_EXCEEDED = new AlertType("EQUITY_MAX_NOTIONAL_EXCEEDED", 40, 40);
        EQUITY_MAX_QUANTITY_EXCEEDED = new AlertType("EQUITY_MAX_QUANTITY_EXCEEDED", 41, 41);
        EQUITY_TOO_LARGE_ORDER = new AlertType("EQUITY_TOO_LARGE_ORDER", 42, 42);
        EQUITY_UNTRADABLE_EXTENDED_HOURS_FRAC_INSTRUMENT = new AlertType("EQUITY_UNTRADABLE_EXTENDED_HOURS_FRAC_INSTRUMENT", 43, 43);
        EQUITY_DELAYED_EXTENDED_HOURS = new AlertType("EQUITY_DELAYED_EXTENDED_HOURS", 44, 44);
        EQUITY_VALIDATION_ERROR = new AlertType("EQUITY_VALIDATION_ERROR", 45, 45);
        EQUITY_IRA_BLOCK_UBTI = new AlertType("EQUITY_IRA_BLOCK_UBTI", 46, 46);
        EQUITY_ALL_DAY_TRADING_ERROR = new AlertType("EQUITY_ALL_DAY_TRADING_ERROR", 47, 55);
        EQUITY_UPDATE_FOR_HYPER_EX = new AlertType("EQUITY_UPDATE_FOR_HYPER_EX", 48, 56);
        EQUITY_UPDATE_FOR_HYPER_EX_BLOCKING = new AlertType("EQUITY_UPDATE_FOR_HYPER_EX_BLOCKING", 49, 57);
        EQUITY_INVALID_SIMPLE_LIMIT_ORDER = new AlertType("EQUITY_INVALID_SIMPLE_LIMIT_ORDER", 50, 58);
        EQUITY_INSTRUMENT_HALT = new AlertType("EQUITY_INSTRUMENT_HALT", 51, 59);
        EQUITY_MAX_SELL_DOLLARS_LIMIT_ORDER_EXCEEDED = new AlertType("EQUITY_MAX_SELL_DOLLARS_LIMIT_ORDER_EXCEEDED", 52, 60);
        EQUITY_NOT_ENOUGH_BP_LIMIT_PRICE = new AlertType("EQUITY_NOT_ENOUGH_BP_LIMIT_PRICE", 53, 61);
        EQUITY_CONVERT_TO_MARKET_ORDER = new AlertType("EQUITY_CONVERT_TO_MARKET_ORDER", 54, 62);
        EQUITY_CONVERT_TO_SIMPLE_LIMIT_ORDER = new AlertType("EQUITY_CONVERT_TO_SIMPLE_LIMIT_ORDER", 55, 63);
        EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED = new AlertType("EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED", 56, 64);
        EQUITY_NOT_ENOUGH_BP_CANCEL_CRYPTO_PENDING_ORDERS = new AlertType("EQUITY_NOT_ENOUGH_BP_CANCEL_CRYPTO_PENDING_ORDERS", 57, 65);
        EQUITY_ALL_DAY_TRADING_FRACTIONAL_ORDER_PROMOTION = new AlertType("EQUITY_ALL_DAY_TRADING_FRACTIONAL_ORDER_PROMOTION", 58, 66);
        EQUITY_ALL_DAY_TRADING_SESSION_KILL_SWITCH_ENABLED = new AlertType("EQUITY_ALL_DAY_TRADING_SESSION_KILL_SWITCH_ENABLED", 59, 67);
        EQUITY_EXTENDED_HOURS_SESSION_KILL_SWITCH_ENABLED = new AlertType("EQUITY_EXTENDED_HOURS_SESSION_KILL_SWITCH_ENABLED", 60, 68);
        EQUITY_ADT_AND_EH_SESSION_KILL_SWITCH_ENABLED = new AlertType("EQUITY_ADT_AND_EH_SESSION_KILL_SWITCH_ENABLED", 61, 69);
        EQUITY_COLLARED_ORDER_DISABLED = new AlertType("EQUITY_COLLARED_ORDER_DISABLED", 62, 70);
        EQUITY_SLIPPAGE_RISK_FROM_OPTION_ASSIGNMENT = new AlertType("EQUITY_SLIPPAGE_RISK_FROM_OPTION_ASSIGNMENT", 63, 71);
        EQUITY_TRADING_WINDOW_CLOSED_FOR_HOOD_EMPLOYEES = new AlertType("EQUITY_TRADING_WINDOW_CLOSED_FOR_HOOD_EMPLOYEES", 64, 72);
        EQUITY_CONCENTRATED_MAINTENANCE_CALL_WARNING = new AlertType("EQUITY_CONCENTRATED_MAINTENANCE_CALL_WARNING", 65, 73);
        EQUITY_ORDER_REPLACEMENT_NO_CHANGE = new AlertType("EQUITY_ORDER_REPLACEMENT_NO_CHANGE", 66, 74);
        EQUITY_ORDER_REPLACEMENT_ORDER_NOT_REPLACEABLE = new AlertType("EQUITY_ORDER_REPLACEMENT_ORDER_NOT_REPLACEABLE", 67, 75);
        EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED_SHARE_BASED_MARKET_BUY = new AlertType("EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED_SHARE_BASED_MARKET_BUY", 68, 76);
        EQUITY_INSTRUMENT_EXTERNAL_HALT = new AlertType("EQUITY_INSTRUMENT_EXTERNAL_HALT", 69, 77);
        EQUITY_TEXAS_CRYPTO_CANCEL_PENDING_ORDER_DISCLOSURE = new AlertType("EQUITY_TEXAS_CRYPTO_CANCEL_PENDING_ORDER_DISCLOSURE", 70, 78);
        EQUITY_OVERNIGHT_MARKET_BUY_FTUX_POPUP = new AlertType("EQUITY_OVERNIGHT_MARKET_BUY_FTUX_POPUP", 71, 79);
        EQUITY_STALE_MARKETDATA = new AlertType("EQUITY_STALE_MARKETDATA", 72, 80);
        EQUITY_TAX_LOT_INVALID_ORDER = new AlertType("EQUITY_TAX_LOT_INVALID_ORDER", 73, 81);
        EQUITY_TAX_LOT_TOO_MANY_SELECTED = new AlertType("EQUITY_TAX_LOT_TOO_MANY_SELECTED", 74, 82);
        EQUITY_TAX_LOT_STALE = new AlertType("EQUITY_TAX_LOT_STALE", 75, 83);
        EQUITY_TAX_LOT_OUT_OF_SYNC = new AlertType("EQUITY_TAX_LOT_OUT_OF_SYNC", 76, 84);
        EQUITY_EXTREMELY_MARKETABLE_STOP_LIMIT_PRICE = new AlertType("EQUITY_EXTREMELY_MARKETABLE_STOP_LIMIT_PRICE", 77, 85);
        EQUITY_EXTREMELY_UNMARKETABLE_STOP_LIMIT_PRICE = new AlertType("EQUITY_EXTREMELY_UNMARKETABLE_STOP_LIMIT_PRICE", 78, 86);
        EQUITY_LIMIT_PRICE_OUTSIDE_PRICEBAND = new AlertType("EQUITY_LIMIT_PRICE_OUTSIDE_PRICEBAND", 79, 87);
        EQUITY_TAX_LOT_CONDITIONAL_ORDER_FRACTIONALLY_UNTRADABLE = new AlertType("EQUITY_TAX_LOT_CONDITIONAL_ORDER_FRACTIONALLY_UNTRADABLE", 80, 88);
        EQUITY_SELL_ORDER_OUTSTANDING_TAX_LOT_ORDER_WARNING = new AlertType("EQUITY_SELL_ORDER_OUTSTANDING_TAX_LOT_ORDER_WARNING", 81, 89);
        EQUITY_SELL_TO_OPEN_MARGIN_LEVERAGE_DISABLED = new AlertType("EQUITY_SELL_TO_OPEN_MARGIN_LEVERAGE_DISABLED", 82, 91);
        EQUITY_SELL_TO_OPEN_SUBJECT_TO_TAX_WITHHOLDING = new AlertType("EQUITY_SELL_TO_OPEN_SUBJECT_TO_TAX_WITHHOLDING", 83, 92);
        EQUITY_SELL_TO_OPEN_HOOD_EMPLOYEE_RESTRICTED = new AlertType("EQUITY_SELL_TO_OPEN_HOOD_EMPLOYEE_RESTRICTED", 84, 93);
        EQUITY_BORROW_FEE_CHANGED = new AlertType("EQUITY_BORROW_FEE_CHANGED", 85, 94);
        EQUITY_SUB_DOLLAR_SHARE_BASED_ORDER = new AlertType("EQUITY_SUB_DOLLAR_SHARE_BASED_ORDER", 86, 95);
        EQUITY_NOT_ENOUGH_BP_CONVERSION_NEEDED = new AlertType("EQUITY_NOT_ENOUGH_BP_CONVERSION_NEEDED", 87, 96);
        EQUITY_SELL_TO_OPEN_INVALID_SESSION = new AlertType("EQUITY_SELL_TO_OPEN_INVALID_SESSION", 88, 99);
        EQUITY_NOT_ENOUGH_BP_MARKET_ORDER_SHARES_CONVERSION_NEEDED = new AlertType("EQUITY_NOT_ENOUGH_BP_MARKET_ORDER_SHARES_CONVERSION_NEEDED", 89, 102);
        EQUITY_EMPLOYEE_SYMBOLS_RESTRICTED_FOR_TRADING = new AlertType("EQUITY_EMPLOYEE_SYMBOLS_RESTRICTED_FOR_TRADING", 90, 97);
        EQUITY_NOT_ENOUGH_BP_SHARES_PERCENT_RESERVED_CONVERSION_NEEDED = new AlertType("EQUITY_NOT_ENOUGH_BP_SHARES_PERCENT_RESERVED_CONVERSION_NEEDED", 91, 98);
        EQUITY_SELL_TO_OPEN_CASH_ACCOUNT_UPGRADABLE_TO_MARGIN = new AlertType("EQUITY_SELL_TO_OPEN_CASH_ACCOUNT_UPGRADABLE_TO_MARGIN", 92, 100);
        EQUITY_SELL_TO_OPEN_LOCATE_UNAVAILABLE = new AlertType("EQUITY_SELL_TO_OPEN_LOCATE_UNAVAILABLE", 93, 101);
        RECURRING_CRYPTO_MIN_2K = new AlertType("RECURRING_CRYPTO_MIN_2K", 94, 47);
        RECURRING_CRYPTO_MIN_25K = new AlertType("RECURRING_CRYPTO_MIN_25K", 95, 48);
        RECURRING_CRYPTO_SIGNUP = new AlertType("RECURRING_CRYPTO_SIGNUP", 96, 49);
        RECURRING_FRACTIONALLY_UNTRADABLE = new AlertType("RECURRING_FRACTIONALLY_UNTRADABLE", 97, 50);
        RECURRING_MAX_AMOUNT = new AlertType("RECURRING_MAX_AMOUNT", 98, 51);
        RECURRING_MIN_AMOUNT = new AlertType("RECURRING_MIN_AMOUNT", 99, 52);
        RECURRING_RHS_CONVERSION = new AlertType("RECURRING_RHS_CONVERSION", 100, 53);
        RECURRING_SUFFICIENT_BUYING_POWER = new AlertType("RECURRING_SUFFICIENT_BUYING_POWER", 101, 54);
        CAR_ELIGIBILITY_NOT_VALID = new AlertType("CAR_ELIGIBILITY_NOT_VALID", 102, 90);
        AlertType[] alertTypeArr$values = $values();
        $VALUES = alertTypeArr$values;
        $ENTRIES = EnumEntries2.enumEntries(alertTypeArr$values);
        INSTANCE = new Companion(null);
        final KClass orCreateKotlinClass = Reflection.getOrCreateKotlinClass(AlertType.class);
        final Syntax syntax = Syntax.PROTO_3;
        ADAPTER = new EnumAdapter<AlertType>(orCreateKotlinClass, syntax, alertType) { // from class: rosetta.order.AlertType$Companion$ADAPTER$1
            /* JADX INFO: Access modifiers changed from: protected */
            @Override // com.squareup.wire.EnumAdapter
            public AlertType fromValue(int value) {
                return AlertType.INSTANCE.fromValue(value);
            }
        };
    }

    /* compiled from: AlertType.kt */
    @Metadata(m3635d1 = {"\u0000\u001e\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\b\n\u0000\b\u0086\u0003\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003J\u0012\u0010\u0007\u001a\u0004\u0018\u00010\u00062\u0006\u0010\b\u001a\u00020\tH\u0007R\u0016\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000¨\u0006\n"}, m3636d2 = {"Lrosetta/order/AlertType$Companion;", "", "<init>", "()V", "ADAPTER", "Lcom/squareup/wire/ProtoAdapter;", "Lrosetta/order/AlertType;", "fromValue", "value", "", "rosetta.order_externalRelease"}, m3637k = 1, m3638mv = {2, 1, 0}, m3640xi = 48)
    public static final class Companion {
        public /* synthetic */ Companion(DefaultConstructorMarker defaultConstructorMarker) {
            this();
        }

        private Companion() {
        }

        @JvmStatic
        public final AlertType fromValue(int value) {
            switch (value) {
                case 0:
                    return AlertType.UNDEFINED;
                case 1:
                    return AlertType.EQUITY_UNTRADABLE;
                case 2:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_DOLLAR_BASED;
                case 3:
                    return AlertType.RHS_CONVERSION;
                case 4:
                    return AlertType.EQUITY_PDT_BLOCK_NOT_EXEMPT;
                case 5:
                    return AlertType.EQUITY_DAY_TRADE_BLOCK_WARNING;
                case 6:
                    return AlertType.EQUITY_NOT_ENOUGH_SHARES;
                case 7:
                    return AlertType.EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_BUY;
                case 8:
                    return AlertType.EQUITY_FRACTIONALLY_UNTRADABLE_ERROR_SELL;
                case 9:
                    return AlertType.EQUITY_DAY_TRADE_BLOCK_DUE_TO_PDT;
                case 10:
                    return AlertType.EQUITY_DAY_TRADE_BLOCK_ERROR;
                case 11:
                    return AlertType.EQUITY_DAY_TRADE_BLOCK_WITH_CANCELABLE_ORDER;
                case 12:
                    return AlertType.EQUITY_NO_QUOTE;
                case 13:
                    return AlertType.EQUITY_HIGH_VOLATILITY;
                case 14:
                    return AlertType.EQUITY_LIQUIDITY;
                case 15:
                    return AlertType.EQUITY_DOLLAR_BASED_SELL_ALL_ERROR;
                case 16:
                    return AlertType.EQUITY_SHORT_POSITION_QUANTITY_WITH_PENDING_ERROR;
                case 17:
                    return AlertType.EQUITY_SHORT_POSITION_QUANTITY_ERROR;
                case 18:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_CONVERT_TO_LIMIT;
                case 19:
                    return AlertType.EQUITY_NOT_ENOUGH_BP;
                case 20:
                    return AlertType.EQUITY_SELL_CAUSES_CASH_COLLATERAL;
                case 21:
                    return AlertType.EQUITY_LARGE_ORDER;
                case 22:
                    return AlertType.EQUITY_DOLLAR_BASED_MINIMUM_AMOUNT_ERROR;
                case 23:
                    return AlertType.EQUITY_ZERO_QUANTITY;
                case 24:
                    return AlertType.EQUITY_SUITABILITY;
                case 25:
                    return AlertType.EQUITY_LIMIT_PRICE_OUTSIDE_SOFT_RANGE;
                case 26:
                    return AlertType.EQUITY_STOP_PRICE_OUTSIDE_SOFT_RANGE;
                case 27:
                    return AlertType.EQUITY_REWARDS_MUST_BE_HELD;
                case 28:
                    return AlertType.EQUITY_MAX_SELL_DOLLARS_EXCEEDED;
                case 29:
                    return AlertType.EQUITY_MAX_SELL_SHARES_EXCEEDED;
                case 30:
                    return AlertType.EQUITY_ETP_WARNING;
                case 31:
                    return AlertType.EQUITY_TSPP_LIMIT_PRICE;
                case 32:
                    return AlertType.EQUITY_TSPP_STOP_PRICE;
                case 33:
                    return AlertType.EQUITY_IPO_FLIPPING_POLICY;
                case 34:
                    return AlertType.EQUITY_INITIAL_TRAILING_STOP_PRICE;
                case 35:
                    return AlertType.EQUITY_EXTREMELY_MARKETABLE_LIMIT_PRICE;
                case 36:
                    return AlertType.EQUITY_EXTREMELY_MARKETABLE_STOP_PRICE;
                case 37:
                    return AlertType.EQUITY_EXTREMELY_UNMARKETABLE_LIMIT_PRICE;
                case 38:
                    return AlertType.EQUITY_EXTREMELY_UNMARKETABLE_STOP_PRICE;
                case 39:
                    return AlertType.EQUITY_MAX_PRICE_EXCEEDED;
                case 40:
                    return AlertType.EQUITY_MAX_NOTIONAL_EXCEEDED;
                case 41:
                    return AlertType.EQUITY_MAX_QUANTITY_EXCEEDED;
                case 42:
                    return AlertType.EQUITY_TOO_LARGE_ORDER;
                case 43:
                    return AlertType.EQUITY_UNTRADABLE_EXTENDED_HOURS_FRAC_INSTRUMENT;
                case 44:
                    return AlertType.EQUITY_DELAYED_EXTENDED_HOURS;
                case 45:
                    return AlertType.EQUITY_VALIDATION_ERROR;
                case 46:
                    return AlertType.EQUITY_IRA_BLOCK_UBTI;
                case 47:
                    return AlertType.RECURRING_CRYPTO_MIN_2K;
                case 48:
                    return AlertType.RECURRING_CRYPTO_MIN_25K;
                case 49:
                    return AlertType.RECURRING_CRYPTO_SIGNUP;
                case 50:
                    return AlertType.RECURRING_FRACTIONALLY_UNTRADABLE;
                case 51:
                    return AlertType.RECURRING_MAX_AMOUNT;
                case 52:
                    return AlertType.RECURRING_MIN_AMOUNT;
                case 53:
                    return AlertType.RECURRING_RHS_CONVERSION;
                case 54:
                    return AlertType.RECURRING_SUFFICIENT_BUYING_POWER;
                case 55:
                    return AlertType.EQUITY_ALL_DAY_TRADING_ERROR;
                case 56:
                    return AlertType.EQUITY_UPDATE_FOR_HYPER_EX;
                case 57:
                    return AlertType.EQUITY_UPDATE_FOR_HYPER_EX_BLOCKING;
                case 58:
                    return AlertType.EQUITY_INVALID_SIMPLE_LIMIT_ORDER;
                case 59:
                    return AlertType.EQUITY_INSTRUMENT_HALT;
                case 60:
                    return AlertType.EQUITY_MAX_SELL_DOLLARS_LIMIT_ORDER_EXCEEDED;
                case 61:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_LIMIT_PRICE;
                case 62:
                    return AlertType.EQUITY_CONVERT_TO_MARKET_ORDER;
                case 63:
                    return AlertType.EQUITY_CONVERT_TO_SIMPLE_LIMIT_ORDER;
                case 64:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED;
                case 65:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_CANCEL_CRYPTO_PENDING_ORDERS;
                case 66:
                    return AlertType.EQUITY_ALL_DAY_TRADING_FRACTIONAL_ORDER_PROMOTION;
                case 67:
                    return AlertType.EQUITY_ALL_DAY_TRADING_SESSION_KILL_SWITCH_ENABLED;
                case SDK_ASSET_ICON_HOME_VALUE:
                    return AlertType.EQUITY_EXTENDED_HOURS_SESSION_KILL_SWITCH_ENABLED;
                case 69:
                    return AlertType.EQUITY_ADT_AND_EH_SESSION_KILL_SWITCH_ENABLED;
                case 70:
                    return AlertType.EQUITY_COLLARED_ORDER_DISABLED;
                case SDK_ASSET_ICON_GUIDE_VALUE:
                    return AlertType.EQUITY_SLIPPAGE_RISK_FROM_OPTION_ASSIGNMENT;
                case SDK_ASSET_ICON_GLOBE_VALUE:
                    return AlertType.EQUITY_TRADING_WINDOW_CLOSED_FOR_HOOD_EMPLOYEES;
                case 73:
                    return AlertType.EQUITY_CONCENTRATED_MAINTENANCE_CALL_WARNING;
                case 74:
                    return AlertType.EQUITY_ORDER_REPLACEMENT_NO_CHANGE;
                case 75:
                    return AlertType.EQUITY_ORDER_REPLACEMENT_ORDER_NOT_REPLACEABLE;
                case 76:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_PERCENT_RESERVED_SHARE_BASED_MARKET_BUY;
                case 77:
                    return AlertType.EQUITY_INSTRUMENT_EXTERNAL_HALT;
                case 78:
                    return AlertType.EQUITY_TEXAS_CRYPTO_CANCEL_PENDING_ORDER_DISCLOSURE;
                case 79:
                    return AlertType.EQUITY_OVERNIGHT_MARKET_BUY_FTUX_POPUP;
                case 80:
                    return AlertType.EQUITY_STALE_MARKETDATA;
                case 81:
                    return AlertType.EQUITY_TAX_LOT_INVALID_ORDER;
                case 82:
                    return AlertType.EQUITY_TAX_LOT_TOO_MANY_SELECTED;
                case 83:
                    return AlertType.EQUITY_TAX_LOT_STALE;
                case 84:
                    return AlertType.EQUITY_TAX_LOT_OUT_OF_SYNC;
                case 85:
                    return AlertType.EQUITY_EXTREMELY_MARKETABLE_STOP_LIMIT_PRICE;
                case 86:
                    return AlertType.EQUITY_EXTREMELY_UNMARKETABLE_STOP_LIMIT_PRICE;
                case 87:
                    return AlertType.EQUITY_LIMIT_PRICE_OUTSIDE_PRICEBAND;
                case 88:
                    return AlertType.EQUITY_TAX_LOT_CONDITIONAL_ORDER_FRACTIONALLY_UNTRADABLE;
                case 89:
                    return AlertType.EQUITY_SELL_ORDER_OUTSTANDING_TAX_LOT_ORDER_WARNING;
                case 90:
                    return AlertType.CAR_ELIGIBILITY_NOT_VALID;
                case 91:
                    return AlertType.EQUITY_SELL_TO_OPEN_MARGIN_LEVERAGE_DISABLED;
                case 92:
                    return AlertType.EQUITY_SELL_TO_OPEN_SUBJECT_TO_TAX_WITHHOLDING;
                case 93:
                    return AlertType.EQUITY_SELL_TO_OPEN_HOOD_EMPLOYEE_RESTRICTED;
                case 94:
                    return AlertType.EQUITY_BORROW_FEE_CHANGED;
                case 95:
                    return AlertType.EQUITY_SUB_DOLLAR_SHARE_BASED_ORDER;
                case 96:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_CONVERSION_NEEDED;
                case 97:
                    return AlertType.EQUITY_EMPLOYEE_SYMBOLS_RESTRICTED_FOR_TRADING;
                case 98:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_SHARES_PERCENT_RESERVED_CONVERSION_NEEDED;
                case 99:
                    return AlertType.EQUITY_SELL_TO_OPEN_INVALID_SESSION;
                case 100:
                    return AlertType.EQUITY_SELL_TO_OPEN_CASH_ACCOUNT_UPGRADABLE_TO_MARGIN;
                case 101:
                    return AlertType.EQUITY_SELL_TO_OPEN_LOCATE_UNAVAILABLE;
                case 102:
                    return AlertType.EQUITY_NOT_ENOUGH_BP_MARKET_ORDER_SHARES_CONVERSION_NEEDED;
                default:
                    return null;
            }
        }
    }

    public static AlertType valueOf(String str) {
        return (AlertType) Enum.valueOf(AlertType.class, str);
    }

    public static AlertType[] values() {
        return (AlertType[]) $VALUES.clone();
    }
}
